# Schedule

This is the schedule for the course (HTML version only). 
Please note that it is liable to change (possibly at short notice). 
If you find a mismatch between this schedule and the official one^[https://mitsdu.sdu.dk/skema/activity/N110040101/e20], then it the official one that is correct.

```{r, echo = FALSE, include=knitr::is_latex_output()}
plot(1,1,type = "n",axes = FALSE,xlab="",ylab="")
text(1,1,labels = "The schedule is only available on the HTML version of this document")
```


```{r, echo = FALSE, message=FALSE,warning=FALSE,eval=knitr::is_html_output()}
library(flextable)
library(readxl)

system("cp -r ~/Dropbox/_SDU_Teaching/BB852/'Course Documents'/BB852_Schedule.xlsx ~/Dropbox/_SDU_Teaching/BB852/BB852_Book/BB852_Schedule.xlsx")
schedule <- read_xlsx("BB852_Schedule.xlsx")
```

```{r, echo = FALSE, message=FALSE,eval=knitr::is_html_output()}
library(lubridate)
schedule2 <- schedule %>% 
  mutate(doy = paste(Day,Month,Year,sep="-")) %>% 
  mutate(Date = lubridate::dmy(doy)) %>% 
  mutate(wd = lubridate::wday(Date,label= TRUE)) %>% 
  mutate(Date = paste0( month(Date,label = TRUE)," ",Day,", ",wd)) %>% 
  select(Date, Session, Part, Type, Topic)
ft <- flextable(schedule2, cwidth = c(2,0.5,2,1,4))
ft <- bold(ft, part = "header") # bold header
ft <- color(ft, i = ~ Type == "Lecture",
         j = ~ Date  + Session + Part + Type + Topic,
        color="red")
ft <- fontsize(ft, part = "all", size = 14)
ft
```

