# Coming soon (maybe)!

## Multivariate statistics

This will cover Principal Component Analysis (PCA) which is a handy statistical tool to reduce the complexity of high-dimensional data (i.e. data sets with many columns).

## Transforming variables

It is often desirable to transform the response variable in order to linearise the relationship between it and the explanatory variables. Generalised Linear Models (GLMs) with non-normal error distributions do this, but sometimes it is useful to do this for ordinary linear regression. It is also useful to understand the different transformations that are part of a GLM. I will cover common transformations, and include "Tukey's ladder" of transformations.

## Non-linear regression

Most of the statistics shown in this book focuses on modelling linear relationships between response variables (or their transformed values) and explanatory variables. Sometimes it is useful to explicitly model a known functional form and non-linear regression is a way of doing that.


## Nested or blocked study designs

Sometimes a study will have a design that has some inherent structure. This chapter covers how to account for this with linear models.
