## Habitat restoration

You are part of a research team that aims to investigate the effects of habitat restoration on the average body mass of a specific bird species. You hypothesise that restored habitats may support healthier bird populations that have a larger body mass. Your task is to plan a study to robustly test this hypothesis.

Dataset

The data file `habitat_restoration.csv`, contains data from a pilot on average bird body size (in grams) from the non-restored habitat.


```{r}
# R Code for Simulating the Dataset
round_to_nearest_half <- function(x) {
  round(x * 2) / 2
}

set.seed(789) # Ensure reproducibility
body_size_non_restored <- rnorm(47, mean = 150, sd = 20)  # Average body size in restored habitats
body_size_non_restored <- round_to_nearest_half(body_size_non_restored)

habitat_restoration <- data.frame(BodySize = body_size_non_restored)
write.csv(habitat_restoration, "DataSetLibrary/habitat_restoration.csv", row.names = FALSE)

#require(ggplot2)
#ggplot(habitat_restoration,aes(x = BodySize)) + geom_histogram()

```

Tasks


1. Summarise the pilot study data to obtain the information necessary required to conduct a power analysis.
2. Conduct a power analysis using simulation techniques. The objective is to determine the sample size required to achieve 80% power to detect a 20% increase in average bird body size in rewilded habitats compared to non-rewilded habitats.
3. Write a description of the methods used for the power analysis. Then present the results in a clear, concise manner. Interpret these results, discussing their implications for the design and feasibility of the proposed study. Ensure that the communication is professional and suitable for a scientific project plan.

