<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta property="og:title" content="14.1 Count data with Poisson errors. | BB852 - Data handling, visualisation and statistics" />
<meta property="og:type" content="book" />


<meta property="og:description" content="This is the course book for BB852." />


<meta name="author" content="Owen Jones" />

<meta name="date" content="2020-08-26" />

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js" type="text/javascript"></script>

<meta name="description" content="This is the course book for BB852.">

<title>14.1 Count data with Poisson errors. | BB852 - Data handling, visualisation and statistics</title>

<script src="libs/header-attrs-2.3/header-attrs.js"></script>
<script src="libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="libs/navigation-1.1/tabsets.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
</style>
</head>

<body>

<div class="container-fluid main-container">


<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul>
<li><a href="index.html#preface"><span class="toc-section-number">1</span> Preface</a>
<ul>
<li><a href="1-1-data-wrangling.html#data-wrangling"><span class="toc-section-number">1.1</span> Data wrangling</a></li>
<li><a href="1-2-data-visualisation.html#data-visualisation"><span class="toc-section-number">1.2</span> Data visualisation</a></li>
<li><a href="1-3-statistics.html#statistics"><span class="toc-section-number">1.3</span> Statistics</a></li>
<li><a href="1-4-general-approach.html#general-approach"><span class="toc-section-number">1.4</span> General approach</a></li>
<li><a href="1-5-data-sources.html#data-sources"><span class="toc-section-number">1.5</span> Data sources</a></li>
<li><a href="1-6-acknowledgements.html#acknowledgements"><span class="toc-section-number">1.6</span> Acknowledgements</a></li>
<li><a href="1-7-error-reporting.html#error-reporting"><span class="toc-section-number">1.7</span> Error reporting</a></li>
</ul></li>
<li><a href="2-getting-acquainted-with-r.html#getting-acquainted-with-r"><span class="toc-section-number">2</span> Getting acquainted with R</a>
<ul>
<li><a href="2-1-introduction.html#introduction"><span class="toc-section-number">2.1</span> Introduction</a></li>
<li><a href="2-2-getting-started-with-r.html#getting-started-with-r"><span class="toc-section-number">2.2</span> Getting started with R</a></li>
<li><a href="2-3-getting-help.html#getting-help"><span class="toc-section-number">2.3</span> Getting help</a></li>
<li><a href="2-4-r-as-a-fancy-calculator.html#r-as-a-fancy-calculator"><span class="toc-section-number">2.4</span> R as a fancy calculator</a></li>
<li><a href="2-5-objects-in-r.html#objects-in-r"><span class="toc-section-number">2.5</span> Objects in R</a></li>
<li><a href="2-6-missing-values-infinity-and-non-numbers.html#missing-values-infinity-and-non-numbers"><span class="toc-section-number">2.6</span> Missing values, infinity and “non-numbers”</a></li>
<li><a href="2-7-basic-information-about-objects.html#basic-information-about-objects"><span class="toc-section-number">2.7</span> Basic information about objects</a></li>
<li><a href="2-8-data-frames.html#data-frames"><span class="toc-section-number">2.8</span> Data frames</a></li>
<li><a href="2-9-classes-in-r.html#classes-in-r"><span class="toc-section-number">2.9</span> Classes in R</a></li>
<li><a href="2-10-tables-and-summary-statistics.html#tables-and-summary-statistics"><span class="toc-section-number">2.10</span> Tables and summary statistics</a></li>
<li><a href="2-11-plotting-data.html#plotting-data"><span class="toc-section-number">2.11</span> Plotting data</a></li>
<li><a href="2-12-exercises-getting-acquainted-with-r.html#exercises---getting-acquainted-with-r"><span class="toc-section-number">2.12</span> Exercises - Getting acquainted with R</a>
<ul>
<li><a href="2-12-exercises-getting-acquainted-with-r.html#background"><span class="toc-section-number">2.12.1</span> Background</a></li>
<li><a href="2-12-exercises-getting-acquainted-with-r.html#the-data"><span class="toc-section-number">2.12.2</span> The data</a></li>
<li><a href="2-12-exercises-getting-acquainted-with-r.html#try-the-following"><span class="toc-section-number">2.12.3</span> Try the following</a></li>
<li><a href="2-12-exercises-getting-acquainted-with-r.html#references"><span class="toc-section-number">2.12.4</span> References</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>I Data Wrangling</b></span></li>
<li><a href="3-data-wrangling-with-dplyr.html#data-wrangling-with-dplyr"><span class="toc-section-number">3</span> Data wrangling with dplyr</a>
<ul>
<li><a href="2-1-introduction.html#introduction"><span class="toc-section-number">3.1</span> Introduction</a></li>
<li><a href="3-2-select.html#select"><span class="toc-section-number">3.2</span> select</a></li>
<li><a href="3-3-filter.html#filter"><span class="toc-section-number">3.3</span> filter</a></li>
<li><a href="3-4-arrange.html#arrange"><span class="toc-section-number">3.4</span> arrange</a></li>
<li><a href="3-5-summarise-and-group-by.html#summarise-and-group_by"><span class="toc-section-number">3.5</span> summarise and group_by</a></li>
<li><a href="3-6-using-pipes-saving-data-.html#using-pipes-saving-data."><span class="toc-section-number">3.6</span> Using pipes, saving data.</a></li>
<li><a href="3-7-exercises-data-wrangling.html#exercises---data-wrangling"><span class="toc-section-number">3.7</span> Exercises - data wrangling</a>
<ul>
<li><a href="3-7-exercises-data-wrangling.html#exploring-the-amniote-life-history-database"><span class="toc-section-number">3.7.1</span> Exploring the Amniote Life History Database</a></li>
</ul></li>
</ul></li>
<li><a href="4-combining-data-sets.html#combining-data-sets"><span class="toc-section-number">4</span> Combining data sets</a>
<ul>
<li><a href="4-1-exercise-joining-datasets.html#exercise---joining-datasets"><span class="toc-section-number">4.1</span> Exercise - joining datasets</a>
<ul>
<li><a href="2-12-exercises-getting-acquainted-with-r.html#the-data"><span class="toc-section-number">4.1.1</span> The data</a></li>
<li><a href="4-1-exercise-joining-datasets.html#the-bird-data"><span class="toc-section-number">4.1.2</span> The bird data</a></li>
<li><a href="4-1-exercise-joining-datasets.html#the-weather-data"><span class="toc-section-number">4.1.3</span> The weather data</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II Data visualisation</b></span></li>
<li><a href="5-visualising-data-with-ggplot2.html#visualising-data-with-ggplot2"><span class="toc-section-number">5</span> Visualising data with ggplot2</a>
<ul>
<li><a href="2-1-introduction.html#introduction"><span class="toc-section-number">5.1</span> Introduction</a></li>
<li><a href="5-2-histograms.html#histograms"><span class="toc-section-number">5.2</span> Histograms</a></li>
<li><a href="5-3-facets-splitting-data-across-panels.html#facets---splitting-data-across-panels"><span class="toc-section-number">5.3</span> “Facets” - splitting data across panels</a></li>
<li><a href="5-4-box-plots.html#box-plots"><span class="toc-section-number">5.4</span> box plots</a></li>
<li><a href="5-5-lines-and-points.html#lines-and-points"><span class="toc-section-number">5.5</span> lines and points</a></li>
<li><a href="5-6-scatter-plot.html#scatter-plot"><span class="toc-section-number">5.6</span> scatter plot</a></li>
</ul></li>
<li><a href="6-distributions-and-summarising-data.html#distributions-and-summarising-data"><span class="toc-section-number">6</span> Distributions and summarising data</a>
<ul>
<li><a href="2-1-introduction.html#introduction"><span class="toc-section-number">6.1</span> Introduction</a></li>
<li><a href="6-2-distributions.html#distributions"><span class="toc-section-number">6.2</span> Distributions</a></li>
<li><a href="6-3-normal-distribution.html#normal-distribution"><span class="toc-section-number">6.3</span> Normal distribution</a></li>
<li><a href="6-4-compare-normal-distributions.html#compare-normal-distributions"><span class="toc-section-number">6.4</span> Compare normal distributions</a></li>
<li><a href="6-5-the-poisson-distribution.html#the-poisson-distribution"><span class="toc-section-number">6.5</span> The Poisson distribution</a></li>
<li><a href="6-6-comparing-normal-and-poisson-distributions.html#comparing-normal-and-poisson-distributions"><span class="toc-section-number">6.6</span> Comparing normal and Poisson distributions</a></li>
</ul></li>
<li><a href="7-customising-your-plots.html#customising-your-plots"><span class="toc-section-number">7</span> Customising your plots</a>
<ul>
<li><a href="2-1-introduction.html#introduction"><span class="toc-section-number">7.1</span> Introduction</a></li>
<li><a href="7-2-a-basic-plot.html#a-basic-plot"><span class="toc-section-number">7.2</span> A basic plot</a></li>
<li><a href="7-3-axis-limits.html#axis-limits"><span class="toc-section-number">7.3</span> Axis limits</a></li>
<li><a href="7-4-transforming-the-axis-log-scale.html#transforming-the-axis-log-scale"><span class="toc-section-number">7.4</span> Transforming the axis (log scale)</a></li>
<li><a href="7-5-changing-the-axis-tick-marks.html#changing-the-axis-tick-marks"><span class="toc-section-number">7.5</span> Changing the axis tick marks</a></li>
<li><a href="7-6-axis-labels.html#axis-labels"><span class="toc-section-number">7.6</span> Axis labels</a></li>
<li><a href="7-7-colours.html#colours"><span class="toc-section-number">7.7</span> Colours</a></li>
<li><a href="7-8-themes.html#themes"><span class="toc-section-number">7.8</span> Themes</a></li>
<li><a href="7-9-moving-the-legend.html#moving-the-legend"><span class="toc-section-number">7.9</span> Moving the legend</a></li>
<li><a href="7-10-combining-multiple-plots.html#combining-multiple-plots"><span class="toc-section-number">7.10</span> Combining multiple plots</a></li>
<li><a href="7-11-saving-your-plot.html#saving-your-plot"><span class="toc-section-number">7.11</span> Saving your plot</a></li>
<li><a href="7-12-final-word-on-plots.html#final-word-on-plots"><span class="toc-section-number">7.12</span> Final word on plots</a></li>
</ul></li>
<li class="part"><span><b>III Statistics</b></span></li>
<li><a href="8-randomisation-tests.html#randomisation-tests"><span class="toc-section-number">8</span> Randomisation Tests</a>
<ul>
<li><a href="2-1-introduction.html#introduction"><span class="toc-section-number">8.1</span> Introduction</a></li>
<li><a href="8-2-the-example.html#the-example"><span class="toc-section-number">8.2</span> The example</a></li>
<li><a href="8-3-setting-up.html#setting-up"><span class="toc-section-number">8.3</span> Setting up</a></li>
<li><a href="8-4-calculate-the-observed-difference.html#calculate-the-observed-difference"><span class="toc-section-number">8.4</span> Calculate the observed difference</a></li>
<li><a href="8-5-null-distribution.html#null-distribution"><span class="toc-section-number">8.5</span> Null distribution</a></li>
<li><a href="8-6-testing-significance.html#testing-significance"><span class="toc-section-number">8.6</span> Testing significance</a></li>
<li><a href="8-7-testing-the-hypothesis.html#testing-the-hypothesis"><span class="toc-section-number">8.7</span> Testing the hypothesis</a></li>
<li><a href="8-8-writing-it-up.html#writing-it-up"><span class="toc-section-number">8.8</span> Writing it up</a></li>
<li><a href="8-9-paired-randomisation-tests.html#paired-randomisation-tests"><span class="toc-section-number">8.9</span> Paired Randomisation Tests</a>
<ul>
<li><a href="8-9-paired-randomisation-tests.html#plot-the-data"><span class="toc-section-number">8.9.1</span> Plot the data</a></li>
<li><a href="8-9-paired-randomisation-tests.html#the-paired-randomisation-test"><span class="toc-section-number">8.9.2</span> The paired randomisation test</a></li>
<li><a href="8-9-paired-randomisation-tests.html#plot-the-null-distribution"><span class="toc-section-number">8.9.3</span> Plot the null distribution</a></li>
<li><a href="8-9-paired-randomisation-tests.html#the-formal-hypothesis-test"><span class="toc-section-number">8.9.4</span> The formal hypothesis test</a></li>
</ul></li>
<li><a href="8-10-exercises-randomisation-tests.html#exercises---randomisation-tests"><span class="toc-section-number">8.10</span> Exercises - Randomisation tests</a>
<ul>
<li><a href="8-10-exercises-randomisation-tests.html#introduction-1"><span class="toc-section-number">8.10.1</span> Introduction</a></li>
<li><a href="8-10-exercises-randomisation-tests.html#your-task"><span class="toc-section-number">8.10.2</span> Your task</a></li>
</ul></li>
</ul></li>
<li><a href="9-comparing-two-means-with-a-t-test.html#comparing-two-means-with-a-t-test"><span class="toc-section-number">9</span> Comparing two means with a t-test</a>
<ul>
<li><a href="9-1-some-theory-.html#some-theory."><span class="toc-section-number">9.1</span> Some theory.</a></li>
<li><a href="9-2-one-sample-t-test.html#one-sample-t-test"><span class="toc-section-number">9.2</span> One sample t-test</a></li>
<li><a href="9-3-doing-it-by-hand-where-does-the-t-statistic-come-from.html#doing-it-by-hand---where-does-the-t-statistic-come-from"><span class="toc-section-number">9.3</span> Doing it “by hand” - where does the t-statistic come from?</a></li>
<li><a href="9-4-paired-t-test.html#paired-t-test"><span class="toc-section-number">9.4</span> Paired t-test</a></li>
<li><a href="9-5-a-paired-t-test-is-a-one-sample-test-.html#a-paired-t-test-is-a-one-sample-test."><span class="toc-section-number">9.5</span> A paired t-test is a one-sample test.</a></li>
<li><a href="9-6-two-sample-t-test.html#two-sample-t-test"><span class="toc-section-number">9.6</span> Two sample t-test</a></li>
<li><a href="9-7-t-tests-are-linear-models.html#t-tests-are-linear-models"><span class="toc-section-number">9.7</span> t-tests are linear models</a></li>
<li><a href="9-8-exercises-two-sample-t-test.html#exercises---two-sample-t-test"><span class="toc-section-number">9.8</span> Exercises - Two-sample t-test</a>
<ul>
<li><a href="9-8-exercises-two-sample-t-test.html#paired-t-test-1"><span class="toc-section-number">9.8.1</span> Paired t-test</a></li>
<li><a href="9-8-exercises-two-sample-t-test.html#optional-extra."><span class="toc-section-number">9.8.2</span> Optional extra.</a></li>
</ul></li>
</ul></li>
<li><a href="10-linear-models-with-a-single-categorical-explanatory-variable.html#linear-models-with-a-single-categorical-explanatory-variable"><span class="toc-section-number">10</span> Linear models with a single categorical explanatory variable</a>
<ul>
<li><a href="2-1-introduction.html#introduction"><span class="toc-section-number">10.1</span> Introduction</a></li>
<li><a href="10-2-one-way-anova.html#one-way-anova"><span class="toc-section-number">10.2</span> One-way ANOVA</a></li>
<li><a href="10-3-fitting-an-anova-in-r.html#fitting-an-anova-in-r"><span class="toc-section-number">10.3</span> Fitting an ANOVA in R</a></li>
<li><a href="10-4-where-are-the-differences.html#where-are-the-differences"><span class="toc-section-number">10.4</span> Where are the differences?</a></li>
<li><a href="10-5-tukeys-honestly-significant-difference-hsd.html#tukeys-honestly-significant-difference-hsd"><span class="toc-section-number">10.5</span> Tukey’s Honestly Significant Difference (HSD)</a></li>
<li><a href="10-6-anova-calculation-by-hand-optional.html#anova-calculation-by-hand-optional"><span class="toc-section-number">10.6</span> ANOVA calculation “by hand” (optional)</a></li>
</ul></li>
<li><a href="11-linear-models-with-a-several-categorical-explanatory-variables.html#linear-models-with-a-several-categorical-explanatory-variables"><span class="toc-section-number">11</span> Linear models with a several categorical explanatory variables</a>
<ul>
<li><a href="2-12-exercises-getting-acquainted-with-r.html#background"><span class="toc-section-number">11.1</span> Background</a></li>
<li><a href="11-2-fitting-a-two-way-anova-model.html#fitting-a-two-way-anova-model"><span class="toc-section-number">11.2</span> Fitting a two-way ANOVA model</a></li>
<li><a href="11-3-summarising-the-model-anova.html#summarising-the-model-anova"><span class="toc-section-number">11.3</span> Summarising the model (<code>anova</code>)</a></li>
<li><a href="11-4-summarising-the-model-summary.html#summarising-the-model-summary"><span class="toc-section-number">11.4</span> Summarising the model (<code>summary</code>)</a></li>
<li><a href="11-5-a-2-way-anova-on-a-fish-behaviour-study.html#a-2-way-anova-on-a-fish-behaviour-study"><span class="toc-section-number">11.5</span> A 2-way ANOVA on a fish behaviour study</a>
<ul>
<li><a href="11-5-a-2-way-anova-on-a-fish-behaviour-study.html#background-1"><span class="toc-section-number">11.5.1</span> Background</a></li>
<li><a href="8-10-exercises-randomisation-tests.html#your-task"><span class="toc-section-number">11.5.2</span> Your task</a></li>
</ul></li>
</ul></li>
<li><a href="12-linear-models-with-a-single-continuous-explanatory-variable.html#linear-models-with-a-single-continuous-explanatory-variable"><span class="toc-section-number">12</span> Linear models with a single continuous explanatory variable</a>
<ul>
<li><a href="2-12-exercises-getting-acquainted-with-r.html#background"><span class="toc-section-number">12.1</span> Background</a></li>
<li><a href="12-2-some-theory.html#some-theory"><span class="toc-section-number">12.2</span> Some theory</a></li>
<li><a href="12-3-evaluating-a-hypothesis-with-a-linear-regression-model.html#evaluating-a-hypothesis-with-a-linear-regression-model"><span class="toc-section-number">12.3</span> Evaluating a hypothesis with a linear regression model</a></li>
<li><a href="12-4-assumptions.html#assumptions"><span class="toc-section-number">12.4</span> Assumptions</a></li>
<li><a href="12-5-an-example-using-r.html#an-example-using-r"><span class="toc-section-number">12.5</span> An example using R</a></li>
<li><a href="12-6-exercises-linear-regression.html#exercises---linear-regression"><span class="toc-section-number">12.6</span> Exercises - Linear Regression</a>
<ul>
<li><a href="11-5-a-2-way-anova-on-a-fish-behaviour-study.html#background-1"><span class="toc-section-number">12.6.1</span> Background</a></li>
<li><a href="8-10-exercises-randomisation-tests.html#your-task"><span class="toc-section-number">12.6.2</span> Your task</a></li>
</ul></li>
</ul></li>
<li><a href="13-linear-models-with-categorical-and-continuous-explanatory-variables.html#linear-models-with-categorical-and-continuous-explanatory-variables"><span class="toc-section-number">13</span> Linear models with categorical and continuous explanatory variables</a>
<ul>
<li><a href="2-12-exercises-getting-acquainted-with-r.html#background"><span class="toc-section-number">13.1</span> Background</a></li>
<li><a href="13-2-the-height-hand-width-example-.html#the-height-hand-width-example."><span class="toc-section-number">13.2</span> The height ~ hand width example.</a></li>
<li><a href="13-3-summarising-with-anova.html#summarising-with-anova"><span class="toc-section-number">13.3</span> Summarising with <code>anova</code></a></li>
<li><a href="13-4-the-summary-of-coefficients-summary.html#the-summary-of-coefficients-summary"><span class="toc-section-number">13.4</span> The summary of coefficients (<code>summary</code>)</a></li>
<li><a href="13-5-simplifying-the-model.html#simplifying-the-model"><span class="toc-section-number">13.5</span> Simplifying the model</a></li>
</ul></li>
<li><a href="14-generalised-linear-models.html#generalised-linear-models"><span class="toc-section-number">14</span> Generalised linear models</a>
<ul>
<li><a href="14-1-count-data-with-poisson-errors-.html#count-data-with-poisson-errors."><span class="toc-section-number">14.1</span> Count data with Poisson errors.</a>
<ul>
<li><a href="14-1-count-data-with-poisson-errors-.html#example-number-of-offspring-in-foxes."><span class="toc-section-number">14.1.1</span> Example: Number of offspring in foxes.</a></li>
<li><a href="14-1-count-data-with-poisson-errors-.html#example-cancer-clusters"><span class="toc-section-number">14.1.2</span> Example: Cancer clusters</a></li>
</ul></li>
</ul></li>
<li><a href="15-extending-use-cases-of-glm.html#extending-use-cases-of-glm"><span class="toc-section-number">15</span> Extending use cases of GLM</a>
<ul>
<li><a href="15-1-logistic-regression-with-binary-01-data.html#logistic-regression-with-binary-01-data"><span class="toc-section-number">15.1</span> Logistic regression with binary (0/1) data</a></li>
<li><a href="15-2-example-species-presenceabsence-data.html#example-species-presenceabsence-data"><span class="toc-section-number">15.2</span> Example: species presence/absence data</a></li>
<li><a href="15-3-binomial-regression-with-proportionratio-data.html#binomial-regression-with-proportionratio-data"><span class="toc-section-number">15.3</span> Binomial regression with proportion/ratio data</a>
<ul>
<li><a href="15-3-binomial-regression-with-proportionratio-data.html#example-sex-ratios"><span class="toc-section-number">15.3.1</span> Example: sex ratios</a></li>
</ul></li>
</ul></li>
<li><a href="16-power-and-study-design.html#power-and-study-design"><span class="toc-section-number">16</span> Power and study design</a>
<ul>
<li><a href="16-1-power-analysis-by-simulation.html#power-analysis-by-simulation"><span class="toc-section-number">16.1</span> Power analysis by simulation</a></li>
</ul></li>
<li class="part"><span><b>IV Coming soon(ish)</b></span></li>
<li><a href="17-coming-soon-maybe.html#coming-soon-maybe"><span class="toc-section-number">17</span> Coming soon (maybe)!</a>
<ul>
<li><a href="17-1-multivariate-statistics.html#multivariate-statistics"><span class="toc-section-number">17.1</span> Multivariate statistics</a></li>
<li><a href="17-2-transforming-variables.html#transforming-variables"><span class="toc-section-number">17.2</span> Transforming variables</a></li>
<li><a href="17-3-non-linear-regression.html#non-linear-regression"><span class="toc-section-number">17.3</span> Non-linear regression</a></li>
<li><a href="17-4-nested-or-blocked-study-designs.html#nested-or-blocked-study-designs"><span class="toc-section-number">17.4</span> Nested or blocked study designs</a></li>
</ul></li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<div id="count-data-with-poisson-errors." class="section level2" number="14.1">
<h2><span class="header-section-number">14.1</span> Count data with Poisson errors.</h2>
<p>The most common kind of count data where Poisson errors would be expected are frequencies of an event: we know how many times an event happened, but not how many times it did not happen (e.g. births, deaths, lightning strikes).</p>
<p>In these cases:</p>
<ul>
<li>Linear model could lead to negative counts.</li>
<li>Variance of response likely to increase with mean (it usually does with count data).</li>
<li>Errors are non-normal.</li>
<li>Zeros difficult to deal with by transformation (e.g. log(0) = -Inf).</li>
<li>Other error families do not allow zero values.</li>
</ul>
<p>The standard (“canonical”) link used with the Poisson error family is the log link. The log link ensures that all fitted (i.e. predicted) values are positive, while the Poisson errors take account of the fact that the data are integer and the variance scales 1:1 with the mean (i.e. variance increases linearly and is equal to the mean). There are other potential link and error families that <em>could</em> be used with this kind of data, but we’ll stick with the standard ones here. Lets look at a couple of examples…</p>
<div id="example-number-of-offspring-in-foxes." class="section level3" number="14.1.1">
<h3><span class="header-section-number">14.1.1</span> Example: Number of offspring in foxes.</h3>
<p>This example uses the <code>fox.csv</code> data set. This data set gives the number of offspring produced by a group of foxes, alongside the weight (in kg) of the mothers. Let’s import and plot the data.</p>
<p><img src="BB852_files/figure-html/unnamed-chunk-231-1.png" width="480" style="display: block; margin: auto;" /></p>
<p>The first thing to notice is that, like all count data, the data are formed into horizontal rows of data reflecting the fact that the response data are integer values. There is clearly an increasing pattern, but how can we formally test for a statistical relationship. It is obvious that fitting an ordinary linear model though this data would not be the right approach: this would lead to the prediction of negative number of offspring for small foxes, and also, the variance appears to increase with weight/number of offpspring. Therefore this is a good candidate for a GLM. The data are bounded at 0, and are integer values, and for this reason the usual approach would be to fit a GLM with Poisson errors (and the standard log link).</p>
<div class="sourceCode" id="cb405"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb405-1"><a href="14-1-count-data-with-poisson-errors-.html#cb405-1" aria-hidden="true"></a>mod1 &lt;-<span class="st"> </span><span class="kw">glm</span>(noffspring <span class="op">~</span><span class="st"> </span>weight, <span class="dt">data =</span> fox, <span class="dt">family =</span> poisson)</span></code></pre></div>
<p>After fitting the model it is a good idea to look at the model diagnostics, using <code>autoplot</code> from the <code>ggfortify</code> package.</p>
<p><img src="BB852_files/figure-html/unnamed-chunk-233-1.png" width="384" style="display: block; margin: auto;" /></p>
<p>Now we can ask for the Analysis of Variance table for this model. This is exactly the same procedure as for the previous linear models (ANOVA, ANCOVA etc.) except for GLMs one must also specify that you would like to see the results of significance tests using hte <code>test = "F"</code> or <code>test = "Chi"</code>. For Poisson and binomial GLMs the chi-squared test is most appropriate while for gaussian (normal), quasibinomial and quasipoisson models the F test is most appropriate.</p>
<div class="sourceCode" id="cb406"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb406-1"><a href="14-1-count-data-with-poisson-errors-.html#cb406-1" aria-hidden="true"></a><span class="kw">anova</span>(mod1,<span class="dt">test =</span> <span class="st">&quot;Chi&quot;</span>)</span></code></pre></div>
<pre><code>## Analysis of Deviance Table
## 
## Model: poisson, link: log
## 
## Response: noffspring
## 
## Terms added sequentially (first to last)
## 
## 
##        Df Deviance Resid. Df Resid. Dev  Pr(&gt;Chi)    
## NULL                      99     166.84              
## weight  1   44.124        98     122.72 3.082e-11 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>This summary table tells us that the single explanatory variable (<code>weight</code>) is fantastically important (p-value is very small indeed).</p>
<p>We can then ask for the coefficient summary using <code>summary</code>.</p>
<div class="sourceCode" id="cb408"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb408-1"><a href="14-1-count-data-with-poisson-errors-.html#cb408-1" aria-hidden="true"></a><span class="kw">summary</span>(mod1)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = noffspring ~ weight, family = poisson, data = fox)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.3891  -0.9719  -0.1183   0.5897   2.3426  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -0.74981    0.31107  -2.410   0.0159 *  
## weight       0.63239    0.09502   6.655 2.83e-11 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 166.85  on 99  degrees of freedom
## Residual deviance: 122.72  on 98  degrees of freedom
## AIC: 405.56
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>The model coefficients and their standard errors are given on the scale of the linear predictor. They tell us that there is a significant association between the weight of the fox mother and the number of offspring she will produce: larger foxes produce more offspring. Because the coefficients are given on the scale of the linear predictor rather than on the real scale it is useful to plot predictions of the model to visualise the relationship.</p>
<p>To do that we must (1) tell the model what to predict <code>from</code> i.e. we must provide a suitable sequence of numbers to predict from using <code>seq</code>, (2) use the <code>predict</code> function to predict values (<code>fit</code>) from the model. We use the argument <code>type = "response"</code> to tell the function that we want the preductions on the backtransformed (real) scale rather than on the scale of the linear predictor. We add the argument <code>se.fit = TRUE</code> to tell the function to give us the standard error estimates of the fit. The <code>se.fit</code> values are added or subtracted from the fit to obtain the plus/minus standard errors. We can multiply these by 1.96 to get the 95% confidence intervals of the fitted values.</p>
<div class="sourceCode" id="cb410"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb410-1"><a href="14-1-count-data-with-poisson-errors-.html#cb410-1" aria-hidden="true"></a><span class="co">#Vector to predict from</span></span>
<span id="cb410-2"><a href="14-1-count-data-with-poisson-errors-.html#cb410-2" aria-hidden="true"></a>newData &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">weight =</span> <span class="kw">seq</span>(<span class="fl">1.7</span>,<span class="fl">4.4</span>,<span class="fl">0.01</span>))</span>
<span id="cb410-3"><a href="14-1-count-data-with-poisson-errors-.html#cb410-3" aria-hidden="true"></a></span>
<span id="cb410-4"><a href="14-1-count-data-with-poisson-errors-.html#cb410-4" aria-hidden="true"></a><span class="co">#Predicted values (and SE)</span></span>
<span id="cb410-5"><a href="14-1-count-data-with-poisson-errors-.html#cb410-5" aria-hidden="true"></a>predVals &lt;-<span class="st"> </span><span class="kw">predict</span>(mod1,newData,<span class="dt">type=</span><span class="st">&quot;response&quot;</span>,<span class="dt">se.fit =</span> <span class="ot">TRUE</span>)</span>
<span id="cb410-6"><a href="14-1-count-data-with-poisson-errors-.html#cb410-6" aria-hidden="true"></a></span>
<span id="cb410-7"><a href="14-1-count-data-with-poisson-errors-.html#cb410-7" aria-hidden="true"></a><span class="co">#Create new data for the predicted fit line</span></span>
<span id="cb410-8"><a href="14-1-count-data-with-poisson-errors-.html#cb410-8" aria-hidden="true"></a>newData &lt;-<span class="st"> </span>newData <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb410-9"><a href="14-1-count-data-with-poisson-errors-.html#cb410-9" aria-hidden="true"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">noffspring =</span> predVals<span class="op">$</span>fit) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb410-10"><a href="14-1-count-data-with-poisson-errors-.html#cb410-10" aria-hidden="true"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">ymin =</span> predVals<span class="op">$</span>fit <span class="op">-</span><span class="st"> </span><span class="fl">1.96</span><span class="op">*</span>predVals<span class="op">$</span>se.fit) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb410-11"><a href="14-1-count-data-with-poisson-errors-.html#cb410-11" aria-hidden="true"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">ymax =</span> predVals<span class="op">$</span>fit <span class="op">+</span><span class="st"> </span><span class="fl">1.96</span><span class="op">*</span>predVals<span class="op">$</span>se.fit)</span></code></pre></div>
<p>Take a look at this data to make sure it looks OK.</p>
<div class="sourceCode" id="cb411"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb411-1"><a href="14-1-count-data-with-poisson-errors-.html#cb411-1" aria-hidden="true"></a><span class="kw">head</span>(newData)</span></code></pre></div>
<pre><code>##   weight noffspring      ymin     ymax
## 1   1.70   1.384392 0.9649333 1.803850
## 2   1.71   1.393174 0.9734837 1.812865
## 3   1.72   1.402013 0.9821017 1.821924
## 4   1.73   1.410907 0.9907879 1.831026
## 5   1.74   1.419858 0.9995426 1.840173
## 6   1.75   1.428865 1.0083663 1.849364</code></pre>
<p>This looks OK. Now we can plot the data and add a the model fit line, and a “ribbon” representing the errors (the 95% confidence interval for the line).</p>
<p><img src="BB852_files/figure-html/unnamed-chunk-238-1.png" width="480" style="display: block; margin: auto;" /></p>
<p>So we could summarise this something like this:</p>
<p>Methods: <em>I modelled the association between mother’s weight and number of pups produced using a generalised linear model with a log link and Poisson error structure. This is appropriate because the data are count data (number of pups) that are bounded at 0 with increasing variance with increased maternal weight.</em></p>
<p>Results: <em>The GLM showed that maternal weight was significantly associated with the number of pups produced (GLM: Null Deviance = 166.8, Residual Deviance = 122.7, d.f. = 1 and 98, p &lt;0.001). The slope of the relationship was 0.63 (on the log scale). The equation of the best fit line was log(nOffspring) = -0.75 + 0.63<span class="math inline">\(\times\)</span>MotherWeight (see Figure XXX)</em></p>
</div>
<div id="example-cancer-clusters" class="section level3" number="14.1.2">
<h3><span class="header-section-number">14.1.2</span> Example: Cancer clusters</h3>
<p>This data show counts of prostate cancer and distance from a nuclear processing plant. Lets take a look at the data.</p>
<p>Let’s first import the data and use summary to examine it by plotting it:</p>
<p>First we can see that there are no negative count values.</p>
<p><img src="BB852_files/figure-html/unnamed-chunk-239-1.png" width="480" style="display: block; margin: auto;" /></p>
<p>Again, you will notice that the data are formed into horizontal rows of integer response values. There are lots of zero values at all distances, but the biggest cluster (6 cases), is very close to the plant. But is there a relationship between the distance from the nuclear plant and the number of cancers?</p>
<p>Let’s fit a Generalised Linear Model to find out. As before will assume that the error is Poisson (that they variance increases directly in proportion to the mean), and we will use the standard log link to ensure that we don’t predict negative values:</p>
<div class="sourceCode" id="cb413"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb413-1"><a href="14-1-count-data-with-poisson-errors-.html#cb413-1" aria-hidden="true"></a>mod1 &lt;-<span class="st"> </span><span class="kw">glm</span>(Cancers <span class="op">~</span><span class="st"> </span>Distance, <span class="dt">data =</span> cancer, <span class="dt">family =</span> poisson)</span></code></pre></div>
<p>Next, plot the diagnostic plots.</p>
<p><img src="BB852_files/figure-html/unnamed-chunk-241-1.png" width="384" style="display: block; margin: auto;" /></p>
<p>These look a bit dodgy, but we’ll stick with it for the moment.</p>
<p>Next ask for the Analysis of Variance table.</p>
<div class="sourceCode" id="cb414"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb414-1"><a href="14-1-count-data-with-poisson-errors-.html#cb414-1" aria-hidden="true"></a><span class="kw">anova</span>(mod1,<span class="dt">test =</span> <span class="st">&quot;Chi&quot;</span>)</span></code></pre></div>
<pre><code>## Analysis of Deviance Table
## 
## Model: poisson, link: log
## 
## Response: Cancers
## 
## Terms added sequentially (first to last)
## 
## 
##          Df Deviance Resid. Df Resid. Dev Pr(&gt;Chi)  
## NULL                        93     149.48           
## Distance  1   2.8408        92     146.64   0.0919 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The ANOVA table tells us that there is no significant effect of the Distance variable. In other words a model that includes the <code>Distance</code> term does not explain significantly more variation than the <code>NULL</code> model that includes no terms and instead assumes that variation in cancer incidence is simply caused by random variation.</p>
<p>We needn’t go further with this model, but go ahead and plot the model in any case (just for practice).</p>
<div class="sourceCode" id="cb416"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb416-1"><a href="14-1-count-data-with-poisson-errors-.html#cb416-1" aria-hidden="true"></a><span class="kw">summary</span>(mod1)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Cancers ~ Distance, family = poisson, data = cancer)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.5504  -1.3491  -1.1553   0.3877   3.1304  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)  
## (Intercept)  0.186865   0.188728   0.990   0.3221  
## Distance    -0.006138   0.003667  -1.674   0.0941 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 149.48  on 93  degrees of freedom
## Residual deviance: 146.64  on 92  degrees of freedom
## AIC: 262.41
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>Use the approach from the fox example as guidance to make a plot with a fit line.</p>

</div>
</div>
<!-- </div> -->
<p style="text-align: center;">
<a href="14-generalised-linear-models.html"><button class="btn btn-default">Previous</button></a>
<a href="15-extending-use-cases-of-glm.html"><button class="btn btn-default">Next</button></a>
</p>
</div>
</div>


</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

</body>
</html>
