<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 25 An example of a past Exam (2020) | BB852 - Data handling, visualisation and statistics</title>
  <meta name="description" content="Course book for BB852 at the Biology Department, University of Southern Denmark" />
  <meta name="generator" content="bookdown 0.27 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 25 An example of a past Exam (2020) | BB852 - Data handling, visualisation and statistics" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Course book for BB852 at the Biology Department, University of Southern Denmark" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 25 An example of a past Exam (2020) | BB852 - Data handling, visualisation and statistics" />
  
  <meta name="twitter:description" content="Course book for BB852 at the Biology Department, University of Southern Denmark" />
  

<meta name="author" content="Owen R. Jones" />


<meta name="date" content="2022-11-02" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="exercise-solutions.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/tabwid-1.0.0/tabwid.css" rel="stylesheet" />
<link href="libs/tabwid-1.0.0/scrool.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">BB852</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Preface</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#data-wrangling"><i class="fa fa-check"></i><b>1.1</b> Data wrangling</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#data-visualisation"><i class="fa fa-check"></i><b>1.2</b> Data visualisation</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#statistics"><i class="fa fa-check"></i><b>1.3</b> Statistics</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#data-sources"><i class="fa fa-check"></i><b>1.4</b> Data sources</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#your-instructors"><i class="fa fa-check"></i><b>1.5</b> Your instructors</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#expectations"><i class="fa fa-check"></i><b>1.6</b> Expectations</a></li>
<li class="chapter" data-level="1.7" data-path="index.html"><a href="index.html#your-feedback"><i class="fa fa-check"></i><b>1.7</b> Your feedback</a></li>
<li class="chapter" data-level="1.8" data-path="index.html"><a href="index.html#assessment"><i class="fa fa-check"></i><b>1.8</b> Assessment</a></li>
<li class="chapter" data-level="1.9" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i><b>1.9</b> Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="schedule.html"><a href="schedule.html"><i class="fa fa-check"></i><b>2</b> Schedule</a></li>
<li class="chapter" data-level="3" data-path="additional-recommended-reading.html"><a href="additional-recommended-reading.html"><i class="fa fa-check"></i><b>3</b> Additional recommended reading</a></li>
<li class="chapter" data-level="4" data-path="an-r-refresher.html"><a href="an-r-refresher.html"><i class="fa fa-check"></i><b>4</b> An R refresher</a>
<ul>
<li class="chapter" data-level="4.1" data-path="an-r-refresher.html"><a href="an-r-refresher.html#getting-started-with-r"><i class="fa fa-check"></i><b>4.1</b> Getting started with R</a></li>
<li class="chapter" data-level="4.2" data-path="an-r-refresher.html"><a href="an-r-refresher.html#getting-help"><i class="fa fa-check"></i><b>4.2</b> Getting help</a></li>
<li class="chapter" data-level="4.3" data-path="an-r-refresher.html"><a href="an-r-refresher.html#r-as-a-fancy-calculator"><i class="fa fa-check"></i><b>4.3</b> R as a fancy calculator</a></li>
<li class="chapter" data-level="4.4" data-path="an-r-refresher.html"><a href="an-r-refresher.html#objects-in-r"><i class="fa fa-check"></i><b>4.4</b> Objects in R</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="manipulating-objects.html"><a href="manipulating-objects.html"><i class="fa fa-check"></i><b>5</b> Manipulating objects</a>
<ul>
<li class="chapter" data-level="5.1" data-path="manipulating-objects.html"><a href="manipulating-objects.html#missing-values-infinity-and-non-numbers"><i class="fa fa-check"></i><b>5.1</b> Missing values, infinity and “non-numbers”</a></li>
<li class="chapter" data-level="5.2" data-path="manipulating-objects.html"><a href="manipulating-objects.html#basic-information-about-objects"><i class="fa fa-check"></i><b>5.2</b> Basic information about objects</a></li>
<li class="chapter" data-level="5.3" data-path="manipulating-objects.html"><a href="manipulating-objects.html#data-frames"><i class="fa fa-check"></i><b>5.3</b> Data frames</a></li>
<li class="chapter" data-level="5.4" data-path="manipulating-objects.html"><a href="manipulating-objects.html#classes-in-r"><i class="fa fa-check"></i><b>5.4</b> Classes in R</a></li>
<li class="chapter" data-level="5.5" data-path="manipulating-objects.html"><a href="manipulating-objects.html#organising-your-work"><i class="fa fa-check"></i><b>5.5</b> Organising your work</a></li>
<li class="chapter" data-level="5.6" data-path="manipulating-objects.html"><a href="manipulating-objects.html#inspecting-the-data"><i class="fa fa-check"></i><b>5.6</b> Inspecting the data</a></li>
<li class="chapter" data-level="5.7" data-path="manipulating-objects.html"><a href="manipulating-objects.html#classes-in-r-1"><i class="fa fa-check"></i><b>5.7</b> “Classes” in R</a></li>
<li class="chapter" data-level="5.8" data-path="manipulating-objects.html"><a href="manipulating-objects.html#tables-and-summary-statistics"><i class="fa fa-check"></i><b>5.8</b> Tables and summary statistics</a></li>
<li class="chapter" data-level="5.9" data-path="manipulating-objects.html"><a href="manipulating-objects.html#plotting-data"><i class="fa fa-check"></i><b>5.9</b> Plotting data</a></li>
<li class="chapter" data-level="5.10" data-path="manipulating-objects.html"><a href="manipulating-objects.html#r-packages"><i class="fa fa-check"></i><b>5.10</b> R Packages</a></li>
<li class="chapter" data-level="5.11" data-path="manipulating-objects.html"><a href="manipulating-objects.html#exercise-californian-bird-diversity"><i class="fa fa-check"></i><b>5.11</b> Exercise: Californian bird diversity</a>
<ul>
<li class="chapter" data-level="5.11.1" data-path="manipulating-objects.html"><a href="manipulating-objects.html#the-data"><i class="fa fa-check"></i><b>5.11.1</b> The data</a></li>
<li class="chapter" data-level="5.11.2" data-path="manipulating-objects.html"><a href="manipulating-objects.html#try-the-following"><i class="fa fa-check"></i><b>5.11.2</b> Try the following</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html"><i class="fa fa-check"></i><b>6</b> Tips and tricks</a>
<ul>
<li class="chapter" data-level="6.1" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#appearance"><i class="fa fa-check"></i><b>6.1</b> Appearance</a></li>
<li class="chapter" data-level="6.2" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#shortcuts"><i class="fa fa-check"></i><b>6.2</b> Shortcuts</a></li>
<li class="chapter" data-level="6.3" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#code-style"><i class="fa fa-check"></i><b>6.3</b> Code style</a></li>
<li class="chapter" data-level="6.4" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#the-plots-pane"><i class="fa fa-check"></i><b>6.4</b> The plots pane</a></li>
<li class="chapter" data-level="6.5" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#tables"><i class="fa fa-check"></i><b>6.5</b> Tables</a></li>
<li class="chapter" data-level="6.6" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#importing-data-from-text-files"><i class="fa fa-check"></i><b>6.6</b> Importing data from text files</a></li>
<li class="chapter" data-level="6.7" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#importing-data-from-excel"><i class="fa fa-check"></i><b>6.7</b> Importing data from Excel</a></li>
<li class="chapter" data-level="6.8" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#numbers"><i class="fa fa-check"></i><b>6.8</b> Numbers</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="paths-and-projects.html"><a href="paths-and-projects.html"><i class="fa fa-check"></i><b>7</b> Paths and projects</a>
<ul>
<li class="chapter" data-level="7.1" data-path="paths-and-projects.html"><a href="paths-and-projects.html#file-structure"><i class="fa fa-check"></i><b>7.1</b> File structure</a></li>
<li class="chapter" data-level="7.2" data-path="paths-and-projects.html"><a href="paths-and-projects.html#paths-and-the-command-line"><i class="fa fa-check"></i><b>7.2</b> Paths and the command line</a></li>
<li class="chapter" data-level="7.3" data-path="paths-and-projects.html"><a href="paths-and-projects.html#r-and-file-structure"><i class="fa fa-check"></i><b>7.3</b> R and file structure</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="paths-and-projects.html"><a href="paths-and-projects.html#setting-the-working-directory"><i class="fa fa-check"></i><b>7.3.1</b> Setting the working directory</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="paths-and-projects.html"><a href="paths-and-projects.html#projects-in-r"><i class="fa fa-check"></i><b>7.4</b> Projects in R</a></li>
</ul></li>
<li class="part"><span><b>I Data Wrangling</b></span></li>
<li class="chapter" data-level="8" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html"><i class="fa fa-check"></i><b>8</b> Data wrangling with <code>dplyr</code></a>
<ul>
<li class="chapter" data-level="8.1" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#select"><i class="fa fa-check"></i><b>8.1</b> <code>select</code></a></li>
<li class="chapter" data-level="8.2" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#filter"><i class="fa fa-check"></i><b>8.2</b> <code>filter</code></a></li>
<li class="chapter" data-level="8.3" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#arrange"><i class="fa fa-check"></i><b>8.3</b> <code>arrange</code></a></li>
<li class="chapter" data-level="8.4" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#summarise-and-group_by"><i class="fa fa-check"></i><b>8.4</b> <code>summarise</code> and <code>group_by</code></a></li>
<li class="chapter" data-level="8.5" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#using-pipes-saving-data."><i class="fa fa-check"></i><b>8.5</b> Using pipes, saving data.</a></li>
<li class="chapter" data-level="8.6" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#exercise-wrangling-the-amniote-life-history-database"><i class="fa fa-check"></i><b>8.6</b> Exercise: Wrangling the Amniote Life History Database</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="combining-data-sets.html"><a href="combining-data-sets.html"><i class="fa fa-check"></i><b>9</b> Combining data sets</a>
<ul>
<li class="chapter" data-level="9.1" data-path="combining-data-sets.html"><a href="combining-data-sets.html#using-join"><i class="fa fa-check"></i><b>9.1</b> Using <code>join</code></a></li>
<li class="chapter" data-level="9.2" data-path="combining-data-sets.html"><a href="combining-data-sets.html#using-pivot_longer"><i class="fa fa-check"></i><b>9.2</b> Using <code>pivot_longer</code></a></li>
<li class="chapter" data-level="9.3" data-path="combining-data-sets.html"><a href="combining-data-sets.html#exercise-temperature-effects-on-egg-laying-dates"><i class="fa fa-check"></i><b>9.3</b> Exercise: Temperature effects on egg laying dates</a></li>
</ul></li>
<li class="part"><span><b>II Data visualisation</b></span></li>
<li class="chapter" data-level="10" data-path="visualising-data-with-ggplot2.html"><a href="visualising-data-with-ggplot2.html"><i class="fa fa-check"></i><b>10</b> Visualising data with <code>ggplot2</code></a>
<ul>
<li class="chapter" data-level="10.1" data-path="visualising-data-with-ggplot2.html"><a href="visualising-data-with-ggplot2.html#histograms"><i class="fa fa-check"></i><b>10.1</b> Histograms</a></li>
<li class="chapter" data-level="10.2" data-path="visualising-data-with-ggplot2.html"><a href="visualising-data-with-ggplot2.html#facets---splitting-data-across-panels"><i class="fa fa-check"></i><b>10.2</b> “Facets” - splitting data across panels</a></li>
<li class="chapter" data-level="10.3" data-path="visualising-data-with-ggplot2.html"><a href="visualising-data-with-ggplot2.html#box-plots"><i class="fa fa-check"></i><b>10.3</b> Box plots</a></li>
<li class="chapter" data-level="10.4" data-path="visualising-data-with-ggplot2.html"><a href="visualising-data-with-ggplot2.html#lines-and-points"><i class="fa fa-check"></i><b>10.4</b> Lines and points</a></li>
<li class="chapter" data-level="10.5" data-path="visualising-data-with-ggplot2.html"><a href="visualising-data-with-ggplot2.html#scatter-plots"><i class="fa fa-check"></i><b>10.5</b> Scatter plots</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html"><i class="fa fa-check"></i><b>11</b> Distributions and summarising data</a>
<ul>
<li class="chapter" data-level="11.1" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#distributions"><i class="fa fa-check"></i><b>11.1</b> Distributions</a></li>
<li class="chapter" data-level="11.2" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#normal-distribution"><i class="fa fa-check"></i><b>11.2</b> Normal distribution</a></li>
<li class="chapter" data-level="11.3" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#comparing-normal-distributions"><i class="fa fa-check"></i><b>11.3</b> Comparing normal distributions</a></li>
<li class="chapter" data-level="11.4" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#poisson-distribution"><i class="fa fa-check"></i><b>11.4</b> Poisson distribution</a></li>
<li class="chapter" data-level="11.5" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#comparing-normal-and-poisson-distributions"><i class="fa fa-check"></i><b>11.5</b> Comparing normal and Poisson distributions</a></li>
<li class="chapter" data-level="11.6" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#the-law-of-large-numbers"><i class="fa fa-check"></i><b>11.6</b> The law of large numbers</a>
<ul>
<li class="chapter" data-level="11.6.1" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#coin-flipping"><i class="fa fa-check"></i><b>11.6.1</b> Coin flipping</a></li>
</ul></li>
<li class="chapter" data-level="11.7" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#exercise-virtual-dice"><i class="fa fa-check"></i><b>11.7</b> Exercise: Virtual dice</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html"><i class="fa fa-check"></i><b>12</b> Pimping your plots</a>
<ul>
<li class="chapter" data-level="12.1" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#a-basic-plot"><i class="fa fa-check"></i><b>12.1</b> A basic plot</a></li>
<li class="chapter" data-level="12.2" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#axis-limits"><i class="fa fa-check"></i><b>12.2</b> Axis limits</a></li>
<li class="chapter" data-level="12.3" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#transforming-the-axis-log-scale"><i class="fa fa-check"></i><b>12.3</b> Transforming the axis (log scale)</a></li>
<li class="chapter" data-level="12.4" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#changing-the-axis-tick-marks"><i class="fa fa-check"></i><b>12.4</b> Changing the axis tick marks</a></li>
<li class="chapter" data-level="12.5" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#axis-labels"><i class="fa fa-check"></i><b>12.5</b> Axis labels</a></li>
<li class="chapter" data-level="12.6" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#colours"><i class="fa fa-check"></i><b>12.6</b> Colours</a></li>
<li class="chapter" data-level="12.7" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#themes"><i class="fa fa-check"></i><b>12.7</b> Themes</a></li>
<li class="chapter" data-level="12.8" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#moving-the-legend"><i class="fa fa-check"></i><b>12.8</b> Moving the legend</a></li>
<li class="chapter" data-level="12.9" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#combining-multiple-plots"><i class="fa fa-check"></i><b>12.9</b> Combining multiple plots</a></li>
<li class="chapter" data-level="12.10" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#saving-your-plot"><i class="fa fa-check"></i><b>12.10</b> Saving your plot</a></li>
<li class="chapter" data-level="12.11" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#final-word-on-plots"><i class="fa fa-check"></i><b>12.11</b> Final word on plots</a></li>
</ul></li>
<li class="part"><span><b>III Statistics</b></span></li>
<li class="chapter" data-level="13" data-path="randomisation-tests.html"><a href="randomisation-tests.html"><i class="fa fa-check"></i><b>13</b> Randomisation Tests</a>
<ul>
<li class="chapter" data-level="13.1" data-path="randomisation-tests.html"><a href="randomisation-tests.html#randomisation-test-in-r"><i class="fa fa-check"></i><b>13.1</b> Randomisation test in R</a>
<ul>
<li class="chapter" data-level="13.1.1" data-path="randomisation-tests.html"><a href="randomisation-tests.html#calculate-the-observed-difference"><i class="fa fa-check"></i><b>13.1.1</b> Calculate the observed difference</a></li>
<li class="chapter" data-level="13.1.2" data-path="randomisation-tests.html"><a href="randomisation-tests.html#null-distribution"><i class="fa fa-check"></i><b>13.1.2</b> Null distribution</a></li>
<li class="chapter" data-level="13.1.3" data-path="randomisation-tests.html"><a href="randomisation-tests.html#testing-significance"><i class="fa fa-check"></i><b>13.1.3</b> Testing significance</a></li>
<li class="chapter" data-level="13.1.4" data-path="randomisation-tests.html"><a href="randomisation-tests.html#testing-the-hypothesis"><i class="fa fa-check"></i><b>13.1.4</b> Testing the hypothesis</a></li>
<li class="chapter" data-level="13.1.5" data-path="randomisation-tests.html"><a href="randomisation-tests.html#writing-it-up"><i class="fa fa-check"></i><b>13.1.5</b> Writing it up</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="randomisation-tests.html"><a href="randomisation-tests.html#paired-randomisation-tests"><i class="fa fa-check"></i><b>13.2</b> Paired Randomisation Tests</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="randomisation-tests.html"><a href="randomisation-tests.html#the-randomisation-test"><i class="fa fa-check"></i><b>13.2.1</b> The randomisation test</a></li>
<li class="chapter" data-level="13.2.2" data-path="randomisation-tests.html"><a href="randomisation-tests.html#null-distribution-1"><i class="fa fa-check"></i><b>13.2.2</b> Null distribution</a></li>
<li class="chapter" data-level="13.2.3" data-path="randomisation-tests.html"><a href="randomisation-tests.html#the-formal-hypothesis-test"><i class="fa fa-check"></i><b>13.2.3</b> The formal hypothesis test</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="randomisation-tests.html"><a href="randomisation-tests.html#exercise-sexual-selection-in-hercules-beetles"><i class="fa fa-check"></i><b>13.3</b> Exercise: Sexual selection in Hercules beetles</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html"><i class="fa fa-check"></i><b>14</b> t-test: Comparing two means</a>
<ul>
<li class="chapter" data-level="14.1" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#some-theory"><i class="fa fa-check"></i><b>14.1</b> Some theory</a></li>
<li class="chapter" data-level="14.2" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#one-sample-t-test"><i class="fa fa-check"></i><b>14.2</b> One sample t-test</a></li>
<li class="chapter" data-level="14.3" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#doing-it-by-hand---where-does-the-t-statistic-come-from"><i class="fa fa-check"></i><b>14.3</b> Doing it “by hand” - where does the t-statistic come from?</a></li>
<li class="chapter" data-level="14.4" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#paired-t-test"><i class="fa fa-check"></i><b>14.4</b> Paired t-test</a></li>
<li class="chapter" data-level="14.5" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#a-paired-t-test-is-a-one-sample-test."><i class="fa fa-check"></i><b>14.5</b> A paired t-test is a one-sample test.</a></li>
<li class="chapter" data-level="14.6" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#two-sample-t-test"><i class="fa fa-check"></i><b>14.6</b> Two sample t-test</a></li>
<li class="chapter" data-level="14.7" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#t-tests-are-linear-models"><i class="fa fa-check"></i><b>14.7</b> t-tests are linear models</a></li>
<li class="chapter" data-level="14.8" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#exercise-sex-differences-in-fine-motor-skills"><i class="fa fa-check"></i><b>14.8</b> Exercise: Sex differences in fine motor skills</a></li>
<li class="chapter" data-level="14.9" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#exercise-therapy-for-anorexia"><i class="fa fa-check"></i><b>14.9</b> Exercise: Therapy for anorexia</a></li>
<li class="chapter" data-level="14.10" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#exercise-compare-t-tests-with-randomisation-tests-optional"><i class="fa fa-check"></i><b>14.10</b> Exercise: Compare t-tests with randomisation tests (optional)</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><i class="fa fa-check"></i><b>15</b> ANOVA: Linear models with a single categorical explanatory variable</a>
<ul>
<li class="chapter" data-level="15.1" data-path="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#one-way-anova"><i class="fa fa-check"></i><b>15.1</b> One-way ANOVA</a></li>
<li class="chapter" data-level="15.2" data-path="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#fitting-an-anova-in-r"><i class="fa fa-check"></i><b>15.2</b> Fitting an ANOVA in R</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#where-are-the-differences"><i class="fa fa-check"></i><b>15.2.1</b> Where are the differences?</a></li>
<li class="chapter" data-level="15.2.2" data-path="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#tukeys-honestly-significant-difference-hsd"><i class="fa fa-check"></i><b>15.2.2</b> Tukey’s Honestly Significant Difference (HSD)</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#anova-calculation-by-hand."><i class="fa fa-check"></i><b>15.3</b> ANOVA calculation “by hand”.</a></li>
<li class="chapter" data-level="15.4" data-path="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#exercise-apple-tree-crop-yield"><i class="fa fa-check"></i><b>15.4</b> Exercise: Apple tree crop yield</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="linear-regression-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html"><i class="fa fa-check"></i><b>16</b> Linear regression: models with a single continuous explanatory variable</a>
<ul>
<li class="chapter" data-level="16.1" data-path="linear-regression-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#some-theory-1"><i class="fa fa-check"></i><b>16.1</b> Some theory</a></li>
<li class="chapter" data-level="16.2" data-path="linear-regression-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#evaluating-a-hypothesis-with-a-linear-regression-model"><i class="fa fa-check"></i><b>16.2</b> Evaluating a hypothesis with a linear regression model</a></li>
<li class="chapter" data-level="16.3" data-path="linear-regression-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#assumptions"><i class="fa fa-check"></i><b>16.3</b> Assumptions</a></li>
<li class="chapter" data-level="16.4" data-path="linear-regression-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#worked-example-height-hand-width-relationship"><i class="fa fa-check"></i><b>16.4</b> Worked example: height-hand width relationship</a></li>
<li class="chapter" data-level="16.5" data-path="linear-regression-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#exercise-chirping-crickets"><i class="fa fa-check"></i><b>16.5</b> Exercise: Chirping crickets</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html"><a href="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html"><i class="fa fa-check"></i><b>17</b> ANCOVA: Linear models with categorical and continuous explanatory variables</a>
<ul>
<li class="chapter" data-level="17.1" data-path="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html"><a href="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html#the-height-hand-width-example."><i class="fa fa-check"></i><b>17.1</b> The height ~ hand width example.</a></li>
<li class="chapter" data-level="17.2" data-path="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html"><a href="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html#summarising-with-anova"><i class="fa fa-check"></i><b>17.2</b> Summarising with <code>anova</code></a></li>
<li class="chapter" data-level="17.3" data-path="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html"><a href="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html#the-summary-of-coefficients-summary"><i class="fa fa-check"></i><b>17.3</b> The summary of coefficients (<code>summary</code>)</a></li>
<li class="chapter" data-level="17.4" data-path="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html"><a href="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html#simplifying-the-model"><i class="fa fa-check"></i><b>17.4</b> Simplifying the model</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html"><i class="fa fa-check"></i><b>18</b> n-way ANOVA: Linear models with &gt;1 categorical explanatory variables</a>
<ul>
<li class="chapter" data-level="18.1" data-path="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#fitting-a-two-way-anova-model"><i class="fa fa-check"></i><b>18.1</b> Fitting a two-way ANOVA model</a></li>
<li class="chapter" data-level="18.2" data-path="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#summarising-the-model-anova"><i class="fa fa-check"></i><b>18.2</b> Summarising the model (<code>anova</code>)</a></li>
<li class="chapter" data-level="18.3" data-path="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#summarising-the-model-summary"><i class="fa fa-check"></i><b>18.3</b> Summarising the model (<code>summary</code>)</a></li>
<li class="chapter" data-level="18.4" data-path="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#exercise-fish-behaviour"><i class="fa fa-check"></i><b>18.4</b> Exercise: Fish behaviour</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="evaluating-linear-models.html"><a href="evaluating-linear-models.html"><i class="fa fa-check"></i><b>19</b> Evaluating linear models</a>
<ul>
<li class="chapter" data-level="19.1" data-path="evaluating-linear-models.html"><a href="evaluating-linear-models.html#r-squared-value"><i class="fa fa-check"></i><b>19.1</b> R-squared value</a></li>
<li class="chapter" data-level="19.2" data-path="evaluating-linear-models.html"><a href="evaluating-linear-models.html#akaike-information-criterion-aic"><i class="fa fa-check"></i><b>19.2</b> Akaike Information Criterion (AIC)</a></li>
<li class="chapter" data-level="19.3" data-path="evaluating-linear-models.html"><a href="evaluating-linear-models.html#variance-partitioning"><i class="fa fa-check"></i><b>19.3</b> Variance partitioning</a></li>
<li class="chapter" data-level="19.4" data-path="evaluating-linear-models.html"><a href="evaluating-linear-models.html#conclusion"><i class="fa fa-check"></i><b>19.4</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html"><i class="fa fa-check"></i><b>20</b> Generalised linear models</a>
<ul>
<li class="chapter" data-level="20.1" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html#count-data-with-poisson-errors."><i class="fa fa-check"></i><b>20.1</b> Count data with Poisson errors.</a>
<ul>
<li class="chapter" data-level="20.1.1" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html#example-number-of-offspring-in-foxes."><i class="fa fa-check"></i><b>20.1.1</b> Example: Number of offspring in foxes.</a></li>
<li class="chapter" data-level="20.1.2" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html#example-cancer-clusters"><i class="fa fa-check"></i><b>20.1.2</b> Example: Cancer clusters</a></li>
</ul></li>
<li class="chapter" data-level="20.2" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html#exercise-maze-runner"><i class="fa fa-check"></i><b>20.2</b> Exercise: Maze runner</a></li>
<li class="chapter" data-level="20.3" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html#overdispersion"><i class="fa fa-check"></i><b>20.3</b> Overdispersion</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="extending-use-cases-of-glm.html"><a href="extending-use-cases-of-glm.html"><i class="fa fa-check"></i><b>21</b> Extending use cases of GLM</a>
<ul>
<li class="chapter" data-level="21.1" data-path="extending-use-cases-of-glm.html"><a href="extending-use-cases-of-glm.html#binomial-response-data"><i class="fa fa-check"></i><b>21.1</b> Binomial response data</a></li>
<li class="chapter" data-level="21.2" data-path="extending-use-cases-of-glm.html"><a href="extending-use-cases-of-glm.html#example-nfl-field-goals"><i class="fa fa-check"></i><b>21.2</b> Example: NFL field goals</a></li>
<li class="chapter" data-level="21.3" data-path="extending-use-cases-of-glm.html"><a href="extending-use-cases-of-glm.html#example-sex-ratio-in-turtles"><i class="fa fa-check"></i><b>21.3</b> Example: Sex ratio in turtles</a></li>
<li class="chapter" data-level="21.4" data-path="extending-use-cases-of-glm.html"><a href="extending-use-cases-of-glm.html#example-smoking"><i class="fa fa-check"></i><b>21.4</b> Example: Smoking</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html"><i class="fa fa-check"></i><b>22</b> Power analysis by simulation</a>
<ul>
<li class="chapter" data-level="22.1" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#type-i-and-ii-errors-and-statistical-power"><i class="fa fa-check"></i><b>22.1</b> Type I and II errors and statistical power</a></li>
<li class="chapter" data-level="22.2" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#what-determines-statistical-power"><i class="fa fa-check"></i><b>22.2</b> What determines statistical power?</a></li>
<li class="chapter" data-level="22.3" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#an-example-of-calculating-statistical-power."><i class="fa fa-check"></i><b>22.3</b> An example of calculating statistical power.</a>
<ul>
<li class="chapter" data-level="22.3.1" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#the-simulation"><i class="fa fa-check"></i><b>22.3.1</b> The simulation</a></li>
<li class="chapter" data-level="22.3.2" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#some-questions-for-you-to-address"><i class="fa fa-check"></i><b>22.3.2</b> Some questions for you to address:</a></li>
</ul></li>
<li class="chapter" data-level="22.4" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#summary"><i class="fa fa-check"></i><b>22.4</b> Summary</a></li>
<li class="chapter" data-level="22.5" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#extending-the-simulation-optional-advanced"><i class="fa fa-check"></i><b>22.5</b> Extending the simulation (optional, advanced)</a></li>
<li class="chapter" data-level="22.6" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#exercise-1-snails-on-the-move"><i class="fa fa-check"></i><b>22.6</b> Exercise 1: Snails on the move</a></li>
<li class="chapter" data-level="22.7" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#exercise-2-mouse-lemur-strength"><i class="fa fa-check"></i><b>22.7</b> Exercise 2: Mouse lemur strength</a></li>
</ul></li>
<li class="part"><span><b>IV Exam</b></span></li>
<li class="chapter" data-level="23" data-path="exam-2022.html"><a href="exam-2022.html"><i class="fa fa-check"></i><b>23</b> Exam 2022</a></li>
<li class="part"><span><b>V Solutions</b></span></li>
<li class="chapter" data-level="24" data-path="exercise-solutions.html"><a href="exercise-solutions.html"><i class="fa fa-check"></i><b>24</b> Exercise Solutions</a>
<ul>
<li class="chapter" data-level="24.1" data-path="exercise-solutions.html"><a href="exercise-solutions.html#californian-bird-diversity"><i class="fa fa-check"></i><b>24.1</b> Californian bird diversity</a></li>
<li class="chapter" data-level="24.2" data-path="exercise-solutions.html"><a href="exercise-solutions.html#wrangling-the-amniote-life-history-database"><i class="fa fa-check"></i><b>24.2</b> Wrangling the Amniote Life History Database</a></li>
<li class="chapter" data-level="24.3" data-path="exercise-solutions.html"><a href="exercise-solutions.html#temperature-effects-on-egg-laying-dates"><i class="fa fa-check"></i><b>24.3</b> Temperature effects on egg laying dates</a></li>
<li class="chapter" data-level="24.4" data-path="exercise-solutions.html"><a href="exercise-solutions.html#virtual-dice"><i class="fa fa-check"></i><b>24.4</b> Virtual dice</a></li>
<li class="chapter" data-level="24.5" data-path="exercise-solutions.html"><a href="exercise-solutions.html#sexual-selection-in-hercules-beetles"><i class="fa fa-check"></i><b>24.5</b> Sexual selection in Hercules beetles</a></li>
<li class="chapter" data-level="24.6" data-path="exercise-solutions.html"><a href="exercise-solutions.html#sex-differences-in-fine-motor-skills"><i class="fa fa-check"></i><b>24.6</b> Sex differences in fine motor skills</a></li>
<li class="chapter" data-level="24.7" data-path="exercise-solutions.html"><a href="exercise-solutions.html#therapy-for-anorexia"><i class="fa fa-check"></i><b>24.7</b> Therapy for anorexia</a></li>
<li class="chapter" data-level="24.8" data-path="exercise-solutions.html"><a href="exercise-solutions.html#compare-t-tests-with-randomisation-tests"><i class="fa fa-check"></i><b>24.8</b> Compare t-tests with randomisation tests</a></li>
<li class="chapter" data-level="24.9" data-path="exercise-solutions.html"><a href="exercise-solutions.html#apple-tree-crop-yield"><i class="fa fa-check"></i><b>24.9</b> Apple tree crop yield</a></li>
<li class="chapter" data-level="24.10" data-path="exercise-solutions.html"><a href="exercise-solutions.html#chirping-crickets"><i class="fa fa-check"></i><b>24.10</b> Chirping crickets</a></li>
<li class="chapter" data-level="24.11" data-path="exercise-solutions.html"><a href="exercise-solutions.html#fish-behaviour"><i class="fa fa-check"></i><b>24.11</b> Fish behaviour</a></li>
<li class="chapter" data-level="24.12" data-path="exercise-solutions.html"><a href="exercise-solutions.html#maze-runner"><i class="fa fa-check"></i><b>24.12</b> Maze runner</a></li>
<li class="chapter" data-level="24.13" data-path="exercise-solutions.html"><a href="exercise-solutions.html#snails-on-the-move"><i class="fa fa-check"></i><b>24.13</b> Snails on the move</a></li>
<li class="chapter" data-level="24.14" data-path="exercise-solutions.html"><a href="exercise-solutions.html#mouse-lemur-strength"><i class="fa fa-check"></i><b>24.14</b> Mouse lemur strength</a></li>
</ul></li>
<li class="chapter" data-level="25" data-path="an-example-of-a-past-exam-2020.html"><a href="an-example-of-a-past-exam-2020.html"><i class="fa fa-check"></i><b>25</b> An example of a past Exam (2020)</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">BB852 - Data handling, visualisation and statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="an-example-of-a-past-exam-2020" class="section level1 hasAnchor" number="25">
<h1><span class="header-section-number">Chapter 25</span> An example of a past Exam (2020)<a href="an-example-of-a-past-exam-2020.html#an-example-of-a-past-exam-2020" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><strong>This is a previous year’s exam!</strong></p>
<p>I am leaving this here so you can see what the final exam will look like.</p>
<div class="do-something">
<p>
This exam includes four questions that test different aspects of your
learning during this course: data wrangling, data visualisation and
statistics. Each question is broken down into a number
sub-questions.
</p>
<p>
Your work should be handed in as a single PDF. The number of each
question should be clearly indicated, and the answer to each question
should start on a new page.
</p>
<p>
For each question you must provide the R code you used to answer the
question. The code should include comments to explain what you are
doing. The code should be provided as text using a fixed-width font such
as <code>Courier</code>. The rest of your answers should be in another
font (e.g. Times New Roman, Cambria). Please use <em>text</em> rather
than a screenshot of your code.
</p>
<p>
You can use the Microsoft Word template provided alongside these
questions (<a
href="https://www.dropbox.com/s/0ecb2c4fl6ygui9/BB852_Exam_template.docx?dl=0">here</a>)
as guidance.
</p>
<ul>
<li>
Plots and tables should have appropriate captions.
</li>
<li>
Plots should be produced using <code>ggplot</code>.
</li>
<li>
Remember that you can make “panels” of plots (e.g. Fig 1A, B)
</li>
<li>
Axis labels are important. Sometimes you may want to edit them to be
different from a data column name.
</li>
<li>
Reporting of any statistics should be appropriate to the type of
analysis you have done. There are examples in the course materials.
</li>
<li>
Reporting of methods and results should be written in the style of a
scientific paper (again, there are examples in the course
materials).
</li>
</ul>
<p>
<em>If you don’t understand any aspects of the questions, please ask
for help!</em>
</p>
<p>
<strong>Hand in deadline is 8th January 2021 at 23:59
CET</strong>
</p>
<p>
<strong>You MUST submit your work via Blackboard (not
email!)</strong>
</p>
</div>
<hr />
<p><strong>1) Amazonian fires (10 points)</strong></p>
<p>The dataset <code>amazon.csv</code> is a record of fire occurrence in the Amazon rainforest. The data set has columns for year, the state where the fire occurred, the month, and the number of fires reported. The month is recorded in Portuguese, so you will probably want to either create a “look up table” and use <code>left_join</code> to convert the month to a number, or use the <code>dplyr</code> function <code>recode</code>. There are many states and it might be useful to group them. For example the legal Amazon includes the states of Acre, Amapá, Pará, Amazonas, Rondonia, Roraima, Mato Grosso, Tocantins, and Maranhão.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Produce a graph showing the the total number of fires per year through time as points joined by lines.</p></li>
<li><p>Produce a table showing the minimum, maximum, mean and median number of fires per month in the legally-defined Amazon.</p></li>
<li><p>Produce a graph using box plots to show the distribution of the number of fires per month in the Amazon (i.e. month on x-axis, number of fires on y-axis).</p></li>
</ol>
<hr />
<p><strong>a) Produce a graph showing the the total number of fires per year through time as points joined by lines.</strong></p>
<div class="sourceCode" id="cb657"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb657-1"><a href="an-example-of-a-past-exam-2020.html#cb657-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import data</span></span>
<span id="cb657-2"><a href="an-example-of-a-past-exam-2020.html#cb657-2" aria-hidden="true" tabindex="-1"></a>amazon <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;CourseData/amazon.csv&quot;</span>)</span>
<span id="cb657-3"><a href="an-example-of-a-past-exam-2020.html#cb657-3" aria-hidden="true" tabindex="-1"></a>amazon <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;CourseData/amazon.csv&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb657-4"><a href="an-example-of-a-past-exam-2020.html#cb657-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">number =</span> <span class="fu">ifelse</span>(number <span class="sc">&gt;=</span> <span class="dv">1000</span>,</span>
<span id="cb657-5"><a href="an-example-of-a-past-exam-2020.html#cb657-5" aria-hidden="true" tabindex="-1"></a>    <span class="dv">1</span> <span class="sc">+</span> (number <span class="sc">-</span> <span class="dv">1000</span>) <span class="sc">/</span> <span class="dv">1000</span>, number</span>
<span id="cb657-6"><a href="an-example-of-a-past-exam-2020.html#cb657-6" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb657-7"><a href="an-example-of-a-past-exam-2020.html#cb657-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb657-8"><a href="an-example-of-a-past-exam-2020.html#cb657-8" aria-hidden="true" tabindex="-1"></a><span class="co"># A) MAKE GRAPH OF TOTAL FIRES PER YEAR.</span></span>
<span id="cb657-9"><a href="an-example-of-a-past-exam-2020.html#cb657-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb657-10"><a href="an-example-of-a-past-exam-2020.html#cb657-10" aria-hidden="true" tabindex="-1"></a>(amazon_YearlyFires <span class="ot">&lt;-</span> amazon <span class="sc">%&gt;%</span></span>
<span id="cb657-11"><a href="an-example-of-a-past-exam-2020.html#cb657-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year) <span class="sc">%&gt;%</span></span>
<span id="cb657-12"><a href="an-example-of-a-past-exam-2020.html#cb657-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n.fires =</span> <span class="fu">sum</span>(number)))</span></code></pre></div>
<pre><code>## # A tibble: 20 × 2
##     year n.fires
##    &lt;int&gt;   &lt;dbl&gt;
##  1  1998  20014.
##  2  1999  26883.
##  3  2000  27351.
##  4  2001  29072.
##  5  2002  37391.
##  6  2003  42761.
##  7  2004  38453.
##  8  2005  35005.
##  9  2006  33832.
## 10  2007  33037.
## 11  2008  29379.
## 12  2009  39117.
## 13  2010  37037.
## 14  2011  34634.
## 15  2012  40085.
## 16  2013  35146.
## 17  2014  39621.
## 18  2015  41208.
## 19  2016  42212.
## 20  2017  36686.</code></pre>
<div class="sourceCode" id="cb659"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb659-1"><a href="an-example-of-a-past-exam-2020.html#cb659-1" aria-hidden="true" tabindex="-1"></a>(A <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(amazon_YearlyFires, <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> n.fires)) <span class="sc">+</span></span>
<span id="cb659-2"><a href="an-example-of-a-past-exam-2020.html#cb659-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb659-3"><a href="an-example-of-a-past-exam-2020.html#cb659-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>())</span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-464-1.png" width="672" /></p>
<p>You may have slightly different values if you used old data that had some fractional numbers (e.g. 1.543 is not “1 point 5” fires, but one thousand five hundred!). Well done those of you that spotted that issue. Don’t worry if you didn’t - you don’t lose points!</p>
<p>Some of you may also have made plots that included ONLY data from the “legal amazon”, by filtering to those states only. Again, that is no problem if you did that.</p>
<p><strong>b) Produce a table showing the minimum, maximum, mean and median number of fires per month in the legally-defined Amazon.</strong></p>
<div class="sourceCode" id="cb660"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb660-1"><a href="an-example-of-a-past-exam-2020.html#cb660-1" aria-hidden="true" tabindex="-1"></a><span class="co"># First filter to only include the &quot;legally defined amazon&quot;</span></span>
<span id="cb660-2"><a href="an-example-of-a-past-exam-2020.html#cb660-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Check that all are included in the result (you might need to</span></span>
<span id="cb660-3"><a href="an-example-of-a-past-exam-2020.html#cb660-3" aria-hidden="true" tabindex="-1"></a><span class="co"># check and fix &quot;foreign&quot; letters - a typical data cleaning task!)</span></span>
<span id="cb660-4"><a href="an-example-of-a-past-exam-2020.html#cb660-4" aria-hidden="true" tabindex="-1"></a>legalAmazonStates <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb660-5"><a href="an-example-of-a-past-exam-2020.html#cb660-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">&quot;Acre&quot;</span>, <span class="st">&quot;Amapa&quot;</span>, <span class="st">&quot;Pará&quot;</span>, <span class="st">&quot;Amazonas&quot;</span>, <span class="st">&quot;Rondonia&quot;</span>,</span>
<span id="cb660-6"><a href="an-example-of-a-past-exam-2020.html#cb660-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">&quot;Roraima&quot;</span>, <span class="st">&quot;Mato Grosso&quot;</span>, <span class="st">&quot;Tocantins&quot;</span>, <span class="st">&quot;Maranhao&quot;</span></span>
<span id="cb660-7"><a href="an-example-of-a-past-exam-2020.html#cb660-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb660-8"><a href="an-example-of-a-past-exam-2020.html#cb660-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb660-9"><a href="an-example-of-a-past-exam-2020.html#cb660-9" aria-hidden="true" tabindex="-1"></a>legalAmazon <span class="ot">&lt;-</span> amazon <span class="sc">%&gt;%</span></span>
<span id="cb660-10"><a href="an-example-of-a-past-exam-2020.html#cb660-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(state <span class="sc">%in%</span> legalAmazonStates)</span>
<span id="cb660-11"><a href="an-example-of-a-past-exam-2020.html#cb660-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb660-12"><a href="an-example-of-a-past-exam-2020.html#cb660-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb660-13"><a href="an-example-of-a-past-exam-2020.html#cb660-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Next make a &quot;look up&quot; table to convert month name</span></span>
<span id="cb660-14"><a href="an-example-of-a-past-exam-2020.html#cb660-14" aria-hidden="true" tabindex="-1"></a><span class="co"># to a numeric value 1-12</span></span>
<span id="cb660-15"><a href="an-example-of-a-past-exam-2020.html#cb660-15" aria-hidden="true" tabindex="-1"></a>(monthLookup <span class="ot">&lt;-</span> amazon <span class="sc">%&gt;%</span></span>
<span id="cb660-16"><a href="an-example-of-a-past-exam-2020.html#cb660-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(month) <span class="sc">%&gt;%</span></span>
<span id="cb660-17"><a href="an-example-of-a-past-exam-2020.html#cb660-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unique</span>() <span class="sc">%&gt;%</span></span>
<span id="cb660-18"><a href="an-example-of-a-past-exam-2020.html#cb660-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">month_numeric =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>))</span></code></pre></div>
<pre><code>##         month month_numeric
## 1     Janeiro             1
## 21  Fevereiro             2
## 41      Março             3
## 61      Abril             4
## 81       Maio             5
## 101     Junho             6
## 121     Julho             7
## 141    Agosto             8
## 161  Setembro             9
## 181   Outubro            10
## 201  Novembro            11
## 221  Dezembro            12</code></pre>
<div class="sourceCode" id="cb662"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb662-1"><a href="an-example-of-a-past-exam-2020.html#cb662-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Then use left_join to add the numeric month to the data</span></span>
<span id="cb662-2"><a href="an-example-of-a-past-exam-2020.html#cb662-2" aria-hidden="true" tabindex="-1"></a><span class="co"># then group_by month and year, and summarise to get total</span></span>
<span id="cb662-3"><a href="an-example-of-a-past-exam-2020.html#cb662-3" aria-hidden="true" tabindex="-1"></a><span class="co"># number (i.e. sum for each month in each year for whole amazon)</span></span>
<span id="cb662-4"><a href="an-example-of-a-past-exam-2020.html#cb662-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Then group_by month again and calculate the min/mean/max etc.</span></span>
<span id="cb662-5"><a href="an-example-of-a-past-exam-2020.html#cb662-5" aria-hidden="true" tabindex="-1"></a>table1 <span class="ot">&lt;-</span> legalAmazon <span class="sc">%&gt;%</span></span>
<span id="cb662-6"><a href="an-example-of-a-past-exam-2020.html#cb662-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(monthLookup) <span class="sc">%&gt;%</span></span>
<span id="cb662-7"><a href="an-example-of-a-past-exam-2020.html#cb662-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(month_numeric, year) <span class="sc">%&gt;%</span></span>
<span id="cb662-8"><a href="an-example-of-a-past-exam-2020.html#cb662-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">sumFires =</span> <span class="fu">sum</span>(number)) <span class="sc">%&gt;%</span></span>
<span id="cb662-9"><a href="an-example-of-a-past-exam-2020.html#cb662-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># total fires per month, per year</span></span>
<span id="cb662-10"><a href="an-example-of-a-past-exam-2020.html#cb662-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(month_numeric) <span class="sc">%&gt;%</span></span>
<span id="cb662-11"><a href="an-example-of-a-past-exam-2020.html#cb662-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># group by month to get min/max/median per month</span></span>
<span id="cb662-12"><a href="an-example-of-a-past-exam-2020.html#cb662-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb662-13"><a href="an-example-of-a-past-exam-2020.html#cb662-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">minimum =</span> <span class="fu">min</span>(sumFires), <span class="at">mean =</span> <span class="fu">mean</span>(sumFires),</span>
<span id="cb662-14"><a href="an-example-of-a-past-exam-2020.html#cb662-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">median =</span> <span class="fu">median</span>(sumFires), <span class="at">maximum =</span> <span class="fu">max</span>(sumFires)</span>
<span id="cb662-15"><a href="an-example-of-a-past-exam-2020.html#cb662-15" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb662-16"><a href="an-example-of-a-past-exam-2020.html#cb662-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb662-17"><a href="an-example-of-a-past-exam-2020.html#cb662-17" aria-hidden="true" tabindex="-1"></a>table1</span></code></pre></div>
<pre><code>## # A tibble: 12 × 5
##    month_numeric minimum  mean median maximum
##            &lt;int&gt;   &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
##  1             1     0   1382.  1370.   3257 
##  2             2     0    880.   801    1859.
##  3             3     0    886.   857    1612 
##  4             4     0    802.   792    1566 
##  5             5     0    980.  1028.   1938 
##  6             6   333.  1480.  1526.   2670 
##  7             7   480.  1983.  2054.   3422.
##  8             8    59.4  976.   907.   3337.
##  9             9   125.   486.   298.   1284.
## 10            10   594.  1966.  2140.   3113.
## 11            11   634.  1796.  1673.   3598.
## 12            12   260.  1205.  1214.   2207.</code></pre>
<p>This question was HARD. It could also have been interpreted in a couple of different ways. For example, it could be interpreted as asking for the mean/median/max (etc.) by state. What I actually meant was to find the TOTAL across ALL of the legal Amazon for each month and each year (20 years * 12 months = 240 values), and then produce a table summarising the mean, min, max etc. of these values.</p>
<p>If you calculate the statistics “by state” as well as by year and month you end up with a different table, like this:</p>
<div class="sourceCode" id="cb664"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb664-1"><a href="an-example-of-a-past-exam-2020.html#cb664-1" aria-hidden="true" tabindex="-1"></a>table1 <span class="ot">&lt;-</span> legalAmazon <span class="sc">%&gt;%</span></span>
<span id="cb664-2"><a href="an-example-of-a-past-exam-2020.html#cb664-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(monthLookup) <span class="sc">%&gt;%</span></span>
<span id="cb664-3"><a href="an-example-of-a-past-exam-2020.html#cb664-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(month_numeric) <span class="sc">%&gt;%</span></span>
<span id="cb664-4"><a href="an-example-of-a-past-exam-2020.html#cb664-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb664-5"><a href="an-example-of-a-past-exam-2020.html#cb664-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">minimum =</span> <span class="fu">min</span>(number), <span class="at">mean =</span> <span class="fu">mean</span>(number),</span>
<span id="cb664-6"><a href="an-example-of-a-past-exam-2020.html#cb664-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">median =</span> <span class="fu">median</span>(number), <span class="at">maximum =</span> <span class="fu">max</span>(number)</span>
<span id="cb664-7"><a href="an-example-of-a-past-exam-2020.html#cb664-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb664-8"><a href="an-example-of-a-past-exam-2020.html#cb664-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb664-9"><a href="an-example-of-a-past-exam-2020.html#cb664-9" aria-hidden="true" tabindex="-1"></a>table1</span></code></pre></div>
<pre><code>## # A tibble: 12 × 5
##    month_numeric minimum  mean median maximum
##            &lt;int&gt;   &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
##  1             1       0 138.   44.5      960
##  2             2       0  88.0  25        871
##  3             3       0  88.6  19        820
##  4             4       0  80.2  15.5      947
##  5             5       0  98.0  12        942
##  6             6       0 148.   32.5      979
##  7             7       0 198.   23.5      989
##  8             8       0  97.6   4.77     960
##  9             9       1  48.6   5.88     998
## 10            10       1 197.    7.70     960
## 11            11       0 180.   88        973
## 12            12       0 120.   43.5      846</code></pre>
<p>I have been lenient with the marking on this one!</p>
<p><strong>c) Produce a graph using box plots to show the distribution of the number of fires per month in the Amazon (i.e. month on x-axis, number of fires on y-axis).</strong></p>
<p>Here I am looking for a box plot of the number of fires per month in the Amazon (or legal Amazon). In other words, each row of data (each data point) should be the total number of fires across all of the states, for each month, in each year.</p>
<p>To check that you are on the right track you could look at the dimensions of the data frame you create - with 12 months per year and 20 years of data you can expect 240 rows of data (though perhaps not all years include all months of data). Nevertheless, it gives you a ballpark figure and if your dataset is not approximately this size, something has gone wrong!</p>
<div class="sourceCode" id="cb666"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb666-1"><a href="an-example-of-a-past-exam-2020.html#cb666-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use summarise to calculate the the total number of</span></span>
<span id="cb666-2"><a href="an-example-of-a-past-exam-2020.html#cb666-2" aria-hidden="true" tabindex="-1"></a><span class="co"># fires per month.</span></span>
<span id="cb666-3"><a href="an-example-of-a-past-exam-2020.html#cb666-3" aria-hidden="true" tabindex="-1"></a><span class="co"># In this case I use the legal amazon, but it is acceptable</span></span>
<span id="cb666-4"><a href="an-example-of-a-past-exam-2020.html#cb666-4" aria-hidden="true" tabindex="-1"></a><span class="co"># to look at the whole data set. You need to make sure that</span></span>
<span id="cb666-5"><a href="an-example-of-a-past-exam-2020.html#cb666-5" aria-hidden="true" tabindex="-1"></a><span class="co"># you are using the numeric month.</span></span>
<span id="cb666-6"><a href="an-example-of-a-past-exam-2020.html#cb666-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb666-7"><a href="an-example-of-a-past-exam-2020.html#cb666-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Group by year and month to calculate the total number of</span></span>
<span id="cb666-8"><a href="an-example-of-a-past-exam-2020.html#cb666-8" aria-hidden="true" tabindex="-1"></a><span class="co"># fires in each year and month.</span></span>
<span id="cb666-9"><a href="an-example-of-a-past-exam-2020.html#cb666-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb666-10"><a href="an-example-of-a-past-exam-2020.html#cb666-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the dataset by filtering to legal amazon, adding</span></span>
<span id="cb666-11"><a href="an-example-of-a-past-exam-2020.html#cb666-11" aria-hidden="true" tabindex="-1"></a><span class="co"># numeric month, grouping by year and month and finally</span></span>
<span id="cb666-12"><a href="an-example-of-a-past-exam-2020.html#cb666-12" aria-hidden="true" tabindex="-1"></a><span class="co"># summarising.</span></span>
<span id="cb666-13"><a href="an-example-of-a-past-exam-2020.html#cb666-13" aria-hidden="true" tabindex="-1"></a>amazon2 <span class="ot">&lt;-</span> amazon <span class="sc">%&gt;%</span></span>
<span id="cb666-14"><a href="an-example-of-a-past-exam-2020.html#cb666-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(state <span class="sc">%in%</span> legalAmazonStates) <span class="sc">%&gt;%</span></span>
<span id="cb666-15"><a href="an-example-of-a-past-exam-2020.html#cb666-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(monthLookup) <span class="sc">%&gt;%</span></span>
<span id="cb666-16"><a href="an-example-of-a-past-exam-2020.html#cb666-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year, month_numeric) <span class="sc">%&gt;%</span></span>
<span id="cb666-17"><a href="an-example-of-a-past-exam-2020.html#cb666-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n_fires =</span> <span class="fu">sum</span>(number))</span>
<span id="cb666-18"><a href="an-example-of-a-past-exam-2020.html#cb666-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb666-19"><a href="an-example-of-a-past-exam-2020.html#cb666-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Check number of rows</span></span>
<span id="cb666-20"><a href="an-example-of-a-past-exam-2020.html#cb666-20" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(amazon2)</span></code></pre></div>
<pre><code>## [1] 239</code></pre>
<div class="sourceCode" id="cb668"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb668-1"><a href="an-example-of-a-past-exam-2020.html#cb668-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the data</span></span>
<span id="cb668-2"><a href="an-example-of-a-past-exam-2020.html#cb668-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(amazon2, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">as.factor</span>(month_numeric), <span class="at">y =</span> n_fires)) <span class="sc">+</span></span>
<span id="cb668-3"><a href="an-example-of-a-past-exam-2020.html#cb668-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb668-4"><a href="an-example-of-a-past-exam-2020.html#cb668-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Month&quot;</span>) <span class="sc">+</span></span>
<span id="cb668-5"><a href="an-example-of-a-past-exam-2020.html#cb668-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Total number of fires&quot;</span>)</span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-467-1.png" width="672" /></p>
<p>Common mistakes -
Understanding how <code>group_by</code> and <code>summarise</code> work is key to answering this question.
To ensure that the months are displayed in the correct order you need to use the <code>numeric</code> month. Failure to do that will cause the plot to be presented in alphabetical order (i.e. with December falling before January!). However, box plots require that the input variable is a <code>factor</code> so you also need to convert back to a <code>factor</code> before plotting.</p>
<hr />
<p><strong>2) Coral bleaching (10 points)</strong></p>
<p>Coral bleaching is when coral polyps expel the endosymbiotic algae that live within their tissues. Although the coral can survive bleaching events, their algae provide most of their energy, so the coral can eventually starve and die. It is thought that deeper corals (from the mesophotic zone) might be protected from bleaching events because the depth offers more stable conditions with fewer stressors. This is known as the “deep reef refugia hypothesis”.</p>
<p>To test this idea, a transplant experiment was carried out on the coral <em>Agaricia lamarcki</em> at the island of Utila, Honduras. In the study, intact samples of the coral were moved from deep (mesophotic) reefs to the shallow reef and <em>vice versa</em>. They were left there for 8 months and then their colouration was measured to assess bleaching: lower colour intensity means more bleaching. The data are provided in <code>coral.csv</code>.</p>
<ol style="list-style-type: lower-alpha">
<li><p>plot the data (e.g. with a box plot)</p></li>
<li><p>carry out a randomisation test to determine if there is a significant difference in the colour intensity in the two habitats. Write (i) a brief method description and (ii) a summary of the results.</p></li>
</ol>
<hr />
<p><strong>a) plot the data (e.g. with a box plot)</strong></p>
<div class="sourceCode" id="cb669"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb669-1"><a href="an-example-of-a-past-exam-2020.html#cb669-1" aria-hidden="true" tabindex="-1"></a>coral <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;CourseData/coral.csv&quot;</span>, <span class="at">stringsAsFactors =</span> <span class="cn">TRUE</span>)</span>
<span id="cb669-2"><a href="an-example-of-a-past-exam-2020.html#cb669-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb669-3"><a href="an-example-of-a-past-exam-2020.html#cb669-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(coral, <span class="fu">aes</span>(<span class="at">x =</span> habitat, <span class="at">y =</span> intensity)) <span class="sc">+</span></span>
<span id="cb669-4"><a href="an-example-of-a-past-exam-2020.html#cb669-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb669-5"><a href="an-example-of-a-past-exam-2020.html#cb669-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.2</span>)</span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-468-1.png" width="672" /></p>
<p><strong>b) carry out a randomisation test to determine if there is a significant difference in the colour intensity in the two habitats. Write (i) a brief method description and (ii) a summary of the results. </strong></p>
<p>First we need to calculate the observed difference between the two habitats.</p>
<p>You can get the mean values like this (there are other ways):</p>
<div class="sourceCode" id="cb670"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb670-1"><a href="an-example-of-a-past-exam-2020.html#cb670-1" aria-hidden="true" tabindex="-1"></a>coral <span class="sc">%&gt;%</span></span>
<span id="cb670-2"><a href="an-example-of-a-past-exam-2020.html#cb670-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(habitat) <span class="sc">%&gt;%</span></span>
<span id="cb670-3"><a href="an-example-of-a-past-exam-2020.html#cb670-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">meanIntensity =</span> <span class="fu">mean</span>(intensity))</span></code></pre></div>
<pre><code>## # A tibble: 2 × 2
##   habitat    meanIntensity
##   &lt;fct&gt;              &lt;dbl&gt;
## 1 mesophotic         187. 
## 2 shallow             81.8</code></pre>
<p>…then subtract one value from the other “by hand”.</p>
<p>You could also do the whole calculation using the pipes syntax like this:</p>
<div class="sourceCode" id="cb672"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb672-1"><a href="an-example-of-a-past-exam-2020.html#cb672-1" aria-hidden="true" tabindex="-1"></a>(obsDiff <span class="ot">&lt;-</span> coral <span class="sc">%&gt;%</span></span>
<span id="cb672-2"><a href="an-example-of-a-past-exam-2020.html#cb672-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(habitat) <span class="sc">%&gt;%</span></span>
<span id="cb672-3"><a href="an-example-of-a-past-exam-2020.html#cb672-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">meanIntensity =</span> <span class="fu">mean</span>(intensity)) <span class="sc">%&gt;%</span></span>
<span id="cb672-4"><a href="an-example-of-a-past-exam-2020.html#cb672-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(meanIntensity) <span class="sc">%&gt;%</span></span>
<span id="cb672-5"><a href="an-example-of-a-past-exam-2020.html#cb672-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">diff</span>())</span></code></pre></div>
<pre><code>## [1] -105.5377</code></pre>
<p>Next we ask “is the observed difference significantly larger than what we would expect by chance?”.<a href="#fn20" class="footnote-ref" id="fnref20"><sup>20</sup></a></p>
<div class="sourceCode" id="cb674"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb674-1"><a href="an-example-of-a-past-exam-2020.html#cb674-1" aria-hidden="true" tabindex="-1"></a>shuffledData <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">rep =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2000</span>) <span class="sc">%&gt;%</span></span>
<span id="cb674-2"><a href="an-example-of-a-past-exam-2020.html#cb674-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">shuffledDiffs =</span> <span class="fu">replicate</span>(</span>
<span id="cb674-3"><a href="an-example-of-a-past-exam-2020.html#cb674-3" aria-hidden="true" tabindex="-1"></a>    <span class="dv">2000</span>,</span>
<span id="cb674-4"><a href="an-example-of-a-past-exam-2020.html#cb674-4" aria-hidden="true" tabindex="-1"></a>    coral <span class="sc">%&gt;%</span></span>
<span id="cb674-5"><a href="an-example-of-a-past-exam-2020.html#cb674-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">mutate</span>(<span class="at">habitat =</span> <span class="fu">sample</span>(habitat)) <span class="sc">%&gt;%</span></span>
<span id="cb674-6"><a href="an-example-of-a-past-exam-2020.html#cb674-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">group_by</span>(habitat) <span class="sc">%&gt;%</span></span>
<span id="cb674-7"><a href="an-example-of-a-past-exam-2020.html#cb674-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">summarise</span>(<span class="at">meanIntensity =</span> <span class="fu">mean</span>(intensity)) <span class="sc">%&gt;%</span></span>
<span id="cb674-8"><a href="an-example-of-a-past-exam-2020.html#cb674-8" aria-hidden="true" tabindex="-1"></a>      <span class="fu">pull</span>(meanIntensity) <span class="sc">%&gt;%</span></span>
<span id="cb674-9"><a href="an-example-of-a-past-exam-2020.html#cb674-9" aria-hidden="true" tabindex="-1"></a>      <span class="fu">diff</span>()</span>
<span id="cb674-10"><a href="an-example-of-a-past-exam-2020.html#cb674-10" aria-hidden="true" tabindex="-1"></a>  ))</span></code></pre></div>
<p>I can plot these data, and add a line to show where the observed value is</p>
<div class="sourceCode" id="cb675"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb675-1"><a href="an-example-of-a-past-exam-2020.html#cb675-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(shuffledData, <span class="fu">aes</span>(<span class="at">x =</span> shuffledDiffs)) <span class="sc">+</span></span>
<span id="cb675-2"><a href="an-example-of-a-past-exam-2020.html#cb675-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb675-3"><a href="an-example-of-a-past-exam-2020.html#cb675-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb675-4"><a href="an-example-of-a-past-exam-2020.html#cb675-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Shuffled differences&quot;</span>) <span class="sc">+</span></span>
<span id="cb675-5"><a href="an-example-of-a-past-exam-2020.html#cb675-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> obsDiff)</span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-472-1.png" width="672" /></p>
<p>Now I can calculate the significance by asking how many of she shuffled differences were more extreme than the observed value.</p>
<div class="sourceCode" id="cb676"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb676-1"><a href="an-example-of-a-past-exam-2020.html#cb676-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(shuffledData<span class="sc">$</span>shuffledDiffs <span class="sc">&lt;=</span> obsDiff)</span></code></pre></div>
<pre><code>## 
## FALSE  TRUE 
##  1999     1</code></pre>
<p>In this case, NONE of the shuffled values are more extreme than the observed value, so the p-value can be reported as “p&lt;0.001”. You could write this up like this</p>
<p><em>To test whether the difference in intensity between the mesophotic and shallow coral habitats is statistically significant I did a 1000 replicate randomisation test with the null hypothesis being that there is no difference between the group means. The alternative hypothesis is that the mean for the mesophotic habitat is significantly lower than the mean for the shallow habitat. I compared the observed difference to this null distribution to calculate a p-value in a one-sided test.</em></p>
<p><em>The observed mean values of light intensity for the mesophotic and shallow corals were 187.4 and 81.8 respectively and the difference between them is therefore -105.6 (shallow - mesophytic). None of the 1000 null distribution replicates were as extreme my observed difference value. I conclude that the observed difference between the means of the two groups is statistically significant (p &lt; 0.001)“</em></p>
<hr />
<p><strong>3) Power in a field experiment (10 points)</strong></p>
<p>Scientists have developed a new eco-friendly fertiliser made from seaweed extract. You are planning a outdoor field experiment to test how effective it is at increasing crop yield in oilseed rape (<em>Brassica napus</em>). A standard industrial chemical fertiliser can increase yield by 30%, and you would like to know if the new seaweed fertiliser has a similar effect. You will grow the plant in a number of 4m x 4m field plots with two treatments: (i) control, with no additional fertiliser (ii) addition of seaweed fertiliser.</p>
<p>You have some preliminary data from an older study (<code>oilseed.csv</code>) which shows the normal crop yield (in <span class="math inline">\(kg/ha\)</span>). Use this data to do your power analysis</p>
<ol style="list-style-type: lower-alpha">
<li><p>Summarise the older study data to obtain mean and standard deviation.</p></li>
<li><p>Conduct a power analysis based on the pilot study data to estimate the number of samples required to carry out your experiment with 80% power. Describe the results of this power analysis.</p></li>
<li><p>Briefly describe a simple proposed experiment design to test the new seaweed fertiliser.</p></li>
</ol>
<hr />
<p><strong>a) Summarise the older study data to obtain mean and standard deviation.</strong></p>
<div class="sourceCode" id="cb678"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb678-1"><a href="an-example-of-a-past-exam-2020.html#cb678-1" aria-hidden="true" tabindex="-1"></a>oilseed <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;CourseData/oilseed.csv&quot;</span>,</span>
<span id="cb678-2"><a href="an-example-of-a-past-exam-2020.html#cb678-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">stringsAsFactors =</span> <span class="cn">TRUE</span></span>
<span id="cb678-3"><a href="an-example-of-a-past-exam-2020.html#cb678-3" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb678-4"><a href="an-example-of-a-past-exam-2020.html#cb678-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb678-5"><a href="an-example-of-a-past-exam-2020.html#cb678-5" aria-hidden="true" tabindex="-1"></a>(controlData <span class="ot">&lt;-</span> oilseed <span class="sc">%&gt;%</span></span>
<span id="cb678-6"><a href="an-example-of-a-past-exam-2020.html#cb678-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">meanVal =</span> <span class="fu">mean</span>(yield), <span class="at">sdVal =</span> <span class="fu">sd</span>(yield)))</span></code></pre></div>
<pre><code>##   meanVal    sdVal
## 1  958.25 277.7619</code></pre>
<p><strong>b) Conduct a power analysis based on the pilot study data to estimate the number of samples required to carry out your experiment with 80% power. Describe the results of this power analysis.</strong></p>
<div class="sourceCode" id="cb680"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb680-1"><a href="an-example-of-a-past-exam-2020.html#cb680-1" aria-hidden="true" tabindex="-1"></a>controlMean <span class="ot">&lt;-</span> controlData<span class="sc">$</span>meanVal</span>
<span id="cb680-2"><a href="an-example-of-a-past-exam-2020.html#cb680-2" aria-hidden="true" tabindex="-1"></a>treatmentMean <span class="ot">&lt;-</span> controlData<span class="sc">$</span>meanVal <span class="sc">*</span> <span class="fl">1.3</span> <span class="co"># Increase of 30%</span></span>
<span id="cb680-3"><a href="an-example-of-a-past-exam-2020.html#cb680-3" aria-hidden="true" tabindex="-1"></a>sdValue <span class="ot">&lt;-</span> controlData<span class="sc">$</span>sdVal</span>
<span id="cb680-4"><a href="an-example-of-a-past-exam-2020.html#cb680-4" aria-hidden="true" tabindex="-1"></a>sampleSize <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb680-5"><a href="an-example-of-a-past-exam-2020.html#cb680-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb680-6"><a href="an-example-of-a-past-exam-2020.html#cb680-6" aria-hidden="true" tabindex="-1"></a>powerResults <span class="ot">&lt;-</span> <span class="fu">replicate</span>(</span>
<span id="cb680-7"><a href="an-example-of-a-past-exam-2020.html#cb680-7" aria-hidden="true" tabindex="-1"></a>  <span class="dv">1000</span>,</span>
<span id="cb680-8"><a href="an-example-of-a-past-exam-2020.html#cb680-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">t.test</span>(</span>
<span id="cb680-9"><a href="an-example-of-a-past-exam-2020.html#cb680-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rnorm</span>(sampleSize, controlMean, sdValue),</span>
<span id="cb680-10"><a href="an-example-of-a-past-exam-2020.html#cb680-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rnorm</span>(sampleSize, treatmentMean, sdValue)</span>
<span id="cb680-11"><a href="an-example-of-a-past-exam-2020.html#cb680-11" aria-hidden="true" tabindex="-1"></a>  )<span class="sc">$</span>p.value</span>
<span id="cb680-12"><a href="an-example-of-a-past-exam-2020.html#cb680-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb680-13"><a href="an-example-of-a-past-exam-2020.html#cb680-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb680-14"><a href="an-example-of-a-past-exam-2020.html#cb680-14" aria-hidden="true" tabindex="-1"></a><span class="co"># How many times is the test successful?</span></span>
<span id="cb680-15"><a href="an-example-of-a-past-exam-2020.html#cb680-15" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(powerResults <span class="sc">&lt;</span> <span class="fl">0.05</span>)</span></code></pre></div>
<pre><code>## [1] 559</code></pre>
<p>For 80% power, you want a sample size that results in 80% (i.e. 800 out of 1000 replicates) correctly detecting that there is a difference between control and treatment. Therefore you can increase <code>sampleSize</code> until you hit that magic number.</p>
<p>A more advanced approach is to write code to try a range of sample sizes, and collect the results so that they can be plotted in a graph showing the relationship between statistical power and samples size:</p>
<div class="sourceCode" id="cb682"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb682-1"><a href="an-example-of-a-past-exam-2020.html#cb682-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set up a data frame for the simulation results</span></span>
<span id="cb682-2"><a href="an-example-of-a-past-exam-2020.html#cb682-2" aria-hidden="true" tabindex="-1"></a>simulData <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">sampleSize =</span> <span class="dv">5</span><span class="sc">:</span><span class="dv">20</span>)</span>
<span id="cb682-3"><a href="an-example-of-a-past-exam-2020.html#cb682-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb682-4"><a href="an-example-of-a-past-exam-2020.html#cb682-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Set basic values</span></span>
<span id="cb682-5"><a href="an-example-of-a-past-exam-2020.html#cb682-5" aria-hidden="true" tabindex="-1"></a>controlMean <span class="ot">&lt;-</span> controlData<span class="sc">$</span>meanVal</span>
<span id="cb682-6"><a href="an-example-of-a-past-exam-2020.html#cb682-6" aria-hidden="true" tabindex="-1"></a>treatmentMean <span class="ot">&lt;-</span> controlData<span class="sc">$</span>meanVal <span class="sc">*</span> <span class="fl">1.3</span> <span class="co"># Increase of 30%</span></span>
<span id="cb682-7"><a href="an-example-of-a-past-exam-2020.html#cb682-7" aria-hidden="true" tabindex="-1"></a>sdValue <span class="ot">&lt;-</span> controlData<span class="sc">$</span>sdVal</span>
<span id="cb682-8"><a href="an-example-of-a-past-exam-2020.html#cb682-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb682-9"><a href="an-example-of-a-past-exam-2020.html#cb682-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to do the t-test</span></span>
<span id="cb682-10"><a href="an-example-of-a-past-exam-2020.html#cb682-10" aria-hidden="true" tabindex="-1"></a>pwr <span class="ot">&lt;-</span> <span class="cf">function</span>(n) {</span>
<span id="cb682-11"><a href="an-example-of-a-past-exam-2020.html#cb682-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(<span class="fu">replicate</span>(</span>
<span id="cb682-12"><a href="an-example-of-a-past-exam-2020.html#cb682-12" aria-hidden="true" tabindex="-1"></a>    <span class="dv">1000</span>,</span>
<span id="cb682-13"><a href="an-example-of-a-past-exam-2020.html#cb682-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">t.test</span>(</span>
<span id="cb682-14"><a href="an-example-of-a-past-exam-2020.html#cb682-14" aria-hidden="true" tabindex="-1"></a>      <span class="fu">rnorm</span>(n, controlMean, sdValue),</span>
<span id="cb682-15"><a href="an-example-of-a-past-exam-2020.html#cb682-15" aria-hidden="true" tabindex="-1"></a>      <span class="fu">rnorm</span>(n, treatmentMean, sdValue)</span>
<span id="cb682-16"><a href="an-example-of-a-past-exam-2020.html#cb682-16" aria-hidden="true" tabindex="-1"></a>    )<span class="sc">$</span>p.value</span>
<span id="cb682-17"><a href="an-example-of-a-past-exam-2020.html#cb682-17" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">&lt;</span> <span class="fl">0.05</span>) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb682-18"><a href="an-example-of-a-past-exam-2020.html#cb682-18" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb682-19"><a href="an-example-of-a-past-exam-2020.html#cb682-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb682-20"><a href="an-example-of-a-past-exam-2020.html#cb682-20" aria-hidden="true" tabindex="-1"></a><span class="co"># map_dbl applying the function for every value of</span></span>
<span id="cb682-21"><a href="an-example-of-a-past-exam-2020.html#cb682-21" aria-hidden="true" tabindex="-1"></a><span class="co"># simulData$sampleSize</span></span>
<span id="cb682-22"><a href="an-example-of-a-past-exam-2020.html#cb682-22" aria-hidden="true" tabindex="-1"></a>simulData<span class="sc">$</span>Power <span class="ot">&lt;-</span> purrr<span class="sc">::</span><span class="fu">map_dbl</span>(simulData<span class="sc">$</span>sampleSize, pwr)</span></code></pre></div>
<p>Now plot the results:</p>
<div class="sourceCode" id="cb683"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb683-1"><a href="an-example-of-a-past-exam-2020.html#cb683-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the output</span></span>
<span id="cb683-2"><a href="an-example-of-a-past-exam-2020.html#cb683-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(simulData, <span class="fu">aes</span>(<span class="at">x =</span> sampleSize, <span class="at">y =</span> Power)) <span class="sc">+</span></span>
<span id="cb683-3"><a href="an-example-of-a-past-exam-2020.html#cb683-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb683-4"><a href="an-example-of-a-past-exam-2020.html#cb683-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb683-5"><a href="an-example-of-a-past-exam-2020.html#cb683-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fl">0.8</span>, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>)</span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-477-1.png" width="672" /></p>
<p>From this, it looks like a power of 80% is achieved with a sample size of about 16.</p>
<p>Summing up:
<em>My power analysis by simulation shows that a sample size of 16 per treatment group is required to detect a difference of 30% with 80% power.</em></p>
<p><strong>c) Briefly describe a simple proposed experiment design to test the new seaweed fertiliser.</strong></p>
<p>You can write something like this:</p>
<p><em>Based on my power analysis, I would set up an experiment with 16 plots per treatment group. [you could also use more samples, and explain that you are adding extra as insurance in case of problems with some plots]</em>
<em>I would try to ensure that the plots were as similar as possible to each other to avoid the effects of unmeasured differences between them. Then I would randomise the assignment of treatments (control vs. treated) to each plot. Ideally the plots would be spaced far apart to avoid pseudo-replication.</em></p>
<hr />
<p><strong>4) Biodiversity (20 points)</strong></p>
<p>There is a well-known relationship between habitat area and biodiversity - the “species-area relationship”. In a nutshell, the number of species tends to increase as the area available increases. This relationship is clearly seen, for example, if we look at island biodiversity: larger islands support more species then small ones. One potential mechanism for this observed pattern is that larger islands tend to have more variety of different habitats, and therefore more niches available for species to occupy (more niches = more species).</p>
<p>The dataset <code>roundabouts.csv</code> shows the results of a study carried out in an urban environment to investigate these ideas. During the study, the number of beetle species (<code>nSpecies</code>) living on roundabouts and other “islands” of vegetation of different sizes (<code>area</code> in <span class="math inline">\(m^2\)</span>) in a sea of concrete and tarmac was counted. Some of these islands had “complex” vegetation (e.g. trees, bushes, shrubs, ponds and rocks) while others were “simple” (only grass), indicated by the variable <code>habitatType</code>,</p>
<p>Use an appropriate statistical model to explore the relationship between area and species richness. Does this relationship differ depending on habitat complexity?</p>
<ol style="list-style-type: lower-alpha">
<li><p>Plot the data to show the relationship between the the number of species and the area of the “island”. Colour code the points by whether the habitat type.</p></li>
<li><p>Fit a suitable statistical model to estimate the statistical relationship between area, habitat type, and species richness. Describe the method and then summarise the results produced by the model as if you were writing a report/thesis.</p></li>
<li><p>Produce a plot that shows (in addition to the raw data points) the fitted values produced by your model and the uncertainty in those estimates.</p></li>
</ol>
<hr />
<p><strong>a) Plot the data to show the relationship between the the number of species and the area of the “island”. Colour code the points by whether the habitat type.</strong></p>
<div class="sourceCode" id="cb684"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb684-1"><a href="an-example-of-a-past-exam-2020.html#cb684-1" aria-hidden="true" tabindex="-1"></a>roundabouts <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;CourseData/roundabouts.csv&quot;</span>,</span>
<span id="cb684-2"><a href="an-example-of-a-past-exam-2020.html#cb684-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">stringsAsFactors =</span> <span class="cn">TRUE</span></span>
<span id="cb684-3"><a href="an-example-of-a-past-exam-2020.html#cb684-3" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb684-4"><a href="an-example-of-a-past-exam-2020.html#cb684-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb684-5"><a href="an-example-of-a-past-exam-2020.html#cb684-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(roundabouts, <span class="fu">aes</span>(</span>
<span id="cb684-6"><a href="an-example-of-a-past-exam-2020.html#cb684-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> area, <span class="at">y =</span> nSpecies,</span>
<span id="cb684-7"><a href="an-example-of-a-past-exam-2020.html#cb684-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">colour =</span> habitatType</span>
<span id="cb684-8"><a href="an-example-of-a-past-exam-2020.html#cb684-8" aria-hidden="true" tabindex="-1"></a>)) <span class="sc">+</span></span>
<span id="cb684-9"><a href="an-example-of-a-past-exam-2020.html#cb684-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-478-1.png" width="672" /></p>
<p><strong>b) Fit a suitable statistical model to estimate the statistical relationship between area, habitat type, and species richness. Describe the method and then summarise the results produced by the model as if you were writing a report/thesis.</strong></p>
<p>The key thing to remember here is that there are limits to counts of species. You can’t count &lt;0. Therefore, models that would allow the prediction of negative values may be problematic.
Generalised Linear Models are designed for handling these kind of issues and, in this case, a Poisson model is most appropriate. This is an analogous situation to the example we looked at modelling the number of fox offspring in relation to mother’s weight.</p>
<p>I could describe the methods like this:
<em>I fitted a generalised linear model with Poisson errors to model how species richness is associated with survey area and habitat complexity. I included species richness as the response variable, and area and habitat complexity as explanatory variables. I used Poisson errors because these are count data and using an ordinary linear model could lead to estimates of negative species richness, and would not account for the fact that variance increases with the mean, which violates one of the assumptions of ordinary regression models. After fitting the model I examined the diagnostic plots of the model to check that the model was appropriate.</em></p>
<div class="sourceCode" id="cb685"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb685-1"><a href="an-example-of-a-past-exam-2020.html#cb685-1" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(nSpecies <span class="sc">~</span> area <span class="sc">*</span> habitatType,</span>
<span id="cb685-2"><a href="an-example-of-a-past-exam-2020.html#cb685-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="st">&quot;poisson&quot;</span>,</span>
<span id="cb685-3"><a href="an-example-of-a-past-exam-2020.html#cb685-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> roundabouts</span>
<span id="cb685-4"><a href="an-example-of-a-past-exam-2020.html#cb685-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb685-5"><a href="an-example-of-a-past-exam-2020.html#cb685-5" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(mod1)</span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-479-1.png" width="672" /></p>
<div class="sourceCode" id="cb686"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb686-1"><a href="an-example-of-a-past-exam-2020.html#cb686-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod1, <span class="at">test =</span> <span class="st">&quot;Chi&quot;</span>)</span></code></pre></div>
<pre><code>## Analysis of Deviance Table
## 
## Model: poisson, link: log
## 
## Response: nSpecies
## 
## Terms added sequentially (first to last)
## 
## 
##                  Df Deviance Resid. Df Resid. Dev  Pr(&gt;Chi)    
## NULL                                35     72.607              
## area              1   21.627        34     50.980 3.311e-06 ***
## habitatType       1   10.945        33     40.035 0.0009386 ***
## area:habitatType  1   13.842        32     26.193 0.0001988 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb688"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb688-1"><a href="an-example-of-a-past-exam-2020.html#cb688-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = nSpecies ~ area * habitatType, family = &quot;poisson&quot;, 
##     data = roundabouts)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.3652  -0.8311  -0.2552   0.5103   1.6721  
## 
## Coefficients:
##                         Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)             0.099910   0.321923   0.310 0.756291    
## area                    0.051446   0.009423   5.460 4.77e-08 ***
## habitatTypesimple       1.171997   0.488857   2.397 0.016511 *  
## area:habitatTypesimple -0.064852   0.017255  -3.758 0.000171 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 72.607  on 35  degrees of freedom
## Residual deviance: 26.193  on 32  degrees of freedom
## AIC: 141.11
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>I can describe the results like this:</p>
<p><em>The GLM results show that the effect of area and habitat type were both highly-significant (GLM, Area: null deviance= 72.707, residual deviance = 50.980, d.f. 1 and 34, p &lt; 0.001; habitat type: null deviance= 72.707, residual deviance = 40.035, d.f. 1 and 33,p &lt; 0.001)). There was also a significant interaction between area and habitat type (i.e. the effect of area depended upon the habitat) (interaction: null deviance= 72.707, residual deviance = 26.193, d.f. 1 and 32,p &lt; 0.001)).</em>
<em>The model showed that area was positively associated with species richness for complex habitats (slope = 0.05+/0.009) but that the slope (on the scale of the linear predictor of the GLM) was close to zero for simple habitats (slope = -0.01 [<code>0.051446 + (-0.064852)</code>]) (see Figure x)</em></p>
<p><strong>c) Produce a plot that shows (in addition to the raw data points) the fitted values produced by your model and the uncertainty in those estimates. </strong></p>
<p>Here I am asking you to add the predicted values (fitted value lines) from your model to the plot of the raw data. I am also asking you to show uncertainty. This is best done by adding a shaded ribbon.</p>
<p>The main thing to remember here is that you need to back-transform from the scale of the linear predictor to the natural scale.</p>
<div class="sourceCode" id="cb690"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb690-1"><a href="an-example-of-a-past-exam-2020.html#cb690-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Data set to predict from</span></span>
<span id="cb690-2"><a href="an-example-of-a-past-exam-2020.html#cb690-2" aria-hidden="true" tabindex="-1"></a>newData <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(</span>
<span id="cb690-3"><a href="an-example-of-a-past-exam-2020.html#cb690-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">area =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">50</span>, <span class="fl">0.1</span>),</span>
<span id="cb690-4"><a href="an-example-of-a-past-exam-2020.html#cb690-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">habitatType =</span> <span class="fu">c</span>(<span class="st">&quot;complex&quot;</span>, <span class="st">&quot;simple&quot;</span>)</span>
<span id="cb690-5"><a href="an-example-of-a-past-exam-2020.html#cb690-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb690-6"><a href="an-example-of-a-past-exam-2020.html#cb690-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb690-7"><a href="an-example-of-a-past-exam-2020.html#cb690-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Predicted values (and SE)</span></span>
<span id="cb690-8"><a href="an-example-of-a-past-exam-2020.html#cb690-8" aria-hidden="true" tabindex="-1"></a>pv <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod1, newData, <span class="at">se.fit =</span> <span class="cn">TRUE</span>)</span>
<span id="cb690-9"><a href="an-example-of-a-past-exam-2020.html#cb690-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb690-10"><a href="an-example-of-a-past-exam-2020.html#cb690-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Create new data for the predicted fit line</span></span>
<span id="cb690-11"><a href="an-example-of-a-past-exam-2020.html#cb690-11" aria-hidden="true" tabindex="-1"></a>newData <span class="ot">&lt;-</span> newData <span class="sc">%&gt;%</span></span>
<span id="cb690-12"><a href="an-example-of-a-past-exam-2020.html#cb690-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">nSpecies_LP =</span> pv<span class="sc">$</span>fit) <span class="sc">%&gt;%</span></span>
<span id="cb690-13"><a href="an-example-of-a-past-exam-2020.html#cb690-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">lowerCI_LP =</span> pv<span class="sc">$</span>fit <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> pv<span class="sc">$</span>se.fit) <span class="sc">%&gt;%</span></span>
<span id="cb690-14"><a href="an-example-of-a-past-exam-2020.html#cb690-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">upperCI_LP =</span> pv<span class="sc">$</span>fit <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> pv<span class="sc">$</span>se.fit)</span>
<span id="cb690-15"><a href="an-example-of-a-past-exam-2020.html#cb690-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb690-16"><a href="an-example-of-a-past-exam-2020.html#cb690-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the inverse link function</span></span>
<span id="cb690-17"><a href="an-example-of-a-past-exam-2020.html#cb690-17" aria-hidden="true" tabindex="-1"></a>inverseFunction <span class="ot">&lt;-</span> <span class="fu">family</span>(mod1)<span class="sc">$</span>linkinv</span>
<span id="cb690-18"><a href="an-example-of-a-past-exam-2020.html#cb690-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb690-19"><a href="an-example-of-a-past-exam-2020.html#cb690-19" aria-hidden="true" tabindex="-1"></a><span class="co"># transform predicted data to the natural scale</span></span>
<span id="cb690-20"><a href="an-example-of-a-past-exam-2020.html#cb690-20" aria-hidden="true" tabindex="-1"></a>newData <span class="ot">&lt;-</span> newData <span class="sc">%&gt;%</span></span>
<span id="cb690-21"><a href="an-example-of-a-past-exam-2020.html#cb690-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb690-22"><a href="an-example-of-a-past-exam-2020.html#cb690-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">nSpecies =</span> <span class="fu">inverseFunction</span>(nSpecies_LP),</span>
<span id="cb690-23"><a href="an-example-of-a-past-exam-2020.html#cb690-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">ymin =</span> <span class="fu">inverseFunction</span>(lowerCI_LP),</span>
<span id="cb690-24"><a href="an-example-of-a-past-exam-2020.html#cb690-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">ymax =</span> <span class="fu">inverseFunction</span>(upperCI_LP)</span>
<span id="cb690-25"><a href="an-example-of-a-past-exam-2020.html#cb690-25" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<p>Now we can add these to the plot:</p>
<div class="sourceCode" id="cb691"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb691-1"><a href="an-example-of-a-past-exam-2020.html#cb691-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(roundabouts, <span class="fu">aes</span>(</span>
<span id="cb691-2"><a href="an-example-of-a-past-exam-2020.html#cb691-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> area, <span class="at">y =</span> nSpecies,</span>
<span id="cb691-3"><a href="an-example-of-a-past-exam-2020.html#cb691-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">colour =</span> habitatType</span>
<span id="cb691-4"><a href="an-example-of-a-past-exam-2020.html#cb691-4" aria-hidden="true" tabindex="-1"></a>)) <span class="sc">+</span></span>
<span id="cb691-5"><a href="an-example-of-a-past-exam-2020.html#cb691-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">data =</span> newData, <span class="fu">aes</span>(</span>
<span id="cb691-6"><a href="an-example-of-a-past-exam-2020.html#cb691-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> area, <span class="at">ymin =</span> ymin, <span class="at">ymax =</span> ymax,</span>
<span id="cb691-7"><a href="an-example-of-a-past-exam-2020.html#cb691-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> habitatType, <span class="at">alpha =</span> <span class="fl">0.3</span></span>
<span id="cb691-8"><a href="an-example-of-a-past-exam-2020.html#cb691-8" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">+</span></span>
<span id="cb691-9"><a href="an-example-of-a-past-exam-2020.html#cb691-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">data =</span> newData, <span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>) <span class="sc">+</span></span>
<span id="cb691-10"><a href="an-example-of-a-past-exam-2020.html#cb691-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb691-11"><a href="an-example-of-a-past-exam-2020.html#cb691-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">alpha =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> <span class="co"># Remove the alpha legend</span></span>
<span id="cb691-12"><a href="an-example-of-a-past-exam-2020.html#cb691-12" aria-hidden="true" tabindex="-1"></a>  <span class="cn">NULL</span></span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-481-1.png" width="672" /></p>
<hr />

</div>

























<div class="footnotes">
<hr />
<ol start="20">
<li id="fn20"><p>I set options <code>options(dplyr.summarise.inform = FALSE)</code> to avoid the annoying messages.<a href="an-example-of-a-past-exam-2020.html#fnref20" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="exercise-solutions.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/jonesor/BB852_Book/edit/master/7_01_Exam_2020.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["BB852.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
},
"split_by": "section"
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
