<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 15 ANOVA: Linear models with a single categorical explanatory variable | BB852 - Data handling, visualisation and statistics</title>
  <meta name="description" content="Course book for BB852 at the Biology Department, University of Southern Denmark" />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 15 ANOVA: Linear models with a single categorical explanatory variable | BB852 - Data handling, visualisation and statistics" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Course book for BB852 at the Biology Department, University of Southern Denmark" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 15 ANOVA: Linear models with a single categorical explanatory variable | BB852 - Data handling, visualisation and statistics" />
  
  <meta name="twitter:description" content="Course book for BB852 at the Biology Department, University of Southern Denmark" />
  

<meta name="author" content="Owen R. Jones" />


<meta name="date" content="2024-08-22" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="assumptions-in-linear-models.html"/>
<link rel="next" href="linear-regression-models-with-a-single-continuous-explanatory-variable.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/tabwid-1.1.3/tabwid.css" rel="stylesheet" />
<script src="libs/tabwid-1.1.3/tabwid.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">BB852</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Preface</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#data-wrangling"><i class="fa fa-check"></i><b>1.1</b> Data wrangling</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#data-visualisation"><i class="fa fa-check"></i><b>1.2</b> Data visualisation</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#statistics"><i class="fa fa-check"></i><b>1.3</b> Statistics</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#data-sources"><i class="fa fa-check"></i><b>1.4</b> Data sources</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#your-instructors"><i class="fa fa-check"></i><b>1.5</b> Your instructor(s)</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#expectations"><i class="fa fa-check"></i><b>1.6</b> Expectations</a></li>
<li class="chapter" data-level="1.7" data-path="index.html"><a href="index.html#your-feedback"><i class="fa fa-check"></i><b>1.7</b> Your feedback</a></li>
<li class="chapter" data-level="1.8" data-path="index.html"><a href="index.html#assessment"><i class="fa fa-check"></i><b>1.8</b> Assessment</a></li>
<li class="chapter" data-level="1.9" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i><b>1.9</b> Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="schedule.html"><a href="schedule.html"><i class="fa fa-check"></i><b>2</b> Schedule</a></li>
<li class="chapter" data-level="3" data-path="additional-recommended-reading.html"><a href="additional-recommended-reading.html"><i class="fa fa-check"></i><b>3</b> Additional recommended reading</a></li>
<li class="chapter" data-level="4" data-path="an-r-refresher.html"><a href="an-r-refresher.html"><i class="fa fa-check"></i><b>4</b> An R refresher</a>
<ul>
<li class="chapter" data-level="4.1" data-path="an-r-refresher.html"><a href="an-r-refresher.html#getting-started-with-r"><i class="fa fa-check"></i><b>4.1</b> Getting started with R</a></li>
<li class="chapter" data-level="4.2" data-path="an-r-refresher.html"><a href="an-r-refresher.html#getting-help"><i class="fa fa-check"></i><b>4.2</b> Getting help</a></li>
<li class="chapter" data-level="4.3" data-path="an-r-refresher.html"><a href="an-r-refresher.html#r-as-a-fancy-calculator"><i class="fa fa-check"></i><b>4.3</b> R as a fancy calculator</a></li>
<li class="chapter" data-level="4.4" data-path="an-r-refresher.html"><a href="an-r-refresher.html#objects-in-r"><i class="fa fa-check"></i><b>4.4</b> Objects in R</a></li>
<li class="chapter" data-level="4.5" data-path="an-r-refresher.html"><a href="an-r-refresher.html#manipulating-objects"><i class="fa fa-check"></i><b>4.5</b> Manipulating objects</a></li>
<li class="chapter" data-level="4.6" data-path="an-r-refresher.html"><a href="an-r-refresher.html#missing-values-infinity-and-non-numbers"><i class="fa fa-check"></i><b>4.6</b> Missing values, infinity and “non-numbers”</a></li>
<li class="chapter" data-level="4.7" data-path="an-r-refresher.html"><a href="an-r-refresher.html#basic-information-about-objects"><i class="fa fa-check"></i><b>4.7</b> Basic information about objects</a></li>
<li class="chapter" data-level="4.8" data-path="an-r-refresher.html"><a href="an-r-refresher.html#data-frames"><i class="fa fa-check"></i><b>4.8</b> Data frames</a></li>
<li class="chapter" data-level="4.9" data-path="an-r-refresher.html"><a href="an-r-refresher.html#classes-in-r"><i class="fa fa-check"></i><b>4.9</b> Classes in R</a></li>
<li class="chapter" data-level="4.10" data-path="an-r-refresher.html"><a href="an-r-refresher.html#organising-your-work"><i class="fa fa-check"></i><b>4.10</b> Organising your work</a></li>
<li class="chapter" data-level="4.11" data-path="an-r-refresher.html"><a href="an-r-refresher.html#inspecting-the-data"><i class="fa fa-check"></i><b>4.11</b> Inspecting the data</a></li>
<li class="chapter" data-level="4.12" data-path="an-r-refresher.html"><a href="an-r-refresher.html#classes-in-r-1"><i class="fa fa-check"></i><b>4.12</b> “Classes” in R</a></li>
<li class="chapter" data-level="4.13" data-path="an-r-refresher.html"><a href="an-r-refresher.html#tables-and-summary-statistics"><i class="fa fa-check"></i><b>4.13</b> Tables and summary statistics</a></li>
<li class="chapter" data-level="4.14" data-path="an-r-refresher.html"><a href="an-r-refresher.html#plotting-data"><i class="fa fa-check"></i><b>4.14</b> Plotting data</a></li>
<li class="chapter" data-level="4.15" data-path="an-r-refresher.html"><a href="an-r-refresher.html#r-packages"><i class="fa fa-check"></i><b>4.15</b> R Packages</a></li>
<li class="chapter" data-level="4.16" data-path="an-r-refresher.html"><a href="an-r-refresher.html#exercise-californian-bird-diversity"><i class="fa fa-check"></i><b>4.16</b> Exercise: Californian bird diversity</a>
<ul>
<li class="chapter" data-level="4.16.1" data-path="an-r-refresher.html"><a href="an-r-refresher.html#the-data"><i class="fa fa-check"></i><b>4.16.1</b> The data</a></li>
<li class="chapter" data-level="4.16.2" data-path="an-r-refresher.html"><a href="an-r-refresher.html#try-the-following"><i class="fa fa-check"></i><b>4.16.2</b> Try the following</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html"><i class="fa fa-check"></i><b>5</b> Tips and tricks</a>
<ul>
<li class="chapter" data-level="5.1" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#appearance"><i class="fa fa-check"></i><b>5.1</b> Appearance</a></li>
<li class="chapter" data-level="5.2" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#shortcuts"><i class="fa fa-check"></i><b>5.2</b> Shortcuts</a></li>
<li class="chapter" data-level="5.3" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#code-style"><i class="fa fa-check"></i><b>5.3</b> Code style</a></li>
<li class="chapter" data-level="5.4" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#the-plots-pane"><i class="fa fa-check"></i><b>5.4</b> The plots pane</a></li>
<li class="chapter" data-level="5.5" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#tables"><i class="fa fa-check"></i><b>5.5</b> Tables</a></li>
<li class="chapter" data-level="5.6" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#importing-data-from-text-files"><i class="fa fa-check"></i><b>5.6</b> Importing data from text files</a></li>
<li class="chapter" data-level="5.7" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#importing-data-from-excel"><i class="fa fa-check"></i><b>5.7</b> Importing data from Excel</a></li>
<li class="chapter" data-level="5.8" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#numbers"><i class="fa fa-check"></i><b>5.8</b> Numbers</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="paths-and-projects.html"><a href="paths-and-projects.html"><i class="fa fa-check"></i><b>6</b> Paths and projects</a>
<ul>
<li class="chapter" data-level="6.1" data-path="paths-and-projects.html"><a href="paths-and-projects.html#file-structure"><i class="fa fa-check"></i><b>6.1</b> File structure</a></li>
<li class="chapter" data-level="6.2" data-path="paths-and-projects.html"><a href="paths-and-projects.html#paths-and-the-command-line"><i class="fa fa-check"></i><b>6.2</b> Paths and the command line</a></li>
<li class="chapter" data-level="6.3" data-path="paths-and-projects.html"><a href="paths-and-projects.html#r-and-file-structure"><i class="fa fa-check"></i><b>6.3</b> R and file structure</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="paths-and-projects.html"><a href="paths-and-projects.html#setting-the-working-directory"><i class="fa fa-check"></i><b>6.3.1</b> Setting the working directory</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="paths-and-projects.html"><a href="paths-and-projects.html#projects-in-r"><i class="fa fa-check"></i><b>6.4</b> Projects in R</a></li>
</ul></li>
<li class="part"><span><b>I Data Wrangling</b></span></li>
<li class="chapter" data-level="7" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html"><i class="fa fa-check"></i><b>7</b> Data wrangling with <code>dplyr</code></a>
<ul>
<li class="chapter" data-level="7.1" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#select"><i class="fa fa-check"></i><b>7.1</b> <code>select</code></a></li>
<li class="chapter" data-level="7.2" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#filter"><i class="fa fa-check"></i><b>7.2</b> <code>filter</code></a></li>
<li class="chapter" data-level="7.3" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#arrange"><i class="fa fa-check"></i><b>7.3</b> <code>arrange</code></a></li>
<li class="chapter" data-level="7.4" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#summarise-and-group_by"><i class="fa fa-check"></i><b>7.4</b> <code>summarise</code> and <code>group_by</code></a></li>
<li class="chapter" data-level="7.5" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#using-pipes-saving-data."><i class="fa fa-check"></i><b>7.5</b> Using pipes, saving data.</a></li>
<li class="chapter" data-level="7.6" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#exercise-wrangling-the-amniote-life-history-database"><i class="fa fa-check"></i><b>7.6</b> Exercise: Wrangling the Amniote Life History Database</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="combining-data-sets.html"><a href="combining-data-sets.html"><i class="fa fa-check"></i><b>8</b> Combining data sets</a>
<ul>
<li class="chapter" data-level="8.1" data-path="combining-data-sets.html"><a href="combining-data-sets.html#using-join"><i class="fa fa-check"></i><b>8.1</b> Using <code>join</code></a></li>
<li class="chapter" data-level="8.2" data-path="combining-data-sets.html"><a href="combining-data-sets.html#using-pivot_longer"><i class="fa fa-check"></i><b>8.2</b> Using <code>pivot_longer</code></a></li>
<li class="chapter" data-level="8.3" data-path="combining-data-sets.html"><a href="combining-data-sets.html#exercise-temperature-effects-on-egg-laying-dates"><i class="fa fa-check"></i><b>8.3</b> Exercise: Temperature effects on egg laying dates</a></li>
</ul></li>
<li class="part"><span><b>II Data visualisation</b></span></li>
<li class="chapter" data-level="9" data-path="visualising-data-with-ggplot2.html"><a href="visualising-data-with-ggplot2.html"><i class="fa fa-check"></i><b>9</b> Visualising data with <code>ggplot2</code></a>
<ul>
<li class="chapter" data-level="9.1" data-path="visualising-data-with-ggplot2.html"><a href="visualising-data-with-ggplot2.html#histograms"><i class="fa fa-check"></i><b>9.1</b> Histograms</a></li>
<li class="chapter" data-level="9.2" data-path="visualising-data-with-ggplot2.html"><a href="visualising-data-with-ggplot2.html#facets---splitting-data-across-panels"><i class="fa fa-check"></i><b>9.2</b> “Facets” - splitting data across panels</a></li>
<li class="chapter" data-level="9.3" data-path="visualising-data-with-ggplot2.html"><a href="visualising-data-with-ggplot2.html#box-plots"><i class="fa fa-check"></i><b>9.3</b> Box plots</a></li>
<li class="chapter" data-level="9.4" data-path="visualising-data-with-ggplot2.html"><a href="visualising-data-with-ggplot2.html#lines-and-points"><i class="fa fa-check"></i><b>9.4</b> Lines and points</a></li>
<li class="chapter" data-level="9.5" data-path="visualising-data-with-ggplot2.html"><a href="visualising-data-with-ggplot2.html#scatter-plots"><i class="fa fa-check"></i><b>9.5</b> Scatter plots</a></li>
<li class="chapter" data-level="9.6" data-path="visualising-data-with-ggplot2.html"><a href="visualising-data-with-ggplot2.html#bar-plots"><i class="fa fa-check"></i><b>9.6</b> Bar plots</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html"><i class="fa fa-check"></i><b>10</b> Distributions and summarising data</a>
<ul>
<li class="chapter" data-level="10.1" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#distributions"><i class="fa fa-check"></i><b>10.1</b> Distributions</a></li>
<li class="chapter" data-level="10.2" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#normal-distribution"><i class="fa fa-check"></i><b>10.2</b> Normal distribution</a></li>
<li class="chapter" data-level="10.3" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#comparing-normal-distributions"><i class="fa fa-check"></i><b>10.3</b> Comparing normal distributions</a></li>
<li class="chapter" data-level="10.4" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#poisson-distribution"><i class="fa fa-check"></i><b>10.4</b> Poisson distribution</a></li>
<li class="chapter" data-level="10.5" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#comparing-normal-and-poisson-distributions"><i class="fa fa-check"></i><b>10.5</b> Comparing normal and Poisson distributions</a></li>
<li class="chapter" data-level="10.6" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#the-law-of-large-numbers"><i class="fa fa-check"></i><b>10.6</b> The law of large numbers</a>
<ul>
<li class="chapter" data-level="10.6.1" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#coin-flipping"><i class="fa fa-check"></i><b>10.6.1</b> Coin flipping</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#exercise-virtual-dice"><i class="fa fa-check"></i><b>10.7</b> Exercise: Virtual dice</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html"><i class="fa fa-check"></i><b>11</b> Pimping your plots</a>
<ul>
<li class="chapter" data-level="11.1" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#a-basic-plot"><i class="fa fa-check"></i><b>11.1</b> A basic plot</a></li>
<li class="chapter" data-level="11.2" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#axis-limits"><i class="fa fa-check"></i><b>11.2</b> Axis limits</a></li>
<li class="chapter" data-level="11.3" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#transforming-the-axis-log-scale"><i class="fa fa-check"></i><b>11.3</b> Transforming the axis (log scale)</a></li>
<li class="chapter" data-level="11.4" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#changing-the-axis-tick-marks"><i class="fa fa-check"></i><b>11.4</b> Changing the axis tick marks</a></li>
<li class="chapter" data-level="11.5" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#axis-labels"><i class="fa fa-check"></i><b>11.5</b> Axis labels</a></li>
<li class="chapter" data-level="11.6" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#colours"><i class="fa fa-check"></i><b>11.6</b> Colours</a></li>
<li class="chapter" data-level="11.7" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#themes"><i class="fa fa-check"></i><b>11.7</b> Themes</a></li>
<li class="chapter" data-level="11.8" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#moving-the-legend"><i class="fa fa-check"></i><b>11.8</b> Moving the legend</a></li>
<li class="chapter" data-level="11.9" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#combining-multiple-plots"><i class="fa fa-check"></i><b>11.9</b> Combining multiple plots</a></li>
<li class="chapter" data-level="11.10" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#saving-your-plot"><i class="fa fa-check"></i><b>11.10</b> Saving your plot</a></li>
<li class="chapter" data-level="11.11" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#final-word-on-plots"><i class="fa fa-check"></i><b>11.11</b> Final word on plots</a></li>
</ul></li>
<li class="part"><span><b>III Statistics</b></span></li>
<li class="chapter" data-level="12" data-path="randomisation-tests.html"><a href="randomisation-tests.html"><i class="fa fa-check"></i><b>12</b> Randomisation Tests</a>
<ul>
<li class="chapter" data-level="12.1" data-path="randomisation-tests.html"><a href="randomisation-tests.html#randomisation-test-in-r"><i class="fa fa-check"></i><b>12.1</b> Randomisation test in R</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="randomisation-tests.html"><a href="randomisation-tests.html#calculate-the-observed-difference"><i class="fa fa-check"></i><b>12.1.1</b> Calculate the observed difference</a></li>
<li class="chapter" data-level="12.1.2" data-path="randomisation-tests.html"><a href="randomisation-tests.html#null-distribution"><i class="fa fa-check"></i><b>12.1.2</b> Null distribution</a></li>
<li class="chapter" data-level="12.1.3" data-path="randomisation-tests.html"><a href="randomisation-tests.html#testing-significance"><i class="fa fa-check"></i><b>12.1.3</b> Testing significance</a></li>
<li class="chapter" data-level="12.1.4" data-path="randomisation-tests.html"><a href="randomisation-tests.html#testing-the-hypothesis"><i class="fa fa-check"></i><b>12.1.4</b> Testing the hypothesis</a></li>
<li class="chapter" data-level="12.1.5" data-path="randomisation-tests.html"><a href="randomisation-tests.html#writing-it-up"><i class="fa fa-check"></i><b>12.1.5</b> Writing it up</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="randomisation-tests.html"><a href="randomisation-tests.html#paired-randomisation-tests"><i class="fa fa-check"></i><b>12.2</b> Paired Randomisation Tests</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="randomisation-tests.html"><a href="randomisation-tests.html#the-randomisation-test"><i class="fa fa-check"></i><b>12.2.1</b> The randomisation test</a></li>
<li class="chapter" data-level="12.2.2" data-path="randomisation-tests.html"><a href="randomisation-tests.html#null-distribution-1"><i class="fa fa-check"></i><b>12.2.2</b> Null distribution</a></li>
<li class="chapter" data-level="12.2.3" data-path="randomisation-tests.html"><a href="randomisation-tests.html#the-formal-hypothesis-test"><i class="fa fa-check"></i><b>12.2.3</b> The formal hypothesis test</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="randomisation-tests.html"><a href="randomisation-tests.html#exercise-sexual-selection-in-hercules-beetles"><i class="fa fa-check"></i><b>12.3</b> Exercise: Sexual selection in Hercules beetles</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html"><i class="fa fa-check"></i><b>13</b> t-test: Comparing two means</a>
<ul>
<li class="chapter" data-level="13.1" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#some-theory"><i class="fa fa-check"></i><b>13.1</b> Some theory</a></li>
<li class="chapter" data-level="13.2" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#one-sample-t-test"><i class="fa fa-check"></i><b>13.2</b> One sample t-test</a></li>
<li class="chapter" data-level="13.3" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#doing-it-by-hand---where-does-the-t-statistic-come-from"><i class="fa fa-check"></i><b>13.3</b> Doing it “by hand” - where does the t-statistic come from?</a></li>
<li class="chapter" data-level="13.4" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#paired-t-test"><i class="fa fa-check"></i><b>13.4</b> Paired t-test</a></li>
<li class="chapter" data-level="13.5" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#a-paired-t-test-is-a-one-sample-test."><i class="fa fa-check"></i><b>13.5</b> A paired t-test is a one-sample test.</a></li>
<li class="chapter" data-level="13.6" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#two-sample-t-test"><i class="fa fa-check"></i><b>13.6</b> Two sample t-test</a></li>
<li class="chapter" data-level="13.7" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#t-tests-are-linear-models"><i class="fa fa-check"></i><b>13.7</b> t-tests are linear models</a></li>
<li class="chapter" data-level="13.8" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#exercise-sex-differences-in-fine-motor-skills"><i class="fa fa-check"></i><b>13.8</b> Exercise: Sex differences in fine motor skills</a></li>
<li class="chapter" data-level="13.9" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#exercise-therapy-for-anorexia"><i class="fa fa-check"></i><b>13.9</b> Exercise: Therapy for anorexia</a></li>
<li class="chapter" data-level="13.10" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#exercise-compare-t-tests-with-randomisation-tests-optional"><i class="fa fa-check"></i><b>13.10</b> Exercise: Compare t-tests with randomisation tests (optional)</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="assumptions-in-linear-models.html"><a href="assumptions-in-linear-models.html"><i class="fa fa-check"></i><b>14</b> Assumptions in linear models</a>
<ul>
<li class="chapter" data-level="14.1" data-path="assumptions-in-linear-models.html"><a href="assumptions-in-linear-models.html#the-assumptions"><i class="fa fa-check"></i><b>14.1</b> The assumptions</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><i class="fa fa-check"></i><b>15</b> ANOVA: Linear models with a single categorical explanatory variable</a>
<ul>
<li class="chapter" data-level="15.1" data-path="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#one-way-anova"><i class="fa fa-check"></i><b>15.1</b> One-way ANOVA</a></li>
<li class="chapter" data-level="15.2" data-path="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#fitting-an-anova-in-r"><i class="fa fa-check"></i><b>15.2</b> Fitting an ANOVA in R</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#where-are-the-differences"><i class="fa fa-check"></i><b>15.2.1</b> Where are the differences?</a></li>
<li class="chapter" data-level="15.2.2" data-path="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#tukeys-honestly-significant-difference-hsd"><i class="fa fa-check"></i><b>15.2.2</b> Tukey’s Honestly Significant Difference (HSD)</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#anova-calculation-by-hand."><i class="fa fa-check"></i><b>15.3</b> ANOVA calculation “by hand”.</a></li>
<li class="chapter" data-level="15.4" data-path="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#exercise-apple-tree-crop-yield"><i class="fa fa-check"></i><b>15.4</b> Exercise: Apple tree crop yield</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="linear-regression-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html"><i class="fa fa-check"></i><b>16</b> Linear regression: models with a single continuous explanatory variable</a>
<ul>
<li class="chapter" data-level="16.1" data-path="linear-regression-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#some-theory-1"><i class="fa fa-check"></i><b>16.1</b> Some theory</a></li>
<li class="chapter" data-level="16.2" data-path="linear-regression-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#evaluating-a-hypothesis-with-a-linear-regression-model"><i class="fa fa-check"></i><b>16.2</b> Evaluating a hypothesis with a linear regression model</a></li>
<li class="chapter" data-level="16.3" data-path="linear-regression-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#assumptions"><i class="fa fa-check"></i><b>16.3</b> Assumptions</a></li>
<li class="chapter" data-level="16.4" data-path="linear-regression-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#worked-example-height-hand-width-relationship"><i class="fa fa-check"></i><b>16.4</b> Worked example: height-hand width relationship</a></li>
<li class="chapter" data-level="16.5" data-path="linear-regression-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#exercise-chirping-crickets"><i class="fa fa-check"></i><b>16.5</b> Exercise: Chirping crickets</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html"><a href="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html"><i class="fa fa-check"></i><b>17</b> ANCOVA: Linear models with categorical and continuous explanatory variables</a>
<ul>
<li class="chapter" data-level="17.1" data-path="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html"><a href="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html#the-height-hand-width-example."><i class="fa fa-check"></i><b>17.1</b> The height ~ hand width example.</a></li>
<li class="chapter" data-level="17.2" data-path="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html"><a href="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html#summarising-with-anova"><i class="fa fa-check"></i><b>17.2</b> Summarising with <code>anova</code></a></li>
<li class="chapter" data-level="17.3" data-path="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html"><a href="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html#the-summary-of-coefficients-summary"><i class="fa fa-check"></i><b>17.3</b> The summary of coefficients (<code>summary</code>)</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html"><i class="fa fa-check"></i><b>18</b> n-way ANOVA: Linear models with &gt;1 categorical explanatory variables</a>
<ul>
<li class="chapter" data-level="18.1" data-path="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#fitting-a-two-way-anova-model"><i class="fa fa-check"></i><b>18.1</b> Fitting a two-way ANOVA model</a></li>
<li class="chapter" data-level="18.2" data-path="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#summarising-the-model-anova"><i class="fa fa-check"></i><b>18.2</b> Summarising the model (<code>anova</code>)</a></li>
<li class="chapter" data-level="18.3" data-path="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#summarising-the-model-summary"><i class="fa fa-check"></i><b>18.3</b> Summarising the model (<code>summary</code>)</a></li>
<li class="chapter" data-level="18.4" data-path="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#exercise-fish-behaviour"><i class="fa fa-check"></i><b>18.4</b> Exercise: Fish behaviour</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="evaluating-linear-models.html"><a href="evaluating-linear-models.html"><i class="fa fa-check"></i><b>19</b> Evaluating linear models</a>
<ul>
<li class="chapter" data-level="19.1" data-path="evaluating-linear-models.html"><a href="evaluating-linear-models.html#r-squared-value"><i class="fa fa-check"></i><b>19.1</b> R-squared value</a></li>
<li class="chapter" data-level="19.2" data-path="evaluating-linear-models.html"><a href="evaluating-linear-models.html#akaike-information-criterion-aic"><i class="fa fa-check"></i><b>19.2</b> Akaike Information Criterion (AIC)</a></li>
<li class="chapter" data-level="19.3" data-path="evaluating-linear-models.html"><a href="evaluating-linear-models.html#variance-partitioning"><i class="fa fa-check"></i><b>19.3</b> Variance partitioning</a></li>
<li class="chapter" data-level="19.4" data-path="evaluating-linear-models.html"><a href="evaluating-linear-models.html#conclusion"><i class="fa fa-check"></i><b>19.4</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html"><i class="fa fa-check"></i><b>20</b> Generalised linear models</a>
<ul>
<li class="chapter" data-level="20.1" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html#count-data-with-poisson-errors."><i class="fa fa-check"></i><b>20.1</b> Count data with Poisson errors.</a>
<ul>
<li class="chapter" data-level="20.1.1" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html#example-number-of-offspring-in-foxes."><i class="fa fa-check"></i><b>20.1.1</b> Example: Number of offspring in foxes.</a></li>
<li class="chapter" data-level="20.1.2" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html#example-cancer-clusters"><i class="fa fa-check"></i><b>20.1.2</b> Example: Cancer clusters</a></li>
</ul></li>
<li class="chapter" data-level="20.2" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html#exercise-maze-runner"><i class="fa fa-check"></i><b>20.2</b> Exercise: Maze runner</a></li>
<li class="chapter" data-level="20.3" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html#overdispersion"><i class="fa fa-check"></i><b>20.3</b> Overdispersion</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="extending-use-cases-of-glm.html"><a href="extending-use-cases-of-glm.html"><i class="fa fa-check"></i><b>21</b> Extending use cases of GLM</a>
<ul>
<li class="chapter" data-level="21.1" data-path="extending-use-cases-of-glm.html"><a href="extending-use-cases-of-glm.html#binomial-response-data"><i class="fa fa-check"></i><b>21.1</b> Binomial response data</a></li>
<li class="chapter" data-level="21.2" data-path="extending-use-cases-of-glm.html"><a href="extending-use-cases-of-glm.html#example-nfl-field-goals"><i class="fa fa-check"></i><b>21.2</b> Example: NFL field goals</a></li>
<li class="chapter" data-level="21.3" data-path="extending-use-cases-of-glm.html"><a href="extending-use-cases-of-glm.html#example-sex-ratio-in-turtles"><i class="fa fa-check"></i><b>21.3</b> Example: Sex ratio in turtles</a></li>
<li class="chapter" data-level="21.4" data-path="extending-use-cases-of-glm.html"><a href="extending-use-cases-of-glm.html#example-smoking"><i class="fa fa-check"></i><b>21.4</b> Example: Smoking</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html"><i class="fa fa-check"></i><b>22</b> Power analysis by simulation</a>
<ul>
<li class="chapter" data-level="22.1" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#type-i-and-ii-errors-and-statistical-power"><i class="fa fa-check"></i><b>22.1</b> Type I and II errors and statistical power</a></li>
<li class="chapter" data-level="22.2" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#what-determines-statistical-power"><i class="fa fa-check"></i><b>22.2</b> What determines statistical power?</a></li>
<li class="chapter" data-level="22.3" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#an-example-of-calculating-statistical-power."><i class="fa fa-check"></i><b>22.3</b> An example of calculating statistical power.</a>
<ul>
<li class="chapter" data-level="22.3.1" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#the-simulation"><i class="fa fa-check"></i><b>22.3.1</b> The simulation</a></li>
<li class="chapter" data-level="22.3.2" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#some-questions-for-you-to-address"><i class="fa fa-check"></i><b>22.3.2</b> Some questions for you to address:</a></li>
</ul></li>
<li class="chapter" data-level="22.4" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#summary"><i class="fa fa-check"></i><b>22.4</b> Summary</a></li>
<li class="chapter" data-level="22.5" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#extending-the-simulation-optional-advanced"><i class="fa fa-check"></i><b>22.5</b> Extending the simulation (optional, advanced)</a></li>
<li class="chapter" data-level="22.6" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#exercise-1-snails-on-the-move"><i class="fa fa-check"></i><b>22.6</b> Exercise 1: Snails on the move</a></li>
<li class="chapter" data-level="22.7" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#exercise-2-mouse-lemur-strength"><i class="fa fa-check"></i><b>22.7</b> Exercise 2: Mouse lemur strength</a></li>
</ul></li>
<li class="part"><span><b>IV Appendix</b></span></li>
<li class="chapter" data-level="23" data-path="examples-of-statistics-reporting.html"><a href="examples-of-statistics-reporting.html"><i class="fa fa-check"></i><b>23</b> Examples of statistics reporting</a>
<ul>
<li class="chapter" data-level="23.1" data-path="examples-of-statistics-reporting.html"><a href="examples-of-statistics-reporting.html#t-test"><i class="fa fa-check"></i><b>23.1</b> t-test</a></li>
<li class="chapter" data-level="23.2" data-path="examples-of-statistics-reporting.html"><a href="examples-of-statistics-reporting.html#simple-linear-regression-model"><i class="fa fa-check"></i><b>23.2</b> Simple linear regression model</a></li>
<li class="chapter" data-level="23.3" data-path="examples-of-statistics-reporting.html"><a href="examples-of-statistics-reporting.html#a-generalised-linear-model-glm"><i class="fa fa-check"></i><b>23.3</b> A Generalised linear model (GLM)</a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="an-example-of-a-past-written-assignment-2020.html"><a href="an-example-of-a-past-written-assignment-2020.html"><i class="fa fa-check"></i><b>24</b> An example of a past Written Assignment (2020)</a></li>
<li class="chapter" data-level="25" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html"><i class="fa fa-check"></i><b>25</b> Leveraging ChatGPT for R Programming Assistance</a>
<ul>
<li class="chapter" data-level="25.1" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#introduction"><i class="fa fa-check"></i><b>25.1</b> Introduction</a></li>
<li class="chapter" data-level="25.2" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#overview"><i class="fa fa-check"></i><b>25.2</b> Overview</a></li>
<li class="chapter" data-level="25.3" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#what-is-a-large-language-model-llm-and-how-do-they-work"><i class="fa fa-check"></i><b>25.3</b> What is a Large Language Model (LLM) and how do they work?</a></li>
<li class="chapter" data-level="25.4" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#limitations"><i class="fa fa-check"></i><b>25.4</b> Limitations</a>
<ul>
<li class="chapter" data-level="25.4.1" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#limited-knowledge"><i class="fa fa-check"></i><b>25.4.1</b> Limited knowledge</a></li>
<li class="chapter" data-level="25.4.2" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#hallucination"><i class="fa fa-check"></i><b>25.4.2</b> Hallucination</a></li>
<li class="chapter" data-level="25.4.3" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#numerical-ability"><i class="fa fa-check"></i><b>25.4.3</b> Numerical ability</a></li>
</ul></li>
<li class="chapter" data-level="25.5" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#ethics-of-using-llms-in-education"><i class="fa fa-check"></i><b>25.5</b> Ethics of using LLMs in education</a></li>
<li class="chapter" data-level="25.6" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#use-cases-in-r"><i class="fa fa-check"></i><b>25.6</b> Use cases in R</a>
<ul>
<li class="chapter" data-level="25.6.1" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#finding-errors."><i class="fa fa-check"></i><b>25.6.1</b> Finding errors.</a></li>
<li class="chapter" data-level="25.6.2" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#explaining-code"><i class="fa fa-check"></i><b>25.6.2</b> Explaining code</a></li>
<li class="chapter" data-level="25.6.3" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#interpreting-output"><i class="fa fa-check"></i><b>25.6.3</b> Interpreting output</a></li>
<li class="chapter" data-level="25.6.4" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#translating-code-e.g.-from-pythonmatlab-to-r"><i class="fa fa-check"></i><b>25.6.4</b> Translating code (e.g. from Python/Matlab to R)</a></li>
<li class="chapter" data-level="25.6.5" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#solving-modelling-problems"><i class="fa fa-check"></i><b>25.6.5</b> Solving modelling problems</a></li>
<li class="chapter" data-level="25.6.6" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#helping-with-documentationcomments"><i class="fa fa-check"></i><b>25.6.6</b> Helping with documentation/comments</a></li>
<li class="chapter" data-level="25.6.7" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#finding-alternativebetter-ways"><i class="fa fa-check"></i><b>25.6.7</b> Finding alternative/better ways</a></li>
</ul></li>
<li class="chapter" data-level="25.7" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#some-tips"><i class="fa fa-check"></i><b>25.7</b> Some tips</a></li>
</ul></li>
<li class="part"><span><b>V Solutions</b></span></li>
<li class="chapter" data-level="26" data-path="exercise-solutions.html"><a href="exercise-solutions.html"><i class="fa fa-check"></i><b>26</b> Exercise Solutions</a>
<ul>
<li class="chapter" data-level="26.1" data-path="exercise-solutions.html"><a href="exercise-solutions.html#californian-bird-diversity"><i class="fa fa-check"></i><b>26.1</b> Californian bird diversity</a></li>
<li class="chapter" data-level="26.2" data-path="exercise-solutions.html"><a href="exercise-solutions.html#wrangling-the-amniote-life-history-database"><i class="fa fa-check"></i><b>26.2</b> Wrangling the Amniote Life History Database</a></li>
<li class="chapter" data-level="26.3" data-path="exercise-solutions.html"><a href="exercise-solutions.html#temperature-effects-on-egg-laying-dates"><i class="fa fa-check"></i><b>26.3</b> Temperature effects on egg laying dates</a></li>
<li class="chapter" data-level="26.4" data-path="exercise-solutions.html"><a href="exercise-solutions.html#virtual-dice"><i class="fa fa-check"></i><b>26.4</b> Virtual dice</a></li>
<li class="chapter" data-level="26.5" data-path="exercise-solutions.html"><a href="exercise-solutions.html#sexual-selection-in-hercules-beetles"><i class="fa fa-check"></i><b>26.5</b> Sexual selection in Hercules beetles</a></li>
<li class="chapter" data-level="26.6" data-path="exercise-solutions.html"><a href="exercise-solutions.html#sex-differences-in-fine-motor-skills"><i class="fa fa-check"></i><b>26.6</b> Sex differences in fine motor skills</a></li>
<li class="chapter" data-level="26.7" data-path="exercise-solutions.html"><a href="exercise-solutions.html#therapy-for-anorexia"><i class="fa fa-check"></i><b>26.7</b> Therapy for anorexia</a></li>
<li class="chapter" data-level="26.8" data-path="exercise-solutions.html"><a href="exercise-solutions.html#compare-t-tests-with-randomisation-tests"><i class="fa fa-check"></i><b>26.8</b> Compare t-tests with randomisation tests</a></li>
<li class="chapter" data-level="26.9" data-path="exercise-solutions.html"><a href="exercise-solutions.html#apple-tree-crop-yield"><i class="fa fa-check"></i><b>26.9</b> Apple tree crop yield</a></li>
<li class="chapter" data-level="26.10" data-path="exercise-solutions.html"><a href="exercise-solutions.html#chirping-crickets"><i class="fa fa-check"></i><b>26.10</b> Chirping crickets</a></li>
<li class="chapter" data-level="26.11" data-path="exercise-solutions.html"><a href="exercise-solutions.html#fish-behaviour"><i class="fa fa-check"></i><b>26.11</b> Fish behaviour</a></li>
<li class="chapter" data-level="26.12" data-path="exercise-solutions.html"><a href="exercise-solutions.html#maze-runner"><i class="fa fa-check"></i><b>26.12</b> Maze runner</a></li>
<li class="chapter" data-level="26.13" data-path="exercise-solutions.html"><a href="exercise-solutions.html#snails-on-the-move"><i class="fa fa-check"></i><b>26.13</b> Snails on the move</a></li>
<li class="chapter" data-level="26.14" data-path="exercise-solutions.html"><a href="exercise-solutions.html#mouse-lemur-strength"><i class="fa fa-check"></i><b>26.14</b> Mouse lemur strength</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">BB852 - Data handling, visualisation and statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="anova-linear-models-with-a-single-categorical-explanatory-variable" class="section level1 hasAnchor" number="15">
<h1><span class="header-section-number">Chapter 15</span> ANOVA: Linear models with a single categorical explanatory variable<a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#anova-linear-models-with-a-single-categorical-explanatory-variable" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>With the previous work on t-tests (and also with randomisation tests), you are now equipped to test for differences between two groups, or between one group and some fixed value. But what if there are more than two groups?</p>
<p>The answer is to use a one-way analysis of variance (ANOVA). Conceptually, this works the same way as a t-test.</p>
<div id="one-way-anova" class="section level2 hasAnchor" number="15.1">
<h2><span class="header-section-number">15.1</span> One-way ANOVA<a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#one-way-anova" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The one-way ANOVA is illustrated below with two cases (Figure <a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#fig:3-03-ANOVA-1">15.1</a>). In both cases there are three groups. These could represent treatment groups in an experiment (e.g. different fertiliser addition to plants). In figure A, the three groups are very close, and the means are not significantly different from each other. In figure B, there is one group that stands apart from the others. The ANOVA will tell us whether <em>at least one</em> of the groups is different from the others.</p>
<div class="figure" style="text-align: left"><span style="display:block;" id="fig:3-03-ANOVA-1"></span>
<img src="BB852_files/figure-html/3-03-ANOVA-1-1.png" alt="Visualising an ANOVA." width="672" />
<p class="caption">
Figure 15.1: Visualising an ANOVA.
</p>
</div>
<p>After figuring out if at least one of the groups is significantly different from the others it is often enough to examine plots (or summary statistics) to see where the differences are (e.g. which group(s) are different from each other). In other cases it might be necessary to do follow up <em>post-hoc multiple comparison</em> tests. We will come to those later.</p>
</div>
<div id="fitting-an-anova-in-r" class="section level2 hasAnchor" number="15.2">
<h2><span class="header-section-number">15.2</span> Fitting an ANOVA in R<a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#fitting-an-anova-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>New coffee machines use “pods” to make espresso. These have become much more popular than the traditional “bar machines”. This data looks at the amount of “crema” or foam produced (a sign of quality!) using three methods: bar machines (BM), Hyper Espresso Pods (HIP) and Illy Espresso System (IES). Are any of these methods better than the others?</p>
<div class="do-something">
<p>
Remember to load the <code>dplyr</code>, <code>magrittr</code> and
<code>ggplot</code> packages, and to set your working directory
correctly.
</p>
</div>
<p>Import the data (<code>espresso.csv</code>) and look at it.</p>
<div class="sourceCode" id="cb352"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb352-1"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb352-1" tabindex="-1"></a>espresso <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;CourseData/espresso.csv&quot;</span>,</span>
<span id="cb352-2"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb352-2" tabindex="-1"></a>  <span class="at">stringsAsFactors =</span> <span class="cn">TRUE</span></span>
<span id="cb352-3"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb352-3" tabindex="-1"></a>)</span>
<span id="cb352-4"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb352-4" tabindex="-1"></a><span class="fu">head</span>(espresso)</span></code></pre></div>
<pre><code>##   foamIndx method
## 1    36.64     BM
## 2    39.65     BM
## 3    37.74     BM
## 4    35.96     BM
## 5    38.52     BM
## 6    21.02     BM</code></pre>
<div class="sourceCode" id="cb354"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb354-1"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb354-1" tabindex="-1"></a>(<span class="fu">ggplot</span>(espresso, <span class="fu">aes</span>(<span class="at">x =</span> method, <span class="at">y =</span> foamIndx)) <span class="sc">+</span></span>
<span id="cb354-2"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb354-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb354-3"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb354-3" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.2</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:3-03-ANOVA-5"></span>
<img src="BB852_files/figure-html/3-03-ANOVA-5-1.png" alt="A box and whisker plot, with jittered points, for the espresso foam data." width="384" />
<p class="caption">
Figure 15.2: A box and whisker plot, with jittered points, for the espresso foam data.
</p>
</div>
<p>You can see in Figure <a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#fig:3-03-ANOVA-5">15.2</a> that the categorical explanatory variable (“method”) defines the three treatment groups and has the three levels representing the different coffee types: BM, HIP and IES.</p>
<p>Let’s first fit the ANOVA using R. One way ANOVAs are fitted using the <code>lm</code> function (<code>lm</code> stands for “linear model” - yes, an ANOVA is a type of linear model).</p>
<div class="sourceCode" id="cb355"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb355-1"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb355-1" tabindex="-1"></a>foam_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(foamIndx <span class="sc">~</span> method, <span class="at">data =</span> espresso)</span></code></pre></div>
<p>Before proceeding, we need to check the assumptions of the model. This can be done visually using the <code>autoplot</code> function in the <code>ggfortify</code> package. If you don’t have the package installed, install it now (<code>install.packages("ggfortify"</code>)).</p>
<div class="sourceCode" id="cb356"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb356-1"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb356-1" tabindex="-1"></a><span class="fu">library</span>(ggfortify)</span>
<span id="cb356-2"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb356-2" tabindex="-1"></a><span class="fu">autoplot</span>(foam_mod)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:3-03-ANOVA-7"></span>
<img src="BB852_files/figure-html/3-03-ANOVA-7-1.png" alt="Diagnostic plots for the ANOVA model. This looks great." width="480" />
<p class="caption">
Figure 15.3: Diagnostic plots for the ANOVA model. This looks great.
</p>
</div>
<p>The main thing to look at here in Figure <a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#fig:3-03-ANOVA-7">15.3</a> is the “Q-Q” plot on the top right. We want those points to be approximately along the line. If that is the case, then it tells us that the model’s residuals are normally distributed (this is one of the assumptions of ANOVA). We may cover these diagnostic plots more thoroughly later. You can find more details on pages 112-113 of the Beckerman et al textbook, or at the following if you are interested: <a href="https://data.library.virginia.edu/diagnostic-plots/" class="uri">https://data.library.virginia.edu/diagnostic-plots/</a>.</p>
<p>Trust me, everything here looks great.</p>
<p>Now let’s evaluate our ANOVA model. We do this using two functions: <code>anova</code> and <code>summary</code> (it sounds strange, but yes we do use a function called <code>anova</code> on our ANOVA model).</p>
<p>First, the <code>anova</code>. This gives us the following summary:</p>
<div class="sourceCode" id="cb357"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb357-1"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb357-1" tabindex="-1"></a><span class="fu">anova</span>(foam_mod)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: foamIndx
##           Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## method     2 4065.2 2032.59  28.413 4.699e-07 ***
## Residuals 24 1716.9   71.54                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>This gives some numbers (degrees of freedom, sum of squares, mean squares). These are the important values that go into calculating an <em>F value</em> (also called an F-statistic). We will not worry about these details now, except to say that large F-statistics mean that we are more certain that there is a difference between the groups (and that the p-value is smaller).</p>
<p>In this case, the F-value is 28.413.</p>
<p>As with the t-test, R compares this value to a theoretical distribution (a “table”), based on <em>two</em> degrees of freedom. The first one is number of groups minus one, i.e. 2.000 in this case. The second one is the overall sample size, minus the number of groups, i.e. 24.000, in this case.</p>
<p>This results in a p-value of 0.0000004699 (very highly significant!).</p>
<p>Based on this p-value we can reject the null hypothesis that there is no difference between groups. We might report this simple result like this:</p>
<p><em>The foam index varied significantly among groups (ANOVA: F = 28.413, d.f. = 2 and 24, p = 0.000).</em></p>
<div id="where-are-the-differences" class="section level3 hasAnchor" number="15.2.1">
<h3><span class="header-section-number">15.2.1</span> Where are the differences?<a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#where-are-the-differences" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>This model output doesn’t tell us <em>where</em> those differences are, nor does it tell us what the estimated mean values of foaminess are for the three groups: what are the effects? We need to dig further into the model to get to these details.</p>
<p>There are several ways to do this and we’ll look at one of them.</p>
<p>We do this using the <code>summary</code> function.</p>
<div class="sourceCode" id="cb359"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb359-1"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb359-1" tabindex="-1"></a><span class="fu">summary</span>(foam_mod)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = foamIndx ~ method, data = espresso)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -14.62  -6.60   0.41   5.73  16.49 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   32.400      2.819  11.492 3.04e-11 ***
## methodHIP     28.900      3.987   7.248 1.73e-07 ***
## methodIES      7.300      3.987   1.831   0.0796 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.458 on 24 degrees of freedom
## Multiple R-squared:  0.7031, Adjusted R-squared:  0.6783 
## F-statistic: 28.41 on 2 and 24 DF,  p-value: 4.699e-07</code></pre>
<p>To properly interpret this output you need to understand something called “treatment contrasts”. Essentially, contrasts define how model coefficients (the estimates made by the model) are presented in R outputs.</p>
<p>They are a bit hard to wrap your head aroudn and I STRONGLY recommend that you always do this with reference to a plot of the actual data, and the mean values for your groups. To do this you can use <code>group_by</code> and <code>summarise</code> to calculate the means for your the levels of your explanatory variable.</p>
<div class="sourceCode" id="cb361"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb361-1"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb361-1" tabindex="-1"></a>espresso <span class="sc">%&gt;%</span></span>
<span id="cb361-2"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb361-2" tabindex="-1"></a>  <span class="fu">group_by</span>(method) <span class="sc">%&gt;%</span></span>
<span id="cb361-3"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb361-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">gp_mean =</span> <span class="fu">mean</span>(foamIndx))</span></code></pre></div>
<pre><code>## # A tibble: 3 × 2
##   method gp_mean
##   &lt;fct&gt;    &lt;dbl&gt;
## 1 BM        32.4
## 2 HIP       61.3
## 3 IES       39.7</code></pre>
<p>Look at the coefficients of the model. Remember that you have three levels in your explanatory variable, but only two levels are shown in the summary. Which one is missing?</p>
<p>The “missing” group is the first one alphabetically (i.e. BM). The estimate (of the mean) for this group is labelled “<code>(Intercept)</code>” (with a value of 32.4. This is like a baseline or reference value, and the estimates for the other groups (HIP and IES), are <em>differences</em> between this baseline value and the estimated mean for those groups. In other words, the second group (HIP) is 28.9 more than 32.4 (32.4 + 28.9 = 61.3). Similarly, the third group (IES) is 7.3 more than 32.4 (32.4 + 7.3 = 39.7). Compare these values with the ones you got above using <code>summarise</code> - they should be the same.</p>
<p>This is illustrated in Figure <a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#fig:3-03-ANOVA-7">15.3</a>A. You can see that the coefficients of the model are the same as the lengths of the arrows that run from 0 (for the first level of method (BM), the Intercept) or <em>from</em> this reference value. It is often a good idea to sketch something like this on paper when you are trying to understand your model outputs!</p>
<!---
Source: A. Parenti, L. Guerrini, P. Masella, S. Spinelli, L. Calamai,
P. Spugnoli (2014). "Comparison of Espresso Coffee Brewing Techniques," 
Journal of Food Engineering, Vol. 121, pp. 112-117.
--->
<p>Likewise, the t-values and p-values, are evaluating <em>differences between the focal group and this baseline</em>. Thus in this case, the comparisons (the “contrasts”) are between the intercept (BM) and the second level (HIP), and the intercept (BM) and the third level (IES). There is no formal statistical comparison between HIP and IES.</p>
<p>You can see that it is very important to understand the levels of your explanatory variable, and how these relate to the summary outputs of the model. It can be useful to use the function <code>relevel</code> to manipulate the explanatory variable to make sure that the output gives you the comparisons you are interested in. Another simple trick would be to always ensure that your reference group (e.g. “control”) comes first alphabetically and is therefore selected by R as the intercept (reference point).</p>
<p>For example, we can <code>relevel</code> the method variable so that the levels are re-ordered as HIP, BM, then IES so that the comparisons are between zero-HIP, HIP-BM and HIP-IES. (make sure that you understand this before proceeding).</p>
<div class="sourceCode" id="cb363"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb363-1"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb363-1" tabindex="-1"></a><span class="co"># This is what the original data looks like:</span></span>
<span id="cb363-2"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb363-2" tabindex="-1"></a><span class="fu">levels</span>(espresso<span class="sc">$</span>method)</span></code></pre></div>
<pre><code>## [1] &quot;BM&quot;  &quot;HIP&quot; &quot;IES&quot;</code></pre>
<div class="sourceCode" id="cb365"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb365-1"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb365-1" tabindex="-1"></a><span class="co"># releveling changes this by changing the reference.</span></span>
<span id="cb365-2"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb365-2" tabindex="-1"></a>espresso_2 <span class="ot">&lt;-</span> espresso <span class="sc">%&gt;%</span></span>
<span id="cb365-3"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb365-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">method =</span> <span class="fu">relevel</span>(method, <span class="at">ref =</span> <span class="st">&quot;HIP&quot;</span>))</span>
<span id="cb365-4"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb365-4" tabindex="-1"></a><span class="fu">levels</span>(espresso_2<span class="sc">$</span>method)</span></code></pre></div>
<pre><code>## [1] &quot;HIP&quot; &quot;BM&quot;  &quot;IES&quot;</code></pre>
<p>Now we can refit the model with this modified data set and see what difference that made:</p>
<div class="sourceCode" id="cb367"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb367-1"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb367-1" tabindex="-1"></a>foam_mod2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(foamIndx <span class="sc">~</span> method, <span class="at">data =</span> espresso_2)</span>
<span id="cb367-2"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb367-2" tabindex="-1"></a><span class="fu">anova</span>(foam_mod2)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: foamIndx
##           Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## method     2 4065.2 2032.59  28.413 4.699e-07 ***
## Residuals 24 1716.9   71.54                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb369"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb369-1"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb369-1" tabindex="-1"></a><span class="fu">summary</span>(foam_mod2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = foamIndx ~ method, data = espresso_2)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -14.62  -6.60   0.41   5.73  16.49 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   61.300      2.819  21.743  &lt; 2e-16 ***
## methodBM     -28.900      3.987  -7.248 1.73e-07 ***
## methodIES    -21.600      3.987  -5.417 1.45e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.458 on 24 degrees of freedom
## Multiple R-squared:  0.7031, Adjusted R-squared:  0.6783 
## F-statistic: 28.41 on 2 and 24 DF,  p-value: 4.699e-07</code></pre>
<p>Now the coefficients in the model summary look different, but the model is actually the same. Compare the two graphs in Figure <a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#fig:3-03-ANOVA-14">15.4</a> - can you see the differences/similarities?</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:3-03-ANOVA-14"></span>
<img src="BB852_files/figure-html/3-03-ANOVA-14-1.png" alt="Comparison illustrating the difference between ANOVA models using (A) BM and (B) HIP as references in the espresso foam data set." width="768" />
<p class="caption">
Figure 15.4: Comparison illustrating the difference between ANOVA models using (A) BM and (B) HIP as references in the espresso foam data set.
</p>
</div>
<p>So, from the first of the model outputs above you can say that BM is significantly different than HIP (t= 7.248, p &lt; 0.0001), but that BM is not significantly different from IES (t = 1.831, p = 0.0796). Then, from the second one you can see that HIP is significantly different from IES (t=-5.417, p &lt; 0.0001). You could write this into the main text, include the information in a figure caption (i.e. add it to the figure).</p>
<p>e.g. <em>The foam index varied significantly among groups (ANOVA: F = 28.413, d.f. = 2 and 24, p = 0.000). The pairwise comparisons in the ANOVA model showed that means of BM and HIP were significantly different (t= 7.248, p &lt; 0.0001), as were those of HIP and IES (t=-5.417, p &lt; 0.0001), but the BM-IES comparison showed no significant difference (t= 1.831, p= 0.0796)</em>.</p>
</div>
<div id="tukeys-honestly-significant-difference-hsd" class="section level3 hasAnchor" number="15.2.2">
<h3><span class="header-section-number">15.2.2</span> Tukey’s Honestly Significant Difference (HSD)<a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#tukeys-honestly-significant-difference-hsd" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>An alternative way to approach these comparisons between groups is to use something called a <strong>post-hoc multiple comparison test</strong>. The words “post-hoc” mean “after the event” – i.e. after the ANOVA in this case – while the “multiple comparison” refers to the (potentially many) pairwise comparisons that you would like to make with an ANOVA. One of the most widely used post-hoc tests is called Tukey’s Honestly Significant Difference (Tukey HSD) test. There is a convenient R package called <code>agricolae</code> that will do these for you.</p>
<div class="sourceCode" id="cb371"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb371-1"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb371-1" tabindex="-1"></a><span class="co"># You only need to do this once!</span></span>
<span id="cb371-2"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb371-2" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;agricolae&quot;</span>)</span></code></pre></div>
<p>When you have the package installed, you can load it (using <code>library</code>). Then you can run the Tukey HSD test using the function <code>HSD.test</code>. The first argument for the function is the name of the model, followed by the name of the variable you are comparing (in this case <code>method</code>) and finally <code>console = TRUE</code> tells the function to print the output to your computer screen.</p>
<div class="sourceCode" id="cb372"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb372-1"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb372-1" tabindex="-1"></a><span class="fu">library</span>(agricolae)</span>
<span id="cb372-2"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb372-2" tabindex="-1"></a><span class="fu">HSD.test</span>(foam_mod2, <span class="st">&quot;method&quot;</span>, <span class="at">console =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
## Study: foam_mod2 ~ &quot;method&quot;
## 
## HSD Test for foamIndx 
## 
## Mean Square Error:  71.5383 
## 
## method,  means
## 
##     foamIndx       std r       se   Min   Max   Q25   Q50   Q75
## BM      32.4  7.300060 9 2.819344 21.02 39.65 24.81 35.96 37.74
## HIP     61.3 10.100604 9 2.819344 46.68 73.19 54.26 62.53 70.84
## IES     39.7  7.700768 9 2.819344 32.68 56.19 35.35 37.12 40.11
## 
## Alpha: 0.05 ; DF Error: 24 
## Critical Value of Studentized Range: 3.531697 
## 
## Minimun Significant Difference: 9.957069 
## 
## Treatments with the same letter are not significantly different.
## 
##     foamIndx groups
## HIP     61.3      a
## IES     39.7      b
## BM      32.4      b</code></pre>
<p>The output is long-winded, and the main thing to look at is the part at the end. The key to understanding this is actually written in the output, “<code>Treatments with the same letter are not significantly different</code>”.</p>
<p>You could include these in a figure or a table with text like, <em>“Means followed by the same letter did not differ significantly (Tukey HSD test, p&gt;0.05)”</em>.</p>
</div>
</div>
<div id="anova-calculation-by-hand." class="section level2 hasAnchor" number="15.3">
<h2><span class="header-section-number">15.3</span> ANOVA calculation “by hand”.<a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#anova-calculation-by-hand." class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="do-something">
<p>
The following is an optional exercise designed to help you understand
how ANOVA works.
</p>
</div>
<p>The ANOVA calculation involves calculating something called an F-value or F-statistic (the F stands for Fisher, who invented ANOVA). This is similar to the t-statistic in that it is a ratio between two quantities, in this case variances. In ANOVA, the F-statistic is calculated as the <strong>treatment variance</strong> divided by the <strong>error variance</strong>.</p>
<p>What does that mean? Let’s consider the espresso data set again.</p>
<p>In Figure <a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#fig:3-03-ANOVA-14">15.4</a>, you can see on the left (A) the black horizontal line which is the overall mean foam index. The vertical lines are the “errors” or departures from the overall mean value, colour coded by treatment (i.e. method). These can be quantified by summing up their square values (squaring ensures that the summed values are all positive). We call this quantity the <em>Total Sum of Squares (SSTotal)</em>. If there is a lot of variation, the sum of squares will be large, if there is little variation the sum of squares will be small.</p>
<p>On the right hand side (Figure <a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#fig:3-03-ANOVA-14">15.4</a>B) we see the same data points. However, this time the horizontal lines represent the treatment-specific mean values, and the vertical lines illustrate the errors from these mean values. Again we can sum up these as sum of squares, which we call the <em>Error Sum of Squares (SSError)</em>.</p>
<p>The difference between those values is called the <em>Treatment Sum of Squares (SSTreatment)</em> and is the key to ANOVA - it represents the importance of the treatment: <span class="math display">\[SSTreatment = SSTotal - SSError\]</span>.</p>
<p>If that doesn’t make sense yet, picture the case where the treatment-specific means are all very similar, and are therefore very close to the overall mean. Now the difference between the <em>Total Sum of Squares</em> and the <em>Error Sum of Squares</em> will be small. Sketch out a couple of examples with pen on paper if that helps. You should now see that you can investigate differences among means by looking at variation.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:3-03-ANOVA-18"></span>
<img src="BB852_files/figure-html/3-03-ANOVA-18-1.png" alt="The relative size of the squared residual errors from the overall mean (SSTotal) (A) and from the treatment-specific means (SSError) (B) tell us about the importance of the treatment variable. The difference between the two values is the &quot;treatment sum of squares&quot;." width="768" />
<p class="caption">
Figure 15.5: The relative size of the squared residual errors from the overall mean (SSTotal) (A) and from the treatment-specific means (SSError) (B) tell us about the importance of the treatment variable. The difference between the two values is the “treatment sum of squares”.
</p>
</div>
<p>In the following I will show how these calculations can be done “by hand” in R. The purpose of showing you this is to demonstrate exactly how the <code>lm</code> model that you fitted above works, and prove to yourself that it is not rocket science… you will never need to do this in real life, because you have the wonderful <code>lm</code> function.</p>
<p>Here goes…</p>
<p>First, calculate the total sum of squares:</p>
<div class="sourceCode" id="cb374"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb374-1"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb374-1" tabindex="-1"></a>overallMean <span class="ot">&lt;-</span> <span class="fu">mean</span>(espresso<span class="sc">$</span>foamIndx)</span>
<span id="cb374-2"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb374-2" tabindex="-1"></a>(SSTotal <span class="ot">&lt;-</span> <span class="fu">sum</span>((overallMean <span class="sc">-</span> espresso<span class="sc">$</span>foamIndx)<span class="sc">^</span><span class="dv">2</span>))</span></code></pre></div>
<pre><code>## [1] 5782.099</code></pre>
<p>Now calculate the group-specific means:</p>
<div class="sourceCode" id="cb376"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb376-1"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb376-1" tabindex="-1"></a>(groupMeans <span class="ot">&lt;-</span> espresso <span class="sc">%&gt;%</span></span>
<span id="cb376-2"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb376-2" tabindex="-1"></a>  <span class="fu">group_by</span>(method) <span class="sc">%&gt;%</span></span>
<span id="cb376-3"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb376-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">groupMean =</span> <span class="fu">mean</span>(foamIndx)) <span class="sc">%&gt;%</span></span>
<span id="cb376-4"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb376-4" tabindex="-1"></a>  <span class="fu">pull</span>(groupMean))</span></code></pre></div>
<pre><code>## [1] 32.4 61.3 39.7</code></pre>
<p>Now add those group-specific mean values to the dataset using <code>left_join</code> so that you can calculate the group-specific errors.</p>
<div class="sourceCode" id="cb378"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb378-1"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb378-1" tabindex="-1"></a>espresso <span class="ot">&lt;-</span> <span class="fu">left_join</span>(espresso, espresso <span class="sc">%&gt;%</span></span>
<span id="cb378-2"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb378-2" tabindex="-1"></a>  <span class="fu">group_by</span>(method) <span class="sc">%&gt;%</span></span>
<span id="cb378-3"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb378-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">groupMean =</span> <span class="fu">mean</span>(foamIndx))) <span class="sc">%&gt;%</span></span>
<span id="cb378-4"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb378-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">groupSS =</span> (foamIndx <span class="sc">-</span> groupMean)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb378-5"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb378-5" tabindex="-1"></a></span>
<span id="cb378-6"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb378-6" tabindex="-1"></a><span class="fu">head</span>(espresso)</span></code></pre></div>
<pre><code>##   foamIndx method groupMean  groupSS
## 1    36.64     BM      32.4  17.9776
## 2    39.65     BM      32.4  52.5625
## 3    37.74     BM      32.4  28.5156
## 4    35.96     BM      32.4  12.6736
## 5    38.52     BM      32.4  37.4544
## 6    21.02     BM      32.4 129.5044</code></pre>
<p>Then, to calculate the errors:</p>
<div class="sourceCode" id="cb380"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb380-1"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb380-1" tabindex="-1"></a>(SSError <span class="ot">&lt;-</span> espresso <span class="sc">%&gt;%</span></span>
<span id="cb380-2"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb380-2" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">sum</span>(groupSS)) <span class="sc">%&gt;%</span></span>
<span id="cb380-3"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb380-3" tabindex="-1"></a>  <span class="fu">pull</span>())</span></code></pre></div>
<pre><code>## [1] 1716.919</code></pre>
<p>From there, you can calculate the <strong>Treatment Sum of Squares</strong></p>
<div class="sourceCode" id="cb382"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb382-1"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb382-1" tabindex="-1"></a>(SSTreatment <span class="ot">&lt;-</span> SSTotal <span class="sc">-</span> SSError)</span></code></pre></div>
<pre><code>## [1] 4065.18</code></pre>
<p>So far, so good - but we can’t just look at the ratio of SSTreatment/SSError, because sum of square errors always increase with sample size. We can account for this by dividing</p>
<p>We need to take account of sample size (degrees of freedom) by dividing these sum of squares by the degrees of freedom to give us variances. There are 3 treatment groups and 9 samples per group. Therefore there are 2 degrees of freedom for the treatment, and 8 degrees of freedom per each of the three treatments, giving a total of 8*3 = 24 error degrees of freedom.</p>
<p>Now we need to correct for degrees of freedom, which will give us variances.</p>
<div class="sourceCode" id="cb384"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb384-1"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb384-1" tabindex="-1"></a>(meanSSTreatment <span class="ot">&lt;-</span> SSTreatment <span class="sc">/</span> <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 2032.59</code></pre>
<div class="sourceCode" id="cb386"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb386-1"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb386-1" tabindex="-1"></a>(meanSSError <span class="ot">&lt;-</span> SSError <span class="sc">/</span> <span class="dv">24</span>)</span></code></pre></div>
<pre><code>## [1] 71.5383</code></pre>
<p>The F-statistic is then the ratio of these values.</p>
<div class="sourceCode" id="cb388"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb388-1"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb388-1" tabindex="-1"></a>(Fstat <span class="ot">&lt;-</span> meanSSTreatment <span class="sc">/</span> meanSSError)</span></code></pre></div>
<pre><code>## [1] 28.41261</code></pre>
<p>We can “look up” the p-value associated with this F-statistic using the <code>pf</code> function (<code>pf</code> stands for probability of f) like this:</p>
<div class="sourceCode" id="cb390"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb390-1"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#cb390-1" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pf</span>(Fstat, <span class="at">df1 =</span> <span class="dv">2</span>, <span class="at">df2 =</span> <span class="dv">24</span>)</span></code></pre></div>
<pre><code>## [1] 4.698636e-07</code></pre>
<p>As you can see, the method is a bit laborious and time consuming but it is conceptually fairly straightforward - it all hinges on the ratio of variation due to treatment effect vs. overall variation. Signal and noise.</p>
</div>
<div id="exercise-apple-tree-crop-yield" class="section level2 hasAnchor" number="15.4">
<h2><span class="header-section-number">15.4</span> Exercise: Apple tree crop yield<a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#exercise-apple-tree-crop-yield" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>An experiment was conducted to look at the effect of tree spacing on apple crop yield (total kg per tree of apples between 1975-1979) in different spacing conditions (i.e. distances between trees). There were 40 trees in each treatment group. The spacing was 6, 10 and 14 feet, and should be treated as a categorical variable. There may be some <code>NA</code> missing yield values.</p>
<p>Import the data (<code>apples.csv</code>) and analyse it using the techniques you have learned in the ANOVA lecture, and the previous chapter, to answer the question “What is the effect of tree spacing on apple yields?”</p>
<ol style="list-style-type: decimal">
<li><p>Import and look at the data (e.g. <code>summary</code> or <code>str</code> or <code>head</code>)</p></li>
<li><p>Ensure that the explanatory variable (<code>spacing</code>) is defined as a categorical variable (i.e. a “factor”, in R-speak). You can use <code>mutate</code> and <code>as.factor</code> functions for this.</p></li>
<li><p>Plot the data using <code>ggplot</code> (a box plot with (optionally) added jittered points would be good).</p></li>
<li><p>Fit an ANOVA model using <code>lm</code>.</p></li>
<li><p>Check the model using a diagnostic plot (i.e. using <code>autoplot</code> from the <code>ggfortify</code> package).</p></li>
<li><p>Use <code>anova</code> to get the ANOVA summary.</p></li>
<li><p>You should see that there are differences among treatments. But where are those differences? Use <code>summary</code> on your model to find out.</p></li>
<li><p>Use a Tukey test to make all the pairwise comparisons among the treatments.</p></li>
<li><p>Write a few sentences that summarise your findings. What biological processes do you think drive the effects that you have detected?</p></li>
<li><p>Optional. Instead of using a Tukey test, use the alternative “relevel” approach to make the missing comparison.</p></li>
</ol>
<div class="do-something">
<p>
If you get this far, try using the ANOVA approach on one of the
previous t-test examples (remember that ANOVA can be used when your
single explanatory variable has TWO or more levels). You should notice
that the results are the same whether you use the <code>t.test</code>
function or the ANOVA approach with <code>lm</code>.
</p>
</div>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="assumptions-in-linear-models.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/jonesor/BB852_Book/edit/master/3_03-ANOVA.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["BB852.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
},
"split_by": "section"
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
