<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 21 Exercise Solutions | BB852 - Data handling, visualisation and statistics</title>
  <meta name="description" content="Course book for BB852 at the Biology Department, University of Southern Denmark" />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 21 Exercise Solutions | BB852 - Data handling, visualisation and statistics" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Course book for BB852 at the Biology Department, University of Southern Denmark" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 21 Exercise Solutions | BB852 - Data handling, visualisation and statistics" />
  
  <meta name="twitter:description" content="Course book for BB852 at the Biology Department, University of Southern Denmark" />
  

<meta name="author" content="Owen R. Jones" />


<meta name="date" content="2020-12-01" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="exam-2020.html"/>

<script src="libs/header-attrs-2.3/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/tabwid-1.0.0/tabwid.css" rel="stylesheet" />
<script src="libs/tabwid-1.0.0/tabwid.js"></script>
<style type="text/css">

.warning-box {
  border: 3px solid #e60000;
  margin:  25px;
  padding: 10px 10px 5px 10px;
  border-radius: 6px 6px 6px 6px;
}

.advanced-box {
  border: 3px solid #268bd2;
  margin:  25px;
  padding: 10px 10px 5px 10px;
  border-radius: 6px 6px 6px 6px;
}

.do-something {
  border: 3px solid #803e00;
  margin:  25px;
  padding: 10px 10px 5px 10px;
  border-radius: 6px 6px 6px 6px;
}

</style>





<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">BB852</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Preface</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#data-wrangling"><i class="fa fa-check"></i><b>1.1</b> Data wrangling</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#data-visualisation"><i class="fa fa-check"></i><b>1.2</b> Data visualisation</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#statistics"><i class="fa fa-check"></i><b>1.3</b> Statistics</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#data-sources"><i class="fa fa-check"></i><b>1.4</b> Data sources</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#your-instructors"><i class="fa fa-check"></i><b>1.5</b> Your instructors</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i><b>1.6</b> Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="schedule.html"><a href="schedule.html"><i class="fa fa-check"></i><b>2</b> Schedule</a>
<ul>
<li class="chapter" data-level="2.1" data-path="schedule.html"><a href="schedule.html#additional-recommended-reading"><i class="fa fa-check"></i><b>2.1</b> Additional recommended reading</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="an-r-refresher.html"><a href="an-r-refresher.html"><i class="fa fa-check"></i><b>3</b> An R refresher</a>
<ul>
<li class="chapter" data-level="3.1" data-path="an-r-refresher.html"><a href="an-r-refresher.html#getting-started-with-r"><i class="fa fa-check"></i><b>3.1</b> Getting started with R</a></li>
<li class="chapter" data-level="3.2" data-path="an-r-refresher.html"><a href="an-r-refresher.html#getting-help"><i class="fa fa-check"></i><b>3.2</b> Getting help</a></li>
<li class="chapter" data-level="3.3" data-path="an-r-refresher.html"><a href="an-r-refresher.html#r-as-a-fancy-calculator"><i class="fa fa-check"></i><b>3.3</b> R as a fancy calculator</a></li>
<li class="chapter" data-level="3.4" data-path="an-r-refresher.html"><a href="an-r-refresher.html#objects-in-r"><i class="fa fa-check"></i><b>3.4</b> Objects in R</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="manipulating-objects.html"><a href="manipulating-objects.html"><i class="fa fa-check"></i><b>4</b> Manipulating objects</a>
<ul>
<li class="chapter" data-level="4.1" data-path="manipulating-objects.html"><a href="manipulating-objects.html#missing-values-infinity-and-non-numbers"><i class="fa fa-check"></i><b>4.1</b> Missing values, infinity and “non-numbers”</a></li>
<li class="chapter" data-level="4.2" data-path="manipulating-objects.html"><a href="manipulating-objects.html#basic-information-about-objects"><i class="fa fa-check"></i><b>4.2</b> Basic information about objects</a></li>
<li class="chapter" data-level="4.3" data-path="manipulating-objects.html"><a href="manipulating-objects.html#data-frames"><i class="fa fa-check"></i><b>4.3</b> Data frames</a></li>
<li class="chapter" data-level="4.4" data-path="manipulating-objects.html"><a href="manipulating-objects.html#organising-your-work"><i class="fa fa-check"></i><b>4.4</b> Organising your work</a></li>
<li class="chapter" data-level="4.5" data-path="manipulating-objects.html"><a href="manipulating-objects.html#inspecting-the-data"><i class="fa fa-check"></i><b>4.5</b> Inspecting the data</a></li>
<li class="chapter" data-level="4.6" data-path="manipulating-objects.html"><a href="manipulating-objects.html#classes-in-r"><i class="fa fa-check"></i><b>4.6</b> “Classes” in R</a></li>
<li class="chapter" data-level="4.7" data-path="manipulating-objects.html"><a href="manipulating-objects.html#tables-and-summary-statistics"><i class="fa fa-check"></i><b>4.7</b> Tables and summary statistics</a></li>
<li class="chapter" data-level="4.8" data-path="manipulating-objects.html"><a href="manipulating-objects.html#plotting-data"><i class="fa fa-check"></i><b>4.8</b> Plotting data</a></li>
<li class="chapter" data-level="4.9" data-path="manipulating-objects.html"><a href="manipulating-objects.html#r-packages"><i class="fa fa-check"></i><b>4.9</b> R Packages</a></li>
<li class="chapter" data-level="4.10" data-path="manipulating-objects.html"><a href="manipulating-objects.html#exercise-californian-bird-diversity"><i class="fa fa-check"></i><b>4.10</b> Exercise: Californian bird diversity</a>
<ul>
<li class="chapter" data-level="4.10.1" data-path="manipulating-objects.html"><a href="manipulating-objects.html#the-data"><i class="fa fa-check"></i><b>4.10.1</b> The data</a></li>
<li class="chapter" data-level="4.10.2" data-path="manipulating-objects.html"><a href="manipulating-objects.html#try-the-following"><i class="fa fa-check"></i><b>4.10.2</b> Try the following</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>I Data Wrangling</b></span></li>
<li class="chapter" data-level="5" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html"><i class="fa fa-check"></i><b>5</b> Data wrangling with <code>dplyr</code></a>
<ul>
<li class="chapter" data-level="5.1" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#select"><i class="fa fa-check"></i><b>5.1</b> <code>select</code></a></li>
<li class="chapter" data-level="5.2" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#filter"><i class="fa fa-check"></i><b>5.2</b> <code>filter</code></a></li>
<li class="chapter" data-level="5.3" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#arrange"><i class="fa fa-check"></i><b>5.3</b> <code>arrange</code></a></li>
<li class="chapter" data-level="5.4" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#summarise-and-group_by"><i class="fa fa-check"></i><b>5.4</b> <code>summarise</code> and <code>group_by</code></a></li>
<li class="chapter" data-level="5.5" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#using-pipes-saving-data."><i class="fa fa-check"></i><b>5.5</b> Using pipes, saving data.</a></li>
<li class="chapter" data-level="5.6" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#exercise-wrangling-the-amniote-life-history-database"><i class="fa fa-check"></i><b>5.6</b> Exercise: Wrangling the Amniote Life History Database</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="combining-data-sets.html"><a href="combining-data-sets.html"><i class="fa fa-check"></i><b>6</b> Combining data sets</a>
<ul>
<li class="chapter" data-level="6.1" data-path="combining-data-sets.html"><a href="combining-data-sets.html#using-join"><i class="fa fa-check"></i><b>6.1</b> Using <code>join</code></a></li>
<li class="chapter" data-level="6.2" data-path="combining-data-sets.html"><a href="combining-data-sets.html#using-pivot_longer"><i class="fa fa-check"></i><b>6.2</b> Using <code>pivot_longer</code></a></li>
<li class="chapter" data-level="6.3" data-path="combining-data-sets.html"><a href="combining-data-sets.html#exercise-temperature-effects-on-egg-laying-dates"><i class="fa fa-check"></i><b>6.3</b> Exercise: Temperature effects on egg laying dates</a></li>
</ul></li>
<li class="part"><span><b>II Data visualisation</b></span></li>
<li class="chapter" data-level="7" data-path="visualising-data-with-ggplot.html"><a href="visualising-data-with-ggplot.html"><i class="fa fa-check"></i><b>7</b> Visualising data with <code>ggplot</code></a>
<ul>
<li class="chapter" data-level="7.1" data-path="visualising-data-with-ggplot.html"><a href="visualising-data-with-ggplot.html#histograms"><i class="fa fa-check"></i><b>7.1</b> Histograms</a></li>
<li class="chapter" data-level="7.2" data-path="visualising-data-with-ggplot.html"><a href="visualising-data-with-ggplot.html#facets---splitting-data-across-panels"><i class="fa fa-check"></i><b>7.2</b> “Facets” - splitting data across panels</a></li>
<li class="chapter" data-level="7.3" data-path="visualising-data-with-ggplot.html"><a href="visualising-data-with-ggplot.html#box-plots"><i class="fa fa-check"></i><b>7.3</b> Box plots</a></li>
<li class="chapter" data-level="7.4" data-path="visualising-data-with-ggplot.html"><a href="visualising-data-with-ggplot.html#lines-and-points"><i class="fa fa-check"></i><b>7.4</b> Lines and points</a></li>
<li class="chapter" data-level="7.5" data-path="visualising-data-with-ggplot.html"><a href="visualising-data-with-ggplot.html#scatter-plots"><i class="fa fa-check"></i><b>7.5</b> Scatter plots</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html"><i class="fa fa-check"></i><b>8</b> Distributions and summarising data</a>
<ul>
<li class="chapter" data-level="8.1" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#distributions"><i class="fa fa-check"></i><b>8.1</b> Distributions</a></li>
<li class="chapter" data-level="8.2" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#normal-distribution"><i class="fa fa-check"></i><b>8.2</b> Normal distribution</a></li>
<li class="chapter" data-level="8.3" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#comparing-normal-distributions"><i class="fa fa-check"></i><b>8.3</b> Comparing normal distributions</a></li>
<li class="chapter" data-level="8.4" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#poisson-distribution"><i class="fa fa-check"></i><b>8.4</b> Poisson distribution</a></li>
<li class="chapter" data-level="8.5" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#comparing-normal-and-poisson-distributions"><i class="fa fa-check"></i><b>8.5</b> Comparing normal and Poisson distributions</a></li>
<li class="chapter" data-level="8.6" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#the-law-of-large-numbers"><i class="fa fa-check"></i><b>8.6</b> The law of large numbers</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#coin-flipping"><i class="fa fa-check"></i><b>8.6.1</b> Coin flipping</a></li>
<li class="chapter" data-level="8.6.2" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#virtual-dice"><i class="fa fa-check"></i><b>8.6.2</b> Virtual dice</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html"><i class="fa fa-check"></i><b>9</b> Pimping your plots</a>
<ul>
<li class="chapter" data-level="9.1" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#a-basic-plot"><i class="fa fa-check"></i><b>9.1</b> A basic plot</a></li>
<li class="chapter" data-level="9.2" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#axis-limits"><i class="fa fa-check"></i><b>9.2</b> Axis limits</a></li>
<li class="chapter" data-level="9.3" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#transforming-the-axis-log-scale"><i class="fa fa-check"></i><b>9.3</b> Transforming the axis (log scale)</a></li>
<li class="chapter" data-level="9.4" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#changing-the-axis-tick-marks"><i class="fa fa-check"></i><b>9.4</b> Changing the axis tick marks</a></li>
<li class="chapter" data-level="9.5" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#axis-labels"><i class="fa fa-check"></i><b>9.5</b> Axis labels</a></li>
<li class="chapter" data-level="9.6" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#colours"><i class="fa fa-check"></i><b>9.6</b> Colours</a></li>
<li class="chapter" data-level="9.7" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#themes"><i class="fa fa-check"></i><b>9.7</b> Themes</a></li>
<li class="chapter" data-level="9.8" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#moving-the-legend"><i class="fa fa-check"></i><b>9.8</b> Moving the legend</a></li>
<li class="chapter" data-level="9.9" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#combining-multiple-plots"><i class="fa fa-check"></i><b>9.9</b> Combining multiple plots</a></li>
<li class="chapter" data-level="9.10" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#saving-your-plot"><i class="fa fa-check"></i><b>9.10</b> Saving your plot</a></li>
<li class="chapter" data-level="9.11" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#final-word-on-plots"><i class="fa fa-check"></i><b>9.11</b> Final word on plots</a></li>
</ul></li>
<li class="part"><span><b>III Statistics</b></span></li>
<li class="chapter" data-level="10" data-path="randomisation-tests.html"><a href="randomisation-tests.html"><i class="fa fa-check"></i><b>10</b> Randomisation Tests</a>
<ul>
<li class="chapter" data-level="10.1" data-path="randomisation-tests.html"><a href="randomisation-tests.html#randomisation-test-in-r"><i class="fa fa-check"></i><b>10.1</b> Randomisation test in R</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="randomisation-tests.html"><a href="randomisation-tests.html#calculate-the-observed-difference"><i class="fa fa-check"></i><b>10.1.1</b> Calculate the observed difference</a></li>
<li class="chapter" data-level="10.1.2" data-path="randomisation-tests.html"><a href="randomisation-tests.html#null-distribution"><i class="fa fa-check"></i><b>10.1.2</b> Null distribution</a></li>
<li class="chapter" data-level="10.1.3" data-path="randomisation-tests.html"><a href="randomisation-tests.html#testing-significance"><i class="fa fa-check"></i><b>10.1.3</b> Testing significance</a></li>
<li class="chapter" data-level="10.1.4" data-path="randomisation-tests.html"><a href="randomisation-tests.html#testing-the-hypothesis"><i class="fa fa-check"></i><b>10.1.4</b> Testing the hypothesis</a></li>
<li class="chapter" data-level="10.1.5" data-path="randomisation-tests.html"><a href="randomisation-tests.html#writing-it-up"><i class="fa fa-check"></i><b>10.1.5</b> Writing it up</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="randomisation-tests.html"><a href="randomisation-tests.html#paired-randomisation-tests"><i class="fa fa-check"></i><b>10.2</b> Paired Randomisation Tests</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="randomisation-tests.html"><a href="randomisation-tests.html#the-randomisation-test"><i class="fa fa-check"></i><b>10.2.1</b> The randomisation test</a></li>
<li class="chapter" data-level="10.2.2" data-path="randomisation-tests.html"><a href="randomisation-tests.html#null-distribution-1"><i class="fa fa-check"></i><b>10.2.2</b> Null distribution</a></li>
<li class="chapter" data-level="10.2.3" data-path="randomisation-tests.html"><a href="randomisation-tests.html#the-formal-hypothesis-test"><i class="fa fa-check"></i><b>10.2.3</b> The formal hypothesis test</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="randomisation-tests.html"><a href="randomisation-tests.html#exercise-sexual-selection-in-hercules-beetles"><i class="fa fa-check"></i><b>10.3</b> Exercise: Sexual selection in Hercules beetles</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="comparing-two-means-with-a-t-test.html"><a href="comparing-two-means-with-a-t-test.html"><i class="fa fa-check"></i><b>11</b> Comparing two means with a t-test</a>
<ul>
<li class="chapter" data-level="11.1" data-path="comparing-two-means-with-a-t-test.html"><a href="comparing-two-means-with-a-t-test.html#some-theory"><i class="fa fa-check"></i><b>11.1</b> Some theory</a></li>
<li class="chapter" data-level="11.2" data-path="comparing-two-means-with-a-t-test.html"><a href="comparing-two-means-with-a-t-test.html#one-sample-t-test"><i class="fa fa-check"></i><b>11.2</b> One sample t-test</a></li>
<li class="chapter" data-level="11.3" data-path="comparing-two-means-with-a-t-test.html"><a href="comparing-two-means-with-a-t-test.html#doing-it-by-hand---where-does-the-t-statistic-come-from"><i class="fa fa-check"></i><b>11.3</b> Doing it “by hand” - where does the t-statistic come from?</a></li>
<li class="chapter" data-level="11.4" data-path="comparing-two-means-with-a-t-test.html"><a href="comparing-two-means-with-a-t-test.html#paired-t-test"><i class="fa fa-check"></i><b>11.4</b> Paired t-test</a></li>
<li class="chapter" data-level="11.5" data-path="comparing-two-means-with-a-t-test.html"><a href="comparing-two-means-with-a-t-test.html#a-paired-t-test-is-a-one-sample-test."><i class="fa fa-check"></i><b>11.5</b> A paired t-test is a one-sample test.</a></li>
<li class="chapter" data-level="11.6" data-path="comparing-two-means-with-a-t-test.html"><a href="comparing-two-means-with-a-t-test.html#two-sample-t-test"><i class="fa fa-check"></i><b>11.6</b> Two sample t-test</a></li>
<li class="chapter" data-level="11.7" data-path="comparing-two-means-with-a-t-test.html"><a href="comparing-two-means-with-a-t-test.html#t-tests-are-linear-models"><i class="fa fa-check"></i><b>11.7</b> t-tests are linear models</a></li>
<li class="chapter" data-level="11.8" data-path="comparing-two-means-with-a-t-test.html"><a href="comparing-two-means-with-a-t-test.html#exercise-sex-differences-in-fine-motor-skills"><i class="fa fa-check"></i><b>11.8</b> Exercise: Sex differences in fine motor skills</a></li>
<li class="chapter" data-level="11.9" data-path="comparing-two-means-with-a-t-test.html"><a href="comparing-two-means-with-a-t-test.html#exercise-therapy-for-anorexia"><i class="fa fa-check"></i><b>11.9</b> Exercise: Therapy for anorexia</a></li>
<li class="chapter" data-level="11.10" data-path="comparing-two-means-with-a-t-test.html"><a href="comparing-two-means-with-a-t-test.html#exercise-compare-t-tests-with-randomisation-tests"><i class="fa fa-check"></i><b>11.10</b> Exercise: Compare t-tests with randomisation tests</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="linear-models-with-a-single-categorical-explanatory-variable.html"><a href="linear-models-with-a-single-categorical-explanatory-variable.html"><i class="fa fa-check"></i><b>12</b> Linear models with a single categorical explanatory variable</a>
<ul>
<li class="chapter" data-level="12.1" data-path="linear-models-with-a-single-categorical-explanatory-variable.html"><a href="linear-models-with-a-single-categorical-explanatory-variable.html#one-way-anova"><i class="fa fa-check"></i><b>12.1</b> One-way ANOVA</a></li>
<li class="chapter" data-level="12.2" data-path="linear-models-with-a-single-categorical-explanatory-variable.html"><a href="linear-models-with-a-single-categorical-explanatory-variable.html#fitting-an-anova-in-r"><i class="fa fa-check"></i><b>12.2</b> Fitting an ANOVA in R</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="linear-models-with-a-single-categorical-explanatory-variable.html"><a href="linear-models-with-a-single-categorical-explanatory-variable.html#where-are-the-differences"><i class="fa fa-check"></i><b>12.2.1</b> Where are the differences?</a></li>
<li class="chapter" data-level="12.2.2" data-path="linear-models-with-a-single-categorical-explanatory-variable.html"><a href="linear-models-with-a-single-categorical-explanatory-variable.html#tukeys-honestly-significant-difference-hsd"><i class="fa fa-check"></i><b>12.2.2</b> Tukey’s Honestly Significant Difference (HSD)</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="linear-models-with-a-single-categorical-explanatory-variable.html"><a href="linear-models-with-a-single-categorical-explanatory-variable.html#anova-calculation-by-hand."><i class="fa fa-check"></i><b>12.3</b> ANOVA calculation “by hand”.</a></li>
<li class="chapter" data-level="12.4" data-path="linear-models-with-a-single-categorical-explanatory-variable.html"><a href="linear-models-with-a-single-categorical-explanatory-variable.html#exercise-apple-tree-crop-yield"><i class="fa fa-check"></i><b>12.4</b> Exercise: Apple tree crop yield</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="linear-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-models-with-a-single-continuous-explanatory-variable.html"><i class="fa fa-check"></i><b>13</b> Linear models with a single continuous explanatory variable</a>
<ul>
<li class="chapter" data-level="13.1" data-path="comparing-two-means-with-a-t-test.html"><a href="comparing-two-means-with-a-t-test.html#some-theory"><i class="fa fa-check"></i><b>13.1</b> Some theory</a></li>
<li class="chapter" data-level="13.2" data-path="linear-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-models-with-a-single-continuous-explanatory-variable.html#evaluating-a-hypothesis-with-a-linear-regression-model"><i class="fa fa-check"></i><b>13.2</b> Evaluating a hypothesis with a linear regression model</a></li>
<li class="chapter" data-level="13.3" data-path="linear-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-models-with-a-single-continuous-explanatory-variable.html#assumptions"><i class="fa fa-check"></i><b>13.3</b> Assumptions</a></li>
<li class="chapter" data-level="13.4" data-path="linear-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-models-with-a-single-continuous-explanatory-variable.html#worked-example-height-hand-width-relationship"><i class="fa fa-check"></i><b>13.4</b> Worked example: height-hand width relationship</a></li>
<li class="chapter" data-level="13.5" data-path="linear-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-models-with-a-single-continuous-explanatory-variable.html#exercise-chirping-crickets"><i class="fa fa-check"></i><b>13.5</b> Exercise: Chirping crickets</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="linear-models-with-categorical-and-continuous-explanatory-variables.html"><a href="linear-models-with-categorical-and-continuous-explanatory-variables.html"><i class="fa fa-check"></i><b>14</b> Linear models with categorical and continuous explanatory variables</a>
<ul>
<li class="chapter" data-level="14.1" data-path="linear-models-with-categorical-and-continuous-explanatory-variables.html"><a href="linear-models-with-categorical-and-continuous-explanatory-variables.html#the-height-hand-width-example."><i class="fa fa-check"></i><b>14.1</b> The height ~ hand width example.</a></li>
<li class="chapter" data-level="14.2" data-path="linear-models-with-categorical-and-continuous-explanatory-variables.html"><a href="linear-models-with-categorical-and-continuous-explanatory-variables.html#summarising-with-anova"><i class="fa fa-check"></i><b>14.2</b> Summarising with <code>anova</code></a></li>
<li class="chapter" data-level="14.3" data-path="linear-models-with-categorical-and-continuous-explanatory-variables.html"><a href="linear-models-with-categorical-and-continuous-explanatory-variables.html#the-summary-of-coefficients-summary"><i class="fa fa-check"></i><b>14.3</b> The summary of coefficients (<code>summary</code>)</a></li>
<li class="chapter" data-level="14.4" data-path="linear-models-with-categorical-and-continuous-explanatory-variables.html"><a href="linear-models-with-categorical-and-continuous-explanatory-variables.html#simplifying-the-model"><i class="fa fa-check"></i><b>14.4</b> Simplifying the model</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="linear-models-with-1-categorical-explanatory-variables.html"><a href="linear-models-with-1-categorical-explanatory-variables.html"><i class="fa fa-check"></i><b>15</b> Linear models with &gt;1 categorical explanatory variables</a>
<ul>
<li class="chapter" data-level="15.1" data-path="linear-models-with-1-categorical-explanatory-variables.html"><a href="linear-models-with-1-categorical-explanatory-variables.html#fitting-a-two-way-anova-model"><i class="fa fa-check"></i><b>15.1</b> Fitting a two-way ANOVA model</a></li>
<li class="chapter" data-level="15.2" data-path="linear-models-with-1-categorical-explanatory-variables.html"><a href="linear-models-with-1-categorical-explanatory-variables.html#summarising-the-model-anova"><i class="fa fa-check"></i><b>15.2</b> Summarising the model (<code>anova</code>)</a></li>
<li class="chapter" data-level="15.3" data-path="linear-models-with-1-categorical-explanatory-variables.html"><a href="linear-models-with-1-categorical-explanatory-variables.html#summarising-the-model-summary"><i class="fa fa-check"></i><b>15.3</b> Summarising the model (<code>summary</code>)</a></li>
<li class="chapter" data-level="15.4" data-path="linear-models-with-1-categorical-explanatory-variables.html"><a href="linear-models-with-1-categorical-explanatory-variables.html#exercise-fish-behaviour"><i class="fa fa-check"></i><b>15.4</b> Exercise: Fish behaviour</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html"><i class="fa fa-check"></i><b>16</b> Generalised linear models</a>
<ul>
<li class="chapter" data-level="16.1" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html#count-data-with-poisson-errors."><i class="fa fa-check"></i><b>16.1</b> Count data with Poisson errors.</a>
<ul>
<li class="chapter" data-level="16.1.1" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html#example-number-of-offspring-in-foxes."><i class="fa fa-check"></i><b>16.1.1</b> Example: Number of offspring in foxes.</a></li>
<li class="chapter" data-level="16.1.2" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html#example-cancer-clusters"><i class="fa fa-check"></i><b>16.1.2</b> Example: Cancer clusters</a></li>
</ul></li>
<li class="chapter" data-level="16.2" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html#exercise-maze-runner"><i class="fa fa-check"></i><b>16.2</b> Exercise: Maze runner</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="extending-use-cases-of-glm.html"><a href="extending-use-cases-of-glm.html"><i class="fa fa-check"></i><b>17</b> Extending use cases of GLM</a>
<ul>
<li class="chapter" data-level="17.1" data-path="extending-use-cases-of-glm.html"><a href="extending-use-cases-of-glm.html#binomial-response-data"><i class="fa fa-check"></i><b>17.1</b> Binomial response data</a></li>
<li class="chapter" data-level="17.2" data-path="extending-use-cases-of-glm.html"><a href="extending-use-cases-of-glm.html#example-nfl-field-goals"><i class="fa fa-check"></i><b>17.2</b> Example: NFL field goals</a></li>
<li class="chapter" data-level="17.3" data-path="extending-use-cases-of-glm.html"><a href="extending-use-cases-of-glm.html#example-sex-ratio-in-turtles"><i class="fa fa-check"></i><b>17.3</b> Example: Sex ratio in turtles</a></li>
<li class="chapter" data-level="17.4" data-path="extending-use-cases-of-glm.html"><a href="extending-use-cases-of-glm.html#example-smoking"><i class="fa fa-check"></i><b>17.4</b> Example: Smoking</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html"><i class="fa fa-check"></i><b>18</b> Power analysis by simulation</a>
<ul>
<li class="chapter" data-level="18.1" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#type-i-and-ii-errors-and-statistical-power"><i class="fa fa-check"></i><b>18.1</b> Type I and II errors and statistical power</a></li>
<li class="chapter" data-level="18.2" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#what-determines-statistical-power"><i class="fa fa-check"></i><b>18.2</b> What determines statistical power?</a></li>
<li class="chapter" data-level="18.3" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#an-example-of-calculating-statistical-power."><i class="fa fa-check"></i><b>18.3</b> An example of calculating statistical power.</a>
<ul>
<li class="chapter" data-level="18.3.1" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#the-simulation"><i class="fa fa-check"></i><b>18.3.1</b> The simulation</a></li>
<li class="chapter" data-level="18.3.2" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#some-questions-for-you-to-address"><i class="fa fa-check"></i><b>18.3.2</b> Some questions for you to address:</a></li>
</ul></li>
<li class="chapter" data-level="18.4" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#summary"><i class="fa fa-check"></i><b>18.4</b> Summary</a></li>
<li class="chapter" data-level="18.5" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#extending-the-simulation-optional-advanced"><i class="fa fa-check"></i><b>18.5</b> Extending the simulation (optional, advanced)</a></li>
<li class="chapter" data-level="18.6" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#exercise-1-snails-on-the-move"><i class="fa fa-check"></i><b>18.6</b> Exercise 1: Snails on the move</a></li>
<li class="chapter" data-level="18.7" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#exercise-2-mouse-lemur-strength"><i class="fa fa-check"></i><b>18.7</b> Exercise 2: Mouse lemur strength</a></li>
</ul></li>
<li class="part"><span><b>IV Coming soon(ish)</b></span></li>
<li class="chapter" data-level="19" data-path="coming-soon-maybe.html"><a href="coming-soon-maybe.html"><i class="fa fa-check"></i><b>19</b> Coming soon (maybe)!</a>
<ul>
<li class="chapter" data-level="19.1" data-path="coming-soon-maybe.html"><a href="coming-soon-maybe.html#multivariate-statistics"><i class="fa fa-check"></i><b>19.1</b> Multivariate statistics</a></li>
<li class="chapter" data-level="19.2" data-path="coming-soon-maybe.html"><a href="coming-soon-maybe.html#transforming-variables"><i class="fa fa-check"></i><b>19.2</b> Transforming variables</a></li>
<li class="chapter" data-level="19.3" data-path="coming-soon-maybe.html"><a href="coming-soon-maybe.html#non-linear-regression"><i class="fa fa-check"></i><b>19.3</b> Non-linear regression</a></li>
<li class="chapter" data-level="19.4" data-path="coming-soon-maybe.html"><a href="coming-soon-maybe.html#nested-or-blocked-study-designs"><i class="fa fa-check"></i><b>19.4</b> Nested or blocked study designs</a></li>
</ul></li>
<li class="part"><span><b>V Exam</b></span></li>
<li class="chapter" data-level="20" data-path="exam-2020.html"><a href="exam-2020.html"><i class="fa fa-check"></i><b>20</b> Exam 2020</a></li>
<li class="part"><span><b>VI Solutions</b></span></li>
<li class="chapter" data-level="21" data-path="exercise-solutions.html"><a href="exercise-solutions.html"><i class="fa fa-check"></i><b>21</b> Exercise Solutions</a>
<ul>
<li class="chapter" data-level="21.1" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-solutions-californian-bird-diversity"><i class="fa fa-check"></i><b>21.1</b> Exercise Solutions: Californian bird diversity</a></li>
<li class="chapter" data-level="21.2" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-solutions-wrangling-the-amniote-life-history-database"><i class="fa fa-check"></i><b>21.2</b> Exercise Solutions: Wrangling the Amniote Life History Database</a></li>
<li class="chapter" data-level="21.3" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-solutions-temperature-effects-on-egg-laying-dates"><i class="fa fa-check"></i><b>21.3</b> Exercise Solutions: Temperature effects on egg laying dates</a></li>
<li class="chapter" data-level="21.4" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-solutions-sexual-selection-in-hercules-beetles"><i class="fa fa-check"></i><b>21.4</b> Exercise Solutions: Sexual selection in Hercules beetles</a></li>
<li class="chapter" data-level="21.5" data-path="comparing-two-means-with-a-t-test.html"><a href="comparing-two-means-with-a-t-test.html#exercise-sex-differences-in-fine-motor-skills"><i class="fa fa-check"></i><b>21.5</b> Exercise: Sex differences in fine motor skills</a></li>
<li class="chapter" data-level="21.6" data-path="comparing-two-means-with-a-t-test.html"><a href="comparing-two-means-with-a-t-test.html#exercise-therapy-for-anorexia"><i class="fa fa-check"></i><b>21.6</b> Exercise: Therapy for anorexia</a></li>
<li class="chapter" data-level="21.7" data-path="comparing-two-means-with-a-t-test.html"><a href="comparing-two-means-with-a-t-test.html#exercise-compare-t-tests-with-randomisation-tests"><i class="fa fa-check"></i><b>21.7</b> Exercise: Compare t-tests with randomisation tests</a></li>
<li class="chapter" data-level="21.8" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-solutions-apple-tree-crop-yield"><i class="fa fa-check"></i><b>21.8</b> Exercise Solutions: Apple tree crop yield</a></li>
<li class="chapter" data-level="21.9" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-solutions-chirping-crickets"><i class="fa fa-check"></i><b>21.9</b> Exercise Solutions: Chirping crickets</a></li>
<li class="chapter" data-level="21.10" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-solutions-fish-behaviour"><i class="fa fa-check"></i><b>21.10</b> Exercise Solutions: Fish behaviour</a></li>
<li class="chapter" data-level="21.11" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-solutions-maze-runner"><i class="fa fa-check"></i><b>21.11</b> Exercise Solutions: Maze runner</a></li>
<li class="chapter" data-level="21.12" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-solutions-snails-on-the-move"><i class="fa fa-check"></i><b>21.12</b> Exercise Solutions: Snails on the move</a></li>
<li class="chapter" data-level="21.13" data-path="exercise-solutions.html"><a href="exercise-solutions.html#exercise-solutions-mouse-lemur-strength"><i class="fa fa-check"></i><b>21.13</b> Exercise Solutions: Mouse lemur strength</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">BB852 - Data handling, visualisation and statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="exercise-solutions" class="section level1" number="21">
<h1><span class="header-section-number">Chapter 21</span> Exercise Solutions</h1>
<p>These are the solutions to the exercises used in the course.</p>

<div id="exercise-solutions-californian-bird-diversity" class="section level2" number="21.1">
<h2><span class="header-section-number">21.1</span> Exercise Solutions: Californian bird diversity</h2>
<ol style="list-style-type: decimal">
<li>First import the data. Check that the columns look as they should. (e.g. use <code>summary</code> or <code>str</code> functions). Tip: use the “Wizard” in RStudio to guide you.</li>
</ol>
<div class="sourceCode" id="cb494"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb494-1"><a href="exercise-solutions.html#cb494-1" aria-hidden="true"></a>df &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;CourseData/suburbanBirds.csv&quot;</span>)</span></code></pre></div>
<ol start="2" style="list-style-type: decimal">
<li>What is the mean, minimum, and maximum number of species seen? (there is more than one way to do this)*</li>
</ol>
<div class="sourceCode" id="cb495"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb495-1"><a href="exercise-solutions.html#cb495-1" aria-hidden="true"></a><span class="kw">mean</span>(df<span class="op">$</span>nSpecies)</span></code></pre></div>
<pre><code>## [1] 9.647059</code></pre>
<div class="sourceCode" id="cb497"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb497-1"><a href="exercise-solutions.html#cb497-1" aria-hidden="true"></a><span class="kw">min</span>(df<span class="op">$</span>nSpecies)</span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<div class="sourceCode" id="cb499"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb499-1"><a href="exercise-solutions.html#cb499-1" aria-hidden="true"></a><span class="kw">max</span>(df<span class="op">$</span>nSpecies)</span></code></pre></div>
<pre><code>## [1] 15</code></pre>
<div class="sourceCode" id="cb501"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb501-1"><a href="exercise-solutions.html#cb501-1" aria-hidden="true"></a><span class="kw">range</span>(df<span class="op">$</span>nSpecies)</span></code></pre></div>
<pre><code>## [1]  3 15</code></pre>
<div class="sourceCode" id="cb503"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb503-1"><a href="exercise-solutions.html#cb503-1" aria-hidden="true"></a><span class="kw">summary</span>(df<span class="op">$</span>nSpecies)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   3.000   6.000  11.000   9.647  13.000  15.000</code></pre>
<ol start="3" style="list-style-type: decimal">
<li>How old are the youngest and oldest suburbs? (hint: the survey was carried out in 1975, do the math!)</li>
</ol>
<div class="sourceCode" id="cb505"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb505-1"><a href="exercise-solutions.html#cb505-1" aria-hidden="true"></a><span class="dv">1975</span><span class="op">-</span><span class="kw">min</span>(df<span class="op">$</span>Year)</span></code></pre></div>
<pre><code>## [1] 29</code></pre>
<div class="sourceCode" id="cb507"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb507-1"><a href="exercise-solutions.html#cb507-1" aria-hidden="true"></a><span class="dv">1975</span><span class="op">-</span><span class="kw">max</span>(df<span class="op">$</span>Year)</span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<ol start="4" style="list-style-type: decimal">
<li>Plot the relationship between <code>Year</code> and <code>nSpecies</code> as a scatterplot using base-R graphics (using the <code>plot</code> function).</li>
</ol>
<div class="sourceCode" id="cb509"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb509-1"><a href="exercise-solutions.html#cb509-1" aria-hidden="true"></a><span class="kw">plot</span>(df<span class="op">$</span>Year,df<span class="op">$</span>nSpecies)</span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-401-1.png" width="672" /></p>
<ol start="5" style="list-style-type: decimal">
<li>The patern might be easier to see if you could replace <code>YearBuilt</code> with suburb age. Create a new vector in your data frame for this variable (e.g. <code>df$Age &lt;- 1975 - Year)</code>). Replot your results.</li>
</ol>
<div class="sourceCode" id="cb510"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb510-1"><a href="exercise-solutions.html#cb510-1" aria-hidden="true"></a>df<span class="op">$</span>Age &lt;-<span class="st"> </span><span class="dv">1975</span><span class="op">-</span>df<span class="op">$</span>Year</span>
<span id="cb510-2"><a href="exercise-solutions.html#cb510-2" aria-hidden="true"></a><span class="kw">plot</span>(df<span class="op">$</span>Age,df<span class="op">$</span>nSpecies)</span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-402-1.png" width="672" /></p>
<ol start="6" style="list-style-type: decimal">
<li>What do the data show? What might be the mechanisms for the patterns you see? Do they match your expectations?</li>
</ol>
<p>If you recall that the average species richness pre-development was about 3.5 species, the data show that suburban development is actually good for bird species. This could be surprising, but a possible explanation is that the gardens, parks, trees etc. that come with development represent additional habitats that would not normally be there. Therefore, these areas attract new species.</p>
<ol start="7" style="list-style-type: decimal">
<li>Export your plots and paste them into a Word Document.</li>
</ol>
<p>You can do this with several methods. My favourite <em>quick</em> method is to click the Export button &gt; Copy to Clipboard, resize the plot so it looks nice, then click Copy Plot. Finally, paste into Word with Cntrl (or Cmd) + V.</p>

</div>
<div id="exercise-solutions-wrangling-the-amniote-life-history-database" class="section level2" number="21.2">
<h2><span class="header-section-number">21.2</span> Exercise Solutions: Wrangling the Amniote Life History Database</h2>
<ol style="list-style-type: decimal">
<li>When you have imported the data, use <code>dim</code> to check the dimensions of the whole data frame (you should see that there are 36 columns and 21322 rows). Use <code>names</code> to look at the names of all columns in the data in <code>amniote</code>.</li>
</ol>
<div class="sourceCode" id="cb511"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb511-1"><a href="exercise-solutions.html#cb511-1" aria-hidden="true"></a>amniote &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;CourseData/Amniote_Database_Aug_2015.csv&quot;</span>,<span class="dt">na.strings =</span> <span class="st">&quot;-999&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb512"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb512-1"><a href="exercise-solutions.html#cb512-1" aria-hidden="true"></a><span class="kw">dim</span>(amniote)</span></code></pre></div>
<pre><code>## [1] 21322    36</code></pre>
<div class="sourceCode" id="cb514"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb514-1"><a href="exercise-solutions.html#cb514-1" aria-hidden="true"></a><span class="kw">names</span>(amniote)</span></code></pre></div>
<pre><code>##  [1] &quot;class&quot;                                
##  [2] &quot;order&quot;                                
##  [3] &quot;family&quot;                               
##  [4] &quot;genus&quot;                                
##  [5] &quot;species&quot;                              
##  [6] &quot;subspecies&quot;                           
##  [7] &quot;common_name&quot;                          
##  [8] &quot;female_maturity_d&quot;                    
##  [9] &quot;litter_or_clutch_size_n&quot;              
## [10] &quot;litters_or_clutches_per_y&quot;            
## [11] &quot;adult_body_mass_g&quot;                    
## [12] &quot;maximum_longevity_y&quot;                  
## [13] &quot;gestation_d&quot;                          
## [14] &quot;weaning_d&quot;                            
## [15] &quot;birth_or_hatching_weight_g&quot;           
## [16] &quot;weaning_weight_g&quot;                     
## [17] &quot;egg_mass_g&quot;                           
## [18] &quot;incubation_d&quot;                         
## [19] &quot;fledging_age_d&quot;                       
## [20] &quot;longevity_y&quot;                          
## [21] &quot;male_maturity_d&quot;                      
## [22] &quot;inter_litter_or_interbirth_interval_y&quot;
## [23] &quot;female_body_mass_g&quot;                   
## [24] &quot;male_body_mass_g&quot;                     
## [25] &quot;no_sex_body_mass_g&quot;                   
## [26] &quot;egg_width_mm&quot;                         
## [27] &quot;egg_length_mm&quot;                        
## [28] &quot;fledging_mass_g&quot;                      
## [29] &quot;adult_svl_cm&quot;                         
## [30] &quot;male_svl_cm&quot;                          
## [31] &quot;female_svl_cm&quot;                        
## [32] &quot;birth_or_hatching_svl_cm&quot;             
## [33] &quot;female_svl_at_maturity_cm&quot;            
## [34] &quot;female_body_mass_at_maturity_g&quot;       
## [35] &quot;no_sex_svl_cm&quot;                        
## [36] &quot;no_sex_maturity_d&quot;</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>We are interested in longevity (lifespan) and body size and reproductive effort and how this might vary depending on the taxonomy (specifically, with Class). Use <code>select</code> to pick relevent columns of the dataset and discard the others. Call the new data frame <code>x</code>.
The relevant columns are the taxonomic variables (<code>class</code>, <code>species</code>) and <code>longevity_y</code>, <code>litter_or_clutch_size_n</code>, <code>litters_or_clutches_per_y</code>, and <code>adult_body_mass_g</code>.</li>
</ol>
<div class="sourceCode" id="cb516"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb516-1"><a href="exercise-solutions.html#cb516-1" aria-hidden="true"></a>x &lt;-<span class="st"> </span>amniote <span class="op">%&gt;%</span></span>
<span id="cb516-2"><a href="exercise-solutions.html#cb516-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">select</span>(class,genus,species,</span>
<span id="cb516-3"><a href="exercise-solutions.html#cb516-3" aria-hidden="true"></a>         longevity_y, adult_body_mass_g,</span>
<span id="cb516-4"><a href="exercise-solutions.html#cb516-4" aria-hidden="true"></a>         litter_or_clutch_size_n,litters_or_clutches_per_y )</span></code></pre></div>
<ol start="3" style="list-style-type: decimal">
<li>Take a look at the first few entries in the <code>species</code> column. You will see that it is only the <em>epithet</em>, the second part of the <em>Genus_species</em> name, that is given.<br />
Use <code>mutate</code> and <code>paste</code> to convert the <code>species</code> column to a <em>Genus_species</em> by pasting the data in <code>genus</code> and <code>species</code> together. To see how this works, try out the following command, <code>paste(1:3, 4:6)</code>. After you have created the new column, remove the <code>genus</code> column (using <code>select</code> and <code>-genus</code>).</li>
</ol>
<div class="sourceCode" id="cb517"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb517-1"><a href="exercise-solutions.html#cb517-1" aria-hidden="true"></a>x &lt;-<span class="st"> </span>x <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb517-2"><a href="exercise-solutions.html#cb517-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">species =</span> <span class="kw">paste</span>(genus,species)) <span class="op">%&gt;%</span></span>
<span id="cb517-3"><a href="exercise-solutions.html#cb517-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>genus)</span>
<span id="cb517-4"><a href="exercise-solutions.html#cb517-4" aria-hidden="true"></a><span class="kw">head</span>(x)</span></code></pre></div>
<pre><code>##   class               species longevity_y
## 1  Aves Accipiter albogularis          NA
## 2  Aves      Accipiter badius          NA
## 3  Aves     Accipiter bicolor          NA
## 4  Aves  Accipiter brachyurus          NA
## 5  Aves    Accipiter brevipes          NA
## 6  Aves Accipiter castanilius          NA
##   adult_body_mass_g litter_or_clutch_size_n
## 1           251.500                      NA
## 2           140.000                    3.25
## 3           345.000                    2.70
## 4           142.000                      NA
## 5           203.500                    4.00
## 6           159.375                      NA
##   litters_or_clutches_per_y
## 1                        NA
## 2                         1
## 3                        NA
## 4                        NA
## 5                         1
## 6                        NA</code></pre>
<ol start="4" style="list-style-type: decimal">
<li>What is the longest living species in the record? Use <code>arrange</code> to sort the data from longest to shortest longevity (<code>longevity_y</code>), and then look at the top of the file using <code>head</code> to find out. (hint: you will need to use reverse sort (<code>-</code>)). Cut and paste the species name into Google to find out more!</li>
</ol>
<div class="sourceCode" id="cb519"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb519-1"><a href="exercise-solutions.html#cb519-1" aria-hidden="true"></a>x &lt;-<span class="st"> </span>x <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">arrange</span>(<span class="op">-</span>longevity_y)</span>
<span id="cb519-2"><a href="exercise-solutions.html#cb519-2" aria-hidden="true"></a><span class="kw">head</span>(x)</span></code></pre></div>
<pre><code>##      class                 species longevity_y
## 1 Reptilia Chelonoidis duncanensis       177.0
## 2 Reptilia  Aldabrachelys gigantea       152.0
## 3 Reptilia          Testudo graeca       127.0
## 4 Mammalia            Homo sapiens       122.5
## 5 Mammalia   Balaenoptera physalus        95.0
## 6 Mammalia            Orcinus orca        90.0
##   adult_body_mass_g litter_or_clutch_size_n
## 1                NA                      NA
## 2            117200                    13.5
## 3              1430                     5.0
## 4             62035                     1.0
## 5          38800000                     1.0
## 6           4300000                     1.0
##   litters_or_clutches_per_y
## 1                        NA
## 2                  2.000000
## 3                  3.200993
## 4                  0.485000
## 5                  0.400000
## 6                  0.210000</code></pre>
<ol start="5" style="list-style-type: decimal">
<li>Do the same thing but this time find the shortest lived species.</li>
</ol>
<div class="sourceCode" id="cb521"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb521-1"><a href="exercise-solutions.html#cb521-1" aria-hidden="true"></a>x &lt;-<span class="st"> </span>x <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">arrange</span>(longevity_y)</span>
<span id="cb521-2"><a href="exercise-solutions.html#cb521-2" aria-hidden="true"></a><span class="kw">head</span>(x)</span></code></pre></div>
<pre><code>##      class              species longevity_y
## 1 Mammalia    Lepus nigricollis  0.08333333
## 2 Mammalia  Notoryctes caurinus  0.08333333
## 3 Mammalia Allactaga balikunica  0.08333333
## 4 Mammalia    Allactaga bullata  0.08333333
## 5 Mammalia       Geomys pinetis  0.08333333
## 6 Mammalia          Mus sorella  0.08333333
##   adult_body_mass_g litter_or_clutch_size_n
## 1          2196.875                    1.59
## 2            34.000                    1.50
## 3                NA                    2.52
## 4                NA                    2.52
## 5           195.750                    1.77
## 6            12.535                    5.20
##   litters_or_clutches_per_y
## 1                     7.150
## 2                        NA
## 3                        NA
## 4                        NA
## 5                     1.865
## 6                     3.000</code></pre>
<ol start="6" style="list-style-type: decimal">
<li>Use <code>summarise</code> and <code>group_by</code> to make a table summarising <code>min</code>, <code>median</code> and <code>max</code> life spans (<code>longevity_y</code>) for the three taxonomic classes in the database. Remember that you need to tell R to remove the <code>NA</code> values using a <code>na.rm = TRUE</code> argument.</li>
</ol>
<div class="sourceCode" id="cb523"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb523-1"><a href="exercise-solutions.html#cb523-1" aria-hidden="true"></a>x <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb523-2"><a href="exercise-solutions.html#cb523-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">group_by</span>(class) <span class="op">%&gt;%</span></span>
<span id="cb523-3"><a href="exercise-solutions.html#cb523-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">min =</span> <span class="kw">min</span>(longevity_y,<span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</span>
<span id="cb523-4"><a href="exercise-solutions.html#cb523-4" aria-hidden="true"></a>            <span class="dt">median =</span> <span class="kw">median</span>(longevity_y,<span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</span>
<span id="cb523-5"><a href="exercise-solutions.html#cb523-5" aria-hidden="true"></a>            <span class="dt">max =</span> <span class="kw">max</span>(longevity_y,<span class="dt">na.rm =</span> <span class="ot">TRUE</span>))</span></code></pre></div>
<pre><code>## # A tibble: 3 x 4
##   class       min median   max
##   &lt;chr&gt;     &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
## 1 Aves     0.75    12.5    75 
## 2 Mammalia 0.0833   8.67  122.
## 3 Reptilia 0.2     11.0   177</code></pre>
<ol start="7" style="list-style-type: decimal">
<li>Body size is thought to be associated with life span. Let’s treat that as a hypothesis and test it graphically. Sketch what would the graph would look like if the hypothesis were true, and if it was false. Plot <code>adult_body_mass_g</code> vs. <code>longevity_y</code> (using base R graphics). You should notice that this looks a bit messy.</li>
</ol>
<div class="sourceCode" id="cb525"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb525-1"><a href="exercise-solutions.html#cb525-1" aria-hidden="true"></a><span class="kw">plot</span>(x<span class="op">$</span>adult_body_mass_g,x<span class="op">$</span>longevity_y)</span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-411-1.png" width="672" /></p>
<ol start="8" style="list-style-type: decimal">
<li>Use <code>mutate</code> to create a new <code>log</code>-transformed variables, <code>logMass</code> and <code>logLongevity</code>. Use these to make a “log-log” plot. You should see that makes the relationship more linear, and easier to “read”.</li>
</ol>
<div class="sourceCode" id="cb526"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb526-1"><a href="exercise-solutions.html#cb526-1" aria-hidden="true"></a>x &lt;-<span class="st"> </span>x <span class="op">%&gt;%</span></span>
<span id="cb526-2"><a href="exercise-solutions.html#cb526-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">logMass =</span> <span class="kw">log</span>(adult_body_mass_g),</span>
<span id="cb526-3"><a href="exercise-solutions.html#cb526-3" aria-hidden="true"></a>         <span class="dt">logLongevity =</span> <span class="kw">log</span>(longevity_y))</span>
<span id="cb526-4"><a href="exercise-solutions.html#cb526-4" aria-hidden="true"></a></span>
<span id="cb526-5"><a href="exercise-solutions.html#cb526-5" aria-hidden="true"></a><span class="kw">plot</span>(x<span class="op">$</span>logMass,x<span class="op">$</span>logLongevity)</span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-412-1.png" width="672" /></p>
<ol start="9" style="list-style-type: decimal">
<li>Is there a trade-off between reproductive effort and life span? Think about this as a hypothesis - sketch what would the graph would look like if that were true, and if it was false. Now use the data to test that hypothesis: Use <code>mutate</code> to create a variable called <code>logOffspring</code> which is the logarithm of number of litters/clutches per year multiplied by the number of babies in each litter/clutch . Then plot <code>logOffspring</code> vs. <code>logLongevity</code>.</li>
</ol>
<div class="sourceCode" id="cb527"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb527-1"><a href="exercise-solutions.html#cb527-1" aria-hidden="true"></a>x &lt;-<span class="st"> </span>x <span class="op">%&gt;%</span></span>
<span id="cb527-2"><a href="exercise-solutions.html#cb527-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">logOffspring =</span> <span class="kw">log</span>(litter_or_clutch_size_n <span class="op">*</span><span class="st"> </span>litters_or_clutches_per_y))</span>
<span id="cb527-3"><a href="exercise-solutions.html#cb527-3" aria-hidden="true"></a></span>
<span id="cb527-4"><a href="exercise-solutions.html#cb527-4" aria-hidden="true"></a><span class="kw">plot</span>(x<span class="op">$</span>logOffspring,x<span class="op">$</span>logLongevity)</span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-413-1.png" width="672" /></p>
<ol start="10" style="list-style-type: decimal">
<li>To answer the final question (differences between taxonomic classes) you could now use <code>filter</code> to subset to particular classes and repeat the plot to see whether the relationships holds universally.</li>
</ol>
<div class="sourceCode" id="cb528"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb528-1"><a href="exercise-solutions.html#cb528-1" aria-hidden="true"></a>aves &lt;-<span class="st"> </span>x <span class="op">%&gt;%</span></span>
<span id="cb528-2"><a href="exercise-solutions.html#cb528-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">filter</span>(class <span class="op">==</span><span class="st"> &quot;Aves&quot;</span>)</span>
<span id="cb528-3"><a href="exercise-solutions.html#cb528-3" aria-hidden="true"></a></span>
<span id="cb528-4"><a href="exercise-solutions.html#cb528-4" aria-hidden="true"></a><span class="kw">plot</span>(aves<span class="op">$</span>logOffspring,aves<span class="op">$</span>logLongevity)</span>
<span id="cb528-5"><a href="exercise-solutions.html#cb528-5" aria-hidden="true"></a><span class="kw">title</span>(<span class="st">&quot;Aves&quot;</span>)</span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-414-1.png" width="672" /></p>
<div class="sourceCode" id="cb529"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb529-1"><a href="exercise-solutions.html#cb529-1" aria-hidden="true"></a>mammalia &lt;-<span class="st"> </span>x <span class="op">%&gt;%</span></span>
<span id="cb529-2"><a href="exercise-solutions.html#cb529-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">filter</span>(class <span class="op">==</span><span class="st"> &quot;Mammalia&quot;</span>)</span>
<span id="cb529-3"><a href="exercise-solutions.html#cb529-3" aria-hidden="true"></a></span>
<span id="cb529-4"><a href="exercise-solutions.html#cb529-4" aria-hidden="true"></a><span class="kw">plot</span>(mammalia<span class="op">$</span>logOffspring,mammalia<span class="op">$</span>logLongevity)</span>
<span id="cb529-5"><a href="exercise-solutions.html#cb529-5" aria-hidden="true"></a><span class="kw">title</span>(<span class="st">&quot;Mammalia&quot;</span>)</span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-415-1.png" width="672" /></p>
<div class="sourceCode" id="cb530"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb530-1"><a href="exercise-solutions.html#cb530-1" aria-hidden="true"></a>reptilia &lt;-<span class="st"> </span>x <span class="op">%&gt;%</span></span>
<span id="cb530-2"><a href="exercise-solutions.html#cb530-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">filter</span>(class <span class="op">==</span><span class="st"> &quot;Reptilia&quot;</span>)</span>
<span id="cb530-3"><a href="exercise-solutions.html#cb530-3" aria-hidden="true"></a></span>
<span id="cb530-4"><a href="exercise-solutions.html#cb530-4" aria-hidden="true"></a><span class="kw">plot</span>(reptilia<span class="op">$</span>logOffspring,reptilia<span class="op">$</span>logLongevity)</span>
<span id="cb530-5"><a href="exercise-solutions.html#cb530-5" aria-hidden="true"></a><span class="kw">title</span>(<span class="st">&quot;Reptilia&quot;</span>)</span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-416-1.png" width="672" /></p>

</div>
<div id="exercise-solutions-temperature-effects-on-egg-laying-dates" class="section level2" number="21.3">
<h2><span class="header-section-number">21.3</span> Exercise Solutions: Temperature effects on egg laying dates</h2>
<ol style="list-style-type: decimal">
<li>Import the data and take a look at it with <code>head</code> or <code>str</code>.</li>
</ol>
<div class="sourceCode" id="cb531"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb531-1"><a href="exercise-solutions.html#cb531-1" aria-hidden="true"></a>eggDates &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;CourseData/eggDates.csv&quot;</span>)</span>
<span id="cb531-2"><a href="exercise-solutions.html#cb531-2" aria-hidden="true"></a><span class="kw">head</span>(eggDates)</span></code></pre></div>
<pre><code>##   boxNumber y2013 y2014 y2016 y2017 y2018 y2019
## 1         1   116   103    NA   107   111    NA
## 2         2    NA    NA    NA   114   118    NA
## 3         3    NA   102   108    NA    NA    NA
## 4         4   121   103   121   155   111   110
## 5         5   135   100   108   102   106   108
## 6         6   122   113   122    NA   124   149</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Use <code>pivot_longer</code> to reformat the data. This might take a bit of trial and error - don’t give up!</li>
</ol>
<p>Maybe this will help: The first argument in the <code>pivot_longer</code> command (<code>cols</code>) tells R which columns contain the data you are interested in (in this case, these are <code>y2013</code>,<code>y2014</code> etc). Then the <code>names_to</code> argument tells R what you want to name the new column from this data (in this case, <code>Year</code>). Then, the <code>values_to</code> argument tells R what the data column should be called (e.g. <code>Day</code>). In addition, there is a useful argument called <code>names_prefix</code> that will remove the part of the column name (e.g. the <code>y</code> of <code>y2013</code>)</p>
<p>You should also make sure that the <code>Year</code> column is recognised as being a numeric variable rather than a character string. You can do this by adding a command using <code>mutate</code> and <code>as.numeric</code>, like this <code>mutate(Year = as.numeric(Year))</code></p>
<p>You should end up with a dataset with three columns as described above.</p>
<div class="sourceCode" id="cb533"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb533-1"><a href="exercise-solutions.html#cb533-1" aria-hidden="true"></a>eggDates &lt;-<span class="st"> </span>eggDates <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pivot_longer</span>(<span class="dt">cols =</span> <span class="kw">starts_with</span>(<span class="st">&quot;y&quot;</span>),<span class="dt">names_to =</span> <span class="st">&quot;Year&quot;</span>,<span class="dt">values_to =</span> <span class="st">&quot;day&quot;</span>)</span>
<span id="cb533-2"><a href="exercise-solutions.html#cb533-2" aria-hidden="true"></a></span>
<span id="cb533-3"><a href="exercise-solutions.html#cb533-3" aria-hidden="true"></a><span class="kw">head</span>(eggDates)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 3
##   boxNumber Year    day
##       &lt;int&gt; &lt;chr&gt; &lt;int&gt;
## 1         1 y2013   116
## 2         1 y2014   103
## 3         1 y2016    NA
## 4         1 y2017   107
## 5         1 y2018   111
## 6         1 y2019    NA</code></pre>
<ol start="3" style="list-style-type: decimal">
<li>Ensure that year is coded as numeric variable using <code>mutate</code>. [Hint, you can use the command <code>as.numeric</code>, but first remove the “y” in the name using <code>gsub</code>].</li>
</ol>
<div class="sourceCode" id="cb535"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb535-1"><a href="exercise-solutions.html#cb535-1" aria-hidden="true"></a>eggDates &lt;-<span class="st"> </span>eggDates <span class="op">%&gt;%</span></span>
<span id="cb535-2"><a href="exercise-solutions.html#cb535-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Year =</span> <span class="kw">gsub</span>(<span class="dt">pattern =</span> <span class="st">&quot;y&quot;</span>,<span class="dt">replacement =</span> <span class="st">&quot;&quot;</span>, Year)) <span class="op">%&gt;%</span></span>
<span id="cb535-3"><a href="exercise-solutions.html#cb535-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Year =</span> <span class="kw">as.numeric</span>(Year))         </span>
<span id="cb535-4"><a href="exercise-solutions.html#cb535-4" aria-hidden="true"></a><span class="kw">head</span>(eggDates)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 3
##   boxNumber  Year   day
##       &lt;int&gt; &lt;dbl&gt; &lt;int&gt;
## 1         1  2013   116
## 2         1  2014   103
## 3         1  2016    NA
## 4         1  2017   107
## 5         1  2018   111
## 6         1  2019    NA</code></pre>
<ol start="4" style="list-style-type: decimal">
<li>Calculate the mean egg date per year using <code>summarise</code> (remember to <code>group_by</code> the year first). Take a look at the data.</li>
</ol>
<div class="sourceCode" id="cb537"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb537-1"><a href="exercise-solutions.html#cb537-1" aria-hidden="true"></a>meanEgg &lt;-<span class="st"> </span>eggDates <span class="op">%&gt;%</span></span>
<span id="cb537-2"><a href="exercise-solutions.html#cb537-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">group_by</span>(Year) <span class="op">%&gt;%</span></span>
<span id="cb537-3"><a href="exercise-solutions.html#cb537-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">meanEggDate =</span> <span class="kw">mean</span>(day,<span class="dt">na.rm=</span><span class="ot">TRUE</span>))</span>
<span id="cb537-4"><a href="exercise-solutions.html#cb537-4" aria-hidden="true"></a></span>
<span id="cb537-5"><a href="exercise-solutions.html#cb537-5" aria-hidden="true"></a>meanEgg</span></code></pre></div>
<pre><code>## # A tibble: 6 x 2
##    Year meanEggDate
##   &lt;dbl&gt;       &lt;dbl&gt;
## 1  2013        125.
## 2  2014        108.
## 3  2016        115.
## 4  2017        112.
## 5  2018        117.
## 6  2019        111.</code></pre>
<p><strong>Preparing the weather data</strong></p>
<ol start="5" style="list-style-type: decimal">
<li>Import the weather data and take a look at it with <code>head</code> or <code>str</code>.</li>
</ol>
<div class="sourceCode" id="cb539"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb539-1"><a href="exercise-solutions.html#cb539-1" aria-hidden="true"></a>weather &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;CourseData/AarslevTemperature.csv&quot;</span>)</span>
<span id="cb539-2"><a href="exercise-solutions.html#cb539-2" aria-hidden="true"></a><span class="kw">str</span>(weather)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:	2767 obs. of  4 variables:
##  $ YEAR : int  2012 2012 2012 2012 2012 2012 2012 2012 2012 2012 ...
##  $ MONTH: int  4 4 4 4 4 4 4 4 4 4 ...
##  $ DAY  : int  11 12 13 14 15 16 17 18 19 20 ...
##  $ TEMP : num  8.1 6.6 5.9 6.2 6.5 4.3 4.3 7 8.9 6.5 ...</code></pre>
<ol start="6" style="list-style-type: decimal">
<li>Use <code>filter</code> subset to the months of interest (February-April) and then <code>summarise</code> the data to calculate the mean temperature in this period (remember to <code>group_by</code> year). Look at the data. You should end up with a dataset with two columns - <code>YEAR</code> and <code>meanSpringTemp</code>.</li>
</ol>
<div class="sourceCode" id="cb541"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb541-1"><a href="exercise-solutions.html#cb541-1" aria-hidden="true"></a>weather &lt;-<span class="st"> </span>weather <span class="op">%&gt;%</span></span>
<span id="cb541-2"><a href="exercise-solutions.html#cb541-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">filter</span>(MONTH <span class="op">%in%</span><span class="st"> </span><span class="dv">2</span><span class="op">:</span><span class="dv">4</span>) <span class="op">%&gt;%</span></span>
<span id="cb541-3"><a href="exercise-solutions.html#cb541-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">group_by</span>(YEAR) <span class="op">%&gt;%</span></span>
<span id="cb541-4"><a href="exercise-solutions.html#cb541-4" aria-hidden="true"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">meanAprilTemp =</span> <span class="kw">mean</span>(TEMP))</span>
<span id="cb541-5"><a href="exercise-solutions.html#cb541-5" aria-hidden="true"></a></span>
<span id="cb541-6"><a href="exercise-solutions.html#cb541-6" aria-hidden="true"></a><span class="kw">head</span>(weather)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 2
##    YEAR meanAprilTemp
##   &lt;int&gt;         &lt;dbl&gt;
## 1  2012          7.86
## 2  2013          1.60
## 3  2014          6.03
## 4  2015          3.53
## 5  2016          4.50
## 6  2017          4.77</code></pre>
<p><strong>Bringing it together</strong></p>
<ol start="7" style="list-style-type: decimal">
<li>Join the two datasets together using <code>left_join</code>. You should now have a dataset with columns <code>nestNumber</code>, <code>Year</code>, <code>dayNumber</code> and <code>meanAprilTemp</code></li>
</ol>
<div class="sourceCode" id="cb543"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb543-1"><a href="exercise-solutions.html#cb543-1" aria-hidden="true"></a>joinedData &lt;-<span class="st"> </span><span class="kw">left_join</span>(meanEgg,weather,<span class="kw">c</span>(<span class="st">&quot;Year&quot;</span> =<span class="st"> &quot;YEAR&quot;</span>))</span>
<span id="cb543-2"><a href="exercise-solutions.html#cb543-2" aria-hidden="true"></a><span class="kw">head</span>(joinedData)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 3
##    Year meanEggDate meanAprilTemp
##   &lt;dbl&gt;       &lt;dbl&gt;         &lt;dbl&gt;
## 1  2013        125.          1.60
## 2  2014        108.          6.03
## 3  2016        115.          4.50
## 4  2017        112.          4.77
## 5  2018        117.          3.07
## 6  2019        111.          6.12</code></pre>
<p><strong>Plot the data</strong></p>
<ol start="8" style="list-style-type: decimal">
<li>plot a graph of <code>meanAprilTemp</code> on the x-axis and <code>dayNumber</code> on the y-axis.</li>
</ol>
<div class="sourceCode" id="cb545"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb545-1"><a href="exercise-solutions.html#cb545-1" aria-hidden="true"></a><span class="kw">plot</span>(joinedData<span class="op">$</span>meanAprilTemp,joinedData<span class="op">$</span>meanEggDate)</span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-425-1.png" width="672" /></p>
<p>Now you should be able to answer the question we started with: is laying date associated with spring temperatures? Yes, there looks to be a negative relationship between temperature and egg laying date.</p>

</div>
<div id="exercise-solutions-sexual-selection-in-hercules-beetles" class="section level2" number="21.4">
<h2><span class="header-section-number">21.4</span> Exercise Solutions: Sexual selection in Hercules beetles</h2>
<ol style="list-style-type: decimal">
<li>What is your null hypothesis?</li>
</ol>
<p><em>Null Hypothesis - There is no difference in the widths of the species.</em></p>
<ol start="2" style="list-style-type: decimal">
<li>What is your alternative hypothesis?</li>
</ol>
<p><em>Alternative Hypothesis - Males have larger widths than females.</em></p>
<ol start="3" style="list-style-type: decimal">
<li>Import the data.</li>
</ol>
<div class="sourceCode" id="cb546"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb546-1"><a href="exercise-solutions.html#cb546-1" aria-hidden="true"></a>hercules &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;CourseData/herculesBeetle.csv&quot;</span>)</span></code></pre></div>
<ol start="4" style="list-style-type: decimal">
<li>Calculate the mean for each sex (either using <code>tapply</code> or using <code>dplyr</code> tools)</li>
</ol>
<div class="sourceCode" id="cb547"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb547-1"><a href="exercise-solutions.html#cb547-1" aria-hidden="true"></a><span class="co">#With dplyr</span></span>
<span id="cb547-2"><a href="exercise-solutions.html#cb547-2" aria-hidden="true"></a>hercules <span class="op">%&gt;%</span></span>
<span id="cb547-3"><a href="exercise-solutions.html#cb547-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">group_by</span>(sex) <span class="op">%&gt;%</span></span>
<span id="cb547-4"><a href="exercise-solutions.html#cb547-4" aria-hidden="true"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">mean=</span><span class="kw">mean</span>(width))</span></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   sex     mean
##   &lt;chr&gt;  &lt;dbl&gt;
## 1 Female  15.0
## 2 Male    17.4</code></pre>
<div class="sourceCode" id="cb549"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb549-1"><a href="exercise-solutions.html#cb549-1" aria-hidden="true"></a><span class="co">#with tapply</span></span>
<span id="cb549-2"><a href="exercise-solutions.html#cb549-2" aria-hidden="true"></a><span class="kw">tapply</span>(hercules<span class="op">$</span>width,hercules<span class="op">$</span>sex,mean)</span></code></pre></div>
<pre><code>##   Female     Male 
## 15.02825 17.36568</code></pre>
<ol start="5" style="list-style-type: decimal">
<li>Plot the data as a histogram.</li>
</ol>
<div class="sourceCode" id="cb551"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb551-1"><a href="exercise-solutions.html#cb551-1" aria-hidden="true"></a><span class="co"># Let&#39;s look at the male and female data</span></span>
<span id="cb551-2"><a href="exercise-solutions.html#cb551-2" aria-hidden="true"></a>(plot1 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(hercules, <span class="kw">aes</span>(<span class="dt">x =</span> width, <span class="dt">fill =</span> sex)) <span class="op">+</span></span>
<span id="cb551-3"><a href="exercise-solutions.html#cb551-3" aria-hidden="true"></a><span class="st">    </span><span class="kw">geom_histogram</span>(<span class="dt">position =</span> <span class="st">&quot;identity&quot;</span>,<span class="dt">alpha=</span>.<span class="dv">7</span>))</span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-429-1.png" width="672" /></p>
<ol start="6" style="list-style-type: decimal">
<li>Add vertical lines to the plot to indicate the mean values.</li>
</ol>
<div class="sourceCode" id="cb552"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb552-1"><a href="exercise-solutions.html#cb552-1" aria-hidden="true"></a>hercules <span class="op">%&gt;%</span></span>
<span id="cb552-2"><a href="exercise-solutions.html#cb552-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">group_by</span>(sex) <span class="op">%&gt;%</span></span>
<span id="cb552-3"><a href="exercise-solutions.html#cb552-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">mean=</span><span class="kw">mean</span>(width)) <span class="op">%&gt;%</span></span>
<span id="cb552-4"><a href="exercise-solutions.html#cb552-4" aria-hidden="true"></a><span class="st">  </span><span class="kw">pull</span>(mean) -&gt;<span class="st"> </span>meanVals</span>
<span id="cb552-5"><a href="exercise-solutions.html#cb552-5" aria-hidden="true"></a></span>
<span id="cb552-6"><a href="exercise-solutions.html#cb552-6" aria-hidden="true"></a>plot1 <span class="op">+</span><span class="st"> </span><span class="kw">geom_vline</span>(<span class="dt">xintercept=</span>meanVals,<span class="dt">colour=</span><span class="kw">c</span>(<span class="st">&quot;red&quot;</span>,<span class="st">&quot;blue&quot;</span>))</span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-430-1.png" width="672" /></p>
<ol start="7" style="list-style-type: decimal">
<li>Now calculate the difference between the mean values using <code>dplyr</code> tools, or <code>tapply</code>.</li>
</ol>
<div class="sourceCode" id="cb553"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb553-1"><a href="exercise-solutions.html#cb553-1" aria-hidden="true"></a><span class="co">#with dplyr</span></span>
<span id="cb553-2"><a href="exercise-solutions.html#cb553-2" aria-hidden="true"></a>hercules <span class="op">%&gt;%</span></span>
<span id="cb553-3"><a href="exercise-solutions.html#cb553-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">group_by</span>(sex) <span class="op">%&gt;%</span></span>
<span id="cb553-4"><a href="exercise-solutions.html#cb553-4" aria-hidden="true"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">mean=</span><span class="kw">mean</span>(width)) <span class="op">%&gt;%</span></span>
<span id="cb553-5"><a href="exercise-solutions.html#cb553-5" aria-hidden="true"></a><span class="st">  </span><span class="kw">pull</span>(mean) <span class="op">%&gt;%</span></span>
<span id="cb553-6"><a href="exercise-solutions.html#cb553-6" aria-hidden="true"></a><span class="st">  </span><span class="kw">diff</span>() -&gt;<span class="st"> </span>observedDiff</span>
<span id="cb553-7"><a href="exercise-solutions.html#cb553-7" aria-hidden="true"></a>observedDiff</span></code></pre></div>
<pre><code>## [1] 2.337433</code></pre>
<div class="sourceCode" id="cb555"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb555-1"><a href="exercise-solutions.html#cb555-1" aria-hidden="true"></a><span class="co">#with tapply</span></span>
<span id="cb555-2"><a href="exercise-solutions.html#cb555-2" aria-hidden="true"></a><span class="kw">diff</span>(<span class="kw">as.vector</span>(<span class="kw">tapply</span>(hercules<span class="op">$</span>width,hercules<span class="op">$</span>sex,mean)))</span></code></pre></div>
<pre><code>## [1] 2.337433</code></pre>
<ol start="8" style="list-style-type: decimal">
<li>Use <code>sample</code> to randomise the sex column of the data, and recalculate the difference between the mean.</li>
</ol>
<div class="sourceCode" id="cb557"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb557-1"><a href="exercise-solutions.html#cb557-1" aria-hidden="true"></a><span class="co">#with dplyr</span></span>
<span id="cb557-2"><a href="exercise-solutions.html#cb557-2" aria-hidden="true"></a>hercules <span class="op">%&gt;%</span></span>
<span id="cb557-3"><a href="exercise-solutions.html#cb557-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">sex =</span> <span class="kw">sample</span>(sex)) <span class="op">%&gt;%</span></span>
<span id="cb557-4"><a href="exercise-solutions.html#cb557-4" aria-hidden="true"></a><span class="st">  </span><span class="kw">group_by</span>(sex) <span class="op">%&gt;%</span></span>
<span id="cb557-5"><a href="exercise-solutions.html#cb557-5" aria-hidden="true"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">mean=</span><span class="kw">mean</span>(width)) <span class="op">%&gt;%</span></span>
<span id="cb557-6"><a href="exercise-solutions.html#cb557-6" aria-hidden="true"></a><span class="st">  </span><span class="kw">pull</span>(mean) <span class="op">%&gt;%</span></span>
<span id="cb557-7"><a href="exercise-solutions.html#cb557-7" aria-hidden="true"></a><span class="st">  </span><span class="kw">diff</span>()</span></code></pre></div>
<pre><code>## [1] -0.3453301</code></pre>
<div class="sourceCode" id="cb559"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb559-1"><a href="exercise-solutions.html#cb559-1" aria-hidden="true"></a><span class="co">#with tapply</span></span>
<span id="cb559-2"><a href="exercise-solutions.html#cb559-2" aria-hidden="true"></a><span class="kw">diff</span>(<span class="kw">as.vector</span>(<span class="kw">tapply</span>(hercules<span class="op">$</span>width,<span class="kw">sample</span>(hercules<span class="op">$</span>sex),mean)))</span></code></pre></div>
<pre><code>## [1] -0.9985928</code></pre>
<ol start="9" style="list-style-type: decimal">
<li>Use <code>replicate</code> to repeat this 10 times (to ensure that you code works).</li>
</ol>
<div class="sourceCode" id="cb561"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb561-1"><a href="exercise-solutions.html#cb561-1" aria-hidden="true"></a><span class="co">#with dplyr</span></span>
<span id="cb561-2"><a href="exercise-solutions.html#cb561-2" aria-hidden="true"></a><span class="kw">replicate</span>(<span class="dv">10</span>,</span>
<span id="cb561-3"><a href="exercise-solutions.html#cb561-3" aria-hidden="true"></a>  hercules <span class="op">%&gt;%</span></span>
<span id="cb561-4"><a href="exercise-solutions.html#cb561-4" aria-hidden="true"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">sex =</span> <span class="kw">sample</span>(sex)) <span class="op">%&gt;%</span></span>
<span id="cb561-5"><a href="exercise-solutions.html#cb561-5" aria-hidden="true"></a><span class="st">  </span><span class="kw">group_by</span>(sex) <span class="op">%&gt;%</span></span>
<span id="cb561-6"><a href="exercise-solutions.html#cb561-6" aria-hidden="true"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">mean=</span><span class="kw">mean</span>(width)) <span class="op">%&gt;%</span></span>
<span id="cb561-7"><a href="exercise-solutions.html#cb561-7" aria-hidden="true"></a><span class="st">  </span><span class="kw">pull</span>(mean) <span class="op">%&gt;%</span></span>
<span id="cb561-8"><a href="exercise-solutions.html#cb561-8" aria-hidden="true"></a><span class="st">  </span><span class="kw">diff</span>())</span></code></pre></div>
<pre><code>##  [1]  0.9754196 -1.5436880  0.9368750  1.1783436
##  [5] -0.3889855  1.4915964 -0.5619737  0.4558331
##  [9]  1.9645041 -2.4930715</code></pre>
<div class="sourceCode" id="cb563"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb563-1"><a href="exercise-solutions.html#cb563-1" aria-hidden="true"></a><span class="co">#with tapply</span></span>
<span id="cb563-2"><a href="exercise-solutions.html#cb563-2" aria-hidden="true"></a><span class="kw">replicate</span>(<span class="dv">10</span>,</span>
<span id="cb563-3"><a href="exercise-solutions.html#cb563-3" aria-hidden="true"></a>          <span class="kw">diff</span>(<span class="kw">as.vector</span>(<span class="kw">tapply</span>(hercules<span class="op">$</span>width,<span class="kw">sample</span>(hercules<span class="op">$</span>sex),mean)))</span>
<span id="cb563-4"><a href="exercise-solutions.html#cb563-4" aria-hidden="true"></a>)</span></code></pre></div>
<pre><code>##  [1] -1.7472242 -0.7941490 -0.5730610  0.6233782
##  [5]  1.1559533 -0.7226716  1.1273298 -0.0555329
##  [9] -0.2148079 -0.6044714</code></pre>
<ol start="10" style="list-style-type: decimal">
<li>When your code is working, use <code>replicate</code> again, but this time with 1000 replicates and pass the results into a data frame.</li>
</ol>
<div class="sourceCode" id="cb565"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb565-1"><a href="exercise-solutions.html#cb565-1" aria-hidden="true"></a><span class="co">#with dplyr</span></span>
<span id="cb565-2"><a href="exercise-solutions.html#cb565-2" aria-hidden="true"></a>diffs &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">diffs =</span> </span>
<span id="cb565-3"><a href="exercise-solutions.html#cb565-3" aria-hidden="true"></a>                      <span class="kw">replicate</span>(<span class="dv">1000</span>,</span>
<span id="cb565-4"><a href="exercise-solutions.html#cb565-4" aria-hidden="true"></a>                                hercules <span class="op">%&gt;%</span></span>
<span id="cb565-5"><a href="exercise-solutions.html#cb565-5" aria-hidden="true"></a><span class="st">                                  </span><span class="kw">mutate</span>(<span class="dt">sex =</span> <span class="kw">sample</span>(sex)) <span class="op">%&gt;%</span></span>
<span id="cb565-6"><a href="exercise-solutions.html#cb565-6" aria-hidden="true"></a><span class="st">                                  </span><span class="kw">group_by</span>(sex) <span class="op">%&gt;%</span></span>
<span id="cb565-7"><a href="exercise-solutions.html#cb565-7" aria-hidden="true"></a><span class="st">                                  </span><span class="kw">summarise</span>(<span class="dt">mean=</span><span class="kw">mean</span>(width)) <span class="op">%&gt;%</span></span>
<span id="cb565-8"><a href="exercise-solutions.html#cb565-8" aria-hidden="true"></a><span class="st">                                  </span><span class="kw">pull</span>(mean) <span class="op">%&gt;%</span></span>
<span id="cb565-9"><a href="exercise-solutions.html#cb565-9" aria-hidden="true"></a><span class="st">                                  </span><span class="kw">diff</span>()))</span>
<span id="cb565-10"><a href="exercise-solutions.html#cb565-10" aria-hidden="true"></a></span>
<span id="cb565-11"><a href="exercise-solutions.html#cb565-11" aria-hidden="true"></a><span class="co">#with tapply</span></span>
<span id="cb565-12"><a href="exercise-solutions.html#cb565-12" aria-hidden="true"></a>diffs &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">diffs =</span></span>
<span id="cb565-13"><a href="exercise-solutions.html#cb565-13" aria-hidden="true"></a>                      <span class="kw">replicate</span>(<span class="dv">1000</span>,</span>
<span id="cb565-14"><a href="exercise-solutions.html#cb565-14" aria-hidden="true"></a>                                <span class="kw">diff</span>(<span class="kw">as.vector</span>(</span>
<span id="cb565-15"><a href="exercise-solutions.html#cb565-15" aria-hidden="true"></a>                                  <span class="kw">tapply</span>(hercules<span class="op">$</span>width, <span class="kw">sample</span>(hercules<span class="op">$</span>sex), mean)</span>
<span id="cb565-16"><a href="exercise-solutions.html#cb565-16" aria-hidden="true"></a>                                ))))</span></code></pre></div>
<ol start="11" style="list-style-type: decimal">
<li>Use <code>ggplot</code> to plot the null distribution you have just created, and add the observed difference.</li>
</ol>
<div class="sourceCode" id="cb566"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb566-1"><a href="exercise-solutions.html#cb566-1" aria-hidden="true"></a><span class="kw">ggplot</span>(diffs,<span class="kw">aes</span>(<span class="dt">x=</span>diffs))<span class="op">+</span></span>
<span id="cb566-2"><a href="exercise-solutions.html#cb566-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_histogram</span>() <span class="op">+</span></span>
<span id="cb566-3"><a href="exercise-solutions.html#cb566-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> observedDiff)</span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-435-1.png" width="672" /></p>
<ol start="12" style="list-style-type: decimal">
<li>Obtain the p-value for the hypothesis test described above. (1) how many of the observed differences are greater than or equal to the shuffled differences in the null distribution. (2) what is this expressed as a proportion of the number of replicates.</li>
</ol>
<div class="sourceCode" id="cb567"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb567-1"><a href="exercise-solutions.html#cb567-1" aria-hidden="true"></a><span class="kw">sum</span>(observedDiff<span class="op">&gt;=</span>diffs<span class="op">$</span>diffs)</span></code></pre></div>
<pre><code>## [1] 994</code></pre>
<div class="sourceCode" id="cb569"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb569-1"><a href="exercise-solutions.html#cb569-1" aria-hidden="true"></a><span class="kw">sum</span>(observedDiff<span class="op">&gt;=</span>diffs<span class="op">$</span>diffs)<span class="op">/</span><span class="dv">1000</span></span></code></pre></div>
<pre><code>## [1] 0.994</code></pre>
<ol start="13" style="list-style-type: decimal">
<li>Summarise your result as in a report. Describe the method, followed by the result and conclusion.</li>
</ol>
<p><em>“I used a randomisation test to estimate the significance of the observed difference of 2.337 (mean values: female=17.366; male = 15.028) in mean widths of the sexes. To do this I generated a null distribution of differences between sexes using 1000 replicates. I found that only 994 of the differences in the null distribution were as extreme as the observed difference. Thus the p-value is 0.994: I therefore reject the null hypothesis that there is no difference between the sexes and accept the alternative hypothesis that males are significantly larger than females.”</em></p>

</div>
<div id="exercise-sex-differences-in-fine-motor-skills" class="section level2" number="21.5">
<h2><span class="header-section-number">21.5</span> Exercise: Sex differences in fine motor skills</h2>
<p>Some people have suggested that there might be sex differences in fine motor skills in humans. Use the data collected on the class to address this topic using t-tests. The relevant data set is called <code>classData.csv</code>, and the columns of interest are <code>Gender</code> and <code>Precision</code>.</p>
<p>Carry out a two-sample t-test.</p>
<ol style="list-style-type: decimal">
<li>Plot the data (e.g. with a box plot, or histogram)</li>
</ol>
<div class="sourceCode" id="cb571"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb571-1"><a href="exercise-solutions.html#cb571-1" aria-hidden="true"></a>classData &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;CourseData/classData.csv&quot;</span>)</span>
<span id="cb571-2"><a href="exercise-solutions.html#cb571-2" aria-hidden="true"></a></span>
<span id="cb571-3"><a href="exercise-solutions.html#cb571-3" aria-hidden="true"></a><span class="kw">ggplot</span>(classData,<span class="kw">aes</span>(<span class="dt">x =</span> Gender,<span class="dt">y =</span> Precision))<span class="op">+</span></span>
<span id="cb571-4"><a href="exercise-solutions.html#cb571-4" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_boxplot</span>()<span class="op">+</span></span>
<span id="cb571-5"><a href="exercise-solutions.html#cb571-5" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_jitter</span>(<span class="dt">width =</span> <span class="fl">0.2</span>)</span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-438-1.png" width="672" /></p>
<ol start="2" style="list-style-type: decimal">
<li>Formulate null and alternative hypotheses.</li>
</ol>
<p>Null hypotheses - the differences in precision between male and female are due to chance alone.
Alternative hypothesis - there is a significant difference between male and female precision scores.</p>
<ol start="3" style="list-style-type: decimal">
<li>Use the <code>t.test</code> function to do the test.</li>
</ol>
<div class="sourceCode" id="cb572"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb572-1"><a href="exercise-solutions.html#cb572-1" aria-hidden="true"></a><span class="kw">t.test</span>(Precision<span class="op">~</span>Gender, <span class="dt">data =</span> classData)</span></code></pre></div>
<pre><code>## 
## 	Welch Two Sample t-test
## 
## data:  Precision by Gender
## t = -1.1617, df = 38.347, p-value = 0.2525
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -5.359500  1.450409
## sample estimates:
## mean in group Female   mean in group Male 
##             28.21212             30.16667</code></pre>
<ol start="4" style="list-style-type: decimal">
<li>Write a sentence or two describing the results.</li>
</ol>
<p>There was no significant difference in mean precision between the two genders (t-test: t = -1.16, df = 38.35, p = 0.253). The 95% confidence interval for the difference between genders overlapped 0 (95% CI = -5.359-1.450). I therefore fail to reject the null hypothesis that the observed differences are due to chance alone.</p>
</div>
<div id="exercise-therapy-for-anorexia" class="section level2" number="21.6">
<h2><span class="header-section-number">21.6</span> Exercise: Therapy for anorexia</h2>
<p>A study was carried out looking at the effect of cognitive behavioural therapy on weight of people with anorexia. Weight was measured in week 1 and again in week 8. Use a paired t-test to assess whether the treatment is effective.</p>
<p>The data is called <code>anorexiaCBT.csv</code></p>
<p>The data are in “wide format”. You may wish to convert it to “long format” depending on how you use the data. You can do that with the <code>pivot_longer</code> function, which rearranges the data:</p>
<ol style="list-style-type: decimal">
<li>Plot the data (e.g. with an interaction plot like Figure <a href="comparing-two-means-with-a-t-test.html#fig:toolData">11.2</a>)</li>
</ol>
<div class="sourceCode" id="cb574"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb574-1"><a href="exercise-solutions.html#cb574-1" aria-hidden="true"></a>anorexiaCBT &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;CourseData/anorexiaCBT.csv&quot;</span>,<span class="dt">header=</span><span class="ot">TRUE</span>)</span>
<span id="cb574-2"><a href="exercise-solutions.html#cb574-2" aria-hidden="true"></a></span>
<span id="cb574-3"><a href="exercise-solutions.html#cb574-3" aria-hidden="true"></a>anorexiaCBT_long &lt;-<span class="st"> </span>anorexiaCBT <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb574-4"><a href="exercise-solutions.html#cb574-4" aria-hidden="true"></a><span class="st">  </span><span class="kw">pivot_longer</span>(<span class="dt">cols =</span> <span class="kw">starts_with</span>(<span class="st">&quot;Week&quot;</span>),<span class="dt">names_to =</span> <span class="st">&quot;time&quot;</span>,<span class="dt">values_to =</span> <span class="st">&quot;weight&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb575"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb575-1"><a href="exercise-solutions.html#cb575-1" aria-hidden="true"></a><span class="kw">ggplot</span>(anorexiaCBT_long,<span class="kw">aes</span>(<span class="dt">x=</span>time,<span class="dt">y=</span>weight,<span class="dt">group=</span>Subject)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb575-2"><a href="exercise-solutions.html#cb575-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_line</span>()<span class="op">+</span></span>
<span id="cb575-3"><a href="exercise-solutions.html#cb575-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb575-4"><a href="exercise-solutions.html#cb575-4" aria-hidden="true"></a><span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;Time&quot;</span>) <span class="op">+</span></span>
<span id="cb575-5"><a href="exercise-solutions.html#cb575-5" aria-hidden="true"></a><span class="st">  </span><span class="kw">ylab</span>(<span class="st">&quot;Weight (kg)&quot;</span>)</span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-442-1.png" width="672" /></p>
<ol start="2" style="list-style-type: decimal">
<li>Formulate a null and alternative hypothesis.</li>
</ol>
<p>Null = The difference in weight between the two times is no different than random chance.
Alternative Hypothesis = There is a significant change in weight between the two time points.</p>
<ol start="3" style="list-style-type: decimal">
<li>Use <code>t.test</code> to conduct a <em>paired</em> t-test.</li>
</ol>
<p>The method here depends on whether you use the “long” data or not:</p>
<div class="sourceCode" id="cb576"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb576-1"><a href="exercise-solutions.html#cb576-1" aria-hidden="true"></a><span class="kw">t.test</span>(anorexiaCBT<span class="op">$</span>Week01,anorexiaCBT<span class="op">$</span>Week08,<span class="dt">paired =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## 
## 	Paired t-test
## 
## data:  anorexiaCBT$Week01 and anorexiaCBT$Week08
## t = -2.2156, df = 28, p-value = 0.03502
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -5.7869029 -0.2268902
## sample estimates:
## mean of the differences 
##               -3.006897</code></pre>
<p>or</p>
<div class="sourceCode" id="cb578"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb578-1"><a href="exercise-solutions.html#cb578-1" aria-hidden="true"></a>anorexiaCBT_long &lt;-<span class="st"> </span>anorexiaCBT_long <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb578-2"><a href="exercise-solutions.html#cb578-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">arrange</span>(Subject, time)</span>
<span id="cb578-3"><a href="exercise-solutions.html#cb578-3" aria-hidden="true"></a></span>
<span id="cb578-4"><a href="exercise-solutions.html#cb578-4" aria-hidden="true"></a><span class="kw">t.test</span>(weight <span class="op">~</span><span class="st"> </span>time, <span class="dt">data =</span> anorexiaCBT_long, <span class="dt">paired =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## 
## 	Paired t-test
## 
## data:  weight by time
## t = -2.2156, df = 28, p-value = 0.03502
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -5.7869029 -0.2268902
## sample estimates:
## mean of the differences 
##               -3.006897</code></pre>
<ol start="4" style="list-style-type: decimal">
<li>Write a couple of sentences to report your result.</li>
</ol>
<div class="sourceCode" id="cb580"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb580-1"><a href="exercise-solutions.html#cb580-1" aria-hidden="true"></a>x &lt;-<span class="st"> </span><span class="kw">t.test</span>(anorexiaCBT<span class="op">$</span>Week01,anorexiaCBT<span class="op">$</span>Week08,<span class="dt">paired =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<p>There was a significant difference in weight of -3.007kg between week 1 and week 8 (t.test: t = -2.22, df = 28.00, p = 0.035). The 95% confidence interval for the difference between weeks was between -5.787 and -0.227. Therefore, I reject the null hypotheses, that the difference is due to chance alone, and accept the alternative hypothesis.</p>
</div>
<div id="exercise-compare-t-tests-with-randomisation-tests" class="section level2" number="21.7">
<h2><span class="header-section-number">21.7</span> Exercise: Compare t-tests with randomisation tests</h2>
<div class="do-something">
<ol style="list-style-type: decimal">
<li>
Try re-fitting some of these tests as randomisation tests (or analyse the randomisation test data using <code>t.test</code>). Do they give the same results?
</li>
</ol>
<p>
They should give approximately the same results.
</p>
<ol start="2" style="list-style-type: decimal">
<li>
Try answering the question - “<em>are people who prefer dogs taller than those who prefer cats?</em>” using the <code>classData.csv</code>. Can you think of any problems with this analysis?
</li>
</ol>
</div>
<p>The problem with the analysis is that it is “confounded”. That is to say, gender is correlated with height, so you would not be sure whether any difference you found would be due to height, or gender.</p>

</div>
<div id="exercise-solutions-apple-tree-crop-yield" class="section level2" number="21.8">
<h2><span class="header-section-number">21.8</span> Exercise Solutions: Apple tree crop yield</h2>
<p>Import the data (<code>apples.csv</code>) and analyse it using the techniques you have learned in the ANOVA lecture, and the previous worksheet, to answer the question “What is the effect of tree spacing on apple yields?”</p>
<ol style="list-style-type: decimal">
<li>Import and look at the data (e.g. <code>summary</code> or <code>str</code> or <code>head</code>)</li>
</ol>
<div class="sourceCode" id="cb581"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb581-1"><a href="exercise-solutions.html#cb581-1" aria-hidden="true"></a>apples &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;CourseData/apples.csv&quot;</span>)</span>
<span id="cb581-2"><a href="exercise-solutions.html#cb581-2" aria-hidden="true"></a><span class="kw">summary</span>(apples)</span></code></pre></div>
<pre><code>##     spacing       yield      
##  Min.   : 6   Min.   : 64.1  
##  1st Qu.: 6   1st Qu.:108.2  
##  Median :10   Median :147.1  
##  Mean   :10   Mean   :145.4  
##  3rd Qu.:14   3rd Qu.:176.5  
##  Max.   :14   Max.   :282.3  
##               NA&#39;s   :28</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Ensure that the explanatory variable (<code>spacing</code>) is defined as a categorical variable (i.e. a “factor”, in R-speak). You can use <code>mutate</code> and <code>as.factor</code> functions for this.</li>
</ol>
<div class="sourceCode" id="cb583"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb583-1"><a href="exercise-solutions.html#cb583-1" aria-hidden="true"></a>apples &lt;-<span class="st"> </span>apples <span class="op">%&gt;%</span></span>
<span id="cb583-2"><a href="exercise-solutions.html#cb583-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">spacing =</span> <span class="kw">as.factor</span>(spacing))</span></code></pre></div>
<ol start="3" style="list-style-type: decimal">
<li>Plot the data using <code>ggplot</code> (a box plot with (optionally) added jittered points would be good).</li>
</ol>
<div class="sourceCode" id="cb584"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb584-1"><a href="exercise-solutions.html#cb584-1" aria-hidden="true"></a><span class="kw">ggplot</span>(apples,<span class="kw">aes</span>(<span class="dt">x =</span> spacing,<span class="dt">y =</span> yield)) <span class="op">+</span></span>
<span id="cb584-2"><a href="exercise-solutions.html#cb584-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_boxplot</span>() <span class="op">+</span><span class="st"> </span></span>
<span id="cb584-3"><a href="exercise-solutions.html#cb584-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_jitter</span>(<span class="dt">width=</span><span class="fl">0.2</span>) <span class="op">+</span></span>
<span id="cb584-4"><a href="exercise-solutions.html#cb584-4" aria-hidden="true"></a><span class="st">  </span><span class="kw">ylab</span>(<span class="st">&quot;Yield (kg per tree)&quot;</span>)</span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-450-1.png" width="672" /></p>
<ol start="4" style="list-style-type: decimal">
<li>Fit an ANOVA model using <code>lm</code>.</li>
</ol>
<div class="sourceCode" id="cb585"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb585-1"><a href="exercise-solutions.html#cb585-1" aria-hidden="true"></a>apple_mod &lt;-<span class="st"> </span><span class="kw">lm</span>(yield<span class="op">~</span>spacing,<span class="dt">data =</span> apples)</span></code></pre></div>
<ol start="5" style="list-style-type: decimal">
<li>Check the model using a diagnostic plot (i.e. using <code>autoplot</code> from the <code>ggfortify</code> package).</li>
</ol>
<div class="sourceCode" id="cb586"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb586-1"><a href="exercise-solutions.html#cb586-1" aria-hidden="true"></a><span class="kw">library</span>(ggfortify)</span>
<span id="cb586-2"><a href="exercise-solutions.html#cb586-2" aria-hidden="true"></a><span class="kw">autoplot</span>(apple_mod)</span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-452-1.png" width="672" /></p>
<ol start="6" style="list-style-type: decimal">
<li>Use <code>anova</code> to get the ANOVA summary.</li>
</ol>
<div class="sourceCode" id="cb587"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb587-1"><a href="exercise-solutions.html#cb587-1" aria-hidden="true"></a><span class="kw">anova</span>(apple_mod)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: yield
##           Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## spacing    2  35801 17900.3  9.3851 0.0002003 ***
## Residuals 89 169750  1907.3                      
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<ol start="7" style="list-style-type: decimal">
<li>You should see that there are differences among treatments. But where are those differences? Use <code>summary</code> on your model to find out.</li>
</ol>
<div class="sourceCode" id="cb589"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb589-1"><a href="exercise-solutions.html#cb589-1" aria-hidden="true"></a><span class="kw">summary</span>(apple_mod)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = yield ~ spacing, data = apples)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -92.389 -30.577  -3.516  33.192 117.628 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)  120.566      7.382  16.332  &lt; 2e-16
## spacing10     35.924     11.073   3.244 0.001659
## spacing14     44.107     10.966   4.022 0.000121
##                
## (Intercept) ***
## spacing10   ** 
## spacing14   ***
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 43.67 on 89 degrees of freedom
##   (28 observations deleted due to missingness)
## Multiple R-squared:  0.1742,	Adjusted R-squared:  0.1556 
## F-statistic: 9.385 on 2 and 89 DF,  p-value: 0.0002003</code></pre>
<ol start="8" style="list-style-type: decimal">
<li>Use a Tukey test to make all the pairwise comparisons among the treatments.</li>
</ol>
<div class="sourceCode" id="cb591"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb591-1"><a href="exercise-solutions.html#cb591-1" aria-hidden="true"></a><span class="kw">library</span>(agricolae)</span>
<span id="cb591-2"><a href="exercise-solutions.html#cb591-2" aria-hidden="true"></a><span class="kw">HSD.test</span>(apple_mod,<span class="st">&quot;spacing&quot;</span>,<span class="dt">console=</span><span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## 
## Study: apple_mod ~ &quot;spacing&quot;
## 
## HSD Test for yield 
## 
## Mean Square Error:  1907.304 
## 
## spacing,  means
## 
##       yield      std  r  Min   Max
## 10 156.4893 45.60411 28 64.1 248.6
## 14 164.6724 50.41401 29 72.3 282.3
## 6  120.5657 35.32755 35 66.4 185.5
## 
## Alpha: 0.05 ; DF Error: 89 
## Critical Value of Studentized Range: 3.370849 
## 
## Groups according to probability of means differences and alpha level( 0.05 )
## 
## Treatments with the same letter are not significantly different.
## 
##       yield groups
## 14 164.6724      a
## 10 156.4893      a
## 6  120.5657      b</code></pre>
<ol start="9" style="list-style-type: decimal">
<li>Write a few sentences that summarise your findings. What biological processes do you think drive the effects that you have detected?</li>
</ol>
<p><em>There was a significant effect of spacing on apple yields (Figure XX, ANOVA: F = 9.385, d.f. = 2 and 89, p = 0.0002). </em></p>
<p>Then: <em>The pairwise comparisons in the ANOVA model showed that means of the 6 and 10 foot spacing treatment were significantly different (t= 3.244, p = 0.0017), as were those of 6 and 14 (t=4.022, p = 0.0001), but the 10 foot - 14 foot comparison showed no significant difference (t= 0.707, p= 0.4813)<a href="#fn17" class="footnote-ref" id="fnref17"><sup>17</sup></a>.</em></p>
<p>Or, more simply: <em>The 6-10ft and 6-14ft comparisons showed signifcant differences (Tukey HSD: p&lt;0.05), but the 10-14ft comparison showed no significant difference (Tukey HSD: p&gt;0.05)</em></p>
<ol start="10" style="list-style-type: decimal">
<li>Optional. Instead of using a Tukey test, use the alternative “relevel” approach to make the missing comparison.</li>
</ol>
<div class="sourceCode" id="cb593"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb593-1"><a href="exercise-solutions.html#cb593-1" aria-hidden="true"></a>apples2 &lt;-<span class="st"> </span>apples <span class="op">%&gt;%</span></span>
<span id="cb593-2"><a href="exercise-solutions.html#cb593-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">spacing =</span> <span class="kw">relevel</span>(spacing,<span class="dt">ref =</span> <span class="st">&quot;10&quot;</span>))</span>
<span id="cb593-3"><a href="exercise-solutions.html#cb593-3" aria-hidden="true"></a>apple_mod2 &lt;-<span class="st"> </span><span class="kw">lm</span>(yield<span class="op">~</span>spacing,<span class="dt">data =</span> apples2)</span>
<span id="cb593-4"><a href="exercise-solutions.html#cb593-4" aria-hidden="true"></a><span class="kw">summary</span>(apple_mod2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = yield ~ spacing, data = apples2)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -92.389 -30.577  -3.516  33.192 117.628 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)  156.489      8.253  18.961  &lt; 2e-16
## spacing6     -35.924     11.073  -3.244  0.00166
## spacing14      8.183     11.571   0.707  0.48128
##                
## (Intercept) ***
## spacing6    ** 
## spacing14      
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 43.67 on 89 degrees of freedom
##   (28 observations deleted due to missingness)
## Multiple R-squared:  0.1742,	Adjusted R-squared:  0.1556 
## F-statistic: 9.385 on 2 and 89 DF,  p-value: 0.0002003</code></pre>
<hr />
<p>If you get this far, try using the ANOVA approach on one of the previous t-test examples (remember that ANOVA can be used when your single explanatory variable has TWO or more levels). You should notice that the results are the same whether you use the <code>t.test</code> function or the ANOVA approach with <code>lm</code>.</p>

</div>
<div id="exercise-solutions-chirping-crickets" class="section level2" number="21.9">
<h2><span class="header-section-number">21.9</span> Exercise Solutions: Chirping crickets</h2>
<ol style="list-style-type: decimal">
<li>Import the data</li>
</ol>
<div class="sourceCode" id="cb595"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb595-1"><a href="exercise-solutions.html#cb595-1" aria-hidden="true"></a>chirps &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;CourseData/chirps.csv&quot;</span>)</span></code></pre></div>
<ol start="2" style="list-style-type: decimal">
<li>Use <code>mutate</code> to convert Fahrenheit to Celsius (Google it)</li>
</ol>
<div class="sourceCode" id="cb596"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb596-1"><a href="exercise-solutions.html#cb596-1" aria-hidden="true"></a>chirps &lt;-<span class="st"> </span>chirps <span class="op">%&gt;%</span></span>
<span id="cb596-2"><a href="exercise-solutions.html#cb596-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">temperatureC =</span> (temperature<span class="dv">-32</span>)<span class="op">*</span>(<span class="dv">5</span><span class="op">/</span><span class="dv">9</span>))</span>
<span id="cb596-3"><a href="exercise-solutions.html#cb596-3" aria-hidden="true"></a><span class="kw">head</span>(chirps)</span></code></pre></div>
<pre><code>##   chirps temperature temperatureC
## 1   20.0        88.6     31.44444
## 2   16.0        71.6     22.00000
## 3   19.8        93.3     34.05556
## 4   18.4        84.3     29.05556
## 5   17.1        80.6     27.00000
## 6   15.5        75.2     24.00000</code></pre>
<ol start="3" style="list-style-type: decimal">
<li>Plot the data</li>
</ol>
<div class="sourceCode" id="cb598"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb598-1"><a href="exercise-solutions.html#cb598-1" aria-hidden="true"></a>(A&lt;-<span class="kw">ggplot</span>(chirps,<span class="kw">aes</span>(<span class="dt">x=</span> temperatureC,<span class="dt">y =</span> chirps)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb598-2"><a href="exercise-solutions.html#cb598-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_point</span>())</span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-461-1.png" width="672" /></p>
<ol start="4" style="list-style-type: decimal">
<li>Fit a linear regression model with <code>lm</code></li>
</ol>
<div class="sourceCode" id="cb599"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb599-1"><a href="exercise-solutions.html#cb599-1" aria-hidden="true"></a>chirp_mod &lt;-<span class="st"> </span><span class="kw">lm</span>(chirps <span class="op">~</span><span class="st"> </span>temperatureC, <span class="dt">data =</span> chirps)</span></code></pre></div>
<ol start="5" style="list-style-type: decimal">
<li>Look at diagnostic plots to evaluate the model</li>
</ol>
<div class="sourceCode" id="cb600"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb600-1"><a href="exercise-solutions.html#cb600-1" aria-hidden="true"></a><span class="kw">library</span>(ggfortify)</span>
<span id="cb600-2"><a href="exercise-solutions.html#cb600-2" aria-hidden="true"></a><span class="kw">autoplot</span>(chirp_mod)</span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-463-1.png" width="672" /></p>
<ol start="6" style="list-style-type: decimal">
<li>Use <code>anova</code> to figure out if the effect of temperature is statistically significant.</li>
</ol>
<div class="sourceCode" id="cb601"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb601-1"><a href="exercise-solutions.html#cb601-1" aria-hidden="true"></a><span class="kw">anova</span>(chirp_mod)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: chirps
##              Df Sum Sq Mean Sq F value    Pr(&gt;F)
## temperatureC  1 28.435 28.4348  29.248 0.0001195
## Residuals    13 12.639  0.9722                  
##                 
## temperatureC ***
## Residuals       
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<ol start="7" style="list-style-type: decimal">
<li>Use <code>summary</code> to obtain information about the coefficients and <span class="math inline">\(R^2\)</span>-value.</li>
</ol>
<div class="sourceCode" id="cb603"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb603-1"><a href="exercise-solutions.html#cb603-1" aria-hidden="true"></a><span class="kw">summary</span>(chirp_mod)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = chirps ~ temperatureC, data = chirps)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1.6181 -0.6154  0.0916  0.7669  1.5549 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)   6.95531    1.79534   3.874 0.001918
## temperatureC  0.36540    0.06756   5.408 0.000119
##                 
## (Intercept)  ** 
## temperatureC ***
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.986 on 13 degrees of freedom
## Multiple R-squared:  0.6923,	Adjusted R-squared:  0.6686 
## F-statistic: 29.25 on 1 and 13 DF,  p-value: 0.0001195</code></pre>
<ol start="8" style="list-style-type: decimal">
<li>Summarise the model in words.</li>
</ol>
<p><em>There is a statistically significant association between temperature and chirp frequency (F = 29.2482, d.f. = 1,13, p &lt; 0.001) The equation of the fitted model is: Chirp Freq = 6.96(<span class="math inline">\(\pm\)</span> 1.80) <span class="math inline">\(\times\)</span> Temp + 0.37(<span class="math inline">\(\pm\)</span> 0.07). The model explains 69% of the variation in chirp frequency (<span class="math inline">\(R^2\)</span> = 0.692).</em></p>
<ol start="9" style="list-style-type: decimal">
<li>Add model fit line to the plot.</li>
</ol>
<div class="sourceCode" id="cb605"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb605-1"><a href="exercise-solutions.html#cb605-1" aria-hidden="true"></a>A <span class="op">+</span><span class="st"> </span><span class="kw">geom_smooth</span>(<span class="dt">method=</span><span class="st">&quot;lm&quot;</span>)</span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-466-1.png" width="672" /></p>
<ol start="10" style="list-style-type: decimal">
<li>Can I use cricket chirp frequency as a kind of thermometer?</li>
</ol>
<p>Yes, using the equation from the model</p>

</div>
<div id="exercise-solutions-fish-behaviour" class="section level2" number="21.10">
<h2><span class="header-section-number">21.10</span> Exercise Solutions: Fish behaviour</h2>
<ol style="list-style-type: decimal">
<li>Import the data set, <code>fishPersonality.csv</code></li>
</ol>
<div class="sourceCode" id="cb606"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb606-1"><a href="exercise-solutions.html#cb606-1" aria-hidden="true"></a>fishPersonality &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;CourseData/fishPersonality.csv&quot;</span>)</span></code></pre></div>
<ol start="2" style="list-style-type: decimal">
<li>Plot the data (e.g. as a box plot)</li>
</ol>
<div class="sourceCode" id="cb607"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb607-1"><a href="exercise-solutions.html#cb607-1" aria-hidden="true"></a><span class="kw">ggplot</span>(fishPersonality,<span class="kw">aes</span>(<span class="dt">x =</span> colouration,<span class="dt">y =</span> spawning,<span class="dt">fill=</span>personality))<span class="op">+</span></span>
<span id="cb607-2"><a href="exercise-solutions.html#cb607-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_boxplot</span>()</span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-469-1.png" width="672" /></p>
<ol start="3" style="list-style-type: decimal">
<li>Fit an ANOVA model using <code>lm</code>.</li>
</ol>
<div class="sourceCode" id="cb608"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb608-1"><a href="exercise-solutions.html#cb608-1" aria-hidden="true"></a>mod_A &lt;-<span class="st"> </span><span class="kw">lm</span>(spawning <span class="op">~</span><span class="st"> </span>personality<span class="op">+</span>colouration <span class="op">+</span><span class="st"> </span>personality<span class="op">:</span>colouration,</span>
<span id="cb608-2"><a href="exercise-solutions.html#cb608-2" aria-hidden="true"></a>            <span class="dt">data =</span> fishPersonality)</span></code></pre></div>
<ol start="4" style="list-style-type: decimal">
<li><p>Look at diagnostic plots from this model (<code>autoplot</code>)</p></li>
<li><p>Use <code>anova</code> to get an Analysis of Variance summary table, and interpret the results.</p></li>
</ol>
<div class="sourceCode" id="cb609"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb609-1"><a href="exercise-solutions.html#cb609-1" aria-hidden="true"></a><span class="kw">anova</span>(mod_A)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: spawning
##                         Df Sum Sq Mean Sq F value
## personality              1   7781    7781  5.5032
## colouration              1  55862   55862 39.5074
## personality:colouration  1   4118    4118  2.9123
## Residuals               28  39591    1414        
##                            Pr(&gt;F)    
## personality               0.02629 *  
## colouration             8.519e-07 ***
## personality:colouration   0.09898 .  
## Residuals                            
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<ol start="6" style="list-style-type: decimal">
<li>Get the coefficient summary (<code>summary</code>) and interpret the output.</li>
</ol>
<div class="sourceCode" id="cb611"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb611-1"><a href="exercise-solutions.html#cb611-1" aria-hidden="true"></a><span class="kw">summary</span>(mod_A)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = spawning ~ personality + colouration + personality:colouration, 
##     data = fishPersonality)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -61.625 -23.344  -5.375  26.313  60.125 
## 
## Coefficients:
##                                           Estimate
## (Intercept)                                 218.50
## personalityReactive                         -53.88
## colourationHomogenous                        60.87
## personalityReactive:colourationHomogenous    45.38
##                                           Std. Error
## (Intercept)                                    13.29
## personalityReactive                            18.80
## colourationHomogenous                          18.80
## personalityReactive:colourationHomogenous      26.59
##                                           t value
## (Intercept)                                16.435
## personalityReactive                        -2.865
## colourationHomogenous                       3.238
## personalityReactive:colourationHomogenous   1.707
##                                           Pr(&gt;|t|)
## (Intercept)                                6.5e-16
## personalityReactive                        0.00781
## colourationHomogenous                      0.00309
## personalityReactive:colourationHomogenous  0.09898
##                                              
## (Intercept)                               ***
## personalityReactive                       ** 
## colourationHomogenous                     ** 
## personalityReactive:colourationHomogenous .  
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 37.6 on 28 degrees of freedom
## Multiple R-squared:  0.6312,	Adjusted R-squared:  0.5917 
## F-statistic: 15.97 on 3 and 28 DF,  p-value: 3.021e-06</code></pre>
<ol start="7" style="list-style-type: decimal">
<li>Do post-hoc Tukey tests (e.g. using <code>HSD.test</code> from the <code>agricolae</code> package). Interpret the results.</li>
</ol>
<div class="sourceCode" id="cb613"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb613-1"><a href="exercise-solutions.html#cb613-1" aria-hidden="true"></a><span class="kw">library</span>(agricolae)</span>
<span id="cb613-2"><a href="exercise-solutions.html#cb613-2" aria-hidden="true"></a><span class="kw">HSD.test</span>(mod_A, <span class="kw">c</span>(<span class="st">&quot;personality&quot;</span>,<span class="st">&quot;colouration&quot;</span>), <span class="dt">console=</span><span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## 
## Study: mod_A ~ c(&quot;personality&quot;, &quot;colouration&quot;)
## 
## HSD Test for spawning 
## 
## Mean Square Error:  1413.951 
## 
## personality:colouration,  means
## 
##                        spawning      std r Min Max
## Proactive:Heterogenous  218.500 34.92850 8 161 268
## Proactive:Homogenous    279.375 40.40133 8 219 339
## Reactive:Heterogenous   164.625 39.86383 8 103 220
## Reactive:Homogenous     270.875 34.84840 8 233 331
## 
## Alpha: 0.05 ; DF Error: 28 
## Critical Value of Studentized Range: 3.861244 
## 
## Minimun Significant Difference: 51.33332 
## 
## Treatments with the same letter are not significantly different.
## 
##                        spawning groups
## Proactive:Homogenous    279.375      a
## Reactive:Homogenous     270.875      a
## Proactive:Heterogenous  218.500      b
## Reactive:Heterogenous   164.625      c</code></pre>
<ol start="8" style="list-style-type: decimal">
<li>Sum up your findings with reference to the initial research questions.</li>
</ol>
<ul>
<li>Homogenous coloured fish seem to do better than heterogenous ones overall (from the plot)</li>
<li>The anova table shows that personality, colouration and the interaction between them are all important variables (p &lt;0.05); Personality seems to be more important than colouration overall (based on p-values)</li>
<li>The Tukey test table shows that - (1) Personality is associated with spawning, but only for heterogenous coloured fish. (2) In the heterogenous coloured fish the proactive fish spawn significantly more than the reactive ones. (3) In the homogenous coloured fish there is no significant difference between the personalities.</li>
</ul>

</div>
<div id="exercise-solutions-maze-runner" class="section level2" number="21.11">
<h2><span class="header-section-number">21.11</span> Exercise Solutions: Maze runner</h2>
<ol style="list-style-type: decimal">
<li>Import the data and graph it (<code>geom_boxplot</code>). Try adding the points to the <code>ggplot</code> using the new (to you) function <code>geom_dotplot(binaxis = "y", stackdir = "center")</code>.</li>
</ol>
<div class="sourceCode" id="cb615"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb615-1"><a href="exercise-solutions.html#cb615-1" aria-hidden="true"></a>maze &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;CourseData/maze.csv&quot;</span>, <span class="dt">stringsAsFactors =</span> <span class="ot">TRUE</span>)</span>
<span id="cb615-2"><a href="exercise-solutions.html#cb615-2" aria-hidden="true"></a><span class="kw">head</span>(maze)</span></code></pre></div>
<pre><code>##     Age nErrors
## 1 Child       2
## 2 Child       4
## 3 Child       2
## 4 Child       5
## 5 Child       6
## 6 Child       0</code></pre>
<div class="sourceCode" id="cb617"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb617-1"><a href="exercise-solutions.html#cb617-1" aria-hidden="true"></a>(A&lt;-<span class="kw">ggplot</span>(maze,<span class="kw">aes</span>(<span class="dt">x =</span> Age,<span class="dt">y =</span> nErrors)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb617-2"><a href="exercise-solutions.html#cb617-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_boxplot</span>() <span class="op">+</span><span class="st"> </span></span>
<span id="cb617-3"><a href="exercise-solutions.html#cb617-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_dotplot</span>(<span class="dt">binaxis =</span> <span class="st">&quot;y&quot;</span>, <span class="dt">stackdir =</span> <span class="st">&quot;center&quot;</span>))</span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-475-1.png" width="672" /></p>
<ol start="2" style="list-style-type: decimal">
<li>Fit an appropriate GLM.</li>
</ol>
<div class="sourceCode" id="cb618"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb618-1"><a href="exercise-solutions.html#cb618-1" aria-hidden="true"></a>mod_A&lt;-<span class="kw">glm</span>(nErrors<span class="op">~</span>Age,<span class="dt">data =</span> maze,<span class="dt">family =</span> poisson)</span></code></pre></div>
<ol start="3" style="list-style-type: decimal">
<li>Examine the diagnostic plots of the model (<code>autoplot</code>).</li>
</ol>
<div class="sourceCode" id="cb619"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb619-1"><a href="exercise-solutions.html#cb619-1" aria-hidden="true"></a><span class="kw">library</span>(ggfortify)</span>
<span id="cb619-2"><a href="exercise-solutions.html#cb619-2" aria-hidden="true"></a><span class="kw">autoplot</span>(mod_A)</span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-477-1.png" width="672" /></p>
<ol start="4" style="list-style-type: decimal">
<li>Get the analysis of variance (deviance) table (<code>anova</code>). What does this tell you?</li>
</ol>
<div class="sourceCode" id="cb620"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb620-1"><a href="exercise-solutions.html#cb620-1" aria-hidden="true"></a><span class="kw">anova</span>(mod_A,<span class="dt">test=</span><span class="st">&quot;Chi&quot;</span>)</span></code></pre></div>
<pre><code>## Analysis of Deviance Table
## 
## Model: poisson, link: log
## 
## Response: nErrors
## 
## Terms added sequentially (first to last)
## 
## 
##      Df Deviance Resid. Df Resid. Dev  Pr(&gt;Chi)    
## NULL                    19     36.672              
## Age   1   11.511        18     25.161 0.0006917 ***
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<ol start="5" style="list-style-type: decimal">
<li>Obtain the <code>summary</code> table. What does this tell you?</li>
</ol>
<div class="sourceCode" id="cb622"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb622-1"><a href="exercise-solutions.html#cb622-1" aria-hidden="true"></a><span class="kw">summary</span>(mod_A)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = nErrors ~ Age, family = poisson, data = maze)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.5690  -0.9503  -0.1323   0.7940   1.4899  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)   
## (Intercept)  0.09531    0.30151   0.316   0.7519   
## AgeChild     1.09861    0.34815   3.156   0.0016 **
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 36.672  on 19  degrees of freedom
## Residual deviance: 25.161  on 18  degrees of freedom
## AIC: 71.845
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<ol start="6" style="list-style-type: decimal">
<li>Use the coefficient information in the <code>summary</code> table to get the model predictions for average number of mistakes (plus/minus 95% Confidence interval). Remember that (i) the model summary is on the scale of the linear predictor, and (ii) the 95% CI can be calculated as 1.96 times the standard error. You can do these calculations “by hand”, or using the <code>predict</code> function. Ask for help if you get stuck.</li>
</ol>
<div class="sourceCode" id="cb624"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb624-1"><a href="exercise-solutions.html#cb624-1" aria-hidden="true"></a>newData &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">Age =</span> <span class="kw">c</span>(<span class="st">&quot;Child&quot;</span>,<span class="st">&quot;Adult&quot;</span>))</span>
<span id="cb624-2"><a href="exercise-solutions.html#cb624-2" aria-hidden="true"></a>pv &lt;-<span class="st"> </span><span class="kw">predict</span>(mod_A,newData,<span class="dt">se.fit =</span> <span class="ot">TRUE</span>)</span>
<span id="cb624-3"><a href="exercise-solutions.html#cb624-3" aria-hidden="true"></a></span>
<span id="cb624-4"><a href="exercise-solutions.html#cb624-4" aria-hidden="true"></a>newData &lt;-<span class="st"> </span>newData <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb624-5"><a href="exercise-solutions.html#cb624-5" aria-hidden="true"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">nErrors_LP =</span> pv<span class="op">$</span>fit) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb624-6"><a href="exercise-solutions.html#cb624-6" aria-hidden="true"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">lowerCI_LP =</span> pv<span class="op">$</span>fit <span class="op">-</span><span class="st"> </span><span class="fl">1.96</span><span class="op">*</span>pv<span class="op">$</span>se.fit) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb624-7"><a href="exercise-solutions.html#cb624-7" aria-hidden="true"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">upperCI_LP =</span> pv<span class="op">$</span>fit <span class="op">+</span><span class="st"> </span><span class="fl">1.96</span><span class="op">*</span>pv<span class="op">$</span>se.fit) </span>
<span id="cb624-8"><a href="exercise-solutions.html#cb624-8" aria-hidden="true"></a></span>
<span id="cb624-9"><a href="exercise-solutions.html#cb624-9" aria-hidden="true"></a>inverseFunction &lt;-<span class="st"> </span><span class="kw">family</span>(mod_A)<span class="op">$</span>linkinv</span>
<span id="cb624-10"><a href="exercise-solutions.html#cb624-10" aria-hidden="true"></a></span>
<span id="cb624-11"><a href="exercise-solutions.html#cb624-11" aria-hidden="true"></a>newData &lt;-<span class="st"> </span>newData <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb624-12"><a href="exercise-solutions.html#cb624-12" aria-hidden="true"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">nErrors =</span> <span class="kw">inverseFunction</span>(nErrors_LP)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb624-13"><a href="exercise-solutions.html#cb624-13" aria-hidden="true"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">lowerCI =</span> <span class="kw">inverseFunction</span>(lowerCI_LP)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb624-14"><a href="exercise-solutions.html#cb624-14" aria-hidden="true"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">upperCI =</span> <span class="kw">inverseFunction</span>(upperCI_LP)) </span>
<span id="cb624-15"><a href="exercise-solutions.html#cb624-15" aria-hidden="true"></a>  </span>
<span id="cb624-16"><a href="exercise-solutions.html#cb624-16" aria-hidden="true"></a></span>
<span id="cb624-17"><a href="exercise-solutions.html#cb624-17" aria-hidden="true"></a>A <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>(<span class="dt">data =</span> newData,<span class="kw">aes</span>(<span class="dt">x =</span> Age,<span class="dt">y =</span> nErrors),<span class="dt">colour=</span><span class="st">&quot;red&quot;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb624-18"><a href="exercise-solutions.html#cb624-18" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_segment</span>(<span class="dt">data =</span> newData,<span class="kw">aes</span>(<span class="dt">x=</span>Age,<span class="dt">xend=</span>Age,<span class="dt">y=</span>lowerCI,<span class="dt">yend=</span>upperCI),<span class="dt">colour=</span><span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-480-1.png" width="672" /></p>

</div>
<div id="exercise-solutions-snails-on-the-move" class="section level2" number="21.12">
<h2><span class="header-section-number">21.12</span> Exercise Solutions: Snails on the move</h2>
<p>Simulate a t-test-based analysis in R to figure out what sample size would result in 80% power.</p>
<div class="sourceCode" id="cb625"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb625-1"><a href="exercise-solutions.html#cb625-1" aria-hidden="true"></a>sampleSize &lt;-<span class="st"> </span><span class="dv">40</span> <span class="co">#vary this until power &gt; 0.8</span></span>
<span id="cb625-2"><a href="exercise-solutions.html#cb625-2" aria-hidden="true"></a>result &lt;-<span class="st"> </span><span class="kw">replicate</span>(<span class="dv">1000</span>,</span>
<span id="cb625-3"><a href="exercise-solutions.html#cb625-3" aria-hidden="true"></a>          <span class="kw">t.test</span>(<span class="kw">rnorm</span>(sampleSize,<span class="dt">mean  =</span> <span class="fl">7.4</span>,<span class="dt">sd =</span> <span class="fl">2.76</span>), </span>
<span id="cb625-4"><a href="exercise-solutions.html#cb625-4" aria-hidden="true"></a>                 <span class="kw">rnorm</span>(sampleSize,<span class="dt">mean  =</span> <span class="fl">7.4</span><span class="op">*</span><span class="fl">1.25</span>,<span class="dt">sd =</span> <span class="fl">2.76</span>))<span class="op">$</span>p.value)</span>
<span id="cb625-5"><a href="exercise-solutions.html#cb625-5" aria-hidden="true"></a><span class="kw">sum</span>(result<span class="op">&lt;</span><span class="fl">0.05</span>)<span class="op">/</span><span class="dv">1000</span></span></code></pre></div>
<pre><code>## [1] 0.83</code></pre>
<p>You should find that you need a sample size of about 40 per group.</p>
</div>
<div id="exercise-solutions-mouse-lemur-strength" class="section level2" number="21.13">
<h2><span class="header-section-number">21.13</span> Exercise Solutions: Mouse lemur strength</h2>
<p>What difference in strength could you reliably detect (with power &gt;80%) with these sample sizes?</p>
<div class="sourceCode" id="cb627"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb627-1"><a href="exercise-solutions.html#cb627-1" aria-hidden="true"></a>diff &lt;-<span class="st"> </span><span class="dv">185</span> <span class="co">#Vary this to give a difference to the 2nd group in the t-test</span></span>
<span id="cb627-2"><a href="exercise-solutions.html#cb627-2" aria-hidden="true"></a>result &lt;-<span class="st"> </span><span class="kw">replicate</span>(<span class="dv">1000</span>,</span>
<span id="cb627-3"><a href="exercise-solutions.html#cb627-3" aria-hidden="true"></a>          <span class="kw">t.test</span>(<span class="kw">rnorm</span>(<span class="dv">25</span>,<span class="dt">mean  =</span> <span class="dv">600</span>,<span class="dt">sd =</span> <span class="dv">145</span>), </span>
<span id="cb627-4"><a href="exercise-solutions.html#cb627-4" aria-hidden="true"></a>                 <span class="kw">rnorm</span>(<span class="dv">8</span>,<span class="dt">mean  =</span> <span class="dv">600</span><span class="op">-</span>diff,<span class="dt">sd =</span> <span class="dv">145</span>))<span class="op">$</span>p.value)</span>
<span id="cb627-5"><a href="exercise-solutions.html#cb627-5" aria-hidden="true"></a><span class="kw">sum</span>(result<span class="op">&lt;</span><span class="fl">0.05</span>)<span class="op">/</span><span class="dv">1000</span></span></code></pre></div>
<pre><code>## [1] 0.812</code></pre>
<p>You should find that you could detect a difference of about 185g or a mean for old animals of 415g which is 70% of the young animals i.e. a 30% reduction.</p>

</div>
</div>






















<div class="footnotes">
<hr />
<ol start="17">
<li id="fn17"><p>These values come from the <code>summary</code> tables for the ANOVA model, and the releveled ANOVA model<a href="exercise-solutions.html#fnref17" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="exam-2020.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/jonesor/BB852_Book/edit/master/6_1_00-AllSolutions.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["BB852.pdf"],
"toc": {
"collapse": "section"
},
"split_by": "section"
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
