<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 18 Extending use cases of GLM | BB852 - Data handling, visualisation and statistics</title>
  <meta name="description" content="Course book for BB852 at the Biology Department, University of Southern Denmark" />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 18 Extending use cases of GLM | BB852 - Data handling, visualisation and statistics" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Course book for BB852 at the Biology Department, University of Southern Denmark" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 18 Extending use cases of GLM | BB852 - Data handling, visualisation and statistics" />
  
  <meta name="twitter:description" content="Course book for BB852 at the Biology Department, University of Southern Denmark" />
  

<meta name="author" content="Owen R. Jones" />


<meta name="date" content="2020-09-29" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="generalised-linear-models.html"/>
<link rel="next" href="power-analysis-by-simulation.html"/>
<script src="libs/header-attrs-2.3/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/tabwid-1.0.0/tabwid.css" rel="stylesheet" />
<script src="libs/tabwid-1.0.0/tabwid.js"></script>
<style type="text/css">

.warning-box {
  border: 3px solid #e60000;
  margin:  25px;
  padding: 10px 10px 5px 10px;
  border-radius: 6px 6px 6px 6px;
}

.advanced-box {
  border: 3px solid #268bd2;
  margin:  25px;
  padding: 10px 10px 5px 10px;
  border-radius: 6px 6px 6px 6px;
}

.do-something {
  border: 3px solid #803e00;
  margin:  25px;
  padding: 10px 10px 5px 10px;
  border-radius: 6px 6px 6px 6px;
}

</style>





<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">BB852</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Preface</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#data-wrangling"><i class="fa fa-check"></i><b>1.1</b> Data wrangling</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#data-visualisation"><i class="fa fa-check"></i><b>1.2</b> Data visualisation</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#statistics"><i class="fa fa-check"></i><b>1.3</b> Statistics</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#data-sources"><i class="fa fa-check"></i><b>1.4</b> Data sources</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#your-instructors"><i class="fa fa-check"></i><b>1.5</b> Your instructors</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i><b>1.6</b> Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="schedule.html"><a href="schedule.html"><i class="fa fa-check"></i><b>2</b> Schedule</a>
<ul>
<li class="chapter" data-level="2.1" data-path="schedule.html"><a href="schedule.html#additional-recommended-reading"><i class="fa fa-check"></i><b>2.1</b> Additional recommended reading</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="an-r-refresher.html"><a href="an-r-refresher.html"><i class="fa fa-check"></i><b>3</b> An R refresher</a>
<ul>
<li class="chapter" data-level="3.1" data-path="an-r-refresher.html"><a href="an-r-refresher.html#getting-started-with-r"><i class="fa fa-check"></i><b>3.1</b> Getting started with R</a></li>
<li class="chapter" data-level="3.2" data-path="an-r-refresher.html"><a href="an-r-refresher.html#getting-help"><i class="fa fa-check"></i><b>3.2</b> Getting help</a></li>
<li class="chapter" data-level="3.3" data-path="an-r-refresher.html"><a href="an-r-refresher.html#r-as-a-fancy-calculator"><i class="fa fa-check"></i><b>3.3</b> R as a fancy calculator</a></li>
<li class="chapter" data-level="3.4" data-path="an-r-refresher.html"><a href="an-r-refresher.html#objects-in-r"><i class="fa fa-check"></i><b>3.4</b> Objects in R</a></li>
<li class="chapter" data-level="3.5" data-path="an-r-refresher.html"><a href="an-r-refresher.html#missing-values-infinity-and-non-numbers"><i class="fa fa-check"></i><b>3.5</b> Missing values, infinity and “non-numbers”</a></li>
<li class="chapter" data-level="3.6" data-path="an-r-refresher.html"><a href="an-r-refresher.html#basic-information-about-objects"><i class="fa fa-check"></i><b>3.6</b> Basic information about objects</a></li>
<li class="chapter" data-level="3.7" data-path="an-r-refresher.html"><a href="an-r-refresher.html#data-frames"><i class="fa fa-check"></i><b>3.7</b> Data frames</a></li>
<li class="chapter" data-level="3.8" data-path="an-r-refresher.html"><a href="an-r-refresher.html#organising-your-work"><i class="fa fa-check"></i><b>3.8</b> Organising your work</a></li>
<li class="chapter" data-level="3.9" data-path="an-r-refresher.html"><a href="an-r-refresher.html#inspecting-the-data"><i class="fa fa-check"></i><b>3.9</b> Inspecting the data</a></li>
<li class="chapter" data-level="3.10" data-path="an-r-refresher.html"><a href="an-r-refresher.html#classes-in-r"><i class="fa fa-check"></i><b>3.10</b> “Classes” in R</a></li>
<li class="chapter" data-level="3.11" data-path="an-r-refresher.html"><a href="an-r-refresher.html#tables-and-summary-statistics"><i class="fa fa-check"></i><b>3.11</b> Tables and summary statistics</a></li>
<li class="chapter" data-level="3.12" data-path="an-r-refresher.html"><a href="an-r-refresher.html#plotting-data"><i class="fa fa-check"></i><b>3.12</b> Plotting data</a></li>
<li class="chapter" data-level="3.13" data-path="an-r-refresher.html"><a href="an-r-refresher.html#r-packages"><i class="fa fa-check"></i><b>3.13</b> R Packages</a></li>
<li class="chapter" data-level="3.14" data-path="an-r-refresher.html"><a href="an-r-refresher.html#exercise-californian-bird-diversity"><i class="fa fa-check"></i><b>3.14</b> Exercise: Californian bird diversity</a>
<ul>
<li class="chapter" data-level="3.14.1" data-path="an-r-refresher.html"><a href="an-r-refresher.html#the-data"><i class="fa fa-check"></i><b>3.14.1</b> The data</a></li>
<li class="chapter" data-level="3.14.2" data-path="an-r-refresher.html"><a href="an-r-refresher.html#try-the-following"><i class="fa fa-check"></i><b>3.14.2</b> Try the following</a></li>
</ul></li>
<li class="chapter" data-level="3.15" data-path="an-r-refresher.html"><a href="an-r-refresher.html#exercise-solutions-californian-bird-diversity"><i class="fa fa-check"></i><b>3.15</b> Exercise Solutions: Californian bird diversity</a></li>
</ul></li>
<li class="part"><span><b>I Data Wrangling</b></span></li>
<li class="chapter" data-level="4" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html"><i class="fa fa-check"></i><b>4</b> Data wrangling with <code>dplyr</code></a>
<ul>
<li class="chapter" data-level="4.1" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#select"><i class="fa fa-check"></i><b>4.1</b> <code>select</code></a></li>
<li class="chapter" data-level="4.2" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#filter"><i class="fa fa-check"></i><b>4.2</b> <code>filter</code></a></li>
<li class="chapter" data-level="4.3" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#arrange"><i class="fa fa-check"></i><b>4.3</b> <code>arrange</code></a></li>
<li class="chapter" data-level="4.4" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#summarise-and-group_by"><i class="fa fa-check"></i><b>4.4</b> <code>summarise</code> and <code>group_by</code></a></li>
<li class="chapter" data-level="4.5" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#using-pipes-saving-data."><i class="fa fa-check"></i><b>4.5</b> Using pipes, saving data.</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="exercise-wrangling-the-amniote-life-history-database.html"><a href="exercise-wrangling-the-amniote-life-history-database.html"><i class="fa fa-check"></i><b>5</b> Exercise: Wrangling the Amniote Life History Database</a>
<ul>
<li class="chapter" data-level="5.1" data-path="exercise-wrangling-the-amniote-life-history-database.html"><a href="exercise-wrangling-the-amniote-life-history-database.html#exercise-solutions-wrangling-the-amniote-life-history-database"><i class="fa fa-check"></i><b>5.1</b> Exercise Solutions: Wrangling the Amniote Life History Database</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="combining-data-sets.html"><a href="combining-data-sets.html"><i class="fa fa-check"></i><b>6</b> Combining data sets</a>
<ul>
<li class="chapter" data-level="6.1" data-path="combining-data-sets.html"><a href="combining-data-sets.html#using-join"><i class="fa fa-check"></i><b>6.1</b> Using <code>join</code></a></li>
<li class="chapter" data-level="6.2" data-path="combining-data-sets.html"><a href="combining-data-sets.html#using-pivot_longer"><i class="fa fa-check"></i><b>6.2</b> Using <code>pivot_longer</code></a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="exercise-temperature-effects-on-egg-laying-dates.html"><a href="exercise-temperature-effects-on-egg-laying-dates.html"><i class="fa fa-check"></i><b>7</b> Exercise: Temperature effects on egg laying dates</a>
<ul>
<li class="chapter" data-level="7.1" data-path="exercise-temperature-effects-on-egg-laying-dates.html"><a href="exercise-temperature-effects-on-egg-laying-dates.html#exercise-solutions-temperature-effects-on-egg-laying-dates"><i class="fa fa-check"></i><b>7.1</b> Exercise Solutions: Temperature effects on egg laying dates</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="exercise-temperature-effects-on-egg-laying-dates.html"><a href="exercise-temperature-effects-on-egg-laying-dates.html#preparing-the-bird-data"><i class="fa fa-check"></i><b>7.1.1</b> Preparing the bird data</a></li>
<li class="chapter" data-level="7.1.2" data-path="exercise-temperature-effects-on-egg-laying-dates.html"><a href="exercise-temperature-effects-on-egg-laying-dates.html#preparing-the-weather-data"><i class="fa fa-check"></i><b>7.1.2</b> Preparing the weather data</a></li>
<li class="chapter" data-level="7.1.3" data-path="exercise-temperature-effects-on-egg-laying-dates.html"><a href="exercise-temperature-effects-on-egg-laying-dates.html#joining-the-two-datasets"><i class="fa fa-check"></i><b>7.1.3</b> Joining the two datasets</a></li>
<li class="chapter" data-level="7.1.4" data-path="exercise-temperature-effects-on-egg-laying-dates.html"><a href="exercise-temperature-effects-on-egg-laying-dates.html#plot-the-data"><i class="fa fa-check"></i><b>7.1.4</b> Plot the data</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II Data visualisation</b></span></li>
<li class="chapter" data-level="8" data-path="visualising-data-with-ggplot.html"><a href="visualising-data-with-ggplot.html"><i class="fa fa-check"></i><b>8</b> Visualising data with <code>ggplot</code></a>
<ul>
<li class="chapter" data-level="8.1" data-path="visualising-data-with-ggplot.html"><a href="visualising-data-with-ggplot.html#histograms"><i class="fa fa-check"></i><b>8.1</b> Histograms</a></li>
<li class="chapter" data-level="8.2" data-path="visualising-data-with-ggplot.html"><a href="visualising-data-with-ggplot.html#facets---splitting-data-across-panels"><i class="fa fa-check"></i><b>8.2</b> “Facets” - splitting data across panels</a></li>
<li class="chapter" data-level="8.3" data-path="visualising-data-with-ggplot.html"><a href="visualising-data-with-ggplot.html#box-plots"><i class="fa fa-check"></i><b>8.3</b> Box plots</a></li>
<li class="chapter" data-level="8.4" data-path="visualising-data-with-ggplot.html"><a href="visualising-data-with-ggplot.html#lines-and-points"><i class="fa fa-check"></i><b>8.4</b> Lines and points</a></li>
<li class="chapter" data-level="8.5" data-path="visualising-data-with-ggplot.html"><a href="visualising-data-with-ggplot.html#scatter-plots"><i class="fa fa-check"></i><b>8.5</b> Scatter plots</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html"><i class="fa fa-check"></i><b>9</b> Distributions and summarising data</a>
<ul>
<li class="chapter" data-level="9.1" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#distributions"><i class="fa fa-check"></i><b>9.1</b> Distributions</a></li>
<li class="chapter" data-level="9.2" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#normal-distribution"><i class="fa fa-check"></i><b>9.2</b> Normal distribution</a></li>
<li class="chapter" data-level="9.3" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#comparing-normal-distributions"><i class="fa fa-check"></i><b>9.3</b> Comparing normal distributions</a></li>
<li class="chapter" data-level="9.4" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#poisson-distribution"><i class="fa fa-check"></i><b>9.4</b> Poisson distribution</a></li>
<li class="chapter" data-level="9.5" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#comparing-normal-and-poisson-distributions"><i class="fa fa-check"></i><b>9.5</b> Comparing normal and Poisson distributions</a></li>
<li class="chapter" data-level="9.6" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#the-law-of-large-numbers"><i class="fa fa-check"></i><b>9.6</b> The law of large numbers</a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#coin-flipping"><i class="fa fa-check"></i><b>9.6.1</b> Coin flipping</a></li>
<li class="chapter" data-level="9.6.2" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#virtual-dice"><i class="fa fa-check"></i><b>9.6.2</b> Virtual dice</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="customising-your-plots.html"><a href="customising-your-plots.html"><i class="fa fa-check"></i><b>10</b> Customising your plots</a>
<ul>
<li class="chapter" data-level="10.1" data-path="customising-your-plots.html"><a href="customising-your-plots.html#a-basic-plot"><i class="fa fa-check"></i><b>10.1</b> A basic plot</a></li>
<li class="chapter" data-level="10.2" data-path="customising-your-plots.html"><a href="customising-your-plots.html#axis-limits"><i class="fa fa-check"></i><b>10.2</b> Axis limits</a></li>
<li class="chapter" data-level="10.3" data-path="customising-your-plots.html"><a href="customising-your-plots.html#transforming-the-axis-log-scale"><i class="fa fa-check"></i><b>10.3</b> Transforming the axis (log scale)</a></li>
<li class="chapter" data-level="10.4" data-path="customising-your-plots.html"><a href="customising-your-plots.html#changing-the-axis-tick-marks"><i class="fa fa-check"></i><b>10.4</b> Changing the axis tick marks</a></li>
<li class="chapter" data-level="10.5" data-path="customising-your-plots.html"><a href="customising-your-plots.html#axis-labels"><i class="fa fa-check"></i><b>10.5</b> Axis labels</a></li>
<li class="chapter" data-level="10.6" data-path="customising-your-plots.html"><a href="customising-your-plots.html#colours"><i class="fa fa-check"></i><b>10.6</b> Colours</a></li>
<li class="chapter" data-level="10.7" data-path="customising-your-plots.html"><a href="customising-your-plots.html#themes"><i class="fa fa-check"></i><b>10.7</b> Themes</a></li>
<li class="chapter" data-level="10.8" data-path="customising-your-plots.html"><a href="customising-your-plots.html#moving-the-legend"><i class="fa fa-check"></i><b>10.8</b> Moving the legend</a></li>
<li class="chapter" data-level="10.9" data-path="customising-your-plots.html"><a href="customising-your-plots.html#combining-multiple-plots"><i class="fa fa-check"></i><b>10.9</b> Combining multiple plots</a></li>
<li class="chapter" data-level="10.10" data-path="customising-your-plots.html"><a href="customising-your-plots.html#saving-your-plot"><i class="fa fa-check"></i><b>10.10</b> Saving your plot</a></li>
<li class="chapter" data-level="10.11" data-path="customising-your-plots.html"><a href="customising-your-plots.html#final-word-on-plots"><i class="fa fa-check"></i><b>10.11</b> Final word on plots</a></li>
</ul></li>
<li class="part"><span><b>III Statistics</b></span></li>
<li class="chapter" data-level="11" data-path="randomisation-tests.html"><a href="randomisation-tests.html"><i class="fa fa-check"></i><b>11</b> Randomisation Tests</a>
<ul>
<li class="chapter" data-level="11.1" data-path="randomisation-tests.html"><a href="randomisation-tests.html#randomisation-test-in-r"><i class="fa fa-check"></i><b>11.1</b> Randomisation test in R</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="randomisation-tests.html"><a href="randomisation-tests.html#calculate-the-observed-difference"><i class="fa fa-check"></i><b>11.1.1</b> Calculate the observed difference</a></li>
<li class="chapter" data-level="11.1.2" data-path="randomisation-tests.html"><a href="randomisation-tests.html#null-distribution"><i class="fa fa-check"></i><b>11.1.2</b> Null distribution</a></li>
<li class="chapter" data-level="11.1.3" data-path="randomisation-tests.html"><a href="randomisation-tests.html#testing-significance"><i class="fa fa-check"></i><b>11.1.3</b> Testing significance</a></li>
<li class="chapter" data-level="11.1.4" data-path="randomisation-tests.html"><a href="randomisation-tests.html#testing-the-hypothesis"><i class="fa fa-check"></i><b>11.1.4</b> Testing the hypothesis</a></li>
<li class="chapter" data-level="11.1.5" data-path="randomisation-tests.html"><a href="randomisation-tests.html#writing-it-up"><i class="fa fa-check"></i><b>11.1.5</b> Writing it up</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="randomisation-tests.html"><a href="randomisation-tests.html#paired-randomisation-tests"><i class="fa fa-check"></i><b>11.2</b> Paired Randomisation Tests</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="randomisation-tests.html"><a href="randomisation-tests.html#the-randomisation-test"><i class="fa fa-check"></i><b>11.2.1</b> The randomisation test</a></li>
<li class="chapter" data-level="11.2.2" data-path="randomisation-tests.html"><a href="randomisation-tests.html#null-distribution-1"><i class="fa fa-check"></i><b>11.2.2</b> Null distribution</a></li>
<li class="chapter" data-level="11.2.3" data-path="randomisation-tests.html"><a href="randomisation-tests.html#the-formal-hypothesis-test"><i class="fa fa-check"></i><b>11.2.3</b> The formal hypothesis test</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="randomisation-tests.html"><a href="randomisation-tests.html#exercise-sexual-selection-in-hercules-beetles"><i class="fa fa-check"></i><b>11.3</b> Exercise: Sexual selection in Hercules beetles</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="comparing-two-means-with-a-t-test.html"><a href="comparing-two-means-with-a-t-test.html"><i class="fa fa-check"></i><b>12</b> Comparing two means with a t-test</a>
<ul>
<li class="chapter" data-level="12.1" data-path="comparing-two-means-with-a-t-test.html"><a href="comparing-two-means-with-a-t-test.html#some-theory"><i class="fa fa-check"></i><b>12.1</b> Some theory</a></li>
<li class="chapter" data-level="12.2" data-path="comparing-two-means-with-a-t-test.html"><a href="comparing-two-means-with-a-t-test.html#one-sample-t-test"><i class="fa fa-check"></i><b>12.2</b> One sample t-test</a></li>
<li class="chapter" data-level="12.3" data-path="comparing-two-means-with-a-t-test.html"><a href="comparing-two-means-with-a-t-test.html#doing-it-by-hand---where-does-the-t-statistic-come-from"><i class="fa fa-check"></i><b>12.3</b> Doing it “by hand” - where does the t-statistic come from?</a></li>
<li class="chapter" data-level="12.4" data-path="comparing-two-means-with-a-t-test.html"><a href="comparing-two-means-with-a-t-test.html#paired-t-test"><i class="fa fa-check"></i><b>12.4</b> Paired t-test</a></li>
<li class="chapter" data-level="12.5" data-path="comparing-two-means-with-a-t-test.html"><a href="comparing-two-means-with-a-t-test.html#a-paired-t-test-is-a-one-sample-test."><i class="fa fa-check"></i><b>12.5</b> A paired t-test is a one-sample test.</a></li>
<li class="chapter" data-level="12.6" data-path="comparing-two-means-with-a-t-test.html"><a href="comparing-two-means-with-a-t-test.html#two-sample-t-test"><i class="fa fa-check"></i><b>12.6</b> Two sample t-test</a></li>
<li class="chapter" data-level="12.7" data-path="comparing-two-means-with-a-t-test.html"><a href="comparing-two-means-with-a-t-test.html#t-tests-are-linear-models"><i class="fa fa-check"></i><b>12.7</b> t-tests are linear models</a></li>
<li class="chapter" data-level="12.8" data-path="comparing-two-means-with-a-t-test.html"><a href="comparing-two-means-with-a-t-test.html#exercise-sex-differences-in-fine-motor-skills"><i class="fa fa-check"></i><b>12.8</b> Exercise: Sex differences in fine motor skills</a></li>
<li class="chapter" data-level="12.9" data-path="comparing-two-means-with-a-t-test.html"><a href="comparing-two-means-with-a-t-test.html#exercise-therapy-for-anorexia"><i class="fa fa-check"></i><b>12.9</b> Exercise: Therapy for anorexia</a></li>
<li class="chapter" data-level="12.10" data-path="comparing-two-means-with-a-t-test.html"><a href="comparing-two-means-with-a-t-test.html#exercise-compare-t-tests-with-randomisation-tests"><i class="fa fa-check"></i><b>12.10</b> Exercise: Compare t-tests with randomisation tests</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="linear-models-with-a-single-categorical-explanatory-variable.html"><a href="linear-models-with-a-single-categorical-explanatory-variable.html"><i class="fa fa-check"></i><b>13</b> Linear models with a single categorical explanatory variable</a>
<ul>
<li class="chapter" data-level="13.1" data-path="linear-models-with-a-single-categorical-explanatory-variable.html"><a href="linear-models-with-a-single-categorical-explanatory-variable.html#one-way-anova"><i class="fa fa-check"></i><b>13.1</b> One-way ANOVA</a></li>
<li class="chapter" data-level="13.2" data-path="linear-models-with-a-single-categorical-explanatory-variable.html"><a href="linear-models-with-a-single-categorical-explanatory-variable.html#fitting-an-anova-in-r"><i class="fa fa-check"></i><b>13.2</b> Fitting an ANOVA in R</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="linear-models-with-a-single-categorical-explanatory-variable.html"><a href="linear-models-with-a-single-categorical-explanatory-variable.html#where-are-the-differences"><i class="fa fa-check"></i><b>13.2.1</b> Where are the differences?</a></li>
<li class="chapter" data-level="13.2.2" data-path="linear-models-with-a-single-categorical-explanatory-variable.html"><a href="linear-models-with-a-single-categorical-explanatory-variable.html#tukeys-honestly-significant-difference-hsd"><i class="fa fa-check"></i><b>13.2.2</b> Tukey’s Honestly Significant Difference (HSD)</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="linear-models-with-a-single-categorical-explanatory-variable.html"><a href="linear-models-with-a-single-categorical-explanatory-variable.html#anova-calculation-by-hand."><i class="fa fa-check"></i><b>13.3</b> ANOVA calculation “by hand”.</a></li>
<li class="chapter" data-level="13.4" data-path="linear-models-with-a-single-categorical-explanatory-variable.html"><a href="linear-models-with-a-single-categorical-explanatory-variable.html#exercise-apple-tree-crop-yield"><i class="fa fa-check"></i><b>13.4</b> Exercise: Apple tree crop yield</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="linear-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-models-with-a-single-continuous-explanatory-variable.html"><i class="fa fa-check"></i><b>14</b> Linear models with a single continuous explanatory variable</a>
<ul>
<li class="chapter" data-level="14.1" data-path="comparing-two-means-with-a-t-test.html"><a href="comparing-two-means-with-a-t-test.html#some-theory"><i class="fa fa-check"></i><b>14.1</b> Some theory</a></li>
<li class="chapter" data-level="14.2" data-path="linear-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-models-with-a-single-continuous-explanatory-variable.html#evaluating-a-hypothesis-with-a-linear-regression-model"><i class="fa fa-check"></i><b>14.2</b> Evaluating a hypothesis with a linear regression model</a></li>
<li class="chapter" data-level="14.3" data-path="linear-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-models-with-a-single-continuous-explanatory-variable.html#assumptions"><i class="fa fa-check"></i><b>14.3</b> Assumptions</a></li>
<li class="chapter" data-level="14.4" data-path="linear-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-models-with-a-single-continuous-explanatory-variable.html#worked-example-height-hand-width-relationship"><i class="fa fa-check"></i><b>14.4</b> Worked example: height-hand width relationship</a></li>
<li class="chapter" data-level="14.5" data-path="linear-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-models-with-a-single-continuous-explanatory-variable.html#exercise-chirping-crickets"><i class="fa fa-check"></i><b>14.5</b> Exercise: Chirping crickets</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="linear-models-with-categorical-and-continuous-explanatory-variables.html"><a href="linear-models-with-categorical-and-continuous-explanatory-variables.html"><i class="fa fa-check"></i><b>15</b> Linear models with categorical and continuous explanatory variables</a>
<ul>
<li class="chapter" data-level="15.1" data-path="linear-models-with-categorical-and-continuous-explanatory-variables.html"><a href="linear-models-with-categorical-and-continuous-explanatory-variables.html#the-height-hand-width-example."><i class="fa fa-check"></i><b>15.1</b> The height ~ hand width example.</a></li>
<li class="chapter" data-level="15.2" data-path="linear-models-with-categorical-and-continuous-explanatory-variables.html"><a href="linear-models-with-categorical-and-continuous-explanatory-variables.html#summarising-with-anova"><i class="fa fa-check"></i><b>15.2</b> Summarising with <code>anova</code></a></li>
<li class="chapter" data-level="15.3" data-path="linear-models-with-categorical-and-continuous-explanatory-variables.html"><a href="linear-models-with-categorical-and-continuous-explanatory-variables.html#the-summary-of-coefficients-summary"><i class="fa fa-check"></i><b>15.3</b> The summary of coefficients (<code>summary</code>)</a></li>
<li class="chapter" data-level="15.4" data-path="linear-models-with-categorical-and-continuous-explanatory-variables.html"><a href="linear-models-with-categorical-and-continuous-explanatory-variables.html#simplifying-the-model"><i class="fa fa-check"></i><b>15.4</b> Simplifying the model</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="linear-models-with-1-categorical-explanatory-variables.html"><a href="linear-models-with-1-categorical-explanatory-variables.html"><i class="fa fa-check"></i><b>16</b> Linear models with &gt;1 categorical explanatory variables</a>
<ul>
<li class="chapter" data-level="16.1" data-path="linear-models-with-1-categorical-explanatory-variables.html"><a href="linear-models-with-1-categorical-explanatory-variables.html#fitting-a-two-way-anova-model"><i class="fa fa-check"></i><b>16.1</b> Fitting a two-way ANOVA model</a></li>
<li class="chapter" data-level="16.2" data-path="linear-models-with-1-categorical-explanatory-variables.html"><a href="linear-models-with-1-categorical-explanatory-variables.html#summarising-the-model-anova"><i class="fa fa-check"></i><b>16.2</b> Summarising the model (<code>anova</code>)</a></li>
<li class="chapter" data-level="16.3" data-path="linear-models-with-1-categorical-explanatory-variables.html"><a href="linear-models-with-1-categorical-explanatory-variables.html#summarising-the-model-summary"><i class="fa fa-check"></i><b>16.3</b> Summarising the model (<code>summary</code>)</a></li>
<li class="chapter" data-level="16.4" data-path="linear-models-with-1-categorical-explanatory-variables.html"><a href="linear-models-with-1-categorical-explanatory-variables.html#exercise-fish-behaviour"><i class="fa fa-check"></i><b>16.4</b> Exercise: Fish behaviour</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html"><i class="fa fa-check"></i><b>17</b> Generalised linear models</a>
<ul>
<li class="chapter" data-level="17.1" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html#count-data-with-poisson-errors."><i class="fa fa-check"></i><b>17.1</b> Count data with Poisson errors.</a>
<ul>
<li class="chapter" data-level="17.1.1" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html#example-number-of-offspring-in-foxes."><i class="fa fa-check"></i><b>17.1.1</b> Example: Number of offspring in foxes.</a></li>
<li class="chapter" data-level="17.1.2" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html#example-cancer-clusters"><i class="fa fa-check"></i><b>17.1.2</b> Example: Cancer clusters</a></li>
</ul></li>
<li class="chapter" data-level="17.2" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html#exercise-maze-runner"><i class="fa fa-check"></i><b>17.2</b> Exercise: Maze runner</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="extending-use-cases-of-glm.html"><a href="extending-use-cases-of-glm.html"><i class="fa fa-check"></i><b>18</b> Extending use cases of GLM</a>
<ul>
<li class="chapter" data-level="18.1" data-path="extending-use-cases-of-glm.html"><a href="extending-use-cases-of-glm.html#binomial-response-data"><i class="fa fa-check"></i><b>18.1</b> Binomial response data</a></li>
<li class="chapter" data-level="18.2" data-path="extending-use-cases-of-glm.html"><a href="extending-use-cases-of-glm.html#example-nfl-field-goals"><i class="fa fa-check"></i><b>18.2</b> Example: NFL field goals</a></li>
<li class="chapter" data-level="18.3" data-path="extending-use-cases-of-glm.html"><a href="extending-use-cases-of-glm.html#example-sex-ratio-in-turtles"><i class="fa fa-check"></i><b>18.3</b> Example: Sex ratio in turtles</a></li>
<li class="chapter" data-level="18.4" data-path="extending-use-cases-of-glm.html"><a href="extending-use-cases-of-glm.html#example-smoking"><i class="fa fa-check"></i><b>18.4</b> Example: Smoking</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html"><i class="fa fa-check"></i><b>19</b> Power analysis by simulation</a>
<ul>
<li class="chapter" data-level="19.1" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#type-i-and-ii-errors-and-statistical-power"><i class="fa fa-check"></i><b>19.1</b> Type I and II errors and statistical power</a></li>
<li class="chapter" data-level="19.2" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#what-determines-statistical-power"><i class="fa fa-check"></i><b>19.2</b> What determines statistical power?</a></li>
<li class="chapter" data-level="19.3" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#an-example-of-calculating-statistical-power."><i class="fa fa-check"></i><b>19.3</b> An example of calculating statistical power.</a>
<ul>
<li class="chapter" data-level="19.3.1" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#the-simulation"><i class="fa fa-check"></i><b>19.3.1</b> The simulation</a></li>
<li class="chapter" data-level="19.3.2" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#some-questions-for-you-to-address"><i class="fa fa-check"></i><b>19.3.2</b> Some questions for you to address:</a></li>
</ul></li>
<li class="chapter" data-level="19.4" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#summary"><i class="fa fa-check"></i><b>19.4</b> Summary</a></li>
<li class="chapter" data-level="19.5" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#extending-the-simulation-optional-advanced"><i class="fa fa-check"></i><b>19.5</b> Extending the simulation (optional, advanced)</a></li>
<li class="chapter" data-level="19.6" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#exercise-1-snails-on-the-move"><i class="fa fa-check"></i><b>19.6</b> Exercise 1: Snails on the move</a></li>
<li class="chapter" data-level="19.7" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#exercise-2-mouse-lemur-strength"><i class="fa fa-check"></i><b>19.7</b> Exercise 2: Mouse lemur strength</a></li>
</ul></li>
<li class="part"><span><b>IV Coming soon(ish)</b></span></li>
<li class="chapter" data-level="20" data-path="coming-soon-maybe.html"><a href="coming-soon-maybe.html"><i class="fa fa-check"></i><b>20</b> Coming soon (maybe)!</a>
<ul>
<li class="chapter" data-level="20.1" data-path="coming-soon-maybe.html"><a href="coming-soon-maybe.html#multivariate-statistics"><i class="fa fa-check"></i><b>20.1</b> Multivariate statistics</a></li>
<li class="chapter" data-level="20.2" data-path="coming-soon-maybe.html"><a href="coming-soon-maybe.html#transforming-variables"><i class="fa fa-check"></i><b>20.2</b> Transforming variables</a></li>
<li class="chapter" data-level="20.3" data-path="coming-soon-maybe.html"><a href="coming-soon-maybe.html#non-linear-regression"><i class="fa fa-check"></i><b>20.3</b> Non-linear regression</a></li>
<li class="chapter" data-level="20.4" data-path="coming-soon-maybe.html"><a href="coming-soon-maybe.html#nested-or-blocked-study-designs"><i class="fa fa-check"></i><b>20.4</b> Nested or blocked study designs</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">BB852 - Data handling, visualisation and statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="extending-use-cases-of-glm" class="section level1" number="18">
<h1><span class="header-section-number">Chapter 18</span> Extending use cases of GLM</h1>
<p>In the previous chapter we used the case of modelling count data, which is bounded at 0 and takes integer values, to understand how Generalised Linear Models work. In this chapter we extend our understanding by looking at another type of data, namely <em>binomial</em> data.</p>
<div id="binomial-response-data" class="section level2" number="18.1">
<h2><span class="header-section-number">18.1</span> Binomial response data</h2>
<p>There are three types of Binomial data, but all three types have the idea of “success” and “failure” at their heart. It is up to you, the modeller, to decide what these successes and failures are, but they can be any kind of data that can be coerced into two discrete categories. Common examples include pass/fail, survived/died, presence/absence and yes/no.</p>
<p>The three data types are as follows:</p>
<ol style="list-style-type: decimal">
<li>The data can be in the form of a two-level factor - often coded as zeros and ones (0/1 data). For example, this could represent whether an died (0) or survived (1) in a study; or it could represent male (<code>M</code>) or female (<code>F</code>) in a study trying to predict sex from other variables (e.g. size or morphology).</li>
<li>The data could be expressed as a numeric vector of proportions, bounded between 0 and 1 (i.e. can take any value between 0 and 1). For example these data could be percentages expressed as proportion, such as proportion (or percent) of individuals in a group surviving. In this case, the total number of cases that contributed to the proportion can be optionally included as <code>weights</code> in the regression model.<a href="#fn13" class="footnote-ref" id="fnref13"><sup>13</sup></a></li>
<li>Finally, the data could be expressed as numbers in a two column matrix where the first column gives the number of “successes” and the second column gives the number of “failures”.</li>
</ol>
<p>The aim of the GLM is usually to estimate probability of “success” (e.g. survival, passing, scoring a goal…). Thus, the outcome (the predicted response, or fit, of the model) is a value between 0 and 1 on the natural scale, that can be interpreted as a probability (e.g. of survival, of success, of presence etc.)</p>
<p>The link function used for a binomial GLM is usually the <em>logit</em> transformation, and therefore another name for this type of regression is <strong>logistic regression</strong>. The logit transformation linearises an S-shaped curve and therefore allows a linear regression line to be fitted from data that follows this pattern. The function is <span class="math inline">\(y = log(\frac{p}{1-p})\)</span>, where <span class="math inline">\(p\)</span> is the probability or proportion. The inverse logit (the anti-logit) is <span class="math inline">\(p = \frac{exp(y)}{exp(y)+1}\)</span>.</p>
<p><img src="BB852_files/figure-html/unnamed-chunk-357-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>We <strong>could</strong> linearise the data and then fit an ordinary linear model using <code>lm</code> but (like with the Poisson regression) the other assumption of the ordinary linear model, homoscedasticity, would cause problems. With S-shaped binomial relationships the expected variance is small at the two ends of the range and large in the middle of the range. This contrasts strongly with the constant variance assumption of ordinary linear models. Therefore it is wise to account for this using a Generalised Linear Model that explicitly accounts for this variance structure.</p>
<p>Let’s try a couple of examples.</p>
<div class="do-something">
<p>
Remember to load the <code>dplyr</code>, <code>magrittr</code> and <code>ggplot</code> packages, and to set your working directory correctly.
</p>
</div>
</div>
<div id="example-nfl-field-goals" class="section level2" number="18.2">
<h2><span class="header-section-number">18.2</span> Example: NFL field goals</h2>
<p>In this example you will be dealing with binary data (0/1, failure/success) from the American National Football League (NFL). The data are a record of field goals, which are a relatively rare method of scoring where someone kicks the ball through over the crossbar and through the uprights of the goal during play.</p>
<p>Our aim is to estimate how the probability of success changes with distance from the goal. We already have a good idea that success probability will decline with increasing distance! But at what rate does the probability decline? And at what distance is there a probability of 0.5 (i.e. 50% chance of success)?</p>
<p>First, import the data and convert the distance from yards to meters.</p>
<div class="sourceCode" id="cb483"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb483-1"><a href="extending-use-cases-of-glm.html#cb483-1" aria-hidden="true"></a>NFL &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;CourseData/NFLfieldgoal.csv&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb483-2"><a href="extending-use-cases-of-glm.html#cb483-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Distance =</span> Distance <span class="op">*</span><span class="st"> </span><span class="fl">0.9144</span>)</span></code></pre></div>
<p>Next, plot the data with <code>ggplot</code> (<code>geom_jitter</code> would be a good option, but you might like to adjust the <code>height</code> and <code>alpha</code> arguments. e.g. <code>geom_jitter(height = 0.05,alpha = 0.5)</code>). You can see that the data is distributed in two bands with 1 representing success and 0 representing failure.</p>
<div class="sourceCode" id="cb484"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb484-1"><a href="extending-use-cases-of-glm.html#cb484-1" aria-hidden="true"></a>(A&lt;-<span class="kw">ggplot</span>(NFL,<span class="kw">aes</span>(<span class="dt">x =</span> Distance,<span class="dt">y =</span> Success)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb484-2"><a href="extending-use-cases-of-glm.html#cb484-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_jitter</span>(<span class="dt">height =</span> <span class="fl">0.05</span>, <span class="dt">alpha =</span> <span class="fl">0.5</span>))</span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-360-1.png" width="480" style="display: block; margin: auto;" /></p>
<p>Now we can fit a GLM using an appropriate binomial error structure.</p>
<div class="sourceCode" id="cb485"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb485-1"><a href="extending-use-cases-of-glm.html#cb485-1" aria-hidden="true"></a>nflMod &lt;-<span class="st"> </span><span class="kw">glm</span>(Success <span class="op">~</span><span class="st"> </span>Distance, <span class="dt">data =</span> NFL, <span class="dt">family =</span> binomial)</span></code></pre></div>
<p>As usual, we should look at the model diagnostics. These look pretty bad. One reason that these diagnostics (e.g. the QQ plot) can look bad is when we are missing important variables in the model. In this case, for example, the distribution could look “off” because we don’t include important information on other aspects of the game (e.g. was the team winning or losing at the time? how many minutes until the end of the game? how experienced is the player?). We can be fairly sure that <code>binomial</code> is the most appropriate variance structure because of the nature of the 0/1 data so let’s stick with it for now!</p>
<div class="sourceCode" id="cb486"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb486-1"><a href="extending-use-cases-of-glm.html#cb486-1" aria-hidden="true"></a><span class="kw">library</span>(ggfortify)</span>
<span id="cb486-2"><a href="extending-use-cases-of-glm.html#cb486-2" aria-hidden="true"></a><span class="kw">autoplot</span>(nflMod)</span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-362-1.png" width="384" style="display: block; margin: auto;" /></p>
<p>We proceed in the normal way by obtaining the ANOVA table for the model. We need to specify that we want to calculated p-values using a “Chi” squared test. This shows us that indeed distance is an important variable in determining probability of success (not so surprising!)</p>
<div class="sourceCode" id="cb487"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb487-1"><a href="extending-use-cases-of-glm.html#cb487-1" aria-hidden="true"></a><span class="kw">anova</span>(nflMod, <span class="dt">test =</span> <span class="st">&quot;Chi&quot;</span>)</span></code></pre></div>
<pre><code>## Analysis of Deviance Table
## 
## Model: binomial, link: logit
## 
## Response: Success
## 
## Terms added sequentially (first to last)
## 
## 
##          Df Deviance Resid. Df Resid. Dev  Pr(&gt;Chi)    
## NULL                       947     955.38              
## Distance  1    137.8       946     817.58 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>We get more useful information from the coefficient <code>summary</code> of the model. This gives the intercept and slope of the model <strong>on the scale of the linear predictor</strong> (see the figure above).</p>
<div class="sourceCode" id="cb489"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb489-1"><a href="extending-use-cases-of-glm.html#cb489-1" aria-hidden="true"></a><span class="kw">summary</span>(nflMod)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Success ~ Distance, family = binomial, data = NFL)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.6681   0.2704   0.4067   0.7094   1.4708  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  5.68958    0.45021   12.64   &lt;2e-16 ***
## Distance    -0.13118    0.01263  -10.38   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 955.38  on 947  degrees of freedom
## Residual deviance: 817.58  on 946  degrees of freedom
## AIC: 821.58
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>We could report this something like this:</p>
<p><em>The binomial GLM showed that distance was significantly associated with the probability of goal success (GLM: Null Deviance = 955.38, Residual Deviance = 817.58, d.f. = 1 and 946 p &lt;0.001). The slope and intercept of the relationship is -0.131 and 5.690 respectively on the logit scale. The equation of the best fit line was therefore logit(nOffspring) = 5.690 - 0.131<span class="math inline">\(\times\)</span>distance (see Figure XXX)</em></p>
<p>The equation of the model if you want to express it on the natural scale works out to be:</p>
<p><span class="math inline">\(y =\frac{1}{1+exp(-(\beta_0 + \beta_1 x))}\)</span>, or <span class="math inline">\(probability =\frac{1}{1+exp(-(5.690 - 0.131\times distance))}\)</span>.</p>
<p>Let’s make sure that works by creating a set of predicted data from this equation and plotting it onto the graph:</p>
<div class="sourceCode" id="cb491"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb491-1"><a href="extending-use-cases-of-glm.html#cb491-1" aria-hidden="true"></a>d1 &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">x =</span> <span class="dv">10</span><span class="op">:</span><span class="dv">50</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb491-2"><a href="extending-use-cases-of-glm.html#cb491-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">y =</span> <span class="dv">1</span><span class="op">/</span>(<span class="dv">1</span><span class="op">+</span><span class="kw">exp</span>(<span class="op">-</span>(<span class="fl">5.690</span> <span class="op">-</span><span class="st"> </span><span class="fl">0.131</span> <span class="op">*</span>x))))</span>
<span id="cb491-3"><a href="extending-use-cases-of-glm.html#cb491-3" aria-hidden="true"></a>A <span class="op">+</span><span class="st"> </span></span>
<span id="cb491-4"><a href="extending-use-cases-of-glm.html#cb491-4" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_line</span>(<span class="dt">data =</span> d1,<span class="kw">aes</span>(x,y),<span class="dt">colour=</span><span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-365-1.png" width="480" style="display: block; margin: auto;" /></p>
<p>Rather than using the equation, there is an easier way by using the <strong>R</strong>’s <code>predict</code> function. We will use <code>predict</code> to get the predicted probability of success across the range of distances that we provide as a new data frame that we are here calling <code>newDat</code>. We will also predict the 95% Confidence Interval (CI) for these estimates. We will use these data to add the CI ribbon and line to the plot.</p>
<p>The <code>predict</code> function returns an object that includes the <code>fit</code> and the <code>se.fit</code> which are the predicted value of the regression and the standard error of that predicted value respectively. Thus, if the output of the <code>predict</code> function is stored as <code>pv</code> we can address those parts as <code>pv$fit</code> and <code>pv$se.fit</code>, and we can save these values alongside the data in <code>newDat</code>.</p>
<div class="do-something">
<p>
Remember that the model, and the predicted values from it, are expressed on the scale of the <em>linear predictor</em> (i.e. the transformed data scale). It is usually desirable to “backtransform” to the natural scale before plotting. See below.
</p>
</div>
<p>First we obtain the predictions and CI on the scale of the linear predictor (logit scale). We calculate 95% CI from the standard errors simply by multiplying by 1.96.</p>
<div class="sourceCode" id="cb492"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb492-1"><a href="extending-use-cases-of-glm.html#cb492-1" aria-hidden="true"></a><span class="co">#Dataset to predict FROM</span></span>
<span id="cb492-2"><a href="extending-use-cases-of-glm.html#cb492-2" aria-hidden="true"></a>newDat  &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">Distance =</span> <span class="dv">14</span><span class="op">:</span><span class="dv">52</span>) </span>
<span id="cb492-3"><a href="extending-use-cases-of-glm.html#cb492-3" aria-hidden="true"></a></span>
<span id="cb492-4"><a href="extending-use-cases-of-glm.html#cb492-4" aria-hidden="true"></a><span class="co">#Get predictions from the model</span></span>
<span id="cb492-5"><a href="extending-use-cases-of-glm.html#cb492-5" aria-hidden="true"></a>pv &lt;-<span class="st"> </span><span class="kw">predict</span>(nflMod, <span class="dt">newdata =</span> newDat,<span class="dt">se.fit =</span> <span class="ot">TRUE</span>)</span>
<span id="cb492-6"><a href="extending-use-cases-of-glm.html#cb492-6" aria-hidden="true"></a></span>
<span id="cb492-7"><a href="extending-use-cases-of-glm.html#cb492-7" aria-hidden="true"></a><span class="co">#Add those predictions to newDat</span></span>
<span id="cb492-8"><a href="extending-use-cases-of-glm.html#cb492-8" aria-hidden="true"></a>newDat &lt;-<span class="st"> </span>newDat <span class="op">%&gt;%</span><span class="st">  </span></span>
<span id="cb492-9"><a href="extending-use-cases-of-glm.html#cb492-9" aria-hidden="true"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Success_LP =</span> pv<span class="op">$</span>fit) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb492-10"><a href="extending-use-cases-of-glm.html#cb492-10" aria-hidden="true"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">lowerCI_LP =</span> pv<span class="op">$</span>fit <span class="op">-</span><span class="st"> </span><span class="fl">1.96</span><span class="op">*</span>pv<span class="op">$</span>se.fit) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb492-11"><a href="extending-use-cases-of-glm.html#cb492-11" aria-hidden="true"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">upperCI_LP =</span> pv<span class="op">$</span>fit <span class="op">+</span><span class="st"> </span><span class="fl">1.96</span><span class="op">*</span>pv<span class="op">$</span>se.fit)</span></code></pre></div>
<p>Now we can first obtain the inverse link from the model object <code>family(nflMod)$linkinv</code>, and use that to backtransform the data onto the natural scale ready for plotting.</p>
<div class="sourceCode" id="cb493"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb493-1"><a href="extending-use-cases-of-glm.html#cb493-1" aria-hidden="true"></a><span class="co">#Get the inverse link function</span></span>
<span id="cb493-2"><a href="extending-use-cases-of-glm.html#cb493-2" aria-hidden="true"></a>inverseFunction &lt;-<span class="kw">family</span>(nflMod)<span class="op">$</span>linkinv</span>
<span id="cb493-3"><a href="extending-use-cases-of-glm.html#cb493-3" aria-hidden="true"></a></span>
<span id="cb493-4"><a href="extending-use-cases-of-glm.html#cb493-4" aria-hidden="true"></a><span class="co">#transform predicted data to the natural scale</span></span>
<span id="cb493-5"><a href="extending-use-cases-of-glm.html#cb493-5" aria-hidden="true"></a>newDat &lt;-<span class="st"> </span>newDat <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb493-6"><a href="extending-use-cases-of-glm.html#cb493-6" aria-hidden="true"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Success =</span> <span class="kw">inverseFunction</span>(Success_LP),</span>
<span id="cb493-7"><a href="extending-use-cases-of-glm.html#cb493-7" aria-hidden="true"></a>         <span class="dt">ymin=</span> <span class="kw">inverseFunction</span>(lowerCI_LP),</span>
<span id="cb493-8"><a href="extending-use-cases-of-glm.html#cb493-8" aria-hidden="true"></a>         <span class="dt">ymax =</span> <span class="kw">inverseFunction</span>(upperCI_LP))</span></code></pre></div>
<p>Now we can finally plot the model predictions and the 95% confidence intervals for them.</p>
<div class="sourceCode" id="cb494"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb494-1"><a href="extending-use-cases-of-glm.html#cb494-1" aria-hidden="true"></a><span class="co">#The plot and ribbon</span></span>
<span id="cb494-2"><a href="extending-use-cases-of-glm.html#cb494-2" aria-hidden="true"></a>(A &lt;-<span class="st"> </span><span class="kw">ggplot</span>(NFL,<span class="kw">aes</span>(<span class="dt">x=</span> Distance,<span class="dt">y=</span>Success)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb494-3"><a href="extending-use-cases-of-glm.html#cb494-3" aria-hidden="true"></a><span class="st">    </span><span class="kw">geom_ribbon</span>(<span class="dt">data =</span> newDat,<span class="kw">aes</span>(<span class="dt">x =</span>Distance,<span class="dt">ymin=</span>ymin,<span class="dt">ymax=</span>ymax),</span>
<span id="cb494-4"><a href="extending-use-cases-of-glm.html#cb494-4" aria-hidden="true"></a>                <span class="dt">fill=</span><span class="st">&quot;grey75&quot;</span>,<span class="dt">alpha =</span> <span class="fl">0.5</span>)<span class="op">+</span></span>
<span id="cb494-5"><a href="extending-use-cases-of-glm.html#cb494-5" aria-hidden="true"></a><span class="st">    </span><span class="kw">geom_smooth</span>(<span class="dt">data =</span> newDat,<span class="dt">stat=</span><span class="st">&quot;identity&quot;</span>)<span class="op">+</span></span>
<span id="cb494-6"><a href="extending-use-cases-of-glm.html#cb494-6" aria-hidden="true"></a><span class="st">    </span><span class="kw">geom_jitter</span>(<span class="dt">height =</span> <span class="fl">0.05</span>,<span class="dt">alpha =</span> <span class="fl">0.5</span>))</span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-369-1.png" width="480" style="display: block; margin: auto;" />
So, at what distance does the probability of success fall to just 50%? You could read this directly from the plot as “approximately 44m”. Alternatively, you could obtain the value from the <code>newDat</code> dataset you created above with predictions from the model, by filtering it. This confirms the probability of success reaches 0.5 somewhere between 43-44m.</p>
<div class="sourceCode" id="cb495"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb495-1"><a href="extending-use-cases-of-glm.html#cb495-1" aria-hidden="true"></a>newDat <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb495-2"><a href="extending-use-cases-of-glm.html#cb495-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">filter</span>(Success <span class="op">&lt;</span><span class="st"> </span><span class="fl">0.55</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb495-3"><a href="extending-use-cases-of-glm.html#cb495-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">filter</span>(Success <span class="op">&gt;</span><span class="st"> </span><span class="fl">0.45</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb495-4"><a href="extending-use-cases-of-glm.html#cb495-4" aria-hidden="true"></a><span class="st">  </span><span class="kw">select</span>(Distance,Success)</span></code></pre></div>
<pre><code>##   Distance   Success
## 1       42 0.5449184
## 2       43 0.5122432
## 3       44 0.4794630</code></pre>
<!--
## Example: Island bird species

This example concerns the presence or absence on a set of islands of a particular species of bird. The response variable we are interested in is called "incidence" and a value of 1 means that the bird is present and breeding on the island, while a value of 0 means that the island has no breeding population there. The explanatory variable is the size of the island in $km^2$ and isolation (the distance of the island from the mainland in km).

Lets take a look at the data.


```r
island <- read.csv("CourseData/isolation.csv")

str(island)
```

```
## 'data.frame':	50 obs. of  3 variables:
##  $ incidence: int  1 0 1 0 0 1 1 0 1 1 ...
##  $ area     : num  7.93 1.93 2.04 4.78 1.54 ...
##  $ isolation: num  3.32 7.55 5.88 5.93 5.31 ...
```

In this case there are two explanatory variables and we are therefore going to fit a *multiple regression* model with two variables using the GLM framework. 


```r
model1 <- glm(incidence ~ area+isolation, data = island, family = binomial)
summary(model1)
```

```
## 
## Call:
## glm(formula = incidence ~ area + isolation, family = binomial, 
##     data = island)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.8189  -0.3089   0.0490   0.3635   2.1192  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(>|z|)   
## (Intercept)   6.6417     2.9218   2.273  0.02302 * 
## area          0.5807     0.2478   2.344  0.01909 * 
## isolation    -1.3719     0.4769  -2.877  0.00401 **
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 68.029  on 49  degrees of freedom
## Residual deviance: 28.402  on 47  degrees of freedom
## AIC: 34.402
## 
## Number of Fisher Scoring iterations: 6
```

Looking at coefficients and standard errors (which are on the logit scale) we can see that area has a significant positive effect on the probability of occupation (larger islands are more likely to be occupied) and isolation has a strong negative effect (isolated islands are much less likely to be occupied). To visualise this we can plot the model fits through a scatter plot of the data. It is best to do this separately for each variable so first we must make two separate models, one for each of the variables.


```r
modela <- glm(incidence ~ area, data = island, family = binomial)
modeli <- glm(incidence ~ isolation, data = island, family = binomial)
```

Then we can plot the two relationships in graphs side-by-side using the same approach as above. In these plots the fitted values (the modelled line) can be interpreted as a probability.


```r
par(mfrow=c(1,2))
plot(island$area,island$incidence)
newData <- data.frame(area = seq(0,9,0.01))
newData$fit <- predict(modela,newData,type="response")
lines(newData$area,newData$fit,col="red")

plot(island$isolation,island$incidence)
newData <- data.frame(isolation = seq(0,10,0.01))
newData$fit <- predict(modeli,newData,type="response")
lines(newData$isolation,newData$fit,col="red")
```

<img src="BB852_files/figure-html/unnamed-chunk-374-1.png" width="672" />
-->
</div>
<div id="example-sex-ratio-in-turtles" class="section level2" number="18.3">
<h2><span class="header-section-number">18.3</span> Example: Sex ratio in turtles</h2>
<p>In this example we will look at sex ratio of hawksbill turtles (<em>Eretmochelys imbricata</em>)<a href="#fn14" class="footnote-ref" id="fnref14"><sup>14</sup></a>. The data are counts of males and females in clutches of eggs incubated at different temperatures.</p>
<p>The sex ratio in the species varies with temperature during incubation. We are interested in what the “tipping point” temperature is between male-female biased ratios.</p>
<div class="sourceCode" id="cb497"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb497-1"><a href="extending-use-cases-of-glm.html#cb497-1" aria-hidden="true"></a>hawksbill &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;CourseData/hawksbill.csv&quot;</span>)</span></code></pre></div>
<p>This is a small dataset, you can look at the whole thing:</p>
<div class="sourceCode" id="cb498"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb498-1"><a href="extending-use-cases-of-glm.html#cb498-1" aria-hidden="true"></a>hawksbill</span></code></pre></div>
<pre><code>##   Temperature Total Nmale Nfemale
## 1        27.9    12    12       0
## 2        28.4    29    29       0
## 3        28.9    31    26       5
## 4        29.3    20    18       2
## 5        29.5    22    14       8
## 6        29.8    10     2       8
## 7        30.4    10     0      10</code></pre>
<p>We are interested in sex ratio which we can calculate as the proportion of the population that is female (i.e. number of females divided by total number).</p>
<div class="sourceCode" id="cb500"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb500-1"><a href="extending-use-cases-of-glm.html#cb500-1" aria-hidden="true"></a>hawksbill &lt;-<span class="st"> </span>hawksbill <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb500-2"><a href="extending-use-cases-of-glm.html#cb500-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">propFemale =</span> Nfemale<span class="op">/</span>(Nmale<span class="op">+</span>Nfemale))</span></code></pre></div>
<p>Let’s plot that data. We can use the trick of telling R to plot the points different sizes depending on the sample size (using the <code>size =</code> argument):</p>
<div class="sourceCode" id="cb501"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb501-1"><a href="extending-use-cases-of-glm.html#cb501-1" aria-hidden="true"></a>(A&lt;-<span class="kw">ggplot</span>(hawksbill,<span class="kw">aes</span>(<span class="dt">x =</span> Temperature,<span class="dt">y =</span> propFemale,<span class="dt">size =</span> Total))<span class="op">+</span></span>
<span id="cb501-2"><a href="extending-use-cases-of-glm.html#cb501-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_point</span>())</span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-378-1.png" width="480" style="display: block; margin: auto;" /></p>
<p>You can see that the proportion of females increases with temperature. Let’s fit a model to these data to better understand them. We could use the <code>propFemale</code> data as the response variable, but there is a big problem with that: we would be giving equal weight to each of the data points, even though the sample size for each one ranges from 10 to 31 This is not good because we would have much more faith in the very large sample sizes than the small ones.</p>
<p>Instead we can bind the data into a two column matrix using <code>cbind</code>. The first column is our “success” and the second column is our “failure”. If we put <code>females</code> in the first column the model will predict “probability of being female”, which is what we want. This two-column approach provides the model with the sample size which it can use to weight the regression appropriately.</p>
<div class="sourceCode" id="cb502"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb502-1"><a href="extending-use-cases-of-glm.html#cb502-1" aria-hidden="true"></a>y &lt;-<span class="st"> </span><span class="kw">cbind</span>(hawksbill<span class="op">$</span>Nfemale,hawksbill<span class="op">$</span>Nmale)</span></code></pre></div>
<p>Now lets fit the model.</p>
<div class="sourceCode" id="cb503"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb503-1"><a href="extending-use-cases-of-glm.html#cb503-1" aria-hidden="true"></a>modA &lt;-<span class="st"> </span><span class="kw">glm</span>(y <span class="op">~</span><span class="st"> </span>Temperature,<span class="dt">data=</span>hawksbill,<span class="dt">family =</span> binomial)</span></code></pre></div>
<p>As ever, we should take a quick look at the model diagnostic plots - these look OK.</p>
<div class="sourceCode" id="cb504"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb504-1"><a href="extending-use-cases-of-glm.html#cb504-1" aria-hidden="true"></a><span class="kw">library</span>(ggfortify)</span>
<span id="cb504-2"><a href="extending-use-cases-of-glm.html#cb504-2" aria-hidden="true"></a><span class="kw">autoplot</span>(modA)</span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-381-1.png" width="384" style="display: block; margin: auto;" /></p>
<p>Now we can look at the anova table. This will tell us what we already know - there is a strong effect of temperature on sex ratio.</p>
<div class="sourceCode" id="cb505"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb505-1"><a href="extending-use-cases-of-glm.html#cb505-1" aria-hidden="true"></a><span class="kw">anova</span>(modA,<span class="dt">test=</span><span class="st">&quot;Chi&quot;</span>)</span></code></pre></div>
<pre><code>## Analysis of Deviance Table
## 
## Model: binomial, link: logit
## 
## Response: y
## 
## Terms added sequentially (first to last)
## 
## 
##             Df Deviance Resid. Df Resid. Dev  Pr(&gt;Chi)    
## NULL                            6     70.353              
## Temperature  1   61.869         5      8.484 3.671e-15 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Now for the coefficients:</p>
<div class="sourceCode" id="cb507"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb507-1"><a href="extending-use-cases-of-glm.html#cb507-1" aria-hidden="true"></a><span class="kw">summary</span>(modA)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = y ~ Temperature, family = binomial, data = hawksbill)
## 
## Deviance Residuals: 
##       1        2        3        4        5        6        7  
## -0.2010  -0.8013   1.7632  -1.6999  -0.4885   0.8010   0.9607  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -111.7200    22.4260  -4.982 6.30e-07 ***
## Temperature    3.7754     0.7625   4.951 7.37e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 70.3528  on 6  degrees of freedom
## Residual deviance:  8.4841  on 5  degrees of freedom
## AIC: 24.184
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>This table gives us the coefficients for the formula of our relationship. We could use these to produce a formula of the form <span class="math inline">\(y =\frac{1}{1+exp(-(\beta_0 + \beta_1 x))}\)</span>.</p>
<p>It is perhaps more useful to plot the model fit onto the plot. First we need to create a data frame to predict from:</p>
<div class="sourceCode" id="cb509"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb509-1"><a href="extending-use-cases-of-glm.html#cb509-1" aria-hidden="true"></a>newDat &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">Temperature =</span> <span class="kw">seq</span>(<span class="fl">27.9</span>,<span class="fl">30.4</span>,<span class="fl">0.1</span>))</span></code></pre></div>
<p>Now we can predict the values (and 95% CI) on the scale of the linear predictor (logit).</p>
<div class="sourceCode" id="cb510"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb510-1"><a href="extending-use-cases-of-glm.html#cb510-1" aria-hidden="true"></a>pv&lt;-<span class="kw">predict</span>(modA,newDat,<span class="dt">se.fit =</span> <span class="ot">TRUE</span>)</span>
<span id="cb510-2"><a href="extending-use-cases-of-glm.html#cb510-2" aria-hidden="true"></a>newDat &lt;-<span class="st"> </span>newDat <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb510-3"><a href="extending-use-cases-of-glm.html#cb510-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">propFemale_LP =</span> pv<span class="op">$</span>fit,</span>
<span id="cb510-4"><a href="extending-use-cases-of-glm.html#cb510-4" aria-hidden="true"></a>         <span class="dt">lowerCI_LP =</span> pv<span class="op">$</span>fit <span class="op">-</span><span class="st"> </span><span class="fl">1.96</span><span class="op">*</span>pv<span class="op">$</span>se.fit,</span>
<span id="cb510-5"><a href="extending-use-cases-of-glm.html#cb510-5" aria-hidden="true"></a>         <span class="dt">upperCI_LP =</span> pv<span class="op">$</span>fit <span class="op">+</span><span class="st"> </span><span class="fl">1.96</span><span class="op">*</span>pv<span class="op">$</span>se.fit)</span></code></pre></div>
<p>Now we can use the inverse link function to backtransform to the natural probability scale.</p>
<div class="sourceCode" id="cb511"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb511-1"><a href="extending-use-cases-of-glm.html#cb511-1" aria-hidden="true"></a><span class="co">#Get the inverse link function</span></span>
<span id="cb511-2"><a href="extending-use-cases-of-glm.html#cb511-2" aria-hidden="true"></a>inverseFunction &lt;-<span class="kw">family</span>(modA)<span class="op">$</span>linkinv</span>
<span id="cb511-3"><a href="extending-use-cases-of-glm.html#cb511-3" aria-hidden="true"></a></span>
<span id="cb511-4"><a href="extending-use-cases-of-glm.html#cb511-4" aria-hidden="true"></a><span class="co">#transform predicted data to the natural scale</span></span>
<span id="cb511-5"><a href="extending-use-cases-of-glm.html#cb511-5" aria-hidden="true"></a>newDat &lt;-<span class="st"> </span>newDat <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb511-6"><a href="extending-use-cases-of-glm.html#cb511-6" aria-hidden="true"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">propFemale =</span> <span class="kw">inverseFunction</span>(propFemale_LP),</span>
<span id="cb511-7"><a href="extending-use-cases-of-glm.html#cb511-7" aria-hidden="true"></a>         <span class="dt">ymin=</span> <span class="kw">inverseFunction</span>(lowerCI_LP),</span>
<span id="cb511-8"><a href="extending-use-cases-of-glm.html#cb511-8" aria-hidden="true"></a>         <span class="dt">ymax =</span> <span class="kw">inverseFunction</span>(upperCI_LP))</span></code></pre></div>
<p>We can add these values to the plot like this:</p>
<div class="sourceCode" id="cb512"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb512-1"><a href="extending-use-cases-of-glm.html#cb512-1" aria-hidden="true"></a><span class="co">#The plot and ribbon</span></span>
<span id="cb512-2"><a href="extending-use-cases-of-glm.html#cb512-2" aria-hidden="true"></a>(A&lt;-<span class="kw">ggplot</span>(hawksbill,<span class="kw">aes</span>(<span class="dt">x =</span> Temperature,<span class="dt">y =</span> propFemale, <span class="dt">size =</span> Total))<span class="op">+</span></span>
<span id="cb512-3"><a href="extending-use-cases-of-glm.html#cb512-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_ribbon</span>(<span class="dt">data =</span> newDat,<span class="kw">aes</span>(<span class="dt">x =</span>Temperature,<span class="dt">ymin=</span>ymin,<span class="dt">ymax=</span>ymax),</span>
<span id="cb512-4"><a href="extending-use-cases-of-glm.html#cb512-4" aria-hidden="true"></a>                <span class="dt">fill=</span><span class="st">&quot;grey75&quot;</span>,<span class="dt">alpha =</span> <span class="fl">0.5</span>,<span class="dt">inherit.aes=</span><span class="ot">FALSE</span>)<span class="op">+</span></span>
<span id="cb512-5"><a href="extending-use-cases-of-glm.html#cb512-5" aria-hidden="true"></a><span class="st">    </span><span class="kw">geom_smooth</span>(<span class="dt">data =</span> newDat,<span class="kw">aes</span>(<span class="dt">x =</span> Temperature,<span class="dt">y=</span>propFemale),<span class="dt">stat=</span><span class="st">&quot;identity&quot;</span>,<span class="dt">inherit.aes=</span><span class="ot">FALSE</span>)<span class="op">+</span></span>
<span id="cb512-6"><a href="extending-use-cases-of-glm.html#cb512-6" aria-hidden="true"></a><span class="st"> </span><span class="kw">geom_point</span>())</span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-387-1.png" width="480" style="display: block; margin: auto;" /></p>
<p>Can you give read off the graph the approximate estimated temperature at which sex ratio is 50:50?</p>
<div class="do-something">
<ol style="list-style-type: decimal">
<li>
Try refitting the model using simply the proportion female (<code>propFemale</code>) data rather than the two-column (<code>cbind</code>) approach.
</li>
<li>
Try writing up the result in the same way as shown for the NFL field goals example.
</li>
</ol>
</div>
</div>
<div id="example-smoking" class="section level2" number="18.4">
<h2><span class="header-section-number">18.4</span> Example: Smoking</h2>
<p>As I mentioned above binomial regression can be applied to anything where there data can be classified into two groups. I’ll illustrate that now with an example about smoking.</p>
<p>The data set is very small and looks like this:</p>
<table>
<thead>
<tr class="header">
<th align="center"></th>
<th align="center">Student smokes</th>
<th align="center">Student does not smoke</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Parent(s) smoke</td>
<td align="center">816</td>
<td align="center">3203</td>
</tr>
<tr class="even">
<td align="center">No parents smoke</td>
<td align="center">188</td>
<td align="center">1168</td>
</tr>
</tbody>
</table>
<p>The dataset is the number of students smoking and not smoking grouped according to whether their parents smoke.
These data are binomial/proportion data because the values in the cells of the table are constrained by the overall total and students must fall into one of the categories. We can use these data to calculate the probability of the student being a smoker.</p>
<p>Before fitting a GLM lets just work out these probabilities by hand. What is the probability that a child of smoking parents is a smoker themselves? This is simply 816/(816+3203) = 0.2030. (i.e. it is the number of smokers divided by the total number). Similarly, the probability that the child of non-smokers smokes is 188/(188+1168) = 0.1386.</p>
<p>But is this a significant difference? That is what we are trying to find out using a GLM.</p>
<p>To do this, we can turn these data into a two column matrix of success (yes - smoker) and failure (no - non-smoker).</p>
<div class="sourceCode" id="cb513"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb513-1"><a href="extending-use-cases-of-glm.html#cb513-1" aria-hidden="true"></a>y &lt;-<span class="st"> </span><span class="kw">cbind</span>(<span class="st">&quot;1_yes&quot;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="dv">816</span>,<span class="dv">188</span>),<span class="st">&quot;0_no&quot;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="dv">3203</span>,<span class="dv">1168</span>))</span>
<span id="cb513-2"><a href="extending-use-cases-of-glm.html#cb513-2" aria-hidden="true"></a>y</span></code></pre></div>
<pre><code>##      1_yes 0_no
## [1,]   816 3203
## [2,]   188 1168</code></pre>
<p>So we can see “success” on the left and “failure” on the right“.
We now create a (tiny) <code>data.frame</code> for the parental status (smoker =”1_yes“, non-smoker =”0_no").</p>
<div class="sourceCode" id="cb515"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb515-1"><a href="extending-use-cases-of-glm.html#cb515-1" aria-hidden="true"></a>smoke &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">parentSmoke =</span> <span class="kw">c</span>(<span class="st">&quot;1_yes&quot;</span>,<span class="st">&quot;0_no&quot;</span>))</span></code></pre></div>
<p>Now we can fit the model. Pause now and think about what the NULL hypothesis is here. It is that parental smoking does not have any influence on whether the child smokes, and that the probability that the student smokes is unrelated to parental smoking.</p>
<div class="sourceCode" id="cb516"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb516-1"><a href="extending-use-cases-of-glm.html#cb516-1" aria-hidden="true"></a>smokeMod &lt;-<span class="st"> </span><span class="kw">glm</span>(y<span class="op">~</span>parentSmoke,<span class="dt">data =</span> smoke,<span class="dt">family=</span>binomial)</span></code></pre></div>
<p>With such a small dataset, diagnostic plots will not tell us anything useful so there’s no point in doing them for this case.</p>
<p>As usual, we first ask for the (Analysis of Deviance table using <code>anova</code>.</p>
<div class="sourceCode" id="cb517"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb517-1"><a href="extending-use-cases-of-glm.html#cb517-1" aria-hidden="true"></a><span class="kw">anova</span>(smokeMod,<span class="dt">test=</span><span class="st">&quot;Chi&quot;</span>)</span></code></pre></div>
<pre><code>## Analysis of Deviance Table
## 
## Model: binomial, link: logit
## 
## Response: y
## 
## Terms added sequentially (first to last)
## 
## 
##             Df Deviance Resid. Df Resid. Dev  Pr(&gt;Chi)    
## NULL                            1     29.121              
## parentSmoke  1   29.121         0      0.000 6.801e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>This tells us that the status of the parents (whether they smoke or not) is highly significant: it explains a lot of the pattern that we see in the data.</p>
<p>We can find out what this pattern is by examining the <code>summary</code> table.</p>
<div class="sourceCode" id="cb519"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb519-1"><a href="extending-use-cases-of-glm.html#cb519-1" aria-hidden="true"></a><span class="kw">summary</span>(smokeMod)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = y ~ parentSmoke, family = binomial, data = smoke)
## 
## Deviance Residuals: 
## [1]  0  0
## 
## Coefficients:
##                  Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)      -1.82661    0.07858 -23.244  &lt; 2e-16 ***
## parentSmoke1_yes  0.45918    0.08782   5.228 1.71e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance:  2.9121e+01  on 1  degrees of freedom
## Residual deviance: -3.7170e-13  on 0  degrees of freedom
## AIC: 19.242
## 
## Number of Fisher Scoring iterations: 2</code></pre>
<p>This shows us the estimates on the logit scale. We can use <code>predict</code> to get a sense for these predictions on the more intuitive probability scale.
First we calculate the fitted values and 95% confidence intervals on the scale of the linear predictor (logit):</p>
<div class="sourceCode" id="cb521"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb521-1"><a href="extending-use-cases-of-glm.html#cb521-1" aria-hidden="true"></a>pv&lt;-<span class="kw">predict</span>(smokeMod,smoke,<span class="dt">se.fit =</span> <span class="ot">TRUE</span>)</span>
<span id="cb521-2"><a href="extending-use-cases-of-glm.html#cb521-2" aria-hidden="true"></a>smoke &lt;-<span class="st"> </span>smoke <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb521-3"><a href="extending-use-cases-of-glm.html#cb521-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">prob_LP =</span> pv<span class="op">$</span>fit,</span>
<span id="cb521-4"><a href="extending-use-cases-of-glm.html#cb521-4" aria-hidden="true"></a>         <span class="dt">lowerCI_LP =</span> pv<span class="op">$</span>fit <span class="op">-</span><span class="st"> </span><span class="fl">1.96</span><span class="op">*</span>pv<span class="op">$</span>se.fit,</span>
<span id="cb521-5"><a href="extending-use-cases-of-glm.html#cb521-5" aria-hidden="true"></a>         <span class="dt">upperCI_LP =</span> pv<span class="op">$</span>fit <span class="op">+</span><span class="st"> </span><span class="fl">1.96</span><span class="op">*</span>pv<span class="op">$</span>se.fit)</span></code></pre></div>
<p>Then we can backtransform these values to the probability scale using the inverse link function:</p>
<div class="sourceCode" id="cb522"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb522-1"><a href="extending-use-cases-of-glm.html#cb522-1" aria-hidden="true"></a><span class="co">#Get the inverse link function</span></span>
<span id="cb522-2"><a href="extending-use-cases-of-glm.html#cb522-2" aria-hidden="true"></a>inverseFunction &lt;-<span class="kw">family</span>(smokeMod)<span class="op">$</span>linkinv</span>
<span id="cb522-3"><a href="extending-use-cases-of-glm.html#cb522-3" aria-hidden="true"></a></span>
<span id="cb522-4"><a href="extending-use-cases-of-glm.html#cb522-4" aria-hidden="true"></a><span class="co">#transform predicted data to the natural scale</span></span>
<span id="cb522-5"><a href="extending-use-cases-of-glm.html#cb522-5" aria-hidden="true"></a>smoke &lt;-<span class="st"> </span>smoke <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb522-6"><a href="extending-use-cases-of-glm.html#cb522-6" aria-hidden="true"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">prob =</span> <span class="kw">inverseFunction</span>(prob_LP),</span>
<span id="cb522-7"><a href="extending-use-cases-of-glm.html#cb522-7" aria-hidden="true"></a>         <span class="dt">ymin=</span> <span class="kw">inverseFunction</span>(lowerCI_LP),</span>
<span id="cb522-8"><a href="extending-use-cases-of-glm.html#cb522-8" aria-hidden="true"></a>         <span class="dt">ymax =</span> <span class="kw">inverseFunction</span>(upperCI_LP))</span>
<span id="cb522-9"><a href="extending-use-cases-of-glm.html#cb522-9" aria-hidden="true"></a>smoke</span></code></pre></div>
<pre><code>##   parentSmoke   prob_LP lowerCI_LP upperCI_LP      prob      ymin      ymax
## 1       1_yes -1.367429  -1.444287  -1.290570 0.2030356 0.1908823 0.2157563
## 2        0_no -1.826606  -1.980629  -1.672583 0.1386431 0.1212518 0.1580801</code></pre>
<p>This table shows us that the probability of the students smoking is 0.2030 (95% CI = 0.191-0.216) for children of smokers, and 0.139 (95% CI = 0.121-0.158) for children of non-smokers. We can plot this using <code>ggplot</code> like this.</p>
<div class="sourceCode" id="cb524"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb524-1"><a href="extending-use-cases-of-glm.html#cb524-1" aria-hidden="true"></a><span class="kw">ggplot</span>(smoke,<span class="kw">aes</span>(<span class="dt">x=</span>parentSmoke,<span class="dt">y =</span> prob,<span class="dt">ymin =</span> ymin,<span class="dt">ymax=</span>ymax))<span class="op">+</span></span>
<span id="cb524-2"><a href="extending-use-cases-of-glm.html#cb524-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_point</span>()<span class="op">+</span></span>
<span id="cb524-3"><a href="extending-use-cases-of-glm.html#cb524-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_segment</span>(<span class="kw">aes</span>(<span class="dt">xend =</span> parentSmoke,<span class="dt">y =</span> ymin,<span class="dt">yend =</span> ymax))</span></code></pre></div>
<p><img src="BB852_files/figure-html/unnamed-chunk-396-1.png" width="672" /></p>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="13">
<li id="fn13"><p>weights allow some data points to be more influential than others - for example you would want to give more importance to points that represent large sample sizes<a href="extending-use-cases-of-glm.html#fnref13" class="footnote-back">↩︎</a></p></li>
<li id="fn14"><p>data from: Godfrey et al. (1999) Can. J. Zool. 77: 1465–1473<a href="extending-use-cases-of-glm.html#fnref14" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="generalised-linear-models.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="power-analysis-by-simulation.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/jonesor/BB852_Book/edit/master/3_08-GLM-otherFamilies.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["BB852.pdf"],
"toc": {
"collapse": "section"
},
"split_by": "section"
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
