<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 16 Linear regression: models with a single continuous explanatory variable | BB852 - Data handling, visualisation and statistics</title>
  <meta name="description" content="Course book for BB852 at the Biology Department, University of Southern Denmark" />
  <meta name="generator" content="bookdown 0.33 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 16 Linear regression: models with a single continuous explanatory variable | BB852 - Data handling, visualisation and statistics" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Course book for BB852 at the Biology Department, University of Southern Denmark" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 16 Linear regression: models with a single continuous explanatory variable | BB852 - Data handling, visualisation and statistics" />
  
  <meta name="twitter:description" content="Course book for BB852 at the Biology Department, University of Southern Denmark" />
  

<meta name="author" content="Owen R. Jones" />


<meta name="date" content="2024-03-04" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="anova-linear-models-with-a-single-categorical-explanatory-variable.html"/>
<link rel="next" href="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/tabwid-1.1.3/tabwid.css" rel="stylesheet" />
<script src="libs/tabwid-1.1.3/tabwid.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">BB852</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Preface</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#data-wrangling"><i class="fa fa-check"></i><b>1.1</b> Data wrangling</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#data-visualisation"><i class="fa fa-check"></i><b>1.2</b> Data visualisation</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#statistics"><i class="fa fa-check"></i><b>1.3</b> Statistics</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#data-sources"><i class="fa fa-check"></i><b>1.4</b> Data sources</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#your-instructors"><i class="fa fa-check"></i><b>1.5</b> Your instructor(s)</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#expectations"><i class="fa fa-check"></i><b>1.6</b> Expectations</a></li>
<li class="chapter" data-level="1.7" data-path="index.html"><a href="index.html#your-feedback"><i class="fa fa-check"></i><b>1.7</b> Your feedback</a></li>
<li class="chapter" data-level="1.8" data-path="index.html"><a href="index.html#assessment"><i class="fa fa-check"></i><b>1.8</b> Assessment</a></li>
<li class="chapter" data-level="1.9" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i><b>1.9</b> Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="schedule.html"><a href="schedule.html"><i class="fa fa-check"></i><b>2</b> Schedule</a></li>
<li class="chapter" data-level="3" data-path="additional-recommended-reading.html"><a href="additional-recommended-reading.html"><i class="fa fa-check"></i><b>3</b> Additional recommended reading</a></li>
<li class="chapter" data-level="4" data-path="an-r-refresher.html"><a href="an-r-refresher.html"><i class="fa fa-check"></i><b>4</b> An R refresher</a>
<ul>
<li class="chapter" data-level="4.1" data-path="an-r-refresher.html"><a href="an-r-refresher.html#getting-started-with-r"><i class="fa fa-check"></i><b>4.1</b> Getting started with R</a></li>
<li class="chapter" data-level="4.2" data-path="an-r-refresher.html"><a href="an-r-refresher.html#getting-help"><i class="fa fa-check"></i><b>4.2</b> Getting help</a></li>
<li class="chapter" data-level="4.3" data-path="an-r-refresher.html"><a href="an-r-refresher.html#r-as-a-fancy-calculator"><i class="fa fa-check"></i><b>4.3</b> R as a fancy calculator</a></li>
<li class="chapter" data-level="4.4" data-path="an-r-refresher.html"><a href="an-r-refresher.html#objects-in-r"><i class="fa fa-check"></i><b>4.4</b> Objects in R</a></li>
<li class="chapter" data-level="4.5" data-path="an-r-refresher.html"><a href="an-r-refresher.html#manipulating-objects"><i class="fa fa-check"></i><b>4.5</b> Manipulating objects</a></li>
<li class="chapter" data-level="4.6" data-path="an-r-refresher.html"><a href="an-r-refresher.html#missing-values-infinity-and-non-numbers"><i class="fa fa-check"></i><b>4.6</b> Missing values, infinity and “non-numbers”</a></li>
<li class="chapter" data-level="4.7" data-path="an-r-refresher.html"><a href="an-r-refresher.html#basic-information-about-objects"><i class="fa fa-check"></i><b>4.7</b> Basic information about objects</a></li>
<li class="chapter" data-level="4.8" data-path="an-r-refresher.html"><a href="an-r-refresher.html#data-frames"><i class="fa fa-check"></i><b>4.8</b> Data frames</a></li>
<li class="chapter" data-level="4.9" data-path="an-r-refresher.html"><a href="an-r-refresher.html#classes-in-r"><i class="fa fa-check"></i><b>4.9</b> Classes in R</a></li>
<li class="chapter" data-level="4.10" data-path="an-r-refresher.html"><a href="an-r-refresher.html#organising-your-work"><i class="fa fa-check"></i><b>4.10</b> Organising your work</a></li>
<li class="chapter" data-level="4.11" data-path="an-r-refresher.html"><a href="an-r-refresher.html#inspecting-the-data"><i class="fa fa-check"></i><b>4.11</b> Inspecting the data</a></li>
<li class="chapter" data-level="4.12" data-path="an-r-refresher.html"><a href="an-r-refresher.html#classes-in-r-1"><i class="fa fa-check"></i><b>4.12</b> “Classes” in R</a></li>
<li class="chapter" data-level="4.13" data-path="an-r-refresher.html"><a href="an-r-refresher.html#tables-and-summary-statistics"><i class="fa fa-check"></i><b>4.13</b> Tables and summary statistics</a></li>
<li class="chapter" data-level="4.14" data-path="an-r-refresher.html"><a href="an-r-refresher.html#plotting-data"><i class="fa fa-check"></i><b>4.14</b> Plotting data</a></li>
<li class="chapter" data-level="4.15" data-path="an-r-refresher.html"><a href="an-r-refresher.html#r-packages"><i class="fa fa-check"></i><b>4.15</b> R Packages</a></li>
<li class="chapter" data-level="4.16" data-path="an-r-refresher.html"><a href="an-r-refresher.html#exercise-californian-bird-diversity"><i class="fa fa-check"></i><b>4.16</b> Exercise: Californian bird diversity</a>
<ul>
<li class="chapter" data-level="4.16.1" data-path="an-r-refresher.html"><a href="an-r-refresher.html#the-data"><i class="fa fa-check"></i><b>4.16.1</b> The data</a></li>
<li class="chapter" data-level="4.16.2" data-path="an-r-refresher.html"><a href="an-r-refresher.html#try-the-following"><i class="fa fa-check"></i><b>4.16.2</b> Try the following</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html"><i class="fa fa-check"></i><b>5</b> Tips and tricks</a>
<ul>
<li class="chapter" data-level="5.1" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#appearance"><i class="fa fa-check"></i><b>5.1</b> Appearance</a></li>
<li class="chapter" data-level="5.2" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#shortcuts"><i class="fa fa-check"></i><b>5.2</b> Shortcuts</a></li>
<li class="chapter" data-level="5.3" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#code-style"><i class="fa fa-check"></i><b>5.3</b> Code style</a></li>
<li class="chapter" data-level="5.4" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#the-plots-pane"><i class="fa fa-check"></i><b>5.4</b> The plots pane</a></li>
<li class="chapter" data-level="5.5" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#tables"><i class="fa fa-check"></i><b>5.5</b> Tables</a></li>
<li class="chapter" data-level="5.6" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#importing-data-from-text-files"><i class="fa fa-check"></i><b>5.6</b> Importing data from text files</a></li>
<li class="chapter" data-level="5.7" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#importing-data-from-excel"><i class="fa fa-check"></i><b>5.7</b> Importing data from Excel</a></li>
<li class="chapter" data-level="5.8" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#numbers"><i class="fa fa-check"></i><b>5.8</b> Numbers</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="paths-and-projects.html"><a href="paths-and-projects.html"><i class="fa fa-check"></i><b>6</b> Paths and projects</a>
<ul>
<li class="chapter" data-level="6.1" data-path="paths-and-projects.html"><a href="paths-and-projects.html#file-structure"><i class="fa fa-check"></i><b>6.1</b> File structure</a></li>
<li class="chapter" data-level="6.2" data-path="paths-and-projects.html"><a href="paths-and-projects.html#paths-and-the-command-line"><i class="fa fa-check"></i><b>6.2</b> Paths and the command line</a></li>
<li class="chapter" data-level="6.3" data-path="paths-and-projects.html"><a href="paths-and-projects.html#r-and-file-structure"><i class="fa fa-check"></i><b>6.3</b> R and file structure</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="paths-and-projects.html"><a href="paths-and-projects.html#setting-the-working-directory"><i class="fa fa-check"></i><b>6.3.1</b> Setting the working directory</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="paths-and-projects.html"><a href="paths-and-projects.html#projects-in-r"><i class="fa fa-check"></i><b>6.4</b> Projects in R</a></li>
</ul></li>
<li class="part"><span><b>I Data Wrangling</b></span></li>
<li class="chapter" data-level="7" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html"><i class="fa fa-check"></i><b>7</b> Data wrangling with <code>dplyr</code></a>
<ul>
<li class="chapter" data-level="7.1" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#select"><i class="fa fa-check"></i><b>7.1</b> <code>select</code></a></li>
<li class="chapter" data-level="7.2" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#filter"><i class="fa fa-check"></i><b>7.2</b> <code>filter</code></a></li>
<li class="chapter" data-level="7.3" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#arrange"><i class="fa fa-check"></i><b>7.3</b> <code>arrange</code></a></li>
<li class="chapter" data-level="7.4" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#summarise-and-group_by"><i class="fa fa-check"></i><b>7.4</b> <code>summarise</code> and <code>group_by</code></a></li>
<li class="chapter" data-level="7.5" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#using-pipes-saving-data."><i class="fa fa-check"></i><b>7.5</b> Using pipes, saving data.</a></li>
<li class="chapter" data-level="7.6" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#exercise-wrangling-the-amniote-life-history-database"><i class="fa fa-check"></i><b>7.6</b> Exercise: Wrangling the Amniote Life History Database</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="combining-data-sets.html"><a href="combining-data-sets.html"><i class="fa fa-check"></i><b>8</b> Combining data sets</a>
<ul>
<li class="chapter" data-level="8.1" data-path="combining-data-sets.html"><a href="combining-data-sets.html#using-join"><i class="fa fa-check"></i><b>8.1</b> Using <code>join</code></a></li>
<li class="chapter" data-level="8.2" data-path="combining-data-sets.html"><a href="combining-data-sets.html#using-pivot_longer"><i class="fa fa-check"></i><b>8.2</b> Using <code>pivot_longer</code></a></li>
<li class="chapter" data-level="8.3" data-path="combining-data-sets.html"><a href="combining-data-sets.html#exercise-temperature-effects-on-egg-laying-dates"><i class="fa fa-check"></i><b>8.3</b> Exercise: Temperature effects on egg laying dates</a></li>
</ul></li>
<li class="part"><span><b>II Data visualisation</b></span></li>
<li class="chapter" data-level="9" data-path="visualising-data-with-ggplot2.html"><a href="visualising-data-with-ggplot2.html"><i class="fa fa-check"></i><b>9</b> Visualising data with <code>ggplot2</code></a>
<ul>
<li class="chapter" data-level="9.1" data-path="visualising-data-with-ggplot2.html"><a href="visualising-data-with-ggplot2.html#histograms"><i class="fa fa-check"></i><b>9.1</b> Histograms</a></li>
<li class="chapter" data-level="9.2" data-path="visualising-data-with-ggplot2.html"><a href="visualising-data-with-ggplot2.html#facets---splitting-data-across-panels"><i class="fa fa-check"></i><b>9.2</b> “Facets” - splitting data across panels</a></li>
<li class="chapter" data-level="9.3" data-path="visualising-data-with-ggplot2.html"><a href="visualising-data-with-ggplot2.html#box-plots"><i class="fa fa-check"></i><b>9.3</b> Box plots</a></li>
<li class="chapter" data-level="9.4" data-path="visualising-data-with-ggplot2.html"><a href="visualising-data-with-ggplot2.html#lines-and-points"><i class="fa fa-check"></i><b>9.4</b> Lines and points</a></li>
<li class="chapter" data-level="9.5" data-path="visualising-data-with-ggplot2.html"><a href="visualising-data-with-ggplot2.html#scatter-plots"><i class="fa fa-check"></i><b>9.5</b> Scatter plots</a></li>
<li class="chapter" data-level="9.6" data-path="visualising-data-with-ggplot2.html"><a href="visualising-data-with-ggplot2.html#bar-plots"><i class="fa fa-check"></i><b>9.6</b> Bar plots</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html"><i class="fa fa-check"></i><b>10</b> Distributions and summarising data</a>
<ul>
<li class="chapter" data-level="10.1" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#distributions"><i class="fa fa-check"></i><b>10.1</b> Distributions</a></li>
<li class="chapter" data-level="10.2" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#normal-distribution"><i class="fa fa-check"></i><b>10.2</b> Normal distribution</a></li>
<li class="chapter" data-level="10.3" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#comparing-normal-distributions"><i class="fa fa-check"></i><b>10.3</b> Comparing normal distributions</a></li>
<li class="chapter" data-level="10.4" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#poisson-distribution"><i class="fa fa-check"></i><b>10.4</b> Poisson distribution</a></li>
<li class="chapter" data-level="10.5" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#comparing-normal-and-poisson-distributions"><i class="fa fa-check"></i><b>10.5</b> Comparing normal and Poisson distributions</a></li>
<li class="chapter" data-level="10.6" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#the-law-of-large-numbers"><i class="fa fa-check"></i><b>10.6</b> The law of large numbers</a>
<ul>
<li class="chapter" data-level="10.6.1" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#coin-flipping"><i class="fa fa-check"></i><b>10.6.1</b> Coin flipping</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#exercise-virtual-dice"><i class="fa fa-check"></i><b>10.7</b> Exercise: Virtual dice</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html"><i class="fa fa-check"></i><b>11</b> Pimping your plots</a>
<ul>
<li class="chapter" data-level="11.1" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#a-basic-plot"><i class="fa fa-check"></i><b>11.1</b> A basic plot</a></li>
<li class="chapter" data-level="11.2" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#axis-limits"><i class="fa fa-check"></i><b>11.2</b> Axis limits</a></li>
<li class="chapter" data-level="11.3" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#transforming-the-axis-log-scale"><i class="fa fa-check"></i><b>11.3</b> Transforming the axis (log scale)</a></li>
<li class="chapter" data-level="11.4" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#changing-the-axis-tick-marks"><i class="fa fa-check"></i><b>11.4</b> Changing the axis tick marks</a></li>
<li class="chapter" data-level="11.5" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#axis-labels"><i class="fa fa-check"></i><b>11.5</b> Axis labels</a></li>
<li class="chapter" data-level="11.6" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#colours"><i class="fa fa-check"></i><b>11.6</b> Colours</a></li>
<li class="chapter" data-level="11.7" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#themes"><i class="fa fa-check"></i><b>11.7</b> Themes</a></li>
<li class="chapter" data-level="11.8" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#moving-the-legend"><i class="fa fa-check"></i><b>11.8</b> Moving the legend</a></li>
<li class="chapter" data-level="11.9" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#combining-multiple-plots"><i class="fa fa-check"></i><b>11.9</b> Combining multiple plots</a></li>
<li class="chapter" data-level="11.10" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#saving-your-plot"><i class="fa fa-check"></i><b>11.10</b> Saving your plot</a></li>
<li class="chapter" data-level="11.11" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#final-word-on-plots"><i class="fa fa-check"></i><b>11.11</b> Final word on plots</a></li>
</ul></li>
<li class="part"><span><b>III Statistics</b></span></li>
<li class="chapter" data-level="12" data-path="randomisation-tests.html"><a href="randomisation-tests.html"><i class="fa fa-check"></i><b>12</b> Randomisation Tests</a>
<ul>
<li class="chapter" data-level="12.1" data-path="randomisation-tests.html"><a href="randomisation-tests.html#randomisation-test-in-r"><i class="fa fa-check"></i><b>12.1</b> Randomisation test in R</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="randomisation-tests.html"><a href="randomisation-tests.html#calculate-the-observed-difference"><i class="fa fa-check"></i><b>12.1.1</b> Calculate the observed difference</a></li>
<li class="chapter" data-level="12.1.2" data-path="randomisation-tests.html"><a href="randomisation-tests.html#null-distribution"><i class="fa fa-check"></i><b>12.1.2</b> Null distribution</a></li>
<li class="chapter" data-level="12.1.3" data-path="randomisation-tests.html"><a href="randomisation-tests.html#testing-significance"><i class="fa fa-check"></i><b>12.1.3</b> Testing significance</a></li>
<li class="chapter" data-level="12.1.4" data-path="randomisation-tests.html"><a href="randomisation-tests.html#testing-the-hypothesis"><i class="fa fa-check"></i><b>12.1.4</b> Testing the hypothesis</a></li>
<li class="chapter" data-level="12.1.5" data-path="randomisation-tests.html"><a href="randomisation-tests.html#writing-it-up"><i class="fa fa-check"></i><b>12.1.5</b> Writing it up</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="randomisation-tests.html"><a href="randomisation-tests.html#paired-randomisation-tests"><i class="fa fa-check"></i><b>12.2</b> Paired Randomisation Tests</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="randomisation-tests.html"><a href="randomisation-tests.html#the-randomisation-test"><i class="fa fa-check"></i><b>12.2.1</b> The randomisation test</a></li>
<li class="chapter" data-level="12.2.2" data-path="randomisation-tests.html"><a href="randomisation-tests.html#null-distribution-1"><i class="fa fa-check"></i><b>12.2.2</b> Null distribution</a></li>
<li class="chapter" data-level="12.2.3" data-path="randomisation-tests.html"><a href="randomisation-tests.html#the-formal-hypothesis-test"><i class="fa fa-check"></i><b>12.2.3</b> The formal hypothesis test</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="randomisation-tests.html"><a href="randomisation-tests.html#exercise-sexual-selection-in-hercules-beetles"><i class="fa fa-check"></i><b>12.3</b> Exercise: Sexual selection in Hercules beetles</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html"><i class="fa fa-check"></i><b>13</b> t-test: Comparing two means</a>
<ul>
<li class="chapter" data-level="13.1" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#some-theory"><i class="fa fa-check"></i><b>13.1</b> Some theory</a></li>
<li class="chapter" data-level="13.2" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#one-sample-t-test"><i class="fa fa-check"></i><b>13.2</b> One sample t-test</a></li>
<li class="chapter" data-level="13.3" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#doing-it-by-hand---where-does-the-t-statistic-come-from"><i class="fa fa-check"></i><b>13.3</b> Doing it “by hand” - where does the t-statistic come from?</a></li>
<li class="chapter" data-level="13.4" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#paired-t-test"><i class="fa fa-check"></i><b>13.4</b> Paired t-test</a></li>
<li class="chapter" data-level="13.5" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#a-paired-t-test-is-a-one-sample-test."><i class="fa fa-check"></i><b>13.5</b> A paired t-test is a one-sample test.</a></li>
<li class="chapter" data-level="13.6" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#two-sample-t-test"><i class="fa fa-check"></i><b>13.6</b> Two sample t-test</a></li>
<li class="chapter" data-level="13.7" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#t-tests-are-linear-models"><i class="fa fa-check"></i><b>13.7</b> t-tests are linear models</a></li>
<li class="chapter" data-level="13.8" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#exercise-sex-differences-in-fine-motor-skills"><i class="fa fa-check"></i><b>13.8</b> Exercise: Sex differences in fine motor skills</a></li>
<li class="chapter" data-level="13.9" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#exercise-therapy-for-anorexia"><i class="fa fa-check"></i><b>13.9</b> Exercise: Therapy for anorexia</a></li>
<li class="chapter" data-level="13.10" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#exercise-compare-t-tests-with-randomisation-tests-optional"><i class="fa fa-check"></i><b>13.10</b> Exercise: Compare t-tests with randomisation tests (optional)</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="assumptions-in-linear-models.html"><a href="assumptions-in-linear-models.html"><i class="fa fa-check"></i><b>14</b> Assumptions in linear models</a>
<ul>
<li class="chapter" data-level="14.1" data-path="assumptions-in-linear-models.html"><a href="assumptions-in-linear-models.html#the-assumptions"><i class="fa fa-check"></i><b>14.1</b> The assumptions</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><i class="fa fa-check"></i><b>15</b> ANOVA: Linear models with a single categorical explanatory variable</a>
<ul>
<li class="chapter" data-level="15.1" data-path="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#one-way-anova"><i class="fa fa-check"></i><b>15.1</b> One-way ANOVA</a></li>
<li class="chapter" data-level="15.2" data-path="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#fitting-an-anova-in-r"><i class="fa fa-check"></i><b>15.2</b> Fitting an ANOVA in R</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#where-are-the-differences"><i class="fa fa-check"></i><b>15.2.1</b> Where are the differences?</a></li>
<li class="chapter" data-level="15.2.2" data-path="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#tukeys-honestly-significant-difference-hsd"><i class="fa fa-check"></i><b>15.2.2</b> Tukey’s Honestly Significant Difference (HSD)</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#anova-calculation-by-hand."><i class="fa fa-check"></i><b>15.3</b> ANOVA calculation “by hand”.</a></li>
<li class="chapter" data-level="15.4" data-path="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#exercise-apple-tree-crop-yield"><i class="fa fa-check"></i><b>15.4</b> Exercise: Apple tree crop yield</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="linear-regression-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html"><i class="fa fa-check"></i><b>16</b> Linear regression: models with a single continuous explanatory variable</a>
<ul>
<li class="chapter" data-level="16.1" data-path="linear-regression-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#some-theory-1"><i class="fa fa-check"></i><b>16.1</b> Some theory</a></li>
<li class="chapter" data-level="16.2" data-path="linear-regression-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#evaluating-a-hypothesis-with-a-linear-regression-model"><i class="fa fa-check"></i><b>16.2</b> Evaluating a hypothesis with a linear regression model</a></li>
<li class="chapter" data-level="16.3" data-path="linear-regression-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#assumptions"><i class="fa fa-check"></i><b>16.3</b> Assumptions</a></li>
<li class="chapter" data-level="16.4" data-path="linear-regression-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#worked-example-height-hand-width-relationship"><i class="fa fa-check"></i><b>16.4</b> Worked example: height-hand width relationship</a></li>
<li class="chapter" data-level="16.5" data-path="linear-regression-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#exercise-chirping-crickets"><i class="fa fa-check"></i><b>16.5</b> Exercise: Chirping crickets</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html"><a href="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html"><i class="fa fa-check"></i><b>17</b> ANCOVA: Linear models with categorical and continuous explanatory variables</a>
<ul>
<li class="chapter" data-level="17.1" data-path="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html"><a href="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html#the-height-hand-width-example."><i class="fa fa-check"></i><b>17.1</b> The height ~ hand width example.</a></li>
<li class="chapter" data-level="17.2" data-path="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html"><a href="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html#summarising-with-anova"><i class="fa fa-check"></i><b>17.2</b> Summarising with <code>anova</code></a></li>
<li class="chapter" data-level="17.3" data-path="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html"><a href="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html#the-summary-of-coefficients-summary"><i class="fa fa-check"></i><b>17.3</b> The summary of coefficients (<code>summary</code>)</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html"><i class="fa fa-check"></i><b>18</b> n-way ANOVA: Linear models with &gt;1 categorical explanatory variables</a>
<ul>
<li class="chapter" data-level="18.1" data-path="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#fitting-a-two-way-anova-model"><i class="fa fa-check"></i><b>18.1</b> Fitting a two-way ANOVA model</a></li>
<li class="chapter" data-level="18.2" data-path="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#summarising-the-model-anova"><i class="fa fa-check"></i><b>18.2</b> Summarising the model (<code>anova</code>)</a></li>
<li class="chapter" data-level="18.3" data-path="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#summarising-the-model-summary"><i class="fa fa-check"></i><b>18.3</b> Summarising the model (<code>summary</code>)</a></li>
<li class="chapter" data-level="18.4" data-path="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#exercise-fish-behaviour"><i class="fa fa-check"></i><b>18.4</b> Exercise: Fish behaviour</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="evaluating-linear-models.html"><a href="evaluating-linear-models.html"><i class="fa fa-check"></i><b>19</b> Evaluating linear models</a>
<ul>
<li class="chapter" data-level="19.1" data-path="evaluating-linear-models.html"><a href="evaluating-linear-models.html#r-squared-value"><i class="fa fa-check"></i><b>19.1</b> R-squared value</a></li>
<li class="chapter" data-level="19.2" data-path="evaluating-linear-models.html"><a href="evaluating-linear-models.html#akaike-information-criterion-aic"><i class="fa fa-check"></i><b>19.2</b> Akaike Information Criterion (AIC)</a></li>
<li class="chapter" data-level="19.3" data-path="evaluating-linear-models.html"><a href="evaluating-linear-models.html#variance-partitioning"><i class="fa fa-check"></i><b>19.3</b> Variance partitioning</a></li>
<li class="chapter" data-level="19.4" data-path="evaluating-linear-models.html"><a href="evaluating-linear-models.html#conclusion"><i class="fa fa-check"></i><b>19.4</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html"><i class="fa fa-check"></i><b>20</b> Generalised linear models</a>
<ul>
<li class="chapter" data-level="20.1" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html#count-data-with-poisson-errors."><i class="fa fa-check"></i><b>20.1</b> Count data with Poisson errors.</a>
<ul>
<li class="chapter" data-level="20.1.1" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html#example-number-of-offspring-in-foxes."><i class="fa fa-check"></i><b>20.1.1</b> Example: Number of offspring in foxes.</a></li>
<li class="chapter" data-level="20.1.2" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html#example-cancer-clusters"><i class="fa fa-check"></i><b>20.1.2</b> Example: Cancer clusters</a></li>
</ul></li>
<li class="chapter" data-level="20.2" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html#exercise-maze-runner"><i class="fa fa-check"></i><b>20.2</b> Exercise: Maze runner</a></li>
<li class="chapter" data-level="20.3" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html#overdispersion"><i class="fa fa-check"></i><b>20.3</b> Overdispersion</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="extending-use-cases-of-glm.html"><a href="extending-use-cases-of-glm.html"><i class="fa fa-check"></i><b>21</b> Extending use cases of GLM</a>
<ul>
<li class="chapter" data-level="21.1" data-path="extending-use-cases-of-glm.html"><a href="extending-use-cases-of-glm.html#binomial-response-data"><i class="fa fa-check"></i><b>21.1</b> Binomial response data</a></li>
<li class="chapter" data-level="21.2" data-path="extending-use-cases-of-glm.html"><a href="extending-use-cases-of-glm.html#example-nfl-field-goals"><i class="fa fa-check"></i><b>21.2</b> Example: NFL field goals</a></li>
<li class="chapter" data-level="21.3" data-path="extending-use-cases-of-glm.html"><a href="extending-use-cases-of-glm.html#example-sex-ratio-in-turtles"><i class="fa fa-check"></i><b>21.3</b> Example: Sex ratio in turtles</a></li>
<li class="chapter" data-level="21.4" data-path="extending-use-cases-of-glm.html"><a href="extending-use-cases-of-glm.html#example-smoking"><i class="fa fa-check"></i><b>21.4</b> Example: Smoking</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html"><i class="fa fa-check"></i><b>22</b> Power analysis by simulation</a>
<ul>
<li class="chapter" data-level="22.1" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#type-i-and-ii-errors-and-statistical-power"><i class="fa fa-check"></i><b>22.1</b> Type I and II errors and statistical power</a></li>
<li class="chapter" data-level="22.2" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#what-determines-statistical-power"><i class="fa fa-check"></i><b>22.2</b> What determines statistical power?</a></li>
<li class="chapter" data-level="22.3" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#an-example-of-calculating-statistical-power."><i class="fa fa-check"></i><b>22.3</b> An example of calculating statistical power.</a>
<ul>
<li class="chapter" data-level="22.3.1" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#the-simulation"><i class="fa fa-check"></i><b>22.3.1</b> The simulation</a></li>
<li class="chapter" data-level="22.3.2" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#some-questions-for-you-to-address"><i class="fa fa-check"></i><b>22.3.2</b> Some questions for you to address:</a></li>
</ul></li>
<li class="chapter" data-level="22.4" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#summary"><i class="fa fa-check"></i><b>22.4</b> Summary</a></li>
<li class="chapter" data-level="22.5" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#extending-the-simulation-optional-advanced"><i class="fa fa-check"></i><b>22.5</b> Extending the simulation (optional, advanced)</a></li>
<li class="chapter" data-level="22.6" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#exercise-1-snails-on-the-move"><i class="fa fa-check"></i><b>22.6</b> Exercise 1: Snails on the move</a></li>
<li class="chapter" data-level="22.7" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#exercise-2-mouse-lemur-strength"><i class="fa fa-check"></i><b>22.7</b> Exercise 2: Mouse lemur strength</a></li>
</ul></li>
<li class="part"><span><b>IV Appendix</b></span></li>
<li class="chapter" data-level="23" data-path="examples-of-statistics-reporting.html"><a href="examples-of-statistics-reporting.html"><i class="fa fa-check"></i><b>23</b> Examples of statistics reporting</a>
<ul>
<li class="chapter" data-level="23.1" data-path="examples-of-statistics-reporting.html"><a href="examples-of-statistics-reporting.html#t-test"><i class="fa fa-check"></i><b>23.1</b> t-test</a></li>
<li class="chapter" data-level="23.2" data-path="examples-of-statistics-reporting.html"><a href="examples-of-statistics-reporting.html#simple-linear-regression-model"><i class="fa fa-check"></i><b>23.2</b> Simple linear regression model</a></li>
<li class="chapter" data-level="23.3" data-path="examples-of-statistics-reporting.html"><a href="examples-of-statistics-reporting.html#a-generalised-linear-model-glm"><i class="fa fa-check"></i><b>23.3</b> A Generalised linear model (GLM)</a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="an-example-of-a-past-exam-2020.html"><a href="an-example-of-a-past-exam-2020.html"><i class="fa fa-check"></i><b>24</b> An example of a past Exam (2020)</a></li>
<li class="chapter" data-level="25" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html"><i class="fa fa-check"></i><b>25</b> Leveraging ChatGPT for R Programming Assistance</a>
<ul>
<li class="chapter" data-level="25.1" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#introduction"><i class="fa fa-check"></i><b>25.1</b> Introduction</a></li>
<li class="chapter" data-level="25.2" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#overview"><i class="fa fa-check"></i><b>25.2</b> Overview</a></li>
<li class="chapter" data-level="25.3" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#what-is-a-large-language-model-llm-and-how-do-they-work"><i class="fa fa-check"></i><b>25.3</b> What is a Large Language Model (LLM) and how do they work?</a></li>
<li class="chapter" data-level="25.4" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#limitations"><i class="fa fa-check"></i><b>25.4</b> Limitations</a>
<ul>
<li class="chapter" data-level="25.4.1" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#limited-knowledge"><i class="fa fa-check"></i><b>25.4.1</b> Limited knowledge</a></li>
<li class="chapter" data-level="25.4.2" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#hallucination"><i class="fa fa-check"></i><b>25.4.2</b> Hallucination</a></li>
<li class="chapter" data-level="25.4.3" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#numerical-ability"><i class="fa fa-check"></i><b>25.4.3</b> Numerical ability</a></li>
</ul></li>
<li class="chapter" data-level="25.5" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#ethics-of-using-llms-in-education"><i class="fa fa-check"></i><b>25.5</b> Ethics of using LLMs in education</a></li>
<li class="chapter" data-level="25.6" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#use-cases-in-r"><i class="fa fa-check"></i><b>25.6</b> Use cases in R</a>
<ul>
<li class="chapter" data-level="25.6.1" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#finding-errors."><i class="fa fa-check"></i><b>25.6.1</b> Finding errors.</a></li>
<li class="chapter" data-level="25.6.2" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#explaining-code"><i class="fa fa-check"></i><b>25.6.2</b> Explaining code</a></li>
<li class="chapter" data-level="25.6.3" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#interpreting-output"><i class="fa fa-check"></i><b>25.6.3</b> Interpreting output</a></li>
<li class="chapter" data-level="25.6.4" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#translating-code-e.g.-from-pythonmatlab-to-r"><i class="fa fa-check"></i><b>25.6.4</b> Translating code (e.g. from Python/Matlab to R)</a></li>
<li class="chapter" data-level="25.6.5" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#solving-modelling-problems"><i class="fa fa-check"></i><b>25.6.5</b> Solving modelling problems</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>V Solutions</b></span></li>
<li class="chapter" data-level="26" data-path="exercise-solutions.html"><a href="exercise-solutions.html"><i class="fa fa-check"></i><b>26</b> Exercise Solutions</a>
<ul>
<li class="chapter" data-level="26.1" data-path="exercise-solutions.html"><a href="exercise-solutions.html#californian-bird-diversity"><i class="fa fa-check"></i><b>26.1</b> Californian bird diversity</a></li>
<li class="chapter" data-level="26.2" data-path="exercise-solutions.html"><a href="exercise-solutions.html#wrangling-the-amniote-life-history-database"><i class="fa fa-check"></i><b>26.2</b> Wrangling the Amniote Life History Database</a></li>
<li class="chapter" data-level="26.3" data-path="exercise-solutions.html"><a href="exercise-solutions.html#temperature-effects-on-egg-laying-dates"><i class="fa fa-check"></i><b>26.3</b> Temperature effects on egg laying dates</a></li>
<li class="chapter" data-level="26.4" data-path="exercise-solutions.html"><a href="exercise-solutions.html#virtual-dice"><i class="fa fa-check"></i><b>26.4</b> Virtual dice</a></li>
<li class="chapter" data-level="26.5" data-path="exercise-solutions.html"><a href="exercise-solutions.html#sexual-selection-in-hercules-beetles"><i class="fa fa-check"></i><b>26.5</b> Sexual selection in Hercules beetles</a></li>
<li class="chapter" data-level="26.6" data-path="exercise-solutions.html"><a href="exercise-solutions.html#sex-differences-in-fine-motor-skills"><i class="fa fa-check"></i><b>26.6</b> Sex differences in fine motor skills</a></li>
<li class="chapter" data-level="26.7" data-path="exercise-solutions.html"><a href="exercise-solutions.html#therapy-for-anorexia"><i class="fa fa-check"></i><b>26.7</b> Therapy for anorexia</a></li>
<li class="chapter" data-level="26.8" data-path="exercise-solutions.html"><a href="exercise-solutions.html#compare-t-tests-with-randomisation-tests"><i class="fa fa-check"></i><b>26.8</b> Compare t-tests with randomisation tests</a></li>
<li class="chapter" data-level="26.9" data-path="exercise-solutions.html"><a href="exercise-solutions.html#apple-tree-crop-yield"><i class="fa fa-check"></i><b>26.9</b> Apple tree crop yield</a></li>
<li class="chapter" data-level="26.10" data-path="exercise-solutions.html"><a href="exercise-solutions.html#chirping-crickets"><i class="fa fa-check"></i><b>26.10</b> Chirping crickets</a></li>
<li class="chapter" data-level="26.11" data-path="exercise-solutions.html"><a href="exercise-solutions.html#fish-behaviour"><i class="fa fa-check"></i><b>26.11</b> Fish behaviour</a></li>
<li class="chapter" data-level="26.12" data-path="exercise-solutions.html"><a href="exercise-solutions.html#maze-runner"><i class="fa fa-check"></i><b>26.12</b> Maze runner</a></li>
<li class="chapter" data-level="26.13" data-path="exercise-solutions.html"><a href="exercise-solutions.html#snails-on-the-move"><i class="fa fa-check"></i><b>26.13</b> Snails on the move</a></li>
<li class="chapter" data-level="26.14" data-path="exercise-solutions.html"><a href="exercise-solutions.html#mouse-lemur-strength"><i class="fa fa-check"></i><b>26.14</b> Mouse lemur strength</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">BB852 - Data handling, visualisation and statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="linear-regression-models-with-a-single-continuous-explanatory-variable" class="section level1 hasAnchor" number="16">
<h1><span class="header-section-number">Chapter 16</span> Linear regression: models with a single continuous explanatory variable<a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#linear-regression-models-with-a-single-continuous-explanatory-variable" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Linear regression models, at their simplest, are a method of estimating the linear (straight line) relationships between two continuous variables. As an example, picture the relationship between two variables height and hand width (Figure <a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#fig:3-04-linearRegression-1">16.1</a>). In this figure there is a clear relationship between the two variables, and the straight line running through the cloud of data points is the fitted linear regression model.</p>
<p>The aim of linear regression is to (1) determine if there is a meaningful statistical relationship between the explanatory variable(s) and the response variable, and (2) to quantify those relationships by estimating the characteristics of those relationships. These characteristics include the slope and intercepts of fitted models, and the amount of variation explained by variables in the model.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:3-04-linearRegression-1"></span>
<img src="BB852_files/figure-html/3-04-linearRegression-1-1.png" alt="A linear regression model fitted through data points." width="288" />
<p class="caption">
Figure 16.1: A linear regression model fitted through data points.
</p>
</div>
<div id="some-theory-1" class="section level2 hasAnchor" number="16.1">
<h2><span class="header-section-number">16.1</span> Some theory<a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#some-theory-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>To understand linear regression models it is important to know that the equation of a straight line is <span class="math inline">\(y = ax+b\)</span>. In this equation, <span class="math inline">\(y\)</span> is the response variable and <span class="math inline">\(x\)</span> is the explanatory variable, and <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> are the slope and intercept of the line with the vertical axis (y-axis). These (<span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span>) are called <strong>coefficients</strong>. These are illustrated in Figure <a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#fig:3-04-linearRegression-2">16.2</a>.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:3-04-linearRegression-2"></span>
<img src="BB852_files/figure-html/3-04-linearRegression-2-1.png" alt="The equation of straight lines." width="672" />
<p class="caption">
Figure 16.2: The equation of straight lines.
</p>
</div>
<p>When looking at data points on a graph, unless all of the data points are arranged perfectly along a straight line, there will be some distance between the points and the line. These distances, measured parallel to the vertical axis, are called residuals (you have encountered them before in this course). These residuals represent the variation left after fitting the line (a linear model) through the data. Because we want to fit a model that explains as much variation as possible, it is intuitive that we should wish to minimise this residual variation.</p>
<p>One way of doing this is by minimising the sum of squares of the residuals (again, you have come across this concept a few times before). In other words, we add up the squares of each of the residuals. We square the values, rather than simply adding up the residuals themselves because we want to ensure that the positive and negative values don’t cancel each other out (a square of a negative number is positive). This method is called <strong>least squares</strong> regression and is illustrated in Figure <a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#fig:3-04-linearRegression-3">16.3</a>: Which is the best fitting line?</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:3-04-linearRegression-3"></span>
<img src="BB852_files/figure-html/3-04-linearRegression-3-1.png" alt="Residuals and least squares: which is the best fitting line?" width="460.8" />
<p class="caption">
Figure 16.3: Residuals and least squares: which is the best fitting line?
</p>
</div>
<p>In fact, these residuals represent “error” caused by factors including measurement error, random variation, variation caused by unmeasured factors etc. This error term is given the label, <span class="math inline">\(\epsilon\)</span>. Thus we can write the model equation as:</p>
<p><span class="math display">\[y = ax+b+\epsilon\]</span></p>
<p>Sometimes, this equation is written with using the beta symbol (<span class="math inline">\(\beta\)</span>) for the coefficients, so that the slope is <span class="math inline">\(\beta_0\)</span> and the intercept is <span class="math inline">\(\beta_1\)</span> for example.</p>
<p><span class="math display">\[y = \beta_0 x+\beta_1+\epsilon\]</span></p>
<p>The idea is that this equation, and its coefficients and error estimates, describe the relationship we are interested in (including the error or uncertainty).</p>
<p>Together this information allows us to not only determine if there <strong>is</strong> a statistically significant relationship, but also what the nature of the relationship is, and the uncertainty in our estimates.</p>
</div>
<div id="evaluating-a-hypothesis-with-a-linear-regression-model" class="section level2 hasAnchor" number="16.2">
<h2><span class="header-section-number">16.2</span> Evaluating a hypothesis with a linear regression model<a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#evaluating-a-hypothesis-with-a-linear-regression-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Usually, the most important hypothesis test involved with a linear regression model relates to the slope: <strong>is the slope coefficient significantly different from 0?</strong>, or should we accept the null hypothesis that the slope is no different from 0.</p>
<p>Sometimes hypotheses like this are a bit boring, because we already know the answer before collecting and analysing the data. What we usually <strong>don’t</strong> know is the nature of the relationship (the slope, intercept, their errors, and amount of variation explained). Usually it is more interesting and meaningful to focus on those details.</p>
<p>The following example, where we focus on the relationship between hand width and height, is one of these “boring” cases: we already know there is a relationship. Nevertheless, we’ll use this example because it helps us understand how this hypothesis test works.</p>
<p>The aim of this section is to give you some intuition on how the hypothesis test works.</p>
<p>We can address the slope hypothesis by calculating an F-value in a similar way to how we used them in ANOVA. Recall that F-values are ratios of variances. To understand how these work in the context of a linear regression we need to think clearly about the slope hypothesis: The <strong>null hypothesis</strong> is that the slope is <strong>not</strong> significantly different to 0 (that the data can be explained by random variation). The <strong>alternative hypothesis</strong> is that the slope is significantly different from 0.</p>
<p>The first step in evaluating these hypotheses is to calculate what the <strong>total sum of squares</strong><a href="#fn11" class="footnote-ref" id="fnref11"><sup>11</sup></a> is when the null hypothesis is true (Figure <a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#fig:3-04-linearRegression-4">16.4</a>A) - this value is the total variation that the model is trying to explain.</p>
<p>Then we fit our model using least squares and figure out what the <strong>residual sum of squares</strong> is from this model (Figure <a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#fig:3-04-linearRegression-4">16.4</a>B). This is the amount of variation left after the model has explained <em>some</em> of the total variation - it is sometimes called <em>residual error</em>, or simply <em>error</em>.</p>
<p>The difference between these two values is the <strong>explained sum of squares</strong>, which measures the amount of variation in <span class="math inline">\(y\)</span> explained by variation in <span class="math inline">\(x\)</span>. The rationale for this is that the model is trying to explain total variation. After fitting the model there will always be some unexplained variation (“<em>residual error</em>”) left. If we can estimate total variation and unexplained variation, then the amount of variation explained can be calculated with a simple subtraction:</p>
<p><span class="math display">\[Total = Explained + Residual\]</span>
… and, therefore …
<span class="math display">\[Explained = Total - Residual\]</span></p>
<p>Before using these values we need to standardise them to control for sample size. This is necessary because sum of squares will <em>always</em> increase with sample size. We make this correction by dividing our sum of squares measures by the degrees of freedom. The d.f. for the <strong>explained sum of squares</strong> is 1, and the d.f. for the <strong>residual sum of squares</strong> is the number of observations minus 2. The result of these calculations is the <strong>mean explained sum of squares</strong> (mESS) and the <strong>mean residual sum of squares</strong> (mRSS). These “mean” quantities are <strong>variances</strong>, and the ratio between them gives us the <strong>F-value</strong>. Notice that this is very similar to the variance ratio used in the ANOVA.</p>
<p><span class="math display">\[F = \frac{mESS}{mRSS}\]</span></p>
<p>If the <em>explained variance</em> (mESS) is large compared to the <em>residual error variance</em> (mRSS), then F will be large. The size of F tells us how likely or unlikely it is that the null hypothesis is true. When F is large, the probability that the slope is significantly different from 0 is high. To obtain the actual probabilities, the F-value must be compared to a theoretical distribution which depends on the two degrees of freedom (explained and residual d.f.). Once upon a time you would have looked this up in a printed table, but now R makes this very straightforward.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:3-04-linearRegression-4"></span>
<img src="BB852_files/figure-html/3-04-linearRegression-4-1.png" alt="(A) the total variation around the overall mean Height value (B) the residual error of the model." width="768" />
<p class="caption">
Figure 16.4: (A) the total variation around the overall mean Height value (B) the residual error of the model.
</p>
</div>
</div>
<div id="assumptions" class="section level2 hasAnchor" number="16.3">
<h2><span class="header-section-number">16.3</span> Assumptions<a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#assumptions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>These models have similar assumptions to the other linear models<a href="#fn12" class="footnote-ref" id="fnref12"><sup>12</sup></a>. These are (1) that the relationship between the variables is linear (hence the name); (2) that the data are continuous variables; (3) that the observations are randomly sampled; (4) that the errors in the model (the “residuals”) can be described by a normal distribution; and (5) and that the errors are “homoscedastic” (that they are constant through the range of the data). You can evaluate these things by looking at diagnostic plots after you have fitted the model. See page 112-113 in GSWR for a nice explanation.</p>
</div>
<div id="worked-example-height-hand-width-relationship" class="section level2 hasAnchor" number="16.4">
<h2><span class="header-section-number">16.4</span> Worked example: height-hand width relationship<a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#worked-example-height-hand-width-relationship" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Let’s now use R to fit a linear regression model to estimate the relationship between hand width and height. One application for such a model could be to predict height from a hand print, for example left at a crime scene. I am restricting my analysis to 2019 data, but you could do it for any year (or all years, but you might need to first get rid of some outliers using <code>filter</code>).</p>
<div class="do-something">
<p>
Remember to load the <code>dplyr</code>, <code>magrittr</code> and
<code>ggplot</code> packages, and to set your working directory
correctly.
</p>
</div>
<p>First, load the data:</p>
<div class="sourceCode" id="cb394"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb394-1"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#cb394-1" tabindex="-1"></a>classData <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;CourseData/classData.csv&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb394-2"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#cb394-2" tabindex="-1"></a>  <span class="fu">filter</span>(Year <span class="sc">==</span> <span class="dv">2019</span>)</span></code></pre></div>
<p>We should then plot the data to make sure it looks OK.</p>
<div class="sourceCode" id="cb395"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb395-1"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#cb395-1" tabindex="-1"></a><span class="fu">ggplot</span>(classData, <span class="fu">aes</span>(<span class="at">x =</span> HandWidth, <span class="at">y =</span> Height)) <span class="sc">+</span></span>
<span id="cb395-2"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#cb395-2" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div>
<p><img src="BB852_files/figure-html/3-04-linearRegression-7-1.png" width="432" style="display: block; margin: auto;" /></p>
<p>This looks OK, and the relationship looks fairly linear. Now we can fit a model using the <code>lm</code> function (same as for ANOVA!).<a href="#fn13" class="footnote-ref" id="fnref13"><sup>13</sup></a></p>
<p>The response variable is always the one we would like to predict, in this case <code>Height</code>. The explanatory variable (sometimes called the predictor) is <code>HandWidth</code>. These are added to the model using a formula where they are separated with the <code>~</code> (“tilde”) symbol: <code>Height ~ HandWidth</code>. In the model expression, we also need to tell R where the data are using the <code>data =</code> argument. We can save the model as an R object by naming it e.g. <code>mod_A &lt;-</code>.</p>
<div class="sourceCode" id="cb396"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb396-1"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#cb396-1" tabindex="-1"></a>mod_A <span class="ot">&lt;-</span> <span class="fu">lm</span>(Height <span class="sc">~</span> HandWidth, <span class="at">data =</span> classData)</span></code></pre></div>
<p>Before proceeding further we should evaluate the model using a diagnostic plot. We can do this using the <code>autoplot</code> function in the <code>ggfortify</code> package (you may need to install and/or load the package).</p>
<div class="sourceCode" id="cb397"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb397-1"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#cb397-1" tabindex="-1"></a><span class="fu">library</span>(ggfortify)</span>
<span id="cb397-2"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#cb397-2" tabindex="-1"></a><span class="fu">autoplot</span>(mod_A)</span></code></pre></div>
<p><img src="BB852_files/figure-html/3-04-linearRegression-9-1.png" width="480" style="display: block; margin: auto;" />
These diagnostic plots allow you to check that the assumptions of the model are not violated. On the left are two plots which (more or less) show the same thing. They show how the residuals (the errors in the model) vary with the predicted value (height). Looking at the plots allows a visual test for constant variance (homoscedasticity) along the range of the data. In an ideal case, there should be no pattern (e.g. humps) in these points. On the top right is the QQ-plot which shows how well the residuals match up to a theoretical normal distribution. In an ideal case, these points should line up on the diagonal line running across the plot. The bottom right plot shows “leverage” which is a measure of how much influence individual data points have on the model. Outliers will have large leverage and can mess up your model. Ideally, the points here should be in a cloud, with no points standing out from the others. Please read the pages 112-113 in the textbook GSWR for more on these. In this case, the model looks pretty good.</p>
<p>Now that we are satisfied that the model doesn’t violate the assumptions we can dig into the model to see what it is telling us.</p>
<p>To test the (slightly boring) slope hypothesis we use the <code>anova</code> function (again, this is the same as with the ANOVA).</p>
<div class="sourceCode" id="cb398"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb398-1"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#cb398-1" tabindex="-1"></a><span class="fu">anova</span>(mod_A)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: Height
##           Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## HandWidth  1  881.6  881.60  22.091 5.064e-05 ***
## Residuals 31 1237.1   39.91                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>When you run this function, you get a summary table that looks exactly like the one you got with an ANOVA. There are degrees of freedom (<code>Df</code>), Sums of Squares (<code>Sum Sq</code>), Mean Sums of Squares (<code>Mean Sq</code>) and the <code>F value</code> and p-value (<code>Pr(&gt;F)</code>).
The most important parts of this table are the F value (22.091) and the p-value (0.000): as described above, large F values lead to small p-values. This tells us that it is unlikely that the null hypothesis is true and we should accept the alternative hypothesis (that height is associated with hand width).</p>
<p>We could report the results of this hypothesis test like this:
<em>There was a statistically significant association between hand width and height (F = 22.0912, d.f. = 1,31, p &lt; 0.001)</em></p>
<p>Now we can dig deeper by asking for a <code>summary</code> of the model.</p>
<div class="sourceCode" id="cb400"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb400-1"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#cb400-1" tabindex="-1"></a><span class="fu">summary</span>(mod_A)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Height ~ HandWidth, data = classData)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -11.749  -3.924   1.251   6.135   9.601 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 140.6817     7.4030    19.0  &lt; 2e-16 ***
## HandWidth     3.8834     0.8262     4.7 5.06e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.317 on 31 degrees of freedom
## Multiple R-squared:  0.4161, Adjusted R-squared:  0.3973 
## F-statistic: 22.09 on 1 and 31 DF,  p-value: 5.064e-05</code></pre>
<p>This summary has a lot of information. First we see <code>Call</code> which reminds us what the formula we have used to fit the model. Then there is some summary information about the residuals. Ideally these should be fairly balanced around 0 (i.e. the <code>Min</code> value should be negative but with the same magnitude as <code>Max</code>). If they are <strong>wildly</strong> different, then you might want to check the data or model. In this case they look OK.</p>
<p>Then we get to the important part of the table - the <code>Coefficients</code>. This lists the coefficients of the model and shows first the <code>Intercept</code> and then the slope, which is given by the name of the explanatory variable (<code>HandWidth</code> here). For each coefficient we get the <code>Estimate</code> of its value, and the uncertainty in that estimate (the standard error (`Std. Error)).</p>
<p>These estimates and errors are each followed by a <code>t value</code> and a p-value (<code>Pr(&gt;|t|</code>)). These values provide a test of whether the slope/intercept is different from zero. In this case they both are. The t-tests are indeed doing t-tests of these estimates, in the same way that a regular t-test works, so that the significance depends on the ratio between signal (the estimate) and the noise (the standard error). This is illustrated for the coefficient estimates for our model in Figure <a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#fig:3-04-linearRegression-12">16.5</a>.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:3-04-linearRegression-12"></span>
<img src="BB852_files/figure-html/3-04-linearRegression-12-1.png" alt="Illustration of the coefficient estimates for our model. The peak of the distribution is at the coefficient estimate, and the spread of the distribution indicates the standard error of the mean for the estimate. The statistical significance of the coefficient is determined by the degree of overlap with 0." width="576" />
<p class="caption">
Figure 16.5: Illustration of the coefficient estimates for our model. The peak of the distribution is at the coefficient estimate, and the spread of the distribution indicates the standard error of the mean for the estimate. The statistical significance of the coefficient is determined by the degree of overlap with 0.
</p>
</div>
<p>The summary then gives some information about the amount of residual variation left after the model has been fitted (this is the <span class="math inline">\(\epsilon\)</span> term in the equations at the start of this chapter). Then we are told what the <span class="math inline">\(R^2\)</span> value is 0.4161. The adjusted <span class="math inline">\(R^2\)</span> is for use in multiple regression models, where there are many explanatory variables and should not be used for this simple regression model. So what does <span class="math inline">\(R^2\)</span> actually mean?</p>
<p><span class="math inline">\(R^2\)</span> is the square of the correlation coefficient <span class="math inline">\(r\)</span> and is a measure of the amount of variation in the response variable (Height) that is explained by the model. If all the points were sitting on the regression line, the <span class="math inline">\(R^2\)</span> value would be 1. This idea is illustrated in Figure <a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#fig:3-04-linearRegression-13">16.6</a>.</p>
<p>We could describe the model like this:</p>
<p><em>There is a statistically significant association between hand width and height (F = 22.0912, d.f. = 1,31, p &lt; 0.001) The equation of the fitted model is: Height = 3.88(<span class="math inline">\(\pm\)</span> 0.83) <span class="math inline">\(\times\)</span> HandWidth + 140.68(<span class="math inline">\(\pm\)</span> 7.40). The model explains 42% of the variation in height (<span class="math inline">\(R^2\)</span> = 0.416).</em></p>
<p>… or maybe, <em>The model, which explained 42% of the variation in height, showed that the slope of the relationship between hand width and height is 3.88 <span class="math inline">\(\pm\)</span> 0.83 which is significantly greater than 0 (t = 19.00, p &lt; 0.01)</em></p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:3-04-linearRegression-13"></span>
<img src="BB852_files/figure-html/3-04-linearRegression-13-1.png" alt="An illustration of different R-squared values." width="384" />
<p class="caption">
Figure 16.6: An illustration of different R-squared values.
</p>
</div>
<p>A plot is usually a good idea because it is easier for the reader to interpret than an equation, or coefficients. The <code>ggplot2</code> package has a neat and simple function called <code>geom_smooth</code> which will add the fitted regression line to simple models like this. For linear regression models you simply need to tell it to use <code>method = "lm"</code>. This will plot the fitted regression model, and will add, by default” a shaded “ribbon” which represents the so called “95% confidence interval” for the fitted values. These are 2 time the standard error.</p>
<div class="sourceCode" id="cb402"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb402-1"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#cb402-1" tabindex="-1"></a><span class="fu">ggplot</span>(classData, <span class="fu">aes</span>(<span class="at">x =</span> HandWidth, <span class="at">y =</span> Height)) <span class="sc">+</span></span>
<span id="cb402-2"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#cb402-2" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb402-3"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#cb402-3" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>)</span></code></pre></div>
<p><img src="BB852_files/figure-html/3-04-linearRegression-14-1.png" width="432" style="display: block; margin: auto;" /></p>
<p><strong>Question:</strong> If police find the 9.8cm wide hand print at a crime scene, what is your best guess of the height of the person involved?</p>
</div>
<div id="exercise-chirping-crickets" class="section level2 hasAnchor" number="16.5">
<h2><span class="header-section-number">16.5</span> Exercise: Chirping crickets<a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#exercise-chirping-crickets" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Male crickets produce a “chirping” sound by rubbing the edges of their wings together: the male cricket rubs a sharp ridge on his wing against a series ridges on the other wing. In a 1948 study on striped ground cricket (<em>Allonemobius fasciatus</em>), the biologist George W. Pierce recorded the frequency of chirps (vibrations per second) in different temperature conditions.</p>
<p>Crickets are ectotherms so their physiology and metabolism is influenced by temperature. We therefore believe that temperature might have an effect on their chirp frequency.</p>
<p>The data file <code>chirps.csv</code> contains data from Pierce’s experiments. Your task is to analyse the data and find (1) whether there is a statistically significant relationship between temperature and chirp frequency and (2) what that relationship is.</p>
<p>The data has two columns - <code>chirps</code> (the frequency in Hertz) and <code>temperature</code> (the temperature in Fahrenheit). You should express the relationship in Celsius.</p>
<ol style="list-style-type: decimal">
<li><p>Import the data</p></li>
<li><p>Use <code>mutate</code> to convert Fahrenheit to Celsius (Google it)</p></li>
<li><p>Plot the data</p></li>
<li><p>Fit a linear regression model with <code>lm</code></p></li>
<li><p>Look at diagnostic plots to evaluate the model</p></li>
<li><p>Use <code>anova</code> to figure out if the effect of temperature is statistically significant.</p></li>
<li><p>Use <code>summary</code> to obtain information about the coefficients and <span class="math inline">\(R^2\)</span>-value.</p></li>
<li><p>Summarise the model in words.</p></li>
<li><p>Add model fit line to the plot.</p></li>
<li><p>Can I use cricket chirp frequency as a kind of thermometer?</p></li>
</ol>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="11">
<li id="fn11"><p>sum of squares is simply a way to estimate variation.<a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#fnref11" class="footnote-back">↩︎</a></p></li>
<li id="fn12"><p>t-tests, ANOVA and linear regression are all types of linear model, mathematically<a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#fnref12" class="footnote-back">↩︎</a></p></li>
<li id="fn13"><p>R knows that this is a linear regression rather than an ANOVA because the explanatory variable is numeric rather than categorical - smart!.<a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#fnref13" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/jonesor/BB852_Book/edit/master/3_04-linearRegression.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["BB852.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
},
"split_by": "section"
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
