<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 18 n-way ANOVA: Linear models with &gt;1 categorical explanatory variables | BB852 - Data handling, visualisation and statistics</title>
  <meta name="description" content="Course book for BB852 at the Biology Department, University of Southern Denmark" />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 18 n-way ANOVA: Linear models with &gt;1 categorical explanatory variables | BB852 - Data handling, visualisation and statistics" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Course book for BB852 at the Biology Department, University of Southern Denmark" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 18 n-way ANOVA: Linear models with &gt;1 categorical explanatory variables | BB852 - Data handling, visualisation and statistics" />
  
  <meta name="twitter:description" content="Course book for BB852 at the Biology Department, University of Southern Denmark" />
  

<meta name="author" content="Owen R. Jones" />


<meta name="date" content="2024-10-17" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html"/>
<link rel="next" href="evaluating-linear-models.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/tabwid-1.1.3/tabwid.css" rel="stylesheet" />
<script src="libs/tabwid-1.1.3/tabwid.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">BB852</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Preface</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#data-wrangling"><i class="fa fa-check"></i><b>1.1</b> Data wrangling</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#data-visualisation"><i class="fa fa-check"></i><b>1.2</b> Data visualisation</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#statistics"><i class="fa fa-check"></i><b>1.3</b> Statistics</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#data-sources"><i class="fa fa-check"></i><b>1.4</b> Data sources</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#your-instructors"><i class="fa fa-check"></i><b>1.5</b> Your instructor(s)</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#expectations"><i class="fa fa-check"></i><b>1.6</b> Expectations</a></li>
<li class="chapter" data-level="1.7" data-path="index.html"><a href="index.html#your-feedback"><i class="fa fa-check"></i><b>1.7</b> Your feedback</a></li>
<li class="chapter" data-level="1.8" data-path="index.html"><a href="index.html#assessment"><i class="fa fa-check"></i><b>1.8</b> Assessment</a></li>
<li class="chapter" data-level="1.9" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i><b>1.9</b> Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="schedule.html"><a href="schedule.html"><i class="fa fa-check"></i><b>2</b> Schedule</a></li>
<li class="chapter" data-level="3" data-path="additional-recommended-reading.html"><a href="additional-recommended-reading.html"><i class="fa fa-check"></i><b>3</b> Additional recommended reading</a></li>
<li class="chapter" data-level="4" data-path="an-r-refresher.html"><a href="an-r-refresher.html"><i class="fa fa-check"></i><b>4</b> An R refresher</a>
<ul>
<li class="chapter" data-level="4.1" data-path="an-r-refresher.html"><a href="an-r-refresher.html#getting-started-with-r"><i class="fa fa-check"></i><b>4.1</b> Getting started with R</a></li>
<li class="chapter" data-level="4.2" data-path="an-r-refresher.html"><a href="an-r-refresher.html#getting-help"><i class="fa fa-check"></i><b>4.2</b> Getting help</a></li>
<li class="chapter" data-level="4.3" data-path="an-r-refresher.html"><a href="an-r-refresher.html#r-as-a-fancy-calculator"><i class="fa fa-check"></i><b>4.3</b> R as a fancy calculator</a></li>
<li class="chapter" data-level="4.4" data-path="an-r-refresher.html"><a href="an-r-refresher.html#objects-in-r"><i class="fa fa-check"></i><b>4.4</b> Objects in R</a></li>
<li class="chapter" data-level="4.5" data-path="an-r-refresher.html"><a href="an-r-refresher.html#manipulating-objects"><i class="fa fa-check"></i><b>4.5</b> Manipulating objects</a></li>
<li class="chapter" data-level="4.6" data-path="an-r-refresher.html"><a href="an-r-refresher.html#missing-values-infinity-and-non-numbers"><i class="fa fa-check"></i><b>4.6</b> Missing values, infinity and “non-numbers”</a></li>
<li class="chapter" data-level="4.7" data-path="an-r-refresher.html"><a href="an-r-refresher.html#basic-information-about-objects"><i class="fa fa-check"></i><b>4.7</b> Basic information about objects</a></li>
<li class="chapter" data-level="4.8" data-path="an-r-refresher.html"><a href="an-r-refresher.html#data-frames"><i class="fa fa-check"></i><b>4.8</b> Data frames</a></li>
<li class="chapter" data-level="4.9" data-path="an-r-refresher.html"><a href="an-r-refresher.html#classes-in-r"><i class="fa fa-check"></i><b>4.9</b> Classes in R</a></li>
<li class="chapter" data-level="4.10" data-path="an-r-refresher.html"><a href="an-r-refresher.html#organising-your-work"><i class="fa fa-check"></i><b>4.10</b> Organising your work</a></li>
<li class="chapter" data-level="4.11" data-path="an-r-refresher.html"><a href="an-r-refresher.html#inspecting-the-data"><i class="fa fa-check"></i><b>4.11</b> Inspecting the data</a></li>
<li class="chapter" data-level="4.12" data-path="an-r-refresher.html"><a href="an-r-refresher.html#classes-in-r-1"><i class="fa fa-check"></i><b>4.12</b> “Classes” in R</a></li>
<li class="chapter" data-level="4.13" data-path="an-r-refresher.html"><a href="an-r-refresher.html#tables-and-summary-statistics"><i class="fa fa-check"></i><b>4.13</b> Tables and summary statistics</a></li>
<li class="chapter" data-level="4.14" data-path="an-r-refresher.html"><a href="an-r-refresher.html#plotting-data"><i class="fa fa-check"></i><b>4.14</b> Plotting data</a></li>
<li class="chapter" data-level="4.15" data-path="an-r-refresher.html"><a href="an-r-refresher.html#r-packages"><i class="fa fa-check"></i><b>4.15</b> R Packages</a></li>
<li class="chapter" data-level="4.16" data-path="an-r-refresher.html"><a href="an-r-refresher.html#exercise-californian-bird-diversity"><i class="fa fa-check"></i><b>4.16</b> Exercise: Californian bird diversity</a>
<ul>
<li class="chapter" data-level="4.16.1" data-path="an-r-refresher.html"><a href="an-r-refresher.html#the-data"><i class="fa fa-check"></i><b>4.16.1</b> The data</a></li>
<li class="chapter" data-level="4.16.2" data-path="an-r-refresher.html"><a href="an-r-refresher.html#try-the-following"><i class="fa fa-check"></i><b>4.16.2</b> Try the following</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html"><i class="fa fa-check"></i><b>5</b> Tips and tricks</a>
<ul>
<li class="chapter" data-level="5.1" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#appearance"><i class="fa fa-check"></i><b>5.1</b> Appearance</a></li>
<li class="chapter" data-level="5.2" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#shortcuts"><i class="fa fa-check"></i><b>5.2</b> Shortcuts</a></li>
<li class="chapter" data-level="5.3" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#code-style"><i class="fa fa-check"></i><b>5.3</b> Code style</a></li>
<li class="chapter" data-level="5.4" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#the-plots-pane"><i class="fa fa-check"></i><b>5.4</b> The plots pane</a></li>
<li class="chapter" data-level="5.5" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#tables"><i class="fa fa-check"></i><b>5.5</b> Tables</a></li>
<li class="chapter" data-level="5.6" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#importing-data-from-text-files"><i class="fa fa-check"></i><b>5.6</b> Importing data from text files</a></li>
<li class="chapter" data-level="5.7" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#importing-data-from-excel"><i class="fa fa-check"></i><b>5.7</b> Importing data from Excel</a></li>
<li class="chapter" data-level="5.8" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#numbers"><i class="fa fa-check"></i><b>5.8</b> Numbers</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="paths-and-projects.html"><a href="paths-and-projects.html"><i class="fa fa-check"></i><b>6</b> Paths and projects</a>
<ul>
<li class="chapter" data-level="6.1" data-path="paths-and-projects.html"><a href="paths-and-projects.html#file-structure"><i class="fa fa-check"></i><b>6.1</b> File structure</a></li>
<li class="chapter" data-level="6.2" data-path="paths-and-projects.html"><a href="paths-and-projects.html#paths-and-the-command-line"><i class="fa fa-check"></i><b>6.2</b> Paths and the command line</a></li>
<li class="chapter" data-level="6.3" data-path="paths-and-projects.html"><a href="paths-and-projects.html#r-and-file-structure"><i class="fa fa-check"></i><b>6.3</b> R and file structure</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="paths-and-projects.html"><a href="paths-and-projects.html#setting-the-working-directory"><i class="fa fa-check"></i><b>6.3.1</b> Setting the working directory</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="paths-and-projects.html"><a href="paths-and-projects.html#projects-in-r"><i class="fa fa-check"></i><b>6.4</b> Projects in R</a></li>
</ul></li>
<li class="part"><span><b>I Data Wrangling</b></span></li>
<li class="chapter" data-level="7" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html"><i class="fa fa-check"></i><b>7</b> Data wrangling with <code>dplyr</code></a>
<ul>
<li class="chapter" data-level="7.1" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#select"><i class="fa fa-check"></i><b>7.1</b> <code>select</code></a></li>
<li class="chapter" data-level="7.2" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#filter"><i class="fa fa-check"></i><b>7.2</b> <code>filter</code></a></li>
<li class="chapter" data-level="7.3" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#arrange"><i class="fa fa-check"></i><b>7.3</b> <code>arrange</code></a></li>
<li class="chapter" data-level="7.4" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#summarise-and-group_by"><i class="fa fa-check"></i><b>7.4</b> <code>summarise</code> and <code>group_by</code></a></li>
<li class="chapter" data-level="7.5" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#using-pipes-saving-data."><i class="fa fa-check"></i><b>7.5</b> Using pipes, saving data.</a></li>
<li class="chapter" data-level="7.6" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#exercise-wrangling-the-amniote-life-history-database"><i class="fa fa-check"></i><b>7.6</b> Exercise: Wrangling the Amniote Life History Database</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="combining-data-sets.html"><a href="combining-data-sets.html"><i class="fa fa-check"></i><b>8</b> Combining data sets</a>
<ul>
<li class="chapter" data-level="8.1" data-path="combining-data-sets.html"><a href="combining-data-sets.html#using-join"><i class="fa fa-check"></i><b>8.1</b> Using <code>join</code></a></li>
<li class="chapter" data-level="8.2" data-path="combining-data-sets.html"><a href="combining-data-sets.html#using-pivot_longer"><i class="fa fa-check"></i><b>8.2</b> Using <code>pivot_longer</code></a></li>
<li class="chapter" data-level="8.3" data-path="combining-data-sets.html"><a href="combining-data-sets.html#exercise-temperature-effects-on-egg-laying-dates"><i class="fa fa-check"></i><b>8.3</b> Exercise: Temperature effects on egg laying dates</a></li>
</ul></li>
<li class="part"><span><b>II Data visualisation</b></span></li>
<li class="chapter" data-level="9" data-path="visualising-data-with-ggplot2.html"><a href="visualising-data-with-ggplot2.html"><i class="fa fa-check"></i><b>9</b> Visualising data with <code>ggplot2</code></a>
<ul>
<li class="chapter" data-level="9.1" data-path="visualising-data-with-ggplot2.html"><a href="visualising-data-with-ggplot2.html#histograms"><i class="fa fa-check"></i><b>9.1</b> Histograms</a></li>
<li class="chapter" data-level="9.2" data-path="visualising-data-with-ggplot2.html"><a href="visualising-data-with-ggplot2.html#facets---splitting-data-across-panels"><i class="fa fa-check"></i><b>9.2</b> “Facets” - splitting data across panels</a></li>
<li class="chapter" data-level="9.3" data-path="visualising-data-with-ggplot2.html"><a href="visualising-data-with-ggplot2.html#box-plots"><i class="fa fa-check"></i><b>9.3</b> Box plots</a></li>
<li class="chapter" data-level="9.4" data-path="visualising-data-with-ggplot2.html"><a href="visualising-data-with-ggplot2.html#lines-and-points"><i class="fa fa-check"></i><b>9.4</b> Lines and points</a></li>
<li class="chapter" data-level="9.5" data-path="visualising-data-with-ggplot2.html"><a href="visualising-data-with-ggplot2.html#scatter-plots"><i class="fa fa-check"></i><b>9.5</b> Scatter plots</a></li>
<li class="chapter" data-level="9.6" data-path="visualising-data-with-ggplot2.html"><a href="visualising-data-with-ggplot2.html#bar-plots"><i class="fa fa-check"></i><b>9.6</b> Bar plots</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html"><i class="fa fa-check"></i><b>10</b> Distributions and summarising data</a>
<ul>
<li class="chapter" data-level="10.1" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#distributions"><i class="fa fa-check"></i><b>10.1</b> Distributions</a></li>
<li class="chapter" data-level="10.2" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#normal-distribution"><i class="fa fa-check"></i><b>10.2</b> Normal distribution</a></li>
<li class="chapter" data-level="10.3" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#comparing-normal-distributions"><i class="fa fa-check"></i><b>10.3</b> Comparing normal distributions</a></li>
<li class="chapter" data-level="10.4" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#poisson-distribution"><i class="fa fa-check"></i><b>10.4</b> Poisson distribution</a></li>
<li class="chapter" data-level="10.5" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#comparing-normal-and-poisson-distributions"><i class="fa fa-check"></i><b>10.5</b> Comparing normal and Poisson distributions</a></li>
<li class="chapter" data-level="10.6" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#the-law-of-large-numbers"><i class="fa fa-check"></i><b>10.6</b> The law of large numbers</a>
<ul>
<li class="chapter" data-level="10.6.1" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#coin-flipping"><i class="fa fa-check"></i><b>10.6.1</b> Coin flipping</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#exercise-virtual-dice"><i class="fa fa-check"></i><b>10.7</b> Exercise: Virtual dice</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html"><i class="fa fa-check"></i><b>11</b> Pimping your plots</a>
<ul>
<li class="chapter" data-level="11.1" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#a-basic-plot"><i class="fa fa-check"></i><b>11.1</b> A basic plot</a></li>
<li class="chapter" data-level="11.2" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#axis-limits"><i class="fa fa-check"></i><b>11.2</b> Axis limits</a></li>
<li class="chapter" data-level="11.3" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#transforming-the-axis-log-scale"><i class="fa fa-check"></i><b>11.3</b> Transforming the axis (log scale)</a></li>
<li class="chapter" data-level="11.4" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#changing-the-axis-tick-marks"><i class="fa fa-check"></i><b>11.4</b> Changing the axis tick marks</a></li>
<li class="chapter" data-level="11.5" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#axis-labels"><i class="fa fa-check"></i><b>11.5</b> Axis labels</a></li>
<li class="chapter" data-level="11.6" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#colours"><i class="fa fa-check"></i><b>11.6</b> Colours</a></li>
<li class="chapter" data-level="11.7" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#themes"><i class="fa fa-check"></i><b>11.7</b> Themes</a></li>
<li class="chapter" data-level="11.8" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#moving-the-legend"><i class="fa fa-check"></i><b>11.8</b> Moving the legend</a></li>
<li class="chapter" data-level="11.9" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#combining-multiple-plots"><i class="fa fa-check"></i><b>11.9</b> Combining multiple plots</a></li>
<li class="chapter" data-level="11.10" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#saving-your-plot"><i class="fa fa-check"></i><b>11.10</b> Saving your plot</a></li>
<li class="chapter" data-level="11.11" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#final-word-on-plots"><i class="fa fa-check"></i><b>11.11</b> Final word on plots</a></li>
</ul></li>
<li class="part"><span><b>III Statistics</b></span></li>
<li class="chapter" data-level="12" data-path="randomisation-tests.html"><a href="randomisation-tests.html"><i class="fa fa-check"></i><b>12</b> Randomisation Tests</a>
<ul>
<li class="chapter" data-level="12.1" data-path="randomisation-tests.html"><a href="randomisation-tests.html#randomisation-test-in-r"><i class="fa fa-check"></i><b>12.1</b> Randomisation test in R</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="randomisation-tests.html"><a href="randomisation-tests.html#calculate-the-observed-difference"><i class="fa fa-check"></i><b>12.1.1</b> Calculate the observed difference</a></li>
<li class="chapter" data-level="12.1.2" data-path="randomisation-tests.html"><a href="randomisation-tests.html#null-distribution"><i class="fa fa-check"></i><b>12.1.2</b> Null distribution</a></li>
<li class="chapter" data-level="12.1.3" data-path="randomisation-tests.html"><a href="randomisation-tests.html#testing-significance"><i class="fa fa-check"></i><b>12.1.3</b> Testing significance</a></li>
<li class="chapter" data-level="12.1.4" data-path="randomisation-tests.html"><a href="randomisation-tests.html#testing-the-hypothesis"><i class="fa fa-check"></i><b>12.1.4</b> Testing the hypothesis</a></li>
<li class="chapter" data-level="12.1.5" data-path="randomisation-tests.html"><a href="randomisation-tests.html#writing-it-up"><i class="fa fa-check"></i><b>12.1.5</b> Writing it up</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="randomisation-tests.html"><a href="randomisation-tests.html#paired-randomisation-tests"><i class="fa fa-check"></i><b>12.2</b> Paired Randomisation Tests</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="randomisation-tests.html"><a href="randomisation-tests.html#the-randomisation-test"><i class="fa fa-check"></i><b>12.2.1</b> The randomisation test</a></li>
<li class="chapter" data-level="12.2.2" data-path="randomisation-tests.html"><a href="randomisation-tests.html#null-distribution-1"><i class="fa fa-check"></i><b>12.2.2</b> Null distribution</a></li>
<li class="chapter" data-level="12.2.3" data-path="randomisation-tests.html"><a href="randomisation-tests.html#the-formal-hypothesis-test"><i class="fa fa-check"></i><b>12.2.3</b> The formal hypothesis test</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="randomisation-tests.html"><a href="randomisation-tests.html#exercise-sexual-selection-in-hercules-beetles"><i class="fa fa-check"></i><b>12.3</b> Exercise: Sexual selection in Hercules beetles</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html"><i class="fa fa-check"></i><b>13</b> t-test: Comparing two means</a>
<ul>
<li class="chapter" data-level="13.1" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#some-theory"><i class="fa fa-check"></i><b>13.1</b> Some theory</a></li>
<li class="chapter" data-level="13.2" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#one-sample-t-test"><i class="fa fa-check"></i><b>13.2</b> One sample t-test</a></li>
<li class="chapter" data-level="13.3" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#doing-it-by-hand---where-does-the-t-statistic-come-from"><i class="fa fa-check"></i><b>13.3</b> Doing it “by hand” - where does the t-statistic come from?</a></li>
<li class="chapter" data-level="13.4" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#paired-t-test"><i class="fa fa-check"></i><b>13.4</b> Paired t-test</a></li>
<li class="chapter" data-level="13.5" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#a-paired-t-test-is-a-one-sample-test."><i class="fa fa-check"></i><b>13.5</b> A paired t-test is a one-sample test.</a></li>
<li class="chapter" data-level="13.6" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#two-sample-t-test"><i class="fa fa-check"></i><b>13.6</b> Two sample t-test</a></li>
<li class="chapter" data-level="13.7" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#t-tests-are-linear-models"><i class="fa fa-check"></i><b>13.7</b> t-tests are linear models</a></li>
<li class="chapter" data-level="13.8" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#exercise-sex-differences-in-fine-motor-skills"><i class="fa fa-check"></i><b>13.8</b> Exercise: Sex differences in fine motor skills</a></li>
<li class="chapter" data-level="13.9" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#exercise-therapy-for-anorexia"><i class="fa fa-check"></i><b>13.9</b> Exercise: Therapy for anorexia</a></li>
<li class="chapter" data-level="13.10" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#exercise-compare-t-tests-with-randomisation-tests-optional"><i class="fa fa-check"></i><b>13.10</b> Exercise: Compare t-tests with randomisation tests (optional)</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="assumptions-in-linear-models.html"><a href="assumptions-in-linear-models.html"><i class="fa fa-check"></i><b>14</b> Assumptions in linear models</a>
<ul>
<li class="chapter" data-level="14.1" data-path="assumptions-in-linear-models.html"><a href="assumptions-in-linear-models.html#the-assumptions"><i class="fa fa-check"></i><b>14.1</b> The assumptions</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><i class="fa fa-check"></i><b>15</b> ANOVA: Linear models with a single categorical explanatory variable</a>
<ul>
<li class="chapter" data-level="15.1" data-path="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#one-way-anova"><i class="fa fa-check"></i><b>15.1</b> One-way ANOVA</a></li>
<li class="chapter" data-level="15.2" data-path="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#fitting-an-anova-in-r"><i class="fa fa-check"></i><b>15.2</b> Fitting an ANOVA in R</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#where-are-the-differences"><i class="fa fa-check"></i><b>15.2.1</b> Where are the differences?</a></li>
<li class="chapter" data-level="15.2.2" data-path="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#tukeys-honestly-significant-difference-hsd"><i class="fa fa-check"></i><b>15.2.2</b> Tukey’s Honestly Significant Difference (HSD)</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#anova-calculation-by-hand."><i class="fa fa-check"></i><b>15.3</b> ANOVA calculation “by hand”.</a></li>
<li class="chapter" data-level="15.4" data-path="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#exercise-apple-tree-crop-yield"><i class="fa fa-check"></i><b>15.4</b> Exercise: Apple tree crop yield</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="linear-regression-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html"><i class="fa fa-check"></i><b>16</b> Linear regression: models with a single continuous explanatory variable</a>
<ul>
<li class="chapter" data-level="16.1" data-path="linear-regression-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#some-theory-1"><i class="fa fa-check"></i><b>16.1</b> Some theory</a></li>
<li class="chapter" data-level="16.2" data-path="linear-regression-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#evaluating-a-hypothesis-with-a-linear-regression-model"><i class="fa fa-check"></i><b>16.2</b> Evaluating a hypothesis with a linear regression model</a></li>
<li class="chapter" data-level="16.3" data-path="linear-regression-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#assumptions"><i class="fa fa-check"></i><b>16.3</b> Assumptions</a></li>
<li class="chapter" data-level="16.4" data-path="linear-regression-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#worked-example-height-hand-width-relationship"><i class="fa fa-check"></i><b>16.4</b> Worked example: height-hand width relationship</a></li>
<li class="chapter" data-level="16.5" data-path="linear-regression-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#exercise-chirping-crickets"><i class="fa fa-check"></i><b>16.5</b> Exercise: Chirping crickets</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html"><a href="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html"><i class="fa fa-check"></i><b>17</b> ANCOVA: Linear models with categorical and continuous explanatory variables</a>
<ul>
<li class="chapter" data-level="17.1" data-path="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html"><a href="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html#the-height-hand-width-example."><i class="fa fa-check"></i><b>17.1</b> The height ~ hand width example.</a></li>
<li class="chapter" data-level="17.2" data-path="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html"><a href="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html#summarising-with-anova"><i class="fa fa-check"></i><b>17.2</b> Summarising with <code>anova</code></a></li>
<li class="chapter" data-level="17.3" data-path="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html"><a href="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html#the-summary-of-coefficients-summary"><i class="fa fa-check"></i><b>17.3</b> The summary of coefficients (<code>summary</code>)</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html"><i class="fa fa-check"></i><b>18</b> n-way ANOVA: Linear models with &gt;1 categorical explanatory variables</a>
<ul>
<li class="chapter" data-level="18.1" data-path="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#fitting-a-two-way-anova-model"><i class="fa fa-check"></i><b>18.1</b> Fitting a two-way ANOVA model</a></li>
<li class="chapter" data-level="18.2" data-path="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#summarising-the-model-anova"><i class="fa fa-check"></i><b>18.2</b> Summarising the model (<code>anova</code>)</a></li>
<li class="chapter" data-level="18.3" data-path="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#summarising-the-model-summary"><i class="fa fa-check"></i><b>18.3</b> Summarising the model (<code>summary</code>)</a></li>
<li class="chapter" data-level="18.4" data-path="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#exercise-fish-behaviour"><i class="fa fa-check"></i><b>18.4</b> Exercise: Fish behaviour</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="evaluating-linear-models.html"><a href="evaluating-linear-models.html"><i class="fa fa-check"></i><b>19</b> Evaluating linear models</a>
<ul>
<li class="chapter" data-level="19.1" data-path="evaluating-linear-models.html"><a href="evaluating-linear-models.html#r-squared-value"><i class="fa fa-check"></i><b>19.1</b> R-squared value</a></li>
<li class="chapter" data-level="19.2" data-path="evaluating-linear-models.html"><a href="evaluating-linear-models.html#akaike-information-criterion-aic"><i class="fa fa-check"></i><b>19.2</b> Akaike Information Criterion (AIC)</a></li>
<li class="chapter" data-level="19.3" data-path="evaluating-linear-models.html"><a href="evaluating-linear-models.html#variance-partitioning"><i class="fa fa-check"></i><b>19.3</b> Variance partitioning</a></li>
<li class="chapter" data-level="19.4" data-path="evaluating-linear-models.html"><a href="evaluating-linear-models.html#conclusion"><i class="fa fa-check"></i><b>19.4</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html"><i class="fa fa-check"></i><b>20</b> Generalised linear models</a>
<ul>
<li class="chapter" data-level="20.1" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html#count-data-with-poisson-errors."><i class="fa fa-check"></i><b>20.1</b> Count data with Poisson errors.</a>
<ul>
<li class="chapter" data-level="20.1.1" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html#example-number-of-offspring-in-foxes."><i class="fa fa-check"></i><b>20.1.1</b> Example: Number of offspring in foxes.</a></li>
<li class="chapter" data-level="20.1.2" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html#example-cancer-clusters"><i class="fa fa-check"></i><b>20.1.2</b> Example: Cancer clusters</a></li>
</ul></li>
<li class="chapter" data-level="20.2" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html#exercise-maze-runner"><i class="fa fa-check"></i><b>20.2</b> Exercise: Maze runner</a></li>
<li class="chapter" data-level="20.3" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html#overdispersion"><i class="fa fa-check"></i><b>20.3</b> Overdispersion</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="extending-use-cases-of-glm.html"><a href="extending-use-cases-of-glm.html"><i class="fa fa-check"></i><b>21</b> Extending use cases of GLM</a>
<ul>
<li class="chapter" data-level="21.1" data-path="extending-use-cases-of-glm.html"><a href="extending-use-cases-of-glm.html#binomial-response-data"><i class="fa fa-check"></i><b>21.1</b> Binomial response data</a></li>
<li class="chapter" data-level="21.2" data-path="extending-use-cases-of-glm.html"><a href="extending-use-cases-of-glm.html#example-nfl-field-goals"><i class="fa fa-check"></i><b>21.2</b> Example: NFL field goals</a></li>
<li class="chapter" data-level="21.3" data-path="extending-use-cases-of-glm.html"><a href="extending-use-cases-of-glm.html#example-sex-ratio-in-turtles"><i class="fa fa-check"></i><b>21.3</b> Example: Sex ratio in turtles</a></li>
<li class="chapter" data-level="21.4" data-path="extending-use-cases-of-glm.html"><a href="extending-use-cases-of-glm.html#example-smoking"><i class="fa fa-check"></i><b>21.4</b> Example: Smoking</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html"><i class="fa fa-check"></i><b>22</b> Power analysis by simulation</a>
<ul>
<li class="chapter" data-level="22.1" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#type-i-and-ii-errors-and-statistical-power"><i class="fa fa-check"></i><b>22.1</b> Type I and II errors and statistical power</a></li>
<li class="chapter" data-level="22.2" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#what-determines-statistical-power"><i class="fa fa-check"></i><b>22.2</b> What determines statistical power?</a></li>
<li class="chapter" data-level="22.3" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#an-example-of-calculating-statistical-power."><i class="fa fa-check"></i><b>22.3</b> An example of calculating statistical power.</a>
<ul>
<li class="chapter" data-level="22.3.1" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#the-simulation"><i class="fa fa-check"></i><b>22.3.1</b> The simulation</a></li>
<li class="chapter" data-level="22.3.2" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#some-questions-for-you-to-address"><i class="fa fa-check"></i><b>22.3.2</b> Some questions for you to address:</a></li>
</ul></li>
<li class="chapter" data-level="22.4" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#summary"><i class="fa fa-check"></i><b>22.4</b> Summary</a></li>
<li class="chapter" data-level="22.5" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#extending-the-simulation-optional-advanced"><i class="fa fa-check"></i><b>22.5</b> Extending the simulation (optional, advanced)</a></li>
<li class="chapter" data-level="22.6" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#exercise-1-snails-on-the-move"><i class="fa fa-check"></i><b>22.6</b> Exercise 1: Snails on the move</a></li>
<li class="chapter" data-level="22.7" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#exercise-2-mouse-lemur-strength"><i class="fa fa-check"></i><b>22.7</b> Exercise 2: Mouse lemur strength</a></li>
</ul></li>
<li class="part"><span><b>IV Appendix</b></span></li>
<li class="chapter" data-level="23" data-path="examples-of-statistics-reporting.html"><a href="examples-of-statistics-reporting.html"><i class="fa fa-check"></i><b>23</b> Examples of statistics reporting</a>
<ul>
<li class="chapter" data-level="23.1" data-path="examples-of-statistics-reporting.html"><a href="examples-of-statistics-reporting.html#t-test"><i class="fa fa-check"></i><b>23.1</b> t-test</a></li>
<li class="chapter" data-level="23.2" data-path="examples-of-statistics-reporting.html"><a href="examples-of-statistics-reporting.html#simple-linear-regression-model"><i class="fa fa-check"></i><b>23.2</b> Simple linear regression model</a></li>
<li class="chapter" data-level="23.3" data-path="examples-of-statistics-reporting.html"><a href="examples-of-statistics-reporting.html#a-generalised-linear-model-glm"><i class="fa fa-check"></i><b>23.3</b> A Generalised linear model (GLM)</a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="an-example-of-a-past-written-assignment-2020.html"><a href="an-example-of-a-past-written-assignment-2020.html"><i class="fa fa-check"></i><b>24</b> An example of a past Written Assignment (2020)</a></li>
<li class="chapter" data-level="25" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html"><i class="fa fa-check"></i><b>25</b> Leveraging ChatGPT for R Programming Assistance</a>
<ul>
<li class="chapter" data-level="25.1" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#introduction"><i class="fa fa-check"></i><b>25.1</b> Introduction</a></li>
<li class="chapter" data-level="25.2" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#overview"><i class="fa fa-check"></i><b>25.2</b> Overview</a></li>
<li class="chapter" data-level="25.3" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#what-is-a-large-language-model-llm-and-how-do-they-work"><i class="fa fa-check"></i><b>25.3</b> What is a Large Language Model (LLM) and how do they work?</a></li>
<li class="chapter" data-level="25.4" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#limitations"><i class="fa fa-check"></i><b>25.4</b> Limitations</a>
<ul>
<li class="chapter" data-level="25.4.1" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#limited-knowledge"><i class="fa fa-check"></i><b>25.4.1</b> Limited knowledge</a></li>
<li class="chapter" data-level="25.4.2" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#hallucination"><i class="fa fa-check"></i><b>25.4.2</b> Hallucination</a></li>
<li class="chapter" data-level="25.4.3" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#numerical-ability"><i class="fa fa-check"></i><b>25.4.3</b> Numerical ability</a></li>
</ul></li>
<li class="chapter" data-level="25.5" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#ethics-of-using-llms-in-education"><i class="fa fa-check"></i><b>25.5</b> Ethics of using LLMs in education</a></li>
<li class="chapter" data-level="25.6" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#use-cases-in-r"><i class="fa fa-check"></i><b>25.6</b> Use cases in R</a>
<ul>
<li class="chapter" data-level="25.6.1" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#finding-errors."><i class="fa fa-check"></i><b>25.6.1</b> Finding errors.</a></li>
<li class="chapter" data-level="25.6.2" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#explaining-code"><i class="fa fa-check"></i><b>25.6.2</b> Explaining code</a></li>
<li class="chapter" data-level="25.6.3" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#interpreting-output"><i class="fa fa-check"></i><b>25.6.3</b> Interpreting output</a></li>
<li class="chapter" data-level="25.6.4" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#translating-code-e.g.-from-pythonmatlab-to-r"><i class="fa fa-check"></i><b>25.6.4</b> Translating code (e.g. from Python/Matlab to R)</a></li>
<li class="chapter" data-level="25.6.5" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#solving-modelling-problems"><i class="fa fa-check"></i><b>25.6.5</b> Solving modelling problems</a></li>
<li class="chapter" data-level="25.6.6" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#helping-with-documentationcomments"><i class="fa fa-check"></i><b>25.6.6</b> Helping with documentation/comments</a></li>
<li class="chapter" data-level="25.6.7" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#finding-alternativebetter-ways"><i class="fa fa-check"></i><b>25.6.7</b> Finding alternative/better ways</a></li>
</ul></li>
<li class="chapter" data-level="25.7" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#some-tips"><i class="fa fa-check"></i><b>25.7</b> Some tips</a></li>
</ul></li>
<li class="part"><span><b>V Solutions</b></span></li>
<li class="chapter" data-level="26" data-path="exercise-solutions.html"><a href="exercise-solutions.html"><i class="fa fa-check"></i><b>26</b> Exercise Solutions</a>
<ul>
<li class="chapter" data-level="26.1" data-path="exercise-solutions.html"><a href="exercise-solutions.html#californian-bird-diversity"><i class="fa fa-check"></i><b>26.1</b> Californian bird diversity</a></li>
<li class="chapter" data-level="26.2" data-path="exercise-solutions.html"><a href="exercise-solutions.html#wrangling-the-amniote-life-history-database"><i class="fa fa-check"></i><b>26.2</b> Wrangling the Amniote Life History Database</a></li>
<li class="chapter" data-level="26.3" data-path="exercise-solutions.html"><a href="exercise-solutions.html#temperature-effects-on-egg-laying-dates"><i class="fa fa-check"></i><b>26.3</b> Temperature effects on egg laying dates</a></li>
<li class="chapter" data-level="26.4" data-path="exercise-solutions.html"><a href="exercise-solutions.html#virtual-dice"><i class="fa fa-check"></i><b>26.4</b> Virtual dice</a></li>
<li class="chapter" data-level="26.5" data-path="exercise-solutions.html"><a href="exercise-solutions.html#sexual-selection-in-hercules-beetles"><i class="fa fa-check"></i><b>26.5</b> Sexual selection in Hercules beetles</a></li>
<li class="chapter" data-level="26.6" data-path="exercise-solutions.html"><a href="exercise-solutions.html#sex-differences-in-fine-motor-skills"><i class="fa fa-check"></i><b>26.6</b> Sex differences in fine motor skills</a></li>
<li class="chapter" data-level="26.7" data-path="exercise-solutions.html"><a href="exercise-solutions.html#therapy-for-anorexia"><i class="fa fa-check"></i><b>26.7</b> Therapy for anorexia</a></li>
<li class="chapter" data-level="26.8" data-path="exercise-solutions.html"><a href="exercise-solutions.html#compare-t-tests-with-randomisation-tests"><i class="fa fa-check"></i><b>26.8</b> Compare t-tests with randomisation tests</a></li>
<li class="chapter" data-level="26.9" data-path="exercise-solutions.html"><a href="exercise-solutions.html#apple-tree-crop-yield"><i class="fa fa-check"></i><b>26.9</b> Apple tree crop yield</a></li>
<li class="chapter" data-level="26.10" data-path="exercise-solutions.html"><a href="exercise-solutions.html#chirping-crickets"><i class="fa fa-check"></i><b>26.10</b> Chirping crickets</a></li>
<li class="chapter" data-level="26.11" data-path="exercise-solutions.html"><a href="exercise-solutions.html#fish-behaviour"><i class="fa fa-check"></i><b>26.11</b> Fish behaviour</a></li>
<li class="chapter" data-level="26.12" data-path="exercise-solutions.html"><a href="exercise-solutions.html#maze-runner"><i class="fa fa-check"></i><b>26.12</b> Maze runner</a></li>
<li class="chapter" data-level="26.13" data-path="exercise-solutions.html"><a href="exercise-solutions.html#snails-on-the-move"><i class="fa fa-check"></i><b>26.13</b> Snails on the move</a></li>
<li class="chapter" data-level="26.14" data-path="exercise-solutions.html"><a href="exercise-solutions.html#mouse-lemur-strength"><i class="fa fa-check"></i><b>26.14</b> Mouse lemur strength</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">BB852 - Data handling, visualisation and statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="n-way-anova-linear-models-with-1-categorical-explanatory-variables" class="section level1 hasAnchor" number="18">
<h1><span class="header-section-number">Chapter 18</span> n-way ANOVA: Linear models with &gt;1 categorical explanatory variables<a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#n-way-anova-linear-models-with-1-categorical-explanatory-variables" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In the one-way ANOVA we covered in the previous chapter we were interested in understanding the effect of a single categorical explanatory variable with two or more levels on a continuous response variable. Although the explanatory variable must be categorical (i.e. with discrete levels), it could represent a continuous variable. For example, the explanatory variable could be a two-level soil nutrient level (high or low), even though nutrient level is a continuous variable and one could measure the actual quantitative value of nutrients in mg/g.</p>
<p>The two-way ANOVA is an extension of one-way ANOVA that allows you to investigate the effect of <strong>two</strong> categorical variables. This can be useful in an experimental context.</p>
<p>For example, one might have run an experiment investigating in the effect of two types of diet (<em>lowProtein</em> and <em>highProtein</em>), and genotype (<em>gt1</em> and <em>gt2</em>), on adult size of a pest species. It is worth thinking about what potential outcomes there are for this experiment. There may be no effect of diet, and no effect of genotype. There may be an effect of one of these variables but not the other. The effect of the diet might be the same for the different genotypes, or it might be different. Some of these different possible outcomes are illustrated in Figure <a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#fig:3-06-n-way-ANOVA-1">18.1</a>. the titles indicate with Y (yes) or N (no) whether the figure shows a significant diet, genotype (gt) or interaction (int) effect. The dotted lines joining the estimates for the two genotypes are a kind of <strong>interaction plot</strong>: where they are parallel, there is no interaction.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:3-06-n-way-ANOVA-1"></span>
<img src="BB852_files/figure-html/3-06-n-way-ANOVA-1-1.png" alt="Some potential results of the experiment. There may be a significant effect (or not) of both of the main effects (diet and genotype) and there may be a significant interaction effect (or not)." width="960" />
<p class="caption">
Figure 18.1: Some potential results of the experiment. There may be a significant effect (or not) of both of the main effects (diet and genotype) and there may be a significant interaction effect (or not).
</p>
</div>
<p>In the model we aim to quantify these effects, and ask if they are statistically significant (i.e. if the effect sizes are &gt;0). We divide the effects of the explanatory variables into two types: <strong>main effects</strong> and <strong>interaction effects</strong>. The main effects are the overall effect of the explanatory variables (genotype and diet in this case) while the interaction effect allows us to ask whether one main effect <em>depends on another</em>. In this case we are asking whether <em>the effect of diet depends on genotype (and vice versa)</em>. Make sure that you understand this important concept.</p>
<div id="fitting-a-two-way-anova-model" class="section level2 hasAnchor" number="18.1">
<h2><span class="header-section-number">18.1</span> Fitting a two-way ANOVA model<a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#fitting-a-two-way-anova-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Let’s use R to fit a two-way ANOVA model using data from the example I just described. As with one-way ANOVA, you can fit a two-way ANOVA model in R using <code>lm</code>.</p>
<div class="do-something">
<p>
Remember to load the <code>dplyr</code>, <code>magrittr</code> and
<code>ggplot</code> packages, and to set your working directory
correctly.
</p>
</div>
<p>First, import the <code>insectDiet.csv</code> data and plot it, to produce a plot like in Figure <a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#fig:3-06-n-way-ANOVA-3">18.2</a>. From looking at the graph in this Figure, you can see (a) genotype 1 tends to be larger than genotype 2; (b) insects raised on a high protein diet tend to be larger than those on a low protein diet; and (c) the effect of the diet (i.e. the <em>difference</em> in size between the insects raised on the different diets) is larger for genotype 1 than it is for genotype 2. But are these differences statistically meaningful?</p>
<div class="sourceCode" id="cb415"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb415-1"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#cb415-1" tabindex="-1"></a>insectDiet <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;CourseData/insectDiet.csv&quot;</span>)</span>
<span id="cb415-2"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#cb415-2" tabindex="-1"></a></span>
<span id="cb415-3"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#cb415-3" tabindex="-1"></a><span class="fu">ggplot</span>(insectDiet, <span class="fu">aes</span>(<span class="at">x =</span> genotype, <span class="at">y =</span> lengthMM, <span class="at">fill =</span> diet)) <span class="sc">+</span></span>
<span id="cb415-4"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#cb415-4" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb415-5"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#cb415-5" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Genotype&quot;</span>) <span class="sc">+</span></span>
<span id="cb415-6"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#cb415-6" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Length (mm)&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:3-06-n-way-ANOVA-3"></span>
<img src="BB852_files/figure-html/3-06-n-way-ANOVA-3-1.png" alt="The effect of diet protein content and genotype on adult size of an insect species" width="480" />
<p class="caption">
Figure 18.2: The effect of diet protein content and genotype on adult size of an insect species
</p>
</div>
<p>To address this question, we will fit a linear model (the two-way ANOVA) to estimate the effects of diet and genotype.</p>
<p>The model formula is <code>lengthMM ~ genotype + diet + genotype:diet</code>.</p>
<p>Let’s try to understand this. The <code>genotype + diet</code> part represents the <strong>main effects</strong> of these two variables, and the <code>genotype:diet</code> part represents the <strong>interaction effect</strong> between them. This formula<em>can</em> be shortened to <code>lengthMM ~ genotype * diet</code> (i.e. this is exactly equivalent to the more complicated-looking formula), but I recommend to use the longer version because it is clearer.</p>
<p>So we fit the model like this - putting the formula first, then telling R which data to use:</p>
<div class="sourceCode" id="cb416"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb416-1"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#cb416-1" tabindex="-1"></a>mod_A <span class="ot">&lt;-</span> <span class="fu">lm</span>(lengthMM <span class="sc">~</span> genotype <span class="sc">+</span> diet <span class="sc">+</span> genotype<span class="sc">:</span>diet,</span>
<span id="cb416-2"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#cb416-2" tabindex="-1"></a>  <span class="at">data =</span> insectDiet</span>
<span id="cb416-3"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#cb416-3" tabindex="-1"></a>)</span></code></pre></div>
<p>Then we can look at diagnostic plots, as with ANOVA etc.:</p>
<div class="sourceCode" id="cb417"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb417-1"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#cb417-1" tabindex="-1"></a><span class="fu">library</span>(ggfortify)</span>
<span id="cb417-2"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#cb417-2" tabindex="-1"></a><span class="fu">autoplot</span>(mod_A)</span></code></pre></div>
<p><img src="BB852_files/figure-html/3-06-n-way-ANOVA-5-1.png" width="672" /></p>
<p>These all look OK. The slightly odd structure in the QQ-plot is caused by the fact that the length data are rounded to the nearest millimeter. There is no evidence of heteroscedasticity (left hand plots) now any major outliers.</p>
</div>
<div id="summarising-the-model-anova" class="section level2 hasAnchor" number="18.2">
<h2><span class="header-section-number">18.2</span> Summarising the model (<code>anova</code>)<a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#summarising-the-model-anova" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Since we are satisfied with the diagnostic plots we can proceed by summarising the model using first <code>anova</code> and then <code>summary</code>.</p>
<div class="sourceCode" id="cb418"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb418-1"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#cb418-1" tabindex="-1"></a><span class="fu">anova</span>(mod_A)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: lengthMM
##               Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## genotype       1 426.02  426.02  99.575 7.135e-13 ***
## diet           1 111.02  111.02  25.949 7.064e-06 ***
## genotype:diet  1  54.19   54.19  12.665 0.0009073 ***
## Residuals     44 188.25    4.28                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>This summary <code>Analysis of Variance Table</code> is similar to the ones you have already seen for one-way ANOVA and linear regression. It just has some extra rows because you have extra explanatory variables. It shows you the degrees of freedom for the different terms in the model (all 1, because they have two levels), the sum of squares (<code>Sum Sq</code>) and mean sum of squares (<code>Mean Sq</code>) and the associated <code>F value</code> and p-value (<code>Pr(&gt;F)</code>). Those F values are all large, leading to highly-significant p-values.</p>
<p>This means that all of those terms in the model explain a significant proportion of the variation in insect length.</p>
<p>But as you know, this summary table doesn’t tell you the direction of the effects. The obvious way to understand your data is to simply look at the plot you have already produced. You could also make an <strong>interaction plot</strong> which is a simplified version of the plot of the raw data.</p>
<p>To do this you first need to create a summary table using <code>dplyr</code> tools <code>summarise</code> and <code>group_by</code> to get the mean and standard errors of the mean:</p>
<div class="sourceCode" id="cb420"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb420-1"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#cb420-1" tabindex="-1"></a>insectDiet_means <span class="ot">&lt;-</span></span>
<span id="cb420-2"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#cb420-2" tabindex="-1"></a>  insectDiet <span class="sc">%&gt;%</span></span>
<span id="cb420-3"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#cb420-3" tabindex="-1"></a>  <span class="fu">group_by</span>(genotype, diet) <span class="sc">%&gt;%</span> <span class="co"># &lt;- remember to group by *both* factors</span></span>
<span id="cb420-4"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#cb420-4" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">MeanLength =</span> <span class="fu">mean</span>(lengthMM), <span class="at">SELength =</span> <span class="fu">sd</span>(lengthMM) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">n</span>()))</span>
<span id="cb420-5"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#cb420-5" tabindex="-1"></a>insectDiet_means</span></code></pre></div>
<pre><code>## # A tibble: 4 × 4
## # Groups:   genotype [2]
##   genotype diet        MeanLength SELength
##   &lt;chr&gt;    &lt;chr&gt;            &lt;dbl&gt;    &lt;dbl&gt;
## 1 gt1      highProtein       25.8    0.672
## 2 gt1      lowProtein        20.7    0.527
## 3 gt2      highProtein       17.8    0.698
## 4 gt2      lowProtein        16.8    0.458</code></pre>
<p>Then you can make a simple plot of this information by plotting points, and lines joining them:</p>
<div class="sourceCode" id="cb422"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb422-1"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#cb422-1" tabindex="-1"></a>(A <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(</span>
<span id="cb422-2"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#cb422-2" tabindex="-1"></a>  insectDiet_means,</span>
<span id="cb422-3"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#cb422-3" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> genotype, <span class="at">y =</span> MeanLength, <span class="at">colour =</span> diet, <span class="at">group =</span> diet)</span>
<span id="cb422-4"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#cb422-4" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb422-5"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#cb422-5" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb422-6"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#cb422-6" tabindex="-1"></a>  <span class="fu">geom_line</span>())</span></code></pre></div>
<p><img src="BB852_files/figure-html/3-06-n-way-ANOVA-8,%20interactionPlot-1.png" width="480" style="display: block; margin: auto;" /></p>
<p>You could add error bars to the points by adding a line defining the <code>ymin</code> and <code>ymax</code> values from the data summary like this:</p>
<div class="sourceCode" id="cb423"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb423-1"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#cb423-1" tabindex="-1"></a><span class="fu">ggplot</span>(</span>
<span id="cb423-2"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#cb423-2" tabindex="-1"></a>  insectDiet_means,</span>
<span id="cb423-3"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#cb423-3" tabindex="-1"></a>  <span class="fu">aes</span>(</span>
<span id="cb423-4"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#cb423-4" tabindex="-1"></a>    <span class="at">x =</span> genotype, <span class="at">y =</span> MeanLength, <span class="at">colour =</span> diet, <span class="at">group =</span> diet,</span>
<span id="cb423-5"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#cb423-5" tabindex="-1"></a>    <span class="at">ymin =</span> MeanLength <span class="sc">-</span> SELength, <span class="at">ymax =</span> MeanLength <span class="sc">+</span> SELength</span>
<span id="cb423-6"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#cb423-6" tabindex="-1"></a>  )</span>
<span id="cb423-7"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#cb423-7" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb423-8"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#cb423-8" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb423-9"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#cb423-9" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb423-10"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#cb423-10" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="at">width =</span> <span class="fl">0.1</span>)</span></code></pre></div>
<p><img src="BB852_files/figure-html/3-06-n-way-ANOVA-9,%20errorBars-1.png" width="480" style="display: block; margin: auto;" /></p>
<p>But are these points statistically significantly different from each other?
To answer that question we need to use a post-hoc test</p>
<div class="sourceCode" id="cb424"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb424-1"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#cb424-1" tabindex="-1"></a><span class="fu">library</span>(agricolae)</span>
<span id="cb424-2"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#cb424-2" tabindex="-1"></a><span class="fu">HSD.test</span>(mod_A, <span class="at">trt =</span> <span class="fu">c</span>(<span class="st">&quot;diet&quot;</span>, <span class="st">&quot;genotype&quot;</span>), <span class="at">console =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
## Study: mod_A ~ c(&quot;diet&quot;, &quot;genotype&quot;)
## 
## HSD Test for lengthMM 
## 
## Mean Square Error:  4.278409 
## 
## diet:genotype,  means
## 
##                 lengthMM      std  r        se Min Max   Q25  Q50   Q75
## highProtein:gt1 25.83333 2.329000 12 0.5971048  23  31 24.75 25.5 26.25
## highProtein:gt2 17.75000 2.416797 12 0.5971048  14  22 15.75 18.0 19.25
## lowProtein:gt1  20.66667 1.825742 12 0.5971048  17  24 19.75 21.0 22.00
## lowProtein:gt2  16.83333 1.585923 12 0.5971048  14  19 16.00 16.5 18.00
## 
## Alpha: 0.05 ; DF Error: 44 
## Critical Value of Studentized Range: 3.775958 
## 
## Minimun Significant Difference: 2.254643 
## 
## Treatments with the same letter are not significantly different.
## 
##                 lengthMM groups
## highProtein:gt1 25.83333      a
## lowProtein:gt1  20.66667      b
## highProtein:gt2 17.75000      c
## lowProtein:gt2  16.83333      c</code></pre>
<p>The important part of this output is at the bottom where it tells us <code>Treatments with the same letter are not significantly different.</code>. You can see that the mean lengths between diets for genotype 1 are significantly different (they do not share a letter). However, there is no significant difference between diets for genotype 2 (they share the same letter, <code>c</code>). The two genotypes are also significantly different from each other.</p>
</div>
<div id="summarising-the-model-summary" class="section level2 hasAnchor" number="18.3">
<h2><span class="header-section-number">18.3</span> Summarising the model (<code>summary</code>)<a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#summarising-the-model-summary" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This (above) is generally enough information for a complete write up of results. However, you can ask R to provide the model summary that includes the <span class="math inline">\(R^2\)</span> values, coefficient estimates and standard errors using <code>summary</code>.</p>
<div class="sourceCode" id="cb426"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb426-1"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#cb426-1" tabindex="-1"></a><span class="fu">summary</span>(mod_A)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = lengthMM ~ genotype + diet + genotype:diet, data = insectDiet)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.7500 -1.0417  0.1667  1.2500  5.1667 
## 
## Coefficients:
##                            Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                 25.8333     0.5971  43.264  &lt; 2e-16 ***
## genotypegt2                 -8.0833     0.8444  -9.572 2.53e-12 ***
## dietlowProtein              -5.1667     0.8444  -6.118 2.26e-07 ***
## genotypegt2:dietlowProtein   4.2500     1.1942   3.559 0.000907 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.068 on 44 degrees of freedom
## Multiple R-squared:  0.7585, Adjusted R-squared:  0.742 
## F-statistic: 46.06 on 3 and 44 DF,  p-value: 1.254e-13</code></pre>
<p>The most useful thing shown here is the <span class="math inline">\(R^2\)</span> value. Because we have several terms in the model we should use the <code>Adjusted R-squared</code> value of 0.742. This indicates that our model explains 74.2% of variation in insect length.</p>
<p>The next bit is not 100% necessary most of the time…</p>
<p>We already have a good idea of the mean values and standard errors for these data look because we calculated them above directly from the data. For completeness though I will now run through the coefficient estimates part of the summary table.</p>
<p>The coefficient <code>Estimates</code> here are interpreted in a similar way to a one-way ANOVA. Again, it is important to know what the reference point is. When you understand this you can reconstruct the mean values for the various levels of the variables that are estimated by the model. You will see that the model estimates lead to precisely the same estimates as obtained from summarising the data.</p>
<p>Here you can see that:</p>
<ul>
<li><p>The <code>(Intercept)</code> is 25.833 and must refer to the point for <em>genotype 1</em> on a <em>high protein diet</em> (look at the value of the intercept and compare to the graph/summary table, and/or the output from the Tukey test).</p></li>
<li><p>The second coefficient (<code>genotypegt2</code>) is -8.083 which is the <strong>difference</strong> between the reference (intercept) and the value for <em>genotype 2</em> on a <em>high protein diet</em>: (25.833 + (-8.083) = 17.75).</p></li>
<li><p>The third coefficient (<code>dietlowProtein</code>) is -5.167 which is the difference between the reference point and for <em>genotype 1</em> on a <em>low protein diet</em>: (25.833 + (-5.167) = 20.666).</p></li>
<li><p>The final coefficient <code>dietlowProtein:genotypegt2</code> is 4.25 and is “interaction effect” of diet and genotype and represents the <em>additional</em> effect of genotype when it is on diet. In other words, in comparison to the reference point (genotype 1 &amp; high protein diet), the effect of a low protein diet is negative (-8.0833), as is the effect of being genotype 2 (-5.1667). However, having both a low protein diet <strong>and</strong> being genotype 2 leads to an additional positive effect (4.25) on length. The resulting estimate of mean length for <em>genotype 2</em> on a <em>low protein diet</em> is 25.833 + (-8.083) + (-5.167) + 4.25 = 16.833.</p></li>
</ul>
<p>This is a bit complicated so my advice is generally to refer to the figures and the outputs of the <code>Tukey.HSD</code> function to obtain the estimate in the different groups.</p>
<p>The logic and methods of the two-way ANOVA can be extended to produce <span class="math inline">\(n\)</span>-way ANOVA with <span class="math inline">\(n\)</span> categorical variables.</p>
</div>
<div id="exercise-fish-behaviour" class="section level2 hasAnchor" number="18.4">
<h2><span class="header-section-number">18.4</span> Exercise: Fish behaviour<a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#exercise-fish-behaviour" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Individual differences in animal personality and external appearance such as colouration patterns have both been extensively studied separately. A significant body of research has explored many of pertinent ecological and biological aspects that can be affected by them and their impact upon fitness. Currently little is known about how both factors interact and their effect on reproductive success.</p>
<p>Researchers carried out a study looking at differences in personality and its interaction with colour phenotype in zebra fish (<em>Danio rerio</em>). They used two colour morphs, “homogeneous” which has clearly defined lateral stripes, and “heterogeneous” which has more variable and less clear patterns.</p>
<p>They also assigned individuals to two personality types which they called “Proactive” (adventurous, risk taking) and “Reactive” (timid, less risk taking). They did this by recording how they explore a new environment</p>
<p>The two variables of interest are:</p>
<ul>
<li>Colour pattern (homogeneous and heterogeneous)</li>
<li>Personality (proactive and reactive)</li>
</ul>
<p>The research questions are: <em>What is the relative influence of colour pattern and personality? Which is more important? How do the variables interact to determine fitness? e.g. do proactive individuals do better than reactive ones, and does this depend on colour pattern? Or some other pattern?</em></p>
<ol style="list-style-type: decimal">
<li><p>Import the data set, <code>fishPersonality.csv</code></p></li>
<li><p>Plot the data (e.g. as a box plot)</p></li>
<li><p>Fit an ANOVA model using <code>lm</code>.</p></li>
<li><p>Look at diagnostic plots from this model (<code>autoplot</code>)</p></li>
<li><p>Use <code>anova</code> to get an Analysis of Variance summary table, and interpret the results.</p></li>
<li><p>Get the coefficient summary (<code>summary</code>) and interpret the output.</p></li>
<li><p>Do post-hoc Tukey tests (e.g. using <code>HSD.test</code> from the <code>agricolae</code> package). Interpret the results.</p></li>
<li><p>Sum up your findings with reference to the initial research questions.</p></li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="evaluating-linear-models.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/jonesor/BB852_Book/edit/master/3_06-n-way_ANOVA.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["BB852.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
},
"split_by": "section"
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
