<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 13 t-test: Comparing two means | BB852 - Data handling, visualisation and statistics</title>
  <meta name="description" content="Course book for BB852 at the Biology Department, University of Southern Denmark" />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 13 t-test: Comparing two means | BB852 - Data handling, visualisation and statistics" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Course book for BB852 at the Biology Department, University of Southern Denmark" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 13 t-test: Comparing two means | BB852 - Data handling, visualisation and statistics" />
  
  <meta name="twitter:description" content="Course book for BB852 at the Biology Department, University of Southern Denmark" />
  

<meta name="author" content="Owen R. Jones" />


<meta name="date" content="2024-11-23" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="randomisation-tests.html"/>
<link rel="next" href="assumptions-in-linear-models.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/tabwid-1.1.3/tabwid.css" rel="stylesheet" />
<script src="libs/tabwid-1.1.3/tabwid.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">BB852</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Preface</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#data-wrangling"><i class="fa fa-check"></i><b>1.1</b> Data wrangling</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#data-visualisation"><i class="fa fa-check"></i><b>1.2</b> Data visualisation</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#statistics"><i class="fa fa-check"></i><b>1.3</b> Statistics</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#data-sources"><i class="fa fa-check"></i><b>1.4</b> Data sources</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#your-instructors"><i class="fa fa-check"></i><b>1.5</b> Your instructor(s)</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#expectations"><i class="fa fa-check"></i><b>1.6</b> Expectations</a></li>
<li class="chapter" data-level="1.7" data-path="index.html"><a href="index.html#your-feedback"><i class="fa fa-check"></i><b>1.7</b> Your feedback</a></li>
<li class="chapter" data-level="1.8" data-path="index.html"><a href="index.html#assessment"><i class="fa fa-check"></i><b>1.8</b> Assessment</a></li>
<li class="chapter" data-level="1.9" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i><b>1.9</b> Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="schedule.html"><a href="schedule.html"><i class="fa fa-check"></i><b>2</b> Schedule</a></li>
<li class="chapter" data-level="3" data-path="additional-recommended-reading.html"><a href="additional-recommended-reading.html"><i class="fa fa-check"></i><b>3</b> Additional recommended reading</a></li>
<li class="chapter" data-level="4" data-path="an-r-refresher.html"><a href="an-r-refresher.html"><i class="fa fa-check"></i><b>4</b> An R refresher</a>
<ul>
<li class="chapter" data-level="4.1" data-path="an-r-refresher.html"><a href="an-r-refresher.html#getting-started-with-r"><i class="fa fa-check"></i><b>4.1</b> Getting started with R</a></li>
<li class="chapter" data-level="4.2" data-path="an-r-refresher.html"><a href="an-r-refresher.html#getting-help"><i class="fa fa-check"></i><b>4.2</b> Getting help</a></li>
<li class="chapter" data-level="4.3" data-path="an-r-refresher.html"><a href="an-r-refresher.html#r-as-a-fancy-calculator"><i class="fa fa-check"></i><b>4.3</b> R as a fancy calculator</a></li>
<li class="chapter" data-level="4.4" data-path="an-r-refresher.html"><a href="an-r-refresher.html#objects-in-r"><i class="fa fa-check"></i><b>4.4</b> Objects in R</a></li>
<li class="chapter" data-level="4.5" data-path="an-r-refresher.html"><a href="an-r-refresher.html#manipulating-objects"><i class="fa fa-check"></i><b>4.5</b> Manipulating objects</a></li>
<li class="chapter" data-level="4.6" data-path="an-r-refresher.html"><a href="an-r-refresher.html#missing-values-infinity-and-non-numbers"><i class="fa fa-check"></i><b>4.6</b> Missing values, infinity and “non-numbers”</a></li>
<li class="chapter" data-level="4.7" data-path="an-r-refresher.html"><a href="an-r-refresher.html#basic-information-about-objects"><i class="fa fa-check"></i><b>4.7</b> Basic information about objects</a></li>
<li class="chapter" data-level="4.8" data-path="an-r-refresher.html"><a href="an-r-refresher.html#data-frames"><i class="fa fa-check"></i><b>4.8</b> Data frames</a></li>
<li class="chapter" data-level="4.9" data-path="an-r-refresher.html"><a href="an-r-refresher.html#classes-in-r"><i class="fa fa-check"></i><b>4.9</b> Classes in R</a></li>
<li class="chapter" data-level="4.10" data-path="an-r-refresher.html"><a href="an-r-refresher.html#organising-your-work"><i class="fa fa-check"></i><b>4.10</b> Organising your work</a></li>
<li class="chapter" data-level="4.11" data-path="an-r-refresher.html"><a href="an-r-refresher.html#inspecting-the-data"><i class="fa fa-check"></i><b>4.11</b> Inspecting the data</a></li>
<li class="chapter" data-level="4.12" data-path="an-r-refresher.html"><a href="an-r-refresher.html#classes-in-r-1"><i class="fa fa-check"></i><b>4.12</b> “Classes” in R</a></li>
<li class="chapter" data-level="4.13" data-path="an-r-refresher.html"><a href="an-r-refresher.html#tables-and-summary-statistics"><i class="fa fa-check"></i><b>4.13</b> Tables and summary statistics</a></li>
<li class="chapter" data-level="4.14" data-path="an-r-refresher.html"><a href="an-r-refresher.html#plotting-data"><i class="fa fa-check"></i><b>4.14</b> Plotting data</a></li>
<li class="chapter" data-level="4.15" data-path="an-r-refresher.html"><a href="an-r-refresher.html#r-packages"><i class="fa fa-check"></i><b>4.15</b> R Packages</a></li>
<li class="chapter" data-level="4.16" data-path="an-r-refresher.html"><a href="an-r-refresher.html#exercise-californian-bird-diversity"><i class="fa fa-check"></i><b>4.16</b> Exercise: Californian bird diversity</a>
<ul>
<li class="chapter" data-level="4.16.1" data-path="an-r-refresher.html"><a href="an-r-refresher.html#the-data"><i class="fa fa-check"></i><b>4.16.1</b> The data</a></li>
<li class="chapter" data-level="4.16.2" data-path="an-r-refresher.html"><a href="an-r-refresher.html#try-the-following"><i class="fa fa-check"></i><b>4.16.2</b> Try the following</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html"><i class="fa fa-check"></i><b>5</b> Tips and tricks</a>
<ul>
<li class="chapter" data-level="5.1" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#appearance"><i class="fa fa-check"></i><b>5.1</b> Appearance</a></li>
<li class="chapter" data-level="5.2" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#shortcuts"><i class="fa fa-check"></i><b>5.2</b> Shortcuts</a></li>
<li class="chapter" data-level="5.3" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#code-style"><i class="fa fa-check"></i><b>5.3</b> Code style</a></li>
<li class="chapter" data-level="5.4" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#the-plots-pane"><i class="fa fa-check"></i><b>5.4</b> The plots pane</a></li>
<li class="chapter" data-level="5.5" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#tables"><i class="fa fa-check"></i><b>5.5</b> Tables</a></li>
<li class="chapter" data-level="5.6" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#importing-data-from-text-files"><i class="fa fa-check"></i><b>5.6</b> Importing data from text files</a></li>
<li class="chapter" data-level="5.7" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#importing-data-from-excel"><i class="fa fa-check"></i><b>5.7</b> Importing data from Excel</a></li>
<li class="chapter" data-level="5.8" data-path="tips-and-tricks.html"><a href="tips-and-tricks.html#numbers"><i class="fa fa-check"></i><b>5.8</b> Numbers</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="paths-and-projects.html"><a href="paths-and-projects.html"><i class="fa fa-check"></i><b>6</b> Paths and projects</a>
<ul>
<li class="chapter" data-level="6.1" data-path="paths-and-projects.html"><a href="paths-and-projects.html#file-paths"><i class="fa fa-check"></i><b>6.1</b> File paths</a></li>
<li class="chapter" data-level="6.2" data-path="paths-and-projects.html"><a href="paths-and-projects.html#file-organisation"><i class="fa fa-check"></i><b>6.2</b> File organisation</a></li>
<li class="chapter" data-level="6.3" data-path="paths-and-projects.html"><a href="paths-and-projects.html#two-types-of-paths"><i class="fa fa-check"></i><b>6.3</b> Two types of paths</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="paths-and-projects.html"><a href="paths-and-projects.html#absolute-paths-the-exact-location"><i class="fa fa-check"></i><b>6.3.1</b> 1. Absolute Paths: The Exact Location</a></li>
<li class="chapter" data-level="6.3.2" data-path="paths-and-projects.html"><a href="paths-and-projects.html#relative-paths-paths-that-start-from-the-project-folder"><i class="fa fa-check"></i><b>6.3.2</b> 2. Relative Paths: Paths That Start from the Project Folder</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="paths-and-projects.html"><a href="paths-and-projects.html#r-and-file-structure"><i class="fa fa-check"></i><b>6.4</b> R and file structure</a></li>
<li class="chapter" data-level="6.5" data-path="paths-and-projects.html"><a href="paths-and-projects.html#setting-the-working-directory-in-r"><i class="fa fa-check"></i><b>6.5</b> Setting the Working Directory in R</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="paths-and-projects.html"><a href="paths-and-projects.html#finding-your-current-working-directory"><i class="fa fa-check"></i><b>6.5.1</b> Finding Your Current Working Directory</a></li>
<li class="chapter" data-level="6.5.2" data-path="paths-and-projects.html"><a href="paths-and-projects.html#changing-the-working-directory"><i class="fa fa-check"></i><b>6.5.2</b> Changing the Working Directory</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="paths-and-projects.html"><a href="paths-and-projects.html#using-projects-in-rstudio-a-simpler-way-to-set-the-working-directory"><i class="fa fa-check"></i><b>6.6</b> Using Projects in RStudio: A Simpler Way to Set the Working Directory</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="paths-and-projects.html"><a href="paths-and-projects.html#steps-to-create-an-r-project"><i class="fa fa-check"></i><b>6.6.1</b> Steps to Create an R Project</a></li>
<li class="chapter" data-level="6.6.2" data-path="paths-and-projects.html"><a href="paths-and-projects.html#organizing-files-within-your-project"><i class="fa fa-check"></i><b>6.6.2</b> Organizing Files Within Your Project</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>I Data Wrangling</b></span></li>
<li class="chapter" data-level="7" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html"><i class="fa fa-check"></i><b>7</b> Data wrangling with <code>dplyr</code></a>
<ul>
<li class="chapter" data-level="7.1" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#select"><i class="fa fa-check"></i><b>7.1</b> <code>select</code></a></li>
<li class="chapter" data-level="7.2" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#filter"><i class="fa fa-check"></i><b>7.2</b> <code>filter</code></a></li>
<li class="chapter" data-level="7.3" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#arrange"><i class="fa fa-check"></i><b>7.3</b> <code>arrange</code></a></li>
<li class="chapter" data-level="7.4" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#summarise-and-group_by"><i class="fa fa-check"></i><b>7.4</b> <code>summarise</code> and <code>group_by</code></a></li>
<li class="chapter" data-level="7.5" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#using-pipes-saving-data."><i class="fa fa-check"></i><b>7.5</b> Using pipes, saving data.</a></li>
<li class="chapter" data-level="7.6" data-path="data-wrangling-with-dplyr.html"><a href="data-wrangling-with-dplyr.html#exercise-wrangling-the-amniote-life-history-database"><i class="fa fa-check"></i><b>7.6</b> Exercise: Wrangling the Amniote Life History Database</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="combining-data-sets.html"><a href="combining-data-sets.html"><i class="fa fa-check"></i><b>8</b> Combining data sets</a>
<ul>
<li class="chapter" data-level="8.1" data-path="combining-data-sets.html"><a href="combining-data-sets.html#using-join"><i class="fa fa-check"></i><b>8.1</b> Using <code>join</code></a></li>
<li class="chapter" data-level="8.2" data-path="combining-data-sets.html"><a href="combining-data-sets.html#using-pivot_longer"><i class="fa fa-check"></i><b>8.2</b> Using <code>pivot_longer</code></a></li>
<li class="chapter" data-level="8.3" data-path="combining-data-sets.html"><a href="combining-data-sets.html#exercise-temperature-effects-on-egg-laying-dates"><i class="fa fa-check"></i><b>8.3</b> Exercise: Temperature effects on egg laying dates</a></li>
</ul></li>
<li class="part"><span><b>II Data visualisation</b></span></li>
<li class="chapter" data-level="9" data-path="visualising-data-with-ggplot2.html"><a href="visualising-data-with-ggplot2.html"><i class="fa fa-check"></i><b>9</b> Visualising data with <code>ggplot2</code></a>
<ul>
<li class="chapter" data-level="9.1" data-path="visualising-data-with-ggplot2.html"><a href="visualising-data-with-ggplot2.html#histograms"><i class="fa fa-check"></i><b>9.1</b> Histograms</a></li>
<li class="chapter" data-level="9.2" data-path="visualising-data-with-ggplot2.html"><a href="visualising-data-with-ggplot2.html#facets---splitting-data-across-panels"><i class="fa fa-check"></i><b>9.2</b> “Facets” - splitting data across panels</a></li>
<li class="chapter" data-level="9.3" data-path="visualising-data-with-ggplot2.html"><a href="visualising-data-with-ggplot2.html#box-plots"><i class="fa fa-check"></i><b>9.3</b> Box plots</a></li>
<li class="chapter" data-level="9.4" data-path="visualising-data-with-ggplot2.html"><a href="visualising-data-with-ggplot2.html#lines-and-points"><i class="fa fa-check"></i><b>9.4</b> Lines and points</a></li>
<li class="chapter" data-level="9.5" data-path="visualising-data-with-ggplot2.html"><a href="visualising-data-with-ggplot2.html#scatter-plots"><i class="fa fa-check"></i><b>9.5</b> Scatter plots</a></li>
<li class="chapter" data-level="9.6" data-path="visualising-data-with-ggplot2.html"><a href="visualising-data-with-ggplot2.html#bar-plots"><i class="fa fa-check"></i><b>9.6</b> Bar plots</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html"><i class="fa fa-check"></i><b>10</b> Distributions and summarising data</a>
<ul>
<li class="chapter" data-level="10.1" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#distributions"><i class="fa fa-check"></i><b>10.1</b> Distributions</a></li>
<li class="chapter" data-level="10.2" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#normal-distribution"><i class="fa fa-check"></i><b>10.2</b> Normal distribution</a></li>
<li class="chapter" data-level="10.3" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#comparing-normal-distributions"><i class="fa fa-check"></i><b>10.3</b> Comparing normal distributions</a></li>
<li class="chapter" data-level="10.4" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#poisson-distribution"><i class="fa fa-check"></i><b>10.4</b> Poisson distribution</a></li>
<li class="chapter" data-level="10.5" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#comparing-normal-and-poisson-distributions"><i class="fa fa-check"></i><b>10.5</b> Comparing normal and Poisson distributions</a></li>
<li class="chapter" data-level="10.6" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#the-law-of-large-numbers"><i class="fa fa-check"></i><b>10.6</b> The law of large numbers</a>
<ul>
<li class="chapter" data-level="10.6.1" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#coin-flipping"><i class="fa fa-check"></i><b>10.6.1</b> Coin flipping</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="distributions-and-summarising-data.html"><a href="distributions-and-summarising-data.html#exercise-virtual-dice"><i class="fa fa-check"></i><b>10.7</b> Exercise: Virtual dice</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html"><i class="fa fa-check"></i><b>11</b> Pimping your plots</a>
<ul>
<li class="chapter" data-level="11.1" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#a-basic-plot"><i class="fa fa-check"></i><b>11.1</b> A basic plot</a></li>
<li class="chapter" data-level="11.2" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#axis-limits"><i class="fa fa-check"></i><b>11.2</b> Axis limits</a></li>
<li class="chapter" data-level="11.3" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#transforming-the-axis-log-scale"><i class="fa fa-check"></i><b>11.3</b> Transforming the axis (log scale)</a></li>
<li class="chapter" data-level="11.4" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#changing-the-axis-tick-marks"><i class="fa fa-check"></i><b>11.4</b> Changing the axis tick marks</a></li>
<li class="chapter" data-level="11.5" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#axis-labels"><i class="fa fa-check"></i><b>11.5</b> Axis labels</a></li>
<li class="chapter" data-level="11.6" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#colours"><i class="fa fa-check"></i><b>11.6</b> Colours</a></li>
<li class="chapter" data-level="11.7" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#themes"><i class="fa fa-check"></i><b>11.7</b> Themes</a></li>
<li class="chapter" data-level="11.8" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#moving-the-legend"><i class="fa fa-check"></i><b>11.8</b> Moving the legend</a></li>
<li class="chapter" data-level="11.9" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#combining-multiple-plots"><i class="fa fa-check"></i><b>11.9</b> Combining multiple plots</a></li>
<li class="chapter" data-level="11.10" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#saving-your-plot"><i class="fa fa-check"></i><b>11.10</b> Saving your plot</a></li>
<li class="chapter" data-level="11.11" data-path="pimping-your-plots.html"><a href="pimping-your-plots.html#final-word-on-plots"><i class="fa fa-check"></i><b>11.11</b> Final word on plots</a></li>
</ul></li>
<li class="part"><span><b>III Statistics</b></span></li>
<li class="chapter" data-level="12" data-path="randomisation-tests.html"><a href="randomisation-tests.html"><i class="fa fa-check"></i><b>12</b> Randomisation Tests</a>
<ul>
<li class="chapter" data-level="12.1" data-path="randomisation-tests.html"><a href="randomisation-tests.html#randomisation-test-in-r"><i class="fa fa-check"></i><b>12.1</b> Randomisation test in R</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="randomisation-tests.html"><a href="randomisation-tests.html#calculate-the-observed-difference"><i class="fa fa-check"></i><b>12.1.1</b> Calculate the observed difference</a></li>
<li class="chapter" data-level="12.1.2" data-path="randomisation-tests.html"><a href="randomisation-tests.html#null-distribution"><i class="fa fa-check"></i><b>12.1.2</b> Null distribution</a></li>
<li class="chapter" data-level="12.1.3" data-path="randomisation-tests.html"><a href="randomisation-tests.html#testing-significance"><i class="fa fa-check"></i><b>12.1.3</b> Testing significance</a></li>
<li class="chapter" data-level="12.1.4" data-path="randomisation-tests.html"><a href="randomisation-tests.html#testing-the-hypothesis"><i class="fa fa-check"></i><b>12.1.4</b> Testing the hypothesis</a></li>
<li class="chapter" data-level="12.1.5" data-path="randomisation-tests.html"><a href="randomisation-tests.html#writing-it-up"><i class="fa fa-check"></i><b>12.1.5</b> Writing it up</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="randomisation-tests.html"><a href="randomisation-tests.html#paired-randomisation-tests"><i class="fa fa-check"></i><b>12.2</b> Paired Randomisation Tests</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="randomisation-tests.html"><a href="randomisation-tests.html#the-randomisation-test"><i class="fa fa-check"></i><b>12.2.1</b> The randomisation test</a></li>
<li class="chapter" data-level="12.2.2" data-path="randomisation-tests.html"><a href="randomisation-tests.html#null-distribution-1"><i class="fa fa-check"></i><b>12.2.2</b> Null distribution</a></li>
<li class="chapter" data-level="12.2.3" data-path="randomisation-tests.html"><a href="randomisation-tests.html#the-formal-hypothesis-test"><i class="fa fa-check"></i><b>12.2.3</b> The formal hypothesis test</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="randomisation-tests.html"><a href="randomisation-tests.html#exercise-sexual-selection-in-hercules-beetles"><i class="fa fa-check"></i><b>12.3</b> Exercise: Sexual selection in Hercules beetles</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html"><i class="fa fa-check"></i><b>13</b> t-test: Comparing two means</a>
<ul>
<li class="chapter" data-level="13.1" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#some-theory"><i class="fa fa-check"></i><b>13.1</b> Some theory</a></li>
<li class="chapter" data-level="13.2" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#one-sample-t-test"><i class="fa fa-check"></i><b>13.2</b> One sample t-test</a></li>
<li class="chapter" data-level="13.3" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#doing-it-by-hand---where-does-the-t-statistic-come-from"><i class="fa fa-check"></i><b>13.3</b> Doing it “by hand” - where does the t-statistic come from?</a></li>
<li class="chapter" data-level="13.4" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#paired-t-test"><i class="fa fa-check"></i><b>13.4</b> Paired t-test</a></li>
<li class="chapter" data-level="13.5" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#a-paired-t-test-is-a-one-sample-test."><i class="fa fa-check"></i><b>13.5</b> A paired t-test is a one-sample test.</a></li>
<li class="chapter" data-level="13.6" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#two-sample-t-test"><i class="fa fa-check"></i><b>13.6</b> Two sample t-test</a></li>
<li class="chapter" data-level="13.7" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#t-tests-are-linear-models"><i class="fa fa-check"></i><b>13.7</b> t-tests are linear models</a></li>
<li class="chapter" data-level="13.8" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#exercise-sex-differences-in-fine-motor-skills"><i class="fa fa-check"></i><b>13.8</b> Exercise: Sex differences in fine motor skills</a></li>
<li class="chapter" data-level="13.9" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#exercise-therapy-for-anorexia"><i class="fa fa-check"></i><b>13.9</b> Exercise: Therapy for anorexia</a></li>
<li class="chapter" data-level="13.10" data-path="t-test-comparing-two-means.html"><a href="t-test-comparing-two-means.html#exercise-compare-t-tests-with-randomisation-tests-optional"><i class="fa fa-check"></i><b>13.10</b> Exercise: Compare t-tests with randomisation tests (optional)</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="assumptions-in-linear-models.html"><a href="assumptions-in-linear-models.html"><i class="fa fa-check"></i><b>14</b> Assumptions in linear models</a>
<ul>
<li class="chapter" data-level="14.1" data-path="assumptions-in-linear-models.html"><a href="assumptions-in-linear-models.html#the-assumptions"><i class="fa fa-check"></i><b>14.1</b> The assumptions</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><i class="fa fa-check"></i><b>15</b> ANOVA: Linear models with a single categorical explanatory variable</a>
<ul>
<li class="chapter" data-level="15.1" data-path="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#one-way-anova"><i class="fa fa-check"></i><b>15.1</b> One-way ANOVA</a></li>
<li class="chapter" data-level="15.2" data-path="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#fitting-an-anova-in-r"><i class="fa fa-check"></i><b>15.2</b> Fitting an ANOVA in R</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#where-are-the-differences"><i class="fa fa-check"></i><b>15.2.1</b> Where are the differences?</a></li>
<li class="chapter" data-level="15.2.2" data-path="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#tukeys-honestly-significant-difference-hsd"><i class="fa fa-check"></i><b>15.2.2</b> Tukey’s Honestly Significant Difference (HSD)</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#anova-calculation-by-hand."><i class="fa fa-check"></i><b>15.3</b> ANOVA calculation “by hand”.</a></li>
<li class="chapter" data-level="15.4" data-path="anova-linear-models-with-a-single-categorical-explanatory-variable.html"><a href="anova-linear-models-with-a-single-categorical-explanatory-variable.html#exercise-apple-tree-crop-yield"><i class="fa fa-check"></i><b>15.4</b> Exercise: Apple tree crop yield</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="linear-regression-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html"><i class="fa fa-check"></i><b>16</b> Linear regression: models with a single continuous explanatory variable</a>
<ul>
<li class="chapter" data-level="16.1" data-path="linear-regression-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#some-theory-1"><i class="fa fa-check"></i><b>16.1</b> Some theory</a></li>
<li class="chapter" data-level="16.2" data-path="linear-regression-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#evaluating-a-hypothesis-with-a-linear-regression-model"><i class="fa fa-check"></i><b>16.2</b> Evaluating a hypothesis with a linear regression model</a></li>
<li class="chapter" data-level="16.3" data-path="linear-regression-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#assumptions"><i class="fa fa-check"></i><b>16.3</b> Assumptions</a></li>
<li class="chapter" data-level="16.4" data-path="linear-regression-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#worked-example-height-hand-width-relationship"><i class="fa fa-check"></i><b>16.4</b> Worked example: height-hand width relationship</a></li>
<li class="chapter" data-level="16.5" data-path="linear-regression-models-with-a-single-continuous-explanatory-variable.html"><a href="linear-regression-models-with-a-single-continuous-explanatory-variable.html#exercise-chirping-crickets"><i class="fa fa-check"></i><b>16.5</b> Exercise: Chirping crickets</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html"><a href="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html"><i class="fa fa-check"></i><b>17</b> ANCOVA: Linear models with categorical and continuous explanatory variables</a>
<ul>
<li class="chapter" data-level="17.1" data-path="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html"><a href="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html#the-height-hand-width-example."><i class="fa fa-check"></i><b>17.1</b> The height ~ hand width example.</a></li>
<li class="chapter" data-level="17.2" data-path="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html"><a href="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html#summarising-with-anova"><i class="fa fa-check"></i><b>17.2</b> Summarising with <code>anova</code></a></li>
<li class="chapter" data-level="17.3" data-path="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html"><a href="ancova-linear-models-with-categorical-and-continuous-explanatory-variables.html#the-summary-of-coefficients-summary"><i class="fa fa-check"></i><b>17.3</b> The summary of coefficients (<code>summary</code>)</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html"><i class="fa fa-check"></i><b>18</b> n-way ANOVA: Linear models with &gt;1 categorical explanatory variables</a>
<ul>
<li class="chapter" data-level="18.1" data-path="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#fitting-a-two-way-anova-model"><i class="fa fa-check"></i><b>18.1</b> Fitting a two-way ANOVA model</a></li>
<li class="chapter" data-level="18.2" data-path="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#summarising-the-model-anova"><i class="fa fa-check"></i><b>18.2</b> Summarising the model (<code>anova</code>)</a></li>
<li class="chapter" data-level="18.3" data-path="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#summarising-the-model-summary"><i class="fa fa-check"></i><b>18.3</b> Summarising the model (<code>summary</code>)</a></li>
<li class="chapter" data-level="18.4" data-path="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html"><a href="n-way-anova-linear-models-with-1-categorical-explanatory-variables.html#exercise-fish-behaviour"><i class="fa fa-check"></i><b>18.4</b> Exercise: Fish behaviour</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="evaluating-linear-models.html"><a href="evaluating-linear-models.html"><i class="fa fa-check"></i><b>19</b> Evaluating linear models</a>
<ul>
<li class="chapter" data-level="19.1" data-path="evaluating-linear-models.html"><a href="evaluating-linear-models.html#r-squared-value"><i class="fa fa-check"></i><b>19.1</b> R-squared value</a></li>
<li class="chapter" data-level="19.2" data-path="evaluating-linear-models.html"><a href="evaluating-linear-models.html#akaike-information-criterion-aic"><i class="fa fa-check"></i><b>19.2</b> Akaike Information Criterion (AIC)</a></li>
<li class="chapter" data-level="19.3" data-path="evaluating-linear-models.html"><a href="evaluating-linear-models.html#variance-partitioning"><i class="fa fa-check"></i><b>19.3</b> Variance partitioning</a></li>
<li class="chapter" data-level="19.4" data-path="evaluating-linear-models.html"><a href="evaluating-linear-models.html#conclusion"><i class="fa fa-check"></i><b>19.4</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html"><i class="fa fa-check"></i><b>20</b> Generalised linear models</a>
<ul>
<li class="chapter" data-level="20.1" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html#count-data-with-poisson-errors."><i class="fa fa-check"></i><b>20.1</b> Count data with Poisson errors.</a>
<ul>
<li class="chapter" data-level="20.1.1" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html#example-number-of-offspring-in-foxes."><i class="fa fa-check"></i><b>20.1.1</b> Example: Number of offspring in foxes.</a></li>
<li class="chapter" data-level="20.1.2" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html#example-cancer-clusters"><i class="fa fa-check"></i><b>20.1.2</b> Example: Cancer clusters</a></li>
<li class="chapter" data-level="20.1.3" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html#overdispersion-what-it-is-and-why-it-matters"><i class="fa fa-check"></i><b>20.1.3</b> Overdispersion: What It Is and Why It Matters</a></li>
</ul></li>
<li class="chapter" data-level="20.2" data-path="generalised-linear-models.html"><a href="generalised-linear-models.html#exercise-maze-runner"><i class="fa fa-check"></i><b>20.2</b> Exercise: Maze runner</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="extending-use-cases-of-glm.html"><a href="extending-use-cases-of-glm.html"><i class="fa fa-check"></i><b>21</b> Extending use cases of GLM</a>
<ul>
<li class="chapter" data-level="21.1" data-path="extending-use-cases-of-glm.html"><a href="extending-use-cases-of-glm.html#binomial-response-data"><i class="fa fa-check"></i><b>21.1</b> Binomial response data</a></li>
<li class="chapter" data-level="21.2" data-path="extending-use-cases-of-glm.html"><a href="extending-use-cases-of-glm.html#example-nfl-field-goals"><i class="fa fa-check"></i><b>21.2</b> Example: NFL field goals</a></li>
<li class="chapter" data-level="21.3" data-path="extending-use-cases-of-glm.html"><a href="extending-use-cases-of-glm.html#example-sex-ratio-in-turtles"><i class="fa fa-check"></i><b>21.3</b> Example: Sex ratio in turtles</a></li>
<li class="chapter" data-level="21.4" data-path="extending-use-cases-of-glm.html"><a href="extending-use-cases-of-glm.html#example-smoking"><i class="fa fa-check"></i><b>21.4</b> Example: Smoking</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="glm-families-and-use-cases.html"><a href="glm-families-and-use-cases.html"><i class="fa fa-check"></i><b>22</b> GLM families and use cases</a>
<ul>
<li class="chapter" data-level="22.1" data-path="glm-families-and-use-cases.html"><a href="glm-families-and-use-cases.html#summary-table-of-glm-families"><i class="fa fa-check"></i><b>22.1</b> Summary Table of GLM Families</a></li>
<li class="chapter" data-level="22.2" data-path="glm-families-and-use-cases.html"><a href="glm-families-and-use-cases.html#further-details-of-common-glm-families"><i class="fa fa-check"></i><b>22.2</b> Further details of common GLM Families</a></li>
</ul></li>
<li class="chapter" data-level="23" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html"><i class="fa fa-check"></i><b>23</b> Power analysis by simulation</a>
<ul>
<li class="chapter" data-level="23.1" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#type-i-and-ii-errors-and-statistical-power"><i class="fa fa-check"></i><b>23.1</b> Type I and II errors and statistical power</a></li>
<li class="chapter" data-level="23.2" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#what-determines-statistical-power"><i class="fa fa-check"></i><b>23.2</b> What determines statistical power?</a></li>
<li class="chapter" data-level="23.3" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#an-example-of-calculating-statistical-power."><i class="fa fa-check"></i><b>23.3</b> An example of calculating statistical power.</a>
<ul>
<li class="chapter" data-level="23.3.1" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#the-simulation"><i class="fa fa-check"></i><b>23.3.1</b> The simulation</a></li>
<li class="chapter" data-level="23.3.2" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#some-questions-for-you-to-address"><i class="fa fa-check"></i><b>23.3.2</b> Some questions for you to address:</a></li>
</ul></li>
<li class="chapter" data-level="23.4" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#summary"><i class="fa fa-check"></i><b>23.4</b> Summary</a></li>
<li class="chapter" data-level="23.5" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#extending-the-simulation-optional-advanced"><i class="fa fa-check"></i><b>23.5</b> Extending the simulation (optional, advanced)</a></li>
<li class="chapter" data-level="23.6" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#exercise-1-snails-on-the-move"><i class="fa fa-check"></i><b>23.6</b> Exercise 1: Snails on the move</a></li>
<li class="chapter" data-level="23.7" data-path="power-analysis-by-simulation.html"><a href="power-analysis-by-simulation.html#exercise-2-mouse-lemur-strength"><i class="fa fa-check"></i><b>23.7</b> Exercise 2: Mouse lemur strength</a></li>
</ul></li>
<li class="part"><span><b>IV Appendix</b></span></li>
<li class="chapter" data-level="24" data-path="examples-of-statistics-reporting.html"><a href="examples-of-statistics-reporting.html"><i class="fa fa-check"></i><b>24</b> Examples of statistics reporting</a>
<ul>
<li class="chapter" data-level="24.1" data-path="examples-of-statistics-reporting.html"><a href="examples-of-statistics-reporting.html#t-test"><i class="fa fa-check"></i><b>24.1</b> t-test</a></li>
<li class="chapter" data-level="24.2" data-path="examples-of-statistics-reporting.html"><a href="examples-of-statistics-reporting.html#simple-linear-regression-model"><i class="fa fa-check"></i><b>24.2</b> Simple linear regression model</a></li>
<li class="chapter" data-level="24.3" data-path="examples-of-statistics-reporting.html"><a href="examples-of-statistics-reporting.html#a-generalised-linear-model-glm"><i class="fa fa-check"></i><b>24.3</b> A Generalised linear model (GLM)</a></li>
</ul></li>
<li class="chapter" data-level="25" data-path="an-example-of-a-past-written-assignment-2020.html"><a href="an-example-of-a-past-written-assignment-2020.html"><i class="fa fa-check"></i><b>25</b> An example of a past Written Assignment (2020)</a></li>
<li class="chapter" data-level="26" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html"><i class="fa fa-check"></i><b>26</b> Leveraging ChatGPT for R Programming Assistance</a>
<ul>
<li class="chapter" data-level="26.1" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#introduction"><i class="fa fa-check"></i><b>26.1</b> Introduction</a></li>
<li class="chapter" data-level="26.2" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#overview"><i class="fa fa-check"></i><b>26.2</b> Overview</a></li>
<li class="chapter" data-level="26.3" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#what-is-a-large-language-model-llm-and-how-do-they-work"><i class="fa fa-check"></i><b>26.3</b> What is a Large Language Model (LLM) and how do they work?</a></li>
<li class="chapter" data-level="26.4" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#limitations"><i class="fa fa-check"></i><b>26.4</b> Limitations</a>
<ul>
<li class="chapter" data-level="26.4.1" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#limited-knowledge"><i class="fa fa-check"></i><b>26.4.1</b> Limited knowledge</a></li>
<li class="chapter" data-level="26.4.2" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#hallucination"><i class="fa fa-check"></i><b>26.4.2</b> Hallucination</a></li>
<li class="chapter" data-level="26.4.3" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#numerical-ability"><i class="fa fa-check"></i><b>26.4.3</b> Numerical ability</a></li>
</ul></li>
<li class="chapter" data-level="26.5" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#ethics-of-using-llms-in-education"><i class="fa fa-check"></i><b>26.5</b> Ethics of using LLMs in education</a></li>
<li class="chapter" data-level="26.6" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#use-cases-in-r"><i class="fa fa-check"></i><b>26.6</b> Use cases in R</a>
<ul>
<li class="chapter" data-level="26.6.1" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#finding-errors."><i class="fa fa-check"></i><b>26.6.1</b> Finding errors.</a></li>
<li class="chapter" data-level="26.6.2" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#explaining-code"><i class="fa fa-check"></i><b>26.6.2</b> Explaining code</a></li>
<li class="chapter" data-level="26.6.3" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#interpreting-output"><i class="fa fa-check"></i><b>26.6.3</b> Interpreting output</a></li>
<li class="chapter" data-level="26.6.4" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#translating-code-e.g.-from-pythonmatlab-to-r"><i class="fa fa-check"></i><b>26.6.4</b> Translating code (e.g. from Python/Matlab to R)</a></li>
<li class="chapter" data-level="26.6.5" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#solving-modelling-problems"><i class="fa fa-check"></i><b>26.6.5</b> Solving modelling problems</a></li>
<li class="chapter" data-level="26.6.6" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#helping-with-documentationcomments"><i class="fa fa-check"></i><b>26.6.6</b> Helping with documentation/comments</a></li>
<li class="chapter" data-level="26.6.7" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#finding-alternativebetter-ways"><i class="fa fa-check"></i><b>26.6.7</b> Finding alternative/better ways</a></li>
</ul></li>
<li class="chapter" data-level="26.7" data-path="leveraging-chatgpt-for-r-programming-assistance.html"><a href="leveraging-chatgpt-for-r-programming-assistance.html#some-tips"><i class="fa fa-check"></i><b>26.7</b> Some tips</a></li>
</ul></li>
<li class="part"><span><b>V Solutions</b></span></li>
<li class="chapter" data-level="27" data-path="exercise-solutions.html"><a href="exercise-solutions.html"><i class="fa fa-check"></i><b>27</b> Exercise Solutions</a>
<ul>
<li class="chapter" data-level="27.1" data-path="exercise-solutions.html"><a href="exercise-solutions.html#californian-bird-diversity"><i class="fa fa-check"></i><b>27.1</b> Californian bird diversity</a></li>
<li class="chapter" data-level="27.2" data-path="exercise-solutions.html"><a href="exercise-solutions.html#wrangling-the-amniote-life-history-database"><i class="fa fa-check"></i><b>27.2</b> Wrangling the Amniote Life History Database</a></li>
<li class="chapter" data-level="27.3" data-path="exercise-solutions.html"><a href="exercise-solutions.html#temperature-effects-on-egg-laying-dates"><i class="fa fa-check"></i><b>27.3</b> Temperature effects on egg laying dates</a></li>
<li class="chapter" data-level="27.4" data-path="exercise-solutions.html"><a href="exercise-solutions.html#virtual-dice"><i class="fa fa-check"></i><b>27.4</b> Virtual dice</a></li>
<li class="chapter" data-level="27.5" data-path="exercise-solutions.html"><a href="exercise-solutions.html#sexual-selection-in-hercules-beetles"><i class="fa fa-check"></i><b>27.5</b> Sexual selection in Hercules beetles</a></li>
<li class="chapter" data-level="27.6" data-path="exercise-solutions.html"><a href="exercise-solutions.html#sex-differences-in-fine-motor-skills"><i class="fa fa-check"></i><b>27.6</b> Sex differences in fine motor skills</a></li>
<li class="chapter" data-level="27.7" data-path="exercise-solutions.html"><a href="exercise-solutions.html#therapy-for-anorexia"><i class="fa fa-check"></i><b>27.7</b> Therapy for anorexia</a></li>
<li class="chapter" data-level="27.8" data-path="exercise-solutions.html"><a href="exercise-solutions.html#compare-t-tests-with-randomisation-tests"><i class="fa fa-check"></i><b>27.8</b> Compare t-tests with randomisation tests</a></li>
<li class="chapter" data-level="27.9" data-path="exercise-solutions.html"><a href="exercise-solutions.html#apple-tree-crop-yield"><i class="fa fa-check"></i><b>27.9</b> Apple tree crop yield</a></li>
<li class="chapter" data-level="27.10" data-path="exercise-solutions.html"><a href="exercise-solutions.html#chirping-crickets"><i class="fa fa-check"></i><b>27.10</b> Chirping crickets</a></li>
<li class="chapter" data-level="27.11" data-path="exercise-solutions.html"><a href="exercise-solutions.html#fish-behaviour"><i class="fa fa-check"></i><b>27.11</b> Fish behaviour</a></li>
<li class="chapter" data-level="27.12" data-path="exercise-solutions.html"><a href="exercise-solutions.html#maze-runner"><i class="fa fa-check"></i><b>27.12</b> Maze runner</a></li>
<li class="chapter" data-level="27.13" data-path="exercise-solutions.html"><a href="exercise-solutions.html#snails-on-the-move"><i class="fa fa-check"></i><b>27.13</b> Snails on the move</a></li>
<li class="chapter" data-level="27.14" data-path="exercise-solutions.html"><a href="exercise-solutions.html#mouse-lemur-strength"><i class="fa fa-check"></i><b>27.14</b> Mouse lemur strength</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">BB852 - Data handling, visualisation and statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="t-test-comparing-two-means" class="section level1 hasAnchor" number="13">
<h1><span class="header-section-number">Chapter 13</span> t-test: Comparing two means<a href="t-test-comparing-two-means.html#t-test-comparing-two-means" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>We will cover the following:</p>
<ul>
<li>One-sample t-test</li>
<li>Paired t-test</li>
<li>Two-sample t-test (“Welch’s t-test”)</li>
</ul>
<div id="some-theory" class="section level2 hasAnchor" number="13.1">
<h2><span class="header-section-number">13.1</span> Some theory<a href="t-test-comparing-two-means.html#some-theory" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this theory section I focus on the one-sample t-test, but the concepts apply to the other types of t-test.</p>
<p>The one-sample t-test is used to compare the mean of a sample to some fixed value. For example, we might want to compare pollution levels (e.g. in mg/m<sup>3</sup>) in a sample to some acceptable threshold value to help us decide whether we need to take action to prevent or clean up pollution.</p>
<p>One of the assumptions of t-tests (and many other tests/models) is that the distribution of <strong>residual</strong> values in the <strong>sample</strong> of data can be described by a normal distribution. For a t-test, in practice, this means that the distribution of measured values <strong>for each group</strong> should be normal.</p>
<p>If this assumption is true, you can use these data to estimate the parameters of this sample’s normal distribution: the mean and standard error of the mean.</p>
<p>We will talk more about model assumptions later.</p>
<p>The mean gives an estimate of location, and the standard error of the mean (which is calculated as <span class="math inline">\(s/ \sqrt{n}\)</span>, where <em>s</em> = standard deviation and <em>n</em> = sample size) gives an estimate of precision of this estimate (i.e. how certain is it that the mean value is really where you think it is?)</p>
<p>The t-test then works by comparing your estimated distribution with some fixed value. Sometimes you are asking “is my mean <em>different</em> from the value?”, other times you are asking “is my mean less than/greater than the value?”. This depends on the hypothesis. The default that R-uses is that it tests whether the mean of your distribution is <em>different</em> to the fixed value, but in many cases you should really be framing a <strong>directional</strong> hypothesis.</p>
<p>It is helpful to visualise this, so some examples of the pollution threshold test are shown in the figure below (Figure <a href="t-test-comparing-two-means.html#fig:3-02-t-tests-1">13.1</a> ). The curves illustrate the estimated normal distributions that describe our estimate of the mean pollution level from some data (e.g. each curve might represent samples from different locations). We are interested in whether the mean values (the vertical dashed lines) are significantly <strong>greater</strong> than the threshold of 100mg/m<sup>2</sup> (solid vertical black line) (this gives us a directional hypothesis).</p>
<p>Formally we do this by establishing two hypotheses a <strong>null hypothesis</strong> and an <strong>alternative hypothesis</strong>. In this case, the null hypothesis is that the mean of the sample measurements is <strong>not</strong> significantly different from the threshold value we define. The alternative hypothesis is that the sample mean is significantly <strong>greater</strong> than this threshold value.</p>
<p>The degree of confidence that we can have that the mean pollution values are different from the threshold value depend on (A) the position of the distribution relative to the threshold value and (B) on the spread of the distribution (the standard deviation/error).</p>
<p>Based on Figure <a href="t-test-comparing-two-means.html#fig:3-02-t-tests-1">13.1</a>, which of these four different samples shows a mean value <strong>significantly</strong> greater than 100? (you should be looking at the amount of the normal distribution curve that is overlapping the threshold value.)</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:3-02-t-tests-1"></span>
<img src="BB852_files/figure-html/3-02-t-tests-1-1.png" alt="Visualisation of a t-test." width="576" />
<p class="caption">
Figure 13.1: Visualisation of a t-test.
</p>
</div>
<p>This should look familiar – it is the same concept as we used in the class on randomisation tests. If you find it confusing, please go back and review the randomisation test materials!</p>
<p>Another useful way to think about t-tests is that it is a way of distinguishing between <strong>signal</strong> and <strong>noise</strong>: the signal is the mean value of the thing you are measuring, and the noise is the uncertainty in that estimate. This uncertainty could be due to measurement error and/or natural variation. In fact, the <em>t-value</em> that the t-test relies on is a ratio between the signal (difference between mean (<span class="math inline">\(\bar{x}\)</span>) and threshold (<span class="math inline">\(\mu_{0}\)</span>)) and noise (variability, standard error of the mean (<span class="math inline">\(s/ \sqrt{n}\)</span>)): <span class="math display">\[t = \frac{\bar{x}-\mu_{0}} {s/ \sqrt{n}}\]</span></p>
<p>The larger the signal is compared to the noise, the higher the t-value will be. e.g. a t-value of 2 means that the signal was 2 times the variability in the data. A t-value of zero, or close to zero, means that the signal is “drowned out” by the noise. Therefore, high t-values give you more confidence that the difference is true.</p>
<p>To know if the t-value means that the difference is significant, the t-value is compared to a known theoretical distribution (the t-distribution). The area under the curve of the distribution is 1, but its shape depends on the degrees of freedom (i.e. sample size - 1). The plot below (Figure <a href="t-test-comparing-two-means.html#fig:3-02-t-tests-2">13.2</a>) shows three t-distributions of different degrees of freedom (d.f.).</p>
<p>What R is doing when it figures out the p-value is calculating the area under the curve <em>beyond</em> the positive/negative values of the t-statistic. If t is small, then this value is large (p-value). If t is large then the area (and the p-value) is small. In the olden-days (&gt;15 years ago) you would have looked these values up in printed tables, but now R does that for us.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:3-02-t-tests-2"></span>
<img src="BB852_files/figure-html/3-02-t-tests-2-1.png" alt="The t-distribution" width="288" />
<p class="caption">
Figure 13.2: The t-distribution
</p>
</div>
</div>
<div id="one-sample-t-test" class="section level2 hasAnchor" number="13.2">
<h2><span class="header-section-number">13.2</span> One sample t-test<a href="t-test-comparing-two-means.html#one-sample-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Enough theory. Here’s how you would apply such a test in R.</p>
<div class="do-something">
<p>
Remember to load the <code>dplyr</code>, <code>magrittr</code> and
<code>ggplot</code> packages, and to set your working directory
correctly.
</p>
</div>
<p>Firstly, lets load some data. Because this is a very small example, you can simply cut and paste the data in rather than loading it from a CSV file.</p>
<div class="sourceCode" id="cb326"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb326-1"><a href="t-test-comparing-two-means.html#cb326-1" tabindex="-1"></a>pollution <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">mgm3 =</span> <span class="fu">c</span>(</span>
<span id="cb326-2"><a href="t-test-comparing-two-means.html#cb326-2" tabindex="-1"></a>  <span class="dv">105</span>, <span class="dv">196</span>, <span class="dv">226</span>, <span class="dv">81</span>, <span class="dv">156</span>, <span class="dv">201</span>, <span class="dv">142</span>, <span class="dv">149</span>, <span class="dv">191</span>, <span class="dv">192</span>,</span>
<span id="cb326-3"><a href="t-test-comparing-two-means.html#cb326-3" tabindex="-1"></a>  <span class="dv">178</span>, <span class="dv">185</span>, <span class="dv">231</span>, <span class="dv">76</span>, <span class="dv">207</span>, <span class="dv">138</span>, <span class="dv">146</span>, <span class="dv">175</span>, <span class="dv">114</span>, <span class="dv">155</span></span>
<span id="cb326-4"><a href="t-test-comparing-two-means.html#cb326-4" tabindex="-1"></a>))</span></code></pre></div>
<p>First I plot the data (Figure <a href="t-test-comparing-two-means.html#fig:3-02-t-tests-5">13.3</a>). One reason for doing this is to check that the data look approximately normally distributed. These data are slightly left-skewed but they are close enough.</p>
<div class="sourceCode" id="cb327"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb327-1"><a href="t-test-comparing-two-means.html#cb327-1" tabindex="-1"></a><span class="fu">ggplot</span>(pollution, <span class="fu">aes</span>(<span class="at">x =</span> mgm3)) <span class="sc">+</span></span>
<span id="cb327-2"><a href="t-test-comparing-two-means.html#cb327-2" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">8</span>) <span class="sc">+</span></span>
<span id="cb327-3"><a href="t-test-comparing-two-means.html#cb327-3" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">100</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:3-02-t-tests-5"></span>
<img src="BB852_files/figure-html/3-02-t-tests-5-1.png" alt="Histogram of the pollution data." width="384" />
<p class="caption">
Figure 13.3: Histogram of the pollution data.
</p>
</div>
<p>Now we can run a t-test in R like this. The command is simple - the first two arguments are the data (<code>x</code>) and the the fixed value you are comparing the data to. The final argument defines the alternative hypothesis. This can take values of “<code>two.sided</code>”, “<code>less</code>” or “<code>greater</code>” (the default is <code>two.sided</code>). In this example, the alternative hypothesis is that the mean of our sample is greater than the threshold of 100.</p>
<div class="sourceCode" id="cb328"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb328-1"><a href="t-test-comparing-two-means.html#cb328-1" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> pollution<span class="sc">$</span>mgm3, <span class="at">mu =</span> <span class="dv">100</span>, <span class="at">alternative =</span> <span class="st">&quot;greater&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  pollution$mgm3
## t = 6.2824, df = 19, p-value = 2.478e-06
## alternative hypothesis: true mean is greater than 100
## 95 percent confidence interval:
##  145.0803      Inf
## sample estimates:
## mean of x 
##     162.2</code></pre>
<p>The output of the model tells us (1) what type of t-test is being fitted (“<code>One Sample t-test</code>”). Then it gives some values for the t-statistic, the degrees of freedom and the p-value. The model output also tells us that the alternative hypothesis “<strong>true mean is greater than 100</strong>”. Because the p-value is very small (p&lt;0.05) we can reject the null hypothesis and accept the alternative hypothesis. Finally, the output gives you the confidence interval (the area where we strongly believe the true mean to lie) and the estimate of the mean.</p>
<p>We could report these results like this: “<em>the mean value of the sample was 162.2 mg/m<sup>3</sup>, which is significantly greater than the acceptable threshold of 100 mg/m<sup>3</sup> (t-test: t = 6.2824, df = 19, p-value = 2.478e-06)</em>.</p>
</div>
<div id="doing-it-by-hand---where-does-the-t-statistic-come-from" class="section level2 hasAnchor" number="13.3">
<h2><span class="header-section-number">13.3</span> Doing it “by hand” - where does the t-statistic come from?<a href="t-test-comparing-two-means.html#doing-it-by-hand---where-does-the-t-statistic-come-from" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>At this point, to ensure that you understand where the t-statistic comes from we will calculate the t-statistic using the equation from above. The purpose of this is to illustrate that this is not brain surgery - it all hinges on a straightforward comparison between signal (the difference between mean and threshold in this case) and noise (the variation, or standard error of the mean).</p>
<p>To do this we first need to know the mean value and the threshold (the signal: <span class="math inline">\(\bar{x} - \mu_{0}\)</span>). We can then divide that by the standard error of the mean (the noise: <span class="math inline">\(s/ \sqrt{n}\)</span>)</p>
<p>Here goes… I first create a vector (<code>x</code>) of the values to save typing. Then I show how to calculate <code>mean</code> and standard error, before dividing the “signal” by the “noise”.</p>
<div class="sourceCode" id="cb330"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb330-1"><a href="t-test-comparing-two-means.html#cb330-1" tabindex="-1"></a><span class="co"># First create a vector of the values</span></span>
<span id="cb330-2"><a href="t-test-comparing-two-means.html#cb330-2" tabindex="-1"></a>x <span class="ot">&lt;-</span> pollution<span class="sc">$</span>mgm3</span>
<span id="cb330-3"><a href="t-test-comparing-two-means.html#cb330-3" tabindex="-1"></a></span>
<span id="cb330-4"><a href="t-test-comparing-two-means.html#cb330-4" tabindex="-1"></a><span class="co"># mean</span></span>
<span id="cb330-5"><a href="t-test-comparing-two-means.html#cb330-5" tabindex="-1"></a><span class="fu">mean</span>(x)</span></code></pre></div>
<pre><code>## [1] 162.2</code></pre>
<div class="sourceCode" id="cb332"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb332-1"><a href="t-test-comparing-two-means.html#cb332-1" tabindex="-1"></a><span class="co"># standard error of the mean</span></span>
<span id="cb332-2"><a href="t-test-comparing-two-means.html#cb332-2" tabindex="-1"></a><span class="fu">sd</span>(x) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">length</span>(x))</span></code></pre></div>
<pre><code>## [1] 9.900718</code></pre>
<div class="sourceCode" id="cb334"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb334-1"><a href="t-test-comparing-two-means.html#cb334-1" tabindex="-1"></a><span class="co"># Putting it all together</span></span>
<span id="cb334-2"><a href="t-test-comparing-two-means.html#cb334-2" tabindex="-1"></a>(<span class="fu">mean</span>(x) <span class="sc">-</span> <span class="dv">100</span>) <span class="sc">/</span> (<span class="fu">sd</span>(x) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">length</span>(x)))</span></code></pre></div>
<pre><code>## [1] 6.282373</code></pre>
<p>This matches exactly with the t-statistic above!</p>
<p>One can obtain a p-value from a given t-statistic and degrees of freedom like this for a t-test like the one fitted above (the d.f. is the sample size minus one for a one-sample t-test):</p>
<div class="sourceCode" id="cb336"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb336-1"><a href="t-test-comparing-two-means.html#cb336-1" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pt</span>(<span class="fl">6.282373</span>, <span class="dv">19</span>)</span></code></pre></div>
<pre><code>## [1] 2.477945e-06</code></pre>
<p>Again, this matches the value from the <code>t.test</code> function above.</p>
</div>
<div id="paired-t-test" class="section level2 hasAnchor" number="13.4">
<h2><span class="header-section-number">13.4</span> Paired t-test<a href="t-test-comparing-two-means.html#paired-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>It’s actually quite hard to find examples of one-sample t-tests in biology. In most cases, the one-sample t-tests are really paired t-tests, which are a special case of the one sample test where rather than using the actual values measured, we use the difference between them instead (Figure <a href="t-test-comparing-two-means.html#fig:3-02-t-tests-9">13.4</a>).</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:3-02-t-tests-9"></span>
<img src="BB852_files/figure-html/3-02-t-tests-9-1.png" alt="Visualising a paired t-test." width="288" />
<p class="caption">
Figure 13.4: Visualising a paired t-test.
</p>
</div>
<p>Here’s a simple example. Anthropologists studied tool use in women from the indigenous Machinguenga of Peru<a href="#fn10" class="footnote-ref" id="fnref10"><sup>10</sup></a>. They estimated the amount of cassava obtained in kg/hour using either a wooden tool (a broken bow) or a metal machete. The study focused on 5 women who were randomly assigned to groups to use the wooden tool then the machete (or vice versa).</p>
<p>The anthropologists hypothesised that using different tools led to different harvesting efficiency. The null hypothesis is that there is no difference between the two groups and that a woman was equally efficient at foraging using either tool. The alternative hypothesis was that there is a difference between the two tools. (NOTE - this could also be formulated as a directional hypothesis e.g. with the expectation that machete is more efficient than the bow.)</p>
<p>First let’s import and look at the data. Make sure you understand it. A plot will be fairly useless to tell if the data are normally distributed, so we will simply have to assume that they are. In fact, t-tests are famously robust to non-normality.</p>
<div class="sourceCode" id="cb338"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb338-1"><a href="t-test-comparing-two-means.html#cb338-1" tabindex="-1"></a>toolUse <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;CourseData/toolUse.csv&quot;</span>)</span>
<span id="cb338-2"><a href="t-test-comparing-two-means.html#cb338-2" tabindex="-1"></a>toolUse</span></code></pre></div>
<pre><code>##    subjectID    tool amount
## 1          1 machete    119
## 2          1     bow     39
## 3          2 machete    216
## 4          2     bow    114
## 5          3 machete    240
## 6          3     bow    150
## 7          4 machete    129
## 8          4     bow     51
## 9          5 machete    137
## 10         5     bow     60</code></pre>
<p>We should now plot our data (Figure <a href="t-test-comparing-two-means.html#fig:3-02-t-tests-11">13.5</a>). A nice way of doing this for paired data is to plot points with lines joining the pairs. This way, the slope of the lines is a striking visual indication of the effect.</p>
<div class="sourceCode" id="cb340"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb340-1"><a href="t-test-comparing-two-means.html#cb340-1" tabindex="-1"></a><span class="fu">ggplot</span>(toolUse, <span class="fu">aes</span>(<span class="at">x =</span> tool, <span class="at">y =</span> amount, <span class="at">group =</span> subjectID)) <span class="sc">+</span></span>
<span id="cb340-2"><a href="t-test-comparing-two-means.html#cb340-2" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb340-3"><a href="t-test-comparing-two-means.html#cb340-3" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb340-4"><a href="t-test-comparing-two-means.html#cb340-4" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Tool used&quot;</span>) <span class="sc">+</span></span>
<span id="cb340-5"><a href="t-test-comparing-two-means.html#cb340-5" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Casava harvested (kg/hr)&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:3-02-t-tests-11"></span>
<img src="BB852_files/figure-html/3-02-t-tests-11-1.png" alt="An interaction plot for the tool use data" width="432" />
<p class="caption">
Figure 13.5: An interaction plot for the tool use data
</p>
</div>
<p>We can also look at the mean values and standard deviations:</p>
<div class="sourceCode" id="cb341"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb341-1"><a href="t-test-comparing-two-means.html#cb341-1" tabindex="-1"></a>toolUse <span class="sc">%&gt;%</span></span>
<span id="cb341-2"><a href="t-test-comparing-two-means.html#cb341-2" tabindex="-1"></a>  <span class="fu">group_by</span>(tool) <span class="sc">%&gt;%</span></span>
<span id="cb341-3"><a href="t-test-comparing-two-means.html#cb341-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">meanAmount =</span> <span class="fu">mean</span>(amount), <span class="at">sdAmount =</span> <span class="fu">sd</span>(amount))</span></code></pre></div>
<pre><code>## # A tibble: 2 × 3
##   tool    meanAmount sdAmount
##   &lt;chr&gt;        &lt;dbl&gt;    &lt;dbl&gt;
## 1 bow           82.8     47.3
## 2 machete      168.      55.6</code></pre>
<p>Now lets do a paired t-test to compare the means using the two tools. The best way to do this is to provide the two samples separately in the <code>t.test</code> command. To do this you will need to create two vectors containing the data from the two groups like this, using the <code>dplyr</code> command <code>pull</code> to extract the variable along with <code>filter</code> to subset the data.</p>
<p><strong>IMPORTANT:</strong> it is very important that the pairs are arranged in the data frame so that the pairs match up when you filter the data to each group. It is therefore advisable to use <code>arrange</code> to sort the data by first the pairing variable (in this case, <code>subjectID</code>), and then the explanatory variable (the variable that defines the group - in this case, <code>tool</code>.</p>
<div class="sourceCode" id="cb343"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb343-1"><a href="t-test-comparing-two-means.html#cb343-1" tabindex="-1"></a>toolUse <span class="ot">&lt;-</span> toolUse <span class="sc">%&gt;%</span></span>
<span id="cb343-2"><a href="t-test-comparing-two-means.html#cb343-2" tabindex="-1"></a>  <span class="fu">arrange</span>(subjectID, tool)</span>
<span id="cb343-3"><a href="t-test-comparing-two-means.html#cb343-3" tabindex="-1"></a></span>
<span id="cb343-4"><a href="t-test-comparing-two-means.html#cb343-4" tabindex="-1"></a>A <span class="ot">&lt;-</span> toolUse <span class="sc">%&gt;%</span></span>
<span id="cb343-5"><a href="t-test-comparing-two-means.html#cb343-5" tabindex="-1"></a>  <span class="fu">filter</span>(tool <span class="sc">==</span> <span class="st">&quot;machete&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb343-6"><a href="t-test-comparing-two-means.html#cb343-6" tabindex="-1"></a>  <span class="fu">pull</span>(amount)</span>
<span id="cb343-7"><a href="t-test-comparing-two-means.html#cb343-7" tabindex="-1"></a></span>
<span id="cb343-8"><a href="t-test-comparing-two-means.html#cb343-8" tabindex="-1"></a>B <span class="ot">&lt;-</span> toolUse <span class="sc">%&gt;%</span></span>
<span id="cb343-9"><a href="t-test-comparing-two-means.html#cb343-9" tabindex="-1"></a>  <span class="fu">filter</span>(tool <span class="sc">==</span> <span class="st">&quot;bow&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb343-10"><a href="t-test-comparing-two-means.html#cb343-10" tabindex="-1"></a>  <span class="fu">pull</span>(amount)</span>
<span id="cb343-11"><a href="t-test-comparing-two-means.html#cb343-11" tabindex="-1"></a></span>
<span id="cb343-12"><a href="t-test-comparing-two-means.html#cb343-12" tabindex="-1"></a><span class="fu">t.test</span>(A, B, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  A and B
## t = 17.98, df = 4, p-value = 5.625e-05
## alternative hypothesis: true mean difference is not equal to 0
## 95 percent confidence interval:
##  72.21262 98.58738
## sample estimates:
## mean difference 
##            85.4</code></pre>
<p>You would report these results something like this: <em>“Women harvested cassava more efficiently with a machete (168.2 kg/hr) than with a wooden tool (82.8kg/hr). The difference of 85.4 kg/hr (95% CI 72.2-98.6 kg) was statistically significant (paired t-test: t = 17.98, df = 4, p-value = 5.625e-05).”</em></p>
<p>NOTE: you could add the argument <code>alternative = "less"</code> or <code>greater</code> to these t-tests to turn them into directional one-tailed hypotheses. However, you should also be aware that the p-value for a one-tailed t-test is always half that of the two-tailed test. Therefore, you could also simply half the p-value when you report it rather than adding the “alternative” argument.</p>
</div>
<div id="a-paired-t-test-is-a-one-sample-test." class="section level2 hasAnchor" number="13.5">
<h2><span class="header-section-number">13.5</span> A paired t-test is a one-sample test.<a href="t-test-comparing-two-means.html#a-paired-t-test-is-a-one-sample-test." class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A paired t-test is the same as a one-sample t-test really. Here’s proof.</p>
<p>First we need to calculate the difference between the two measures</p>
<div class="sourceCode" id="cb345"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb345-1"><a href="t-test-comparing-two-means.html#cb345-1" tabindex="-1"></a>difference <span class="ot">&lt;-</span> A <span class="sc">-</span> B</span></code></pre></div>
<p>Then we can fit the one-sample t-test from above, with the <code>mu</code> set as 0 (because the null hypothesis is that there is no difference between the groups). Compare this result with the paired t-test above.</p>
<div class="sourceCode" id="cb346"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb346-1"><a href="t-test-comparing-two-means.html#cb346-1" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> difference, <span class="at">mu =</span> <span class="dv">0</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  difference
## t = 17.98, df = 4, p-value = 5.625e-05
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  72.21262 98.58738
## sample estimates:
## mean of x 
##      85.4</code></pre>
</div>
<div id="two-sample-t-test" class="section level2 hasAnchor" number="13.6">
<h2><span class="header-section-number">13.6</span> Two sample t-test<a href="t-test-comparing-two-means.html#two-sample-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The two sample t-test is used for comparing the means of two samples [no shit!? :)]</p>
<p>You can visualise this by picturing your two distributions (Figure <a href="t-test-comparing-two-means.html#fig:3-02-t-tests-17">13.6</a>) and thinking about their overlap. If they overlap a lot the difference between means will not be significant. If they don’t overlap very much then the difference between means <em>will</em> be significant.</p>
<p>The underlying mathematical machinery for the two-sample t-test is similar to the one-sample and paired t-tests.
Again, the important value is the t-statistic, which can be thought of as a measure of signal:noise ratio (<em>see above</em>). It is harder to detect a signal (the true difference between means) if there is a lot of noise (the variability, or spread of the distributions), or if the signal is small (the difference between means is small).</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:3-02-t-tests-17"></span>
<img src="BB852_files/figure-html/3-02-t-tests-17-1.png" alt="A two-sample t-test." width="576" />
<p class="caption">
Figure 13.6: A two-sample t-test.
</p>
</div>
<p>The mathematics involved with calculating the t-statistic is very similar to the one-sample t-test, except the numerator in the fraction is the difference between two means rather than between a mean and a fixed value.</p>
<p><span class="math display">\[t = \frac{\bar{x_1}-\bar{x_2}} {s/ \sqrt{n}}\]</span>
So far so good… let’s push on and use R to do some statistics.</p>
<p>In this example, we can revisit the class data and ask the question, <em>Is the reaction time of males different than that of females?</em> The null hypothesis for this question is that there is no difference in mean reaction times between the two groups. The alternative hypothesis is that there <strong>is</strong> a difference in the mean reaction time between the two groups.</p>
<p>Import the data in the usual way, and subset it to the right year (in the example below I am using 2019 data).</p>
<div class="sourceCode" id="cb348"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb348-1"><a href="t-test-comparing-two-means.html#cb348-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;CourseData/classData.csv&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb348-2"><a href="t-test-comparing-two-means.html#cb348-2" tabindex="-1"></a>  <span class="fu">filter</span>(Year <span class="sc">==</span> <span class="dv">2019</span>) <span class="sc">%&gt;%</span></span>
<span id="cb348-3"><a href="t-test-comparing-two-means.html#cb348-3" tabindex="-1"></a>  <span class="fu">filter</span>(Gender <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;Male&quot;</span>, <span class="st">&quot;Female&quot;</span>))</span></code></pre></div>
<p>Then look at the data. Here I do this using a box plot with jittered points (a nice way of plotting data with small sample sizes) (Figure <a href="t-test-comparing-two-means.html#fig:3-02-t-tests-19">13.7</a>). From this figure, it looks like males have a faster reaction time than females, but there is a lot of variation. We need to apply the t-test in a similar way to above.</p>
<div class="sourceCode" id="cb349"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb349-1"><a href="t-test-comparing-two-means.html#cb349-1" tabindex="-1"></a><span class="fu">ggplot</span>(x, <span class="fu">aes</span>(<span class="at">x =</span> Gender, <span class="at">y =</span> Reaction)) <span class="sc">+</span></span>
<span id="cb349-2"><a href="t-test-comparing-two-means.html#cb349-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb349-3"><a href="t-test-comparing-two-means.html#cb349-3" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">col =</span> <span class="st">&quot;grey60&quot;</span>, <span class="at">width =</span> <span class="fl">0.2</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:3-02-t-tests-19"></span>
<img src="BB852_files/figure-html/3-02-t-tests-19-1.png" alt="Reaction time of both sexes" width="384" />
<p class="caption">
Figure 13.7: Reaction time of both sexes
</p>
</div>
<div class="sourceCode" id="cb350"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb350-1"><a href="t-test-comparing-two-means.html#cb350-1" tabindex="-1"></a><span class="fu">t.test</span>(Reaction <span class="sc">~</span> Gender, <span class="at">data =</span> x, <span class="at">var.equal =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  Reaction by Gender
## t = 1.9655, df = 30.528, p-value = 0.05851
## alternative hypothesis: true difference in means between group Female and group Male is not equal to 0
## 95 percent confidence interval:
##  -0.001716093  0.091311649
## sample estimates:
## mean in group Female   mean in group Male 
##            0.3483778            0.3035800</code></pre>
<p>This output first tells us that we are using something called a “Welch Two Sample t-test”. This is a form of the two-sample t-test that relaxes the assumption that the variance in the two groups is the same. This is a good thing. Although it <em>is</em> possible to fit a t-test with equal variances, I recommend that you stick with the default Welch’s test and <strong>not</strong> make this limiting assumption.</p>
<p>Then we are told the t-statistic (1.965), the degrees of freedom (30.528) and the p-value (0.059). We must therefore accept the null hypothesis: there is no significant difference between the two groups. Males are <em>not</em> faster than females. We could write report this something like this:</p>
<p>“<em>Although females had a slightly slower reaction time than males (0.348 seconds compared to 0.304 seconds), this difference was not statistically significant (Welch’s t-test: t= 1.965, d.f.= 30.528), p=0.059).</em>”</p>
<p>Note: With a t-test that <em>did</em> assume equal variances in the two groups, the d.f. is calculated as the sample size - 2 (the number of groups). You can do this by adding the argument “<code>var.equal = TRUE</code>” to the t-test command. With the Welch test, the appropriate degrees of freedom are estimated by looking at the sample sizes and variances in the two groups. The details of this are beyond the scope of this course.</p>
</div>
<div id="t-tests-are-linear-models" class="section level2 hasAnchor" number="13.7">
<h2><span class="header-section-number">13.7</span> t-tests are linear models<a href="t-test-comparing-two-means.html#t-tests-are-linear-models" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>It is also possible to formulate t-tests as linear models (using the <code>lm</code> function). To do this with the paired t-test you would specify a model that estimates an intercept. In R you can do this by writing the formula as <code>x ~ 1</code>. So, for the tool use example you can write the code like this:</p>
<div class="sourceCode" id="cb352"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb352-1"><a href="t-test-comparing-two-means.html#cb352-1" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(difference <span class="sc">~</span> <span class="dv">1</span>)</span>
<span id="cb352-2"><a href="t-test-comparing-two-means.html#cb352-2" tabindex="-1"></a><span class="fu">summary</span>(mod1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = difference ~ 1)
## 
## Residuals:
##    1    2    3    4    5 
## -5.4 16.6  4.6 -7.4 -8.4 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    85.40       4.75   17.98 5.62e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 10.62 on 4 degrees of freedom</code></pre>
<p>If you look at the summary will notice that the estimate of the intercept (the average difference between the two pairs), the degrees of freedom and the t-value and the p-value are all the same as the value reported when using <code>t.test</code>.</p>
<p>In fact, all of the t-tests, and ANOVA (below) are kinds linear models and can be also fitted with <code>lm</code>.</p>
<p>Here is the paired t-test investigating gender differences in reaction time. You can see that the test statistics and coefficients match those obtained from <code>t.test</code>.</p>
<div class="sourceCode" id="cb354"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb354-1"><a href="t-test-comparing-two-means.html#cb354-1" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(Reaction <span class="sc">~</span> Gender, <span class="at">data =</span> x)</span>
<span id="cb354-2"><a href="t-test-comparing-two-means.html#cb354-2" tabindex="-1"></a><span class="fu">anova</span>(mod)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: Reaction
##           Df  Sum Sq   Mean Sq F value  Pr(&gt;F)  
## Gender     1 0.01642 0.0164196  3.6482 0.06542 .
## Residuals 31 0.13952 0.0045008                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb356"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb356-1"><a href="t-test-comparing-two-means.html#cb356-1" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Reaction ~ Gender, data = x)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.08938 -0.04558 -0.01258  0.03662  0.22542 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.34838    0.01581   22.03   &lt;2e-16 ***
## GenderMale  -0.04480    0.02345   -1.91   0.0654 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.06709 on 31 degrees of freedom
## Multiple R-squared:  0.1053, Adjusted R-squared:  0.07643 
## F-statistic: 3.648 on 1 and 31 DF,  p-value: 0.06542</code></pre>
</div>
<div id="exercise-sex-differences-in-fine-motor-skills" class="section level2 hasAnchor" number="13.8">
<h2><span class="header-section-number">13.8</span> Exercise: Sex differences in fine motor skills<a href="t-test-comparing-two-means.html#exercise-sex-differences-in-fine-motor-skills" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Some people have suggested that there might be sex differences in fine motor skills in humans. Use the data collected on the class to address this topic using t-tests. The relevant data set is called <code>classData.csv</code>, and the columns of interest are <code>Gender</code> and <code>Precision</code>.</p>
<p>Carry out a two-sample t-test.</p>
<ol style="list-style-type: decimal">
<li><p>Plot the data (e.g. with a box plot, or histogram)</p></li>
<li><p>Formulate null and alternative hypotheses.</p></li>
<li><p>Use the <code>t.test</code> function to do the test.</p></li>
<li><p>Write a sentence or two describing the results.</p></li>
</ol>
</div>
<div id="exercise-therapy-for-anorexia" class="section level2 hasAnchor" number="13.9">
<h2><span class="header-section-number">13.9</span> Exercise: Therapy for anorexia<a href="t-test-comparing-two-means.html#exercise-therapy-for-anorexia" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A study was carried out looking at the effect of cognitive behavioural therapy on weight of people with anorexia. Weight was measured in week 1 and again in week 8. Use a paired t-test to assess whether the treatment is effective.</p>
<p>The data is called <code>anorexiaCBT.csv</code></p>
<p>The data are in “wide format”. You may wish to convert it to “long format” depending on how you use the data. You can do that with the <code>pivot_longer</code> function, which rearranges the data:</p>
<div class="sourceCode" id="cb358"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb358-1"><a href="t-test-comparing-two-means.html#cb358-1" tabindex="-1"></a>anorexiaCBT_long <span class="ot">&lt;-</span> anorexiaCBT <span class="sc">%&gt;%</span></span>
<span id="cb358-2"><a href="t-test-comparing-two-means.html#cb358-2" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb358-3"><a href="t-test-comparing-two-means.html#cb358-3" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">starts_with</span>(<span class="st">&quot;Week&quot;</span>), <span class="at">names_to =</span> <span class="st">&quot;time&quot;</span>,</span>
<span id="cb358-4"><a href="t-test-comparing-two-means.html#cb358-4" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">&quot;weight&quot;</span></span>
<span id="cb358-5"><a href="t-test-comparing-two-means.html#cb358-5" tabindex="-1"></a>  )</span></code></pre></div>
<ol style="list-style-type: decimal">
<li><p>Plot the data (e.g. with an interaction plot).</p></li>
<li><p>Formulate a null and alternative hypothesis.</p></li>
<li><p>Use <code>t.test</code> to conduct a <em>paired</em> t-test.</p></li>
<li><p>Write a couple of sentences to report your result.</p></li>
</ol>
</div>
<div id="exercise-compare-t-tests-with-randomisation-tests-optional" class="section level2 hasAnchor" number="13.10">
<h2><span class="header-section-number">13.10</span> Exercise: Compare t-tests with randomisation tests (optional)<a href="t-test-comparing-two-means.html#exercise-compare-t-tests-with-randomisation-tests-optional" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="do-something">
<ol style="list-style-type: decimal">
<li>
<p>
Try re-analysing some of the tests in this chapter as
randomisation tests (or analyse the randomisation test data using
<code>t.test</code>). Do they give the same results?
</p>
</li>
<li>
<p>
Try answering the question - “<em>are people who prefer dogs
taller than those who prefer cats?</em>” using the
<code>classData.csv</code>. Can you think of any problems with this
analysis?
</p>
</li>
</ol>
</div>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="10">
<li id="fn10"><p>A.M. Hurtado, K. Hill (1989). “Experimental Studies of Tool Efficiency Among Machinguenga Women and Implications for Root-Digging Foragers”, Journal of Anthropological Research, Vol.45,2,pp207-217.<a href="t-test-comparing-two-means.html#fnref10" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="randomisation-tests.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="assumptions-in-linear-models.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/jonesor/BB852_Book/edit/master/3_02-t-tests.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["BB852.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
},
"split_by": "section"
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
